### ISSUE TITLE
Cannot Create Admin - Could not retrieve server key. Please contact administrator. 

### ISSUE THREAD

**Issue by zorin1st** [passbolt/passbolt_api#100]
Hallo,
i have the following issue:
[Could not retrieve server key. Please contact administrator.](https://ibb.co/jS3X2k)

Can somebody help me?
Passbolt/Healthcheck is fine (all green).

Kind regards,
Elmar

**Comment by zorin1st** [comment]
No suggestions?

**Comment by passboltUser** [comment]
Hi,
I have the same problem: It says: 

> Could not retrieve server key. Please contact administrator.

I've done successfully all the other steps from this tutorial: https://medium.com/passbolt/passbolt-on-debian-8-71-from-scratch-4438dad18908 , but after 

> app/Console/cake passbolt register_user -u admin@... -f ada -l lovelace -r admin

I get the same error as zorin1st

My only guess is that some permissions with the gnupg keys are wrong, or a wrong path, but I double-checked according to the aforementioned tutorial and everything seems correct.

**Comment by cedricalfonsi** [comment]
Could you please check that :
1. Your passbolt instances use a valid domain name url (rfc1035)
2. The gpg key of the passbolt API (the one you generated and added the fingerprint to the app config) uses a valid email address

**Comment by passboltUser** [comment]
Thanks. 
I created a new key, entered no passphrase, exported and set permissions:
root@...# rm /home/www-data/.gnupg/ -R
root@...# gpg --gen-key
root@...# gpg --armor --export-secret-keys AB93232F > /var/www/pb/app/Config/gpg/serverkey.private.asc
root@...# gpg --armor --export AB93232F > /var/www/pb/app/Config/gpg/serverkey.asc
root@...# mkdir /home/www-data/.gnupg
root@...# cp /root/.gnupg/* /home/www-data/.gnupg/
root@...# chown -R www-data /home/www-data/.gnupg/
and it works now.
