### ISSUE TITLE
The readme should point to the documentation for how to upgrade passbolt

### ISSUE THREAD

**Issue by sebster** [passbolt/passbolt_api#101]
I've installed passbolt as per the installation document.

However, since passbolt is currently alpha, and there will be changes every now and then, I would like to know how to upgrade to migrate to the latest version without destroying my data.

A short document describing this procedure next to the installation document would be great.

**Comment by kevinmuller** [comment]
@sebster 
Thanks for your feedback. 
A documentation on how to upgrade passbolt is available here: http://www.passbolt.com/help/tech/update
We'll update the README to mention it though. Good point. (PASSBOLT-2170)

**Comment by sebster** [comment]
Awesome, thanks for the quick reaction! :)

**Comment by stripthis** [comment]
Fixed with 2.1
