### ISSUE TITLE
As a user adding new resources the current order is not applied and new resources appear at the top

### ISSUE THREAD

**Issue by sebster** [passbolt/passbolt_api#104]
When I sort my passwords by name, I would like this to be remembered and used.

Currently it always defaults to sorting by "modified" (when I switch to users and back the sort is reset).

Futhermore, even when it's sorted by resource, new entries are added at the top instead of in the correct location.

**Comment by stripthis** [comment]
Hello thank you for the bug report and the ehancement suggestions.

- PASSBOLT-2177: As a user adding new resources the current order is not applied and new resources appear at the top. I could reproduce the issue and this is indeed a bug.
- PASSBOLT-2178: As a user navigating in the user workspace user filters my resource order should be remembered
- PASSBOLT-2179 - As a user navigating between workspace my resource/user orders should be remembered 

Cheers,

**Comment by stripthis** [comment]
Partially moved to https://community.passbolt.com/t/as-a-logged-in-user-navigating-the-ui-my-sort-orders-should-be-remembered/57

**Comment by cedricalfonsi** [comment]
Fixed with v2.11.0.
Current order is now applied when creating a resource.
