### ISSUE TITLE
Button to reset the search filter

### ISSUE THREAD

**Issue by sebster** [passbolt/passbolt_api#105]
It would be very useful to have a little "x" button at the end of the search field to clear it in one click.

Currently you have to select all and press backspace.

**Comment by stripthis** [comment]
Thank you for the suggestion I have added this improvement to our backlog. Ref. PASSBOLT-2175

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-a-user-search-for-something-else-i-can-easily-reset-my-current-search/29
