### ISSUE TITLE
Broken image link in emails (proxying through Google Drive?)

### ISSUE THREAD

**Issue by eric-tucker** [passbolt/passbolt_api#107]
I noticed this in recovery emails but it could be others.

I'm seeing this as a link to the logo:

https://ci3.googleusercontent.com/proxy/<giant 106 character hash>#https://www.mydomain.com//img/logo/logo.png

The logo link actually works if I just grab out the mydomain/log part.

PS - the double slash is also troubling - I don't have a trailing slash in my value for `App.fullBaseUrl`.

**Comment by cedricalfonsi** [comment]
Looks like you have a problem similar to :
https://stackoverflow.com/questions/20491590/image-links-broken-in-gmail-because-of-googles-image-proxy

I'm interested by your setup, could you share your experience with the community. It could help to debug your issue if the link above doesn't.

**Comment by eric-tucker** [comment]
I'm hosting passbolt private restricted to our offices IP. So I guess this isn't something you can fix. Google's fault...

**Comment by cedricalfonsi** [comment]
I didn't know about the _Google Image Proxy_, but yeah we can't do anything when accessing an email through gmail.
