### ISSUE TITLE
Ran into gnupg issues during install

### ISSUE THREAD

**Issue by Emereoth** [passbolt/passbolt_api#108]
Hello,

I'm trying to install Passbolt on my LAMP, installed gnupg properly (version displayed in phpinfo, gpg executable present), but when I use the command shown in the installation page : 

`sudo /bin/bash -c "app/Console/cake install --no-admin" www-data`

(it's supposed to be `su -s` instead of `sudo`, but it's a VM and I don't know its root password).

Nevertheless, I get a magnificent 

```
PHP Gnupg library is not installed
Installation failed.
```

Any ideas how to solve this? It's been a few days, I'd be really grateful.

**Comment by passboltUser** [comment]
I guess you need the php-gnupg module. Try # apt install php-gnupg

**Comment by stripthis** [comment]
You also need to make sure the module is enabled for both php cli (as well as the regular php).

**Comment by Emereoth** [comment]
Thanks, anonymous user! Now after two days of wandering around and being lost with gpg, gnupg, gpgme and all these, I feel like a complete moron.

So, no more `PHP Gnupg library not installed`. 

Trying to fix the next issue now, something about /home/www-data/.gnupg not found/writeable. I don't even have a /home/www-data

**Comment by passboltUser** [comment]
I had the same problem, check my solved issue: https://github.com/passbolt/passbolt_api/issues/100

**Comment by Emereoth** [comment]
That worked too! (I definitely should ask questions more often instead of staying stuck by myself).

I've got the `Invalid key` error now, any pointers on that? The whole process of gpg key generating was quite shady to me, to be completely honest.

**Comment by passboltUser** [comment]
Emereoth, cedricalfonsi has closed your issue and it now moved to closed issues. I suggest you open a new one and provide more infos on how you're getting `Invalid key`.
