### ISSUE TITLE
Ability to Audit or control password ownership centrally

### ISSUE THREAD

**Issue by bluenetinc** [passbolt/passbolt_api#110]
I would like to ensure ownership of ANY shared credentials be added to an "owners group" and that individuals should ONLY retain ownership of personal passwords.

Perhaps this could be accomplished in conjunction with categories/tags where you could mark a password as "personal" and then perform an audit of any passwords NOT marked as personal that are still owned by an individual.

This is to protect from a scenario like this:

Employee adds a critical company credential.  Perhaps they even share it with some relevant groups.
Employee leaves the company, there is no way for us to access their account and change ownership of passwords if they had not done so already.  I don't see an easy way to identify non-personal passwords that a user added but didn't change the ownership to the proper user/group.

To prevent this I would like to periodically run an "audit" and request those users that retained ownership of non-personal passwords to relinquish ownership to a designated owners "group".

Perhaps this could also be managed through a checkbox when creating a new password: "Personal", and if it is NOT marked personal, the owner is automatically (and mandatory) set to a particular group, and the creating user is ONLY added as a "can change" credential.

**Comment by stripthis** [comment]
I understand your use case, thank you for your suggestions. We'll wait to see if this feature request has traction with other users before moving on this.

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-an-admin-i-can-audit-passwords-that-are-not-shared-with-anyone/56
