### ISSUE TITLE
As a logged in user I should be able to change my secret key passphrase

### ISSUE THREAD

**Issue by et304383** [passbolt/passbolt_api#112]
Don't know if this is the wrong place to create this but I cannot change my personal login password.  Is this a coming feature?  Is this because we can't change our key?

**Comment by stripthis** [comment]
Hi @eric-tucker 

Yes you are right it is not possible at the moment to change the key from the UI, it is indeed an coming feature. The good news is that there is a workaround, the bad news is that it's not very user friendly. What you need to do:
- Export your private key
- Import your private key in another Gpg compatible keyring and change the passphrase there
- Export your updated private key
- Follow the recover procedure in passbolt load up your private key with the new passphrase.

Sorry for the inconvenience. I hope this help,

**Comment by eric-tucker** [comment]
OK awesome.  How do I initiative a recovery?  The Chrome extension keeps initiating the login window with only a spot to put in my password.  There's no clear way to initiative recovery.

**Comment by stripthis** [comment]
Yes that's another issue, the recovery link is not present when your keyring is already set. You can just go to https://<yourdomain/recover and follow the instructions from there.

**Comment by AustinBrrtt** [comment]
I tried following your instructions, but I may be misunderstanding something as the recovery complains that, "This key is not a valid private key." I imported my key from the original passbolt_private.asc (using gpg --import), and was able to successfully change the password using gpg --edit-key. I exported it using gpg --armor --export and then copied and pasted that into the field asking for my key in the recovery, which gave me the error about an invalid key.

**Comment by stripthis** [comment]
@AustinBrrtt make sure you are not copy pasting the public key with it. That can happen when you export that the public key is on top (or that you exported the public key only).

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-a-logged-in-user-i-should-be-able-to-change-my-secret-key-passphrase/48
