### ISSUE TITLE
As a logged in user I should be able to change my email address

### ISSUE THREAD

**Issue by et304383** [passbolt/passbolt_api#113]
I would like this feature at some point.  Is the current work-around to edit the users table record in the database or are there multiple tables containing the email address?

**Comment by stripthis** [comment]
That is not a valid workaround. The email address is linked to the public key that is shared with other users when encrypting. This will certainly create bugs and potentially corrupt your data.

**Comment by stripthis** [comment]
I would say the workaround would be to create a new account with a different email, transfer ownership of your passwords to this account.

**Comment by eric-tucker** [comment]
OK.  Hopefully we'll have this at some point.

Thanks for all the work you folks do.  This is still a great product!

**Comment by bryanmathers** [comment]
Moved to: https://community.passbolt.com/t/as-a-logged-in-user-i-should-be-able-to-change-my-email-address/51
(plus other stories)
