### ISSUE TITLE
As a user on the login screen or master password dialog, my cursor should get auto focused on the password field

### ISSUE THREAD

**Issue by danbovey** [passbolt/passbolt_api#115]
When logging in, the password input should be autofocused so I can log in quickly (especially as my email is pre-filled by the extension, I assume).

When I copy a password or do some other protected action and Passbolt asks for my master password again, the password input in the modal should be focused automatically as well.

On a similar note, it would be nice if Passbolt remembers that I always want it to remember my master password for 5 minutes, and have the checkbox checked already.

Stuff like this will speed up interactions within the Passbolt client :smiley:

**Comment by stripthis** [comment]
Hello I created an issue in our backlog for you first two user stories, ref. PASSBOLT-2196. Concerning the remember me improvements we already have ticket for this one ref. PASSBOLT-2132, which is scheduled for v1.6.2.

**Comment by bluenetinc** [comment]
Not sure if this should be its own issue, but I feel it is related. on that same dialog box, it would be nice if when you hit tab, the cursor moves to the "remember for 5 minutes", so you can do a quick "Tab", spacebar to enable the remember feature quickly.

**Comment by stripthis** [comment]
@bluenetinc yes please open a separate issue.

**Comment by bryanmathers** [comment]
Moved to:
https://community.passbolt.com/t/as-a-user-on-the-login-screen-or-master-password-dialog-my-cursor-should-get-auto-focused-on-the-password-field/50
(plus other stories)
