### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by danbovey** [passbolt/passbolt_api#116]
As a team password manager, it makes sense to integrate with the most popular team software out there. I'd imagine there'd be a use case for receiving notifications in Slack like:

![passbolt](https://user-images.githubusercontent.com/1503076/27921308-48b18f52-626f-11e7-90e4-16681f342591.png)

**Comment by stripthis** [comment]
Hello @danbovey,

We already started working on a passbolt slack integration plugin here: https://github.com/passbolt/passbolt_slack

Currently it only notifies when a new user register to passbolt, but it could be extended to cover the use case your describe. Could you open an issue on that repository instead? Thanks!
