### ISSUE TITLE
Don't restrict the character set for username in a password

### ISSUE THREAD

**Issue by ktosiek** [passbolt/passbolt_api#118]
Currently (Passbolt 1.6.0) usernames on the password creating screen can't contain a backslash `\` - a character commonly used to separate domain name from username (CORPO\john.smith).

Actually, why is there such a strict validation on the username field? It should take pretty much anything IMHO.

**Comment by ktosiek** [comment]
Same goes for the password name - is there any reason for restricting allowed characters there?

**Comment by lcpdn** [comment]
Got the same issue for username whiches are mail adresses including a "+".
And the description field does not accept this neither.

**Comment by cedricalfonsi** [comment]
Hello @ktosiek, @lcpdn 

Thanks for reporting. We totally agree, validation rules are too strict. 
These issues are already discussed here #103, I invite to continue the discussion there.
