### ISSUE TITLE
Error on account creation - Validation of username

### ISSUE THREAD

**Issue by lcpdn** [passbolt/passbolt_api#120]
Linked to the string validation issue #103 , but implies that the validation does not work on this field.

Description : When I register a new user whose username/mail adress is an email which has a specific pattern, a validation error is issued but the account is still created (and mail are sent), and, *sometimes* (cache problem ?), does not appear in the list of accounts. 

How to reproduce: 
On Passbolt 1.6.0: 
The specific pattern is of the type : lcpdnlcpd+savety@gmail.com

Note that, lcpd.nlcpd+savety@gmail.com does not reproduce the problem. Neither does lcpdnlcpd+test@gmail.com. I figure there is something in the length of the strings and the place of the special caracter ?

Cheers :)

**Comment by stripthis** [comment]
ref. PASSBOLT-2180

**Comment by kevinmuller** [comment]
This issue has been solved in 1.6.1: http://www.passbolt.com/release/notes#Fresh
