### ISSUE TITLE
No email sent by Passbolt

### ISSUE THREAD

**Issue by PierfrancescoElia** [passbolt/passbolt_api#121]
Hi, I've just installed Passbolt on my server. I'm so impressed about the power of this software.

My Passbolt installation works well, but the system does not send any email.

I have created a mailbox _no-reply@passbolt.domain.com_, and I've checked that everything is good with Outlook (and all works), but Passbolt continue to not send emails.

The SMTP server require authentication, need SSL/TLS and use port 465.

That's my code.
`public $default = array(`
`                'transport' => 'Smtp',`
`                'from' => array('no-reply@passbolt.domain.com' => 'Passbolt'),`
`                'host' => 'smtp.domain.com',`
`                'port' => 465,`
`                'timeout' => 30,`
`                'username' => 'no-reply@passbolt.domain.com',`
`                'password' => 'xxxxxxx',`
`                'tls' => true,`
`        );`

I don't know if I forgot something...
Passbolt does not send emails, and the log is empty..

I've created a Passbolt account via the browser UI, but I didn't received any email. Is there a way to resend or get the activation URL? 
Thanks everyone!

**Comment by stripthis** [comment]
Can you try the solution mentionned in #119 ? Feel free to reopen the issue with a way for us to reproduce the issue.

**Comment by ghaberek** [comment]
Hi @DevNIX , are you hitting the `send_tries` limit in the database? See my thread on the forum:

[As an admin, I should be able to see when queued emails will not be sent](https://community.passbolt.com/t/as-an-admin-i-should-be-able-to-see-when-queued-emails-will-not-be-sent/279)

**Comment by chkchaitu** [comment]
Hi have ran into similar problem. Installation of passbolt is successful. I am able to login admin and then create users. but emails are not being sent to newly created used. 

I have used bin/cake passbolt send_test_email and it says - The message has been successfully sent! . I can see the logs in SMTP as well. But when a new user is created in the admin webinterface I do not see any logs in SMTP. Below is config from my server config - config/passbolt.php

 // Email configuration.
    'EmailTransport' => [
        'default' => [
            'host' => 'SMTPServerIP',
            'port' => 25,
            //'username' => '',
            //'password' => '',
            // Is this a secure connection? true if yes, null if no.
            'tls' => null,
            //'timeout' => 30,
            //'client' => null,
            //'url' => null,
        ],
    ],
