### ISSUE TITLE
Passbolt email notifications to user/group sent multiple times

### ISSUE THREAD

**Issue by claudiutraistaru** [passbolt/passbolt_api#123]
I am using latest version of passbolt  1.6.0 in docker.
In package.json I have: 
        "name": "Passbolt",                                                     
        "version": "1.6.0",   

When Sharing a password with a group or editing, the emails are sent multiple times (even in debug log multiple emails with the same subject but different messageId are shown). 
For sharing with one user , is 2 times , for sharing with a group the email is received usually 4 times, simetimes 2.

The problem is in the email sender. 
Note: I had installed it by having the latest passbolt docker image in place and manually replacing it with version 1.6.0 of passbotl from github.

Can sombody help me to see why is this happening?

**Comment by claudiutraistaru** [comment]
My bad,

I have found that in cron for the 1 min scripts , the execution line was duplicated many times , not just 2 , deleted all others and left only one, now the emails are sent once. 

I wil close this issue . Thank you.

**Comment by elboletaire** [comment]
I have this issue with the docker installation. How could I fix it? :\

**Comment by claudiutraistaru** [comment]
Hi , it seems that on every restart the script that runs at the begining at the docker version adds the line in cron , so you end up getting the email as many restarts you have done, you could edit the cronfile inside docker at every restart or just modify the entry script. I do not know it now , but for me editing the script solved the issue.

**Comment by elboletaire** [comment]
Thanks @claudiutraistaru! You pointed me to the right direction 😄 

https://github.com/passbolt/passbolt_docker/blob/master/bin/docker-entrypoint.sh#L161
