### ISSUE TITLE
As a logged in user I cannot share passwords with a group of more than 200 people.

### ISSUE THREAD

**Issue by tomofumi0003** [passbolt/passbolt_api#124]
Cannot share passwords to group

- Preparation
1. Register password about 250 or more
2. Create a group
3. Share all passwords to the group
4. Create a user

- Description
1. Edit group
2. Add user (preparation:4) to the group
-> password share is not finish.

![clipboard01](https://user-images.githubusercontent.com/30283534/28357486-8aea5516-6ca6-11e7-9a37-13a58cac406b.png)

If registered passwords are about 200, I can share them to group.

Regards,

**Comment by cedricalfonsi** [comment]
Hello @tomofumi0003,

What versions of passbolt API and plugin are you using ?
Did the newly created user complete the registration process ?

Cheers

**Comment by tomofumi0003** [comment]
> What versions of passbolt API and plugin are you using ?
passbolt API and plugin's version are both 1.6.0.

> Did the newly created user complete the registration process ?
Yes. New user creation succeeded.
If 200 passwords I want to share, this operation is successful. But 250 or more passwords I want to share, this operation is failure.

Regards,

![clipboard04](https://user-images.githubusercontent.com/30283534/28392686-f31cbcb0-6d1d-11e7-8895-b7fca53ec1fe.png)

![clipboard03](https://user-images.githubusercontent.com/30283534/28392683-eee36d38-6d1d-11e7-9bef-be4f01d322e7.png)

**Comment by cedricalfonsi** [comment]
Can you tell us if there are any errors on the browser or on the API ?

Check extension errors by opening the browser console :
1. go to _chrome://extensions/_
2. locate the passbolt extension and click on the _index.html_ link in the _Inspect views_ section 

Check client application errors by opening the tab console :
Press Ctrl+Shift+J (Windows / Linux) or Cmd+Opt+J (Mac).

Check the API error in app/tmp/logs/error.log

**Comment by tomofumi0003** [comment]
The api don't show any errors.

But the browser shows one error and I found an interesting message.
- Error
  - Failed to load resource: the server responded with a status of 403 (Forbidden)
  [fqdn]auth/checkSession.json
  -> This error message is shown from when I opened opening chrome-extension console.

- Interest message
  - [Violation] 'message' handler took 737ms  openpgp.js:3058

![clipboard05](https://user-images.githubusercontent.com/30283534/28442978-4d6edf10-6dee-11e7-9a17-08c8da66bc69.png)

**Comment by cedricalfonsi** [comment]
Hello @tomofumi0003,

We are able to reproduce your bug.
The only thing we get is an error from the encryption promise.

`A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Full Message: Error: Error decrypting message: Random number buffer depleted
Full Stack: [70]</AsyncProxy.prototype.onMessage@resource://gre/modules/commonjs/toolkit/loader.js -> resource://passbolt-at-passbolt-dot-com/lib/vendors/openpgp.js:20624:35`

We created a ticket on our ticketing system PASSBOLT-2669.
We come back to you when we get improvements.

Thanks for helping to make passbolt better.

**Comment by cedricalfonsi** [comment]
Fixed with v1.6.3
