### ISSUE TITLE
As a user on 1040px screen, I should have an option to access the left side menu & see the action buttons

### ISSUE THREAD

**Issue by tomofumi0003** [passbolt/passbolt_api#125]
If browser width less than 1041 pixel, left site menu is missing.

![clipboard02](https://user-images.githubusercontent.com/30283534/28358017-46b87d08-6ca8-11e7-9e82-ec3f1ca15703.png)

Regards,

**Comment by stripthis** [comment]
Hello, this is actually a design choice not a bug :).

**Comment by stripthis** [comment]
ref. PASSBOLT-2160

**Comment by bryanmathers** [comment]
moved to: https://community.passbolt.com/t/as-a-user-on-1040px-screen-i-should-have-an-option-to-access-the-left-side-menu-see-the-action-buttons/49
(plus other stories)
