### ISSUE TITLE
All items grayed out

### ISSUE THREAD

**Issue by passboltUser** [passbolt/passbolt_api#126]
Selecting all passwords at once is grayed out:
![grayed_out](https://user-images.githubusercontent.com/29798595/28516019-0312fb08-7060-11e7-887d-e832ad061f5a.png)

**Comment by stripthis** [comment]
See. https://github.com/passbolt/passbolt_api/issues/62

**Comment by passboltUser** [comment]
Ok. Maybe you should remove this non-working greyed out checkbox and change the other individual checkboxes to radio buttons then, so one sees that one can only select one item at a time?

**Comment by stripthis** [comment]
We will actually keep them there for now since the export functionality is coming up.
