### ISSUE TITLE
As a group manager deleting a user I can transfer ownership of this user shared passwords to another user who has already read access.

### ISSUE THREAD

**Issue by stripthis** [passbolt/passbolt_api#128]
From Quentin on support channel, ref. 441:
If a user has created a password and shared this with other people with only read rights and the person is not available anymore (in any way, like for example dead). When you try to delete the user it says that it has a sole password which is shared with other, so it can’t be deleted unless you transfer the ownership. However there is currently no way to do this.

**Comment by stripthis** [comment]
ref. PASSBOLT-2267

**Comment by quentinsch** [comment]
I assume if a user password isn't shared and the user is deleted it also deletes its passwords?

**Comment by quentinsch** [comment]
Maybe you could consider (an optional) four eyes principle to take ownership of abandoned passwords. So two administrators should approve or something like that. 
For larger organisations it could be useful to not let a single administrator take ownership of passwords (could be against security policies).

**Comment by bryanmathers** [comment]
Moved & merged to:
https://community.passbolt.com/t/as-an-admin-while-deleting-a-user-who-is-the-sole-owner-of-a-password-that-is-shared-i-should-be-able-to-transfer-the-ownership-to-another-user-in-order-to-be-able-to-perform-the-deletion/45
(plus other stories)

**Comment by souladm** [comment]
Hi!
How can I transfer resource ownership via API?
