### ISSUE TITLE
When modifying a value in a password the modified by is not updated. - V1.6.1

### ISSUE THREAD

**Issue by bradhowe** [passbolt/passbolt_api#129]
Create a password as userx
share with userY
Login as userY
Update password.
Login as userX

Results: modified by remains UserX - however settings are changed appropriately.

Expected, modified should be userY

**Comment by stripthis** [comment]
Hi @bradhowe I could reproduce the issue, it is indeed a regression. Thanks for your report.

**Comment by stripthis** [comment]
This issue have been fixed with v1.6.2 release.
