### ISSUE TITLE
As a user after login in passbolt should by default remember my passphrase for the next 5 minutes

### ISSUE THREAD

**Issue by bluenetinc** [passbolt/passbolt_api#131]
Right after logging into passbolt, and attempting to retrieve a password, you are always prompted with:
You need your passphrase to continue.

I think it would be desirable that when you first log in [to passbolt] it grants you access to your passwords for the next "5 minutes".  I think generally that most times when a user logs into the passbolt system it seems a healthy assumption is they probably came here to immediately retrieve a password, should we ALWAYS force the user to enter the passphrase twice before they can get access to their 1st password, even if they JUST finished entering their passphrase?

**Comment by TheVakman** [comment]
I'd second this idea as the initial default setting. If one logs in, in my opinion, it's safe to assume they want a password and should not have to enter it again until another five minutes passes.

**Comment by bryanmathers** [comment]
Moved to: 
https://community.passbolt.com/t/as-a-user-after-login-in-passbolt-should-by-default-remember-my-passphrase-for-the-next-5-minutes/47
(plus more stories)
