### ISSUE TITLE
As a logged in user that used "remember me" before, the checkbox should be checked by default on the passphrase dialog

### ISSUE THREAD

**Issue by stripthis** [passbolt/passbolt_api#132]
It would be nice if Passbolt remembers that I always want it to remember my master password for 5 minutes, and have the checkbox checked already if I already used the remember me before.

**Comment by stripthis** [comment]
ref. PASSBOLT-2274
Split from https://github.com/passbolt/passbolt_api/issues/131

**Comment by bryanmathers** [comment]
Moved to: https://community.passbolt.com/t/as-a-logged-in-user-that-used-remember-me-before-the-checkbox-should-be-checked-by-default-on-the-passphrase-dialog/46
(plus other stories)
