### ISSUE TITLE
As a logged in user I can configure which notifications I receive by email

### ISSUE THREAD

**Issue by glamic-ep** [passbolt/passbolt_api#134]
At the bottom of each notification mail it says:

> You can choose which messages you wish to receive from your profile in the "email notifications" section.

But you can't. I guess it is not yet implemented. Is there another place to tweak that for now? Because receiving mails for each change might be a bit much.

**Comment by Poeticode** [comment]
You can merge pull request #98 locally if you'd like. It's planned to be added in for the next release.

**Comment by stripthis** [comment]
I wouldn't merge the PR #98 as it is likely to be reworked with different naming conventions. If you can wait for another week that's better.

**Comment by et304383** [comment]
Is this eventually going to address not being able to turn off notifications for emails regarding a password item being updated?

The current email says:

```
You can disable these notifications by requesting an administrator to delete your account.
```

lol

Delete account to turn off email notifications?  Someone should have known this was bad as they were typing this message.  :)

**Comment by bryanmathers** [comment]
moved to:
https://community.passbolt.com/t/as-a-logged-in-user-i-can-configure-which-notifications-i-receive-by-email/44
(plus more stories)
