### ISSUE TITLE
Setup email and no emails sent but the following error in my log?

### ISSUE THREAD

**Issue by mannp** [passbolt/passbolt_api#135]
**Summary:**

I am testing passbolt on a mac using the auto built docker script for mariadb and passbolt. Looks great btw :)

I have created an account and successfully added a password record.

I cannot though sort out email sending which seems a critical part of passbolt and account management.

My email config is as follows using a passbolt specific gmail app password (config works for other php server apps I use)

**Config:**

        public $default = array(
                'transport' => 'Smtp',
                'from' => array('admin@passbolt.local' => 'Passbolt'),
                'host' => 'smtp.gmail.com',
                'port' => 587,
                'timeout' => 300,
                'username' => 'redacted@gmail.com',
                'password' => 'passbolt app password',
                'tls' => 'true',
        );

**Error log:**

crond[75]: USER root pid 104 cmd run-parts /etc/periodic/1min
PHP Warning:  SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_file_map): failed to open stream: Permission denied in /var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php on line 356
PHP Warning:  SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_cake_console_eng): failed to open stream: Permission denied in /var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php on line 356
PHP Warning:  SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_cake_console_eng): failed to open stream: Permission denied in /var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php on line 356
PHP Warning:  _cake_core_ cache was unable to write 'cake_console_eng' to File cache in /var/www/passbolt/lib/Cake/Cache/Cache.php on line 328
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_cake_console_eng): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
2017-08-03 11:19:00 Warning: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_cake_console_eng): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_cake_console_eng): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
2017-08-03 11:19:00 Warning: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_cake_console_eng): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: _cake_core_ cache was unable to write 'cake_console_eng' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
2017-08-03 11:19:00 Warning: _cake_core_ cache was unable to write 'cake_console_eng' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_list): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_list): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: _cake_model_ cache was unable to write 'default_passbolt_list' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_method_cache): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_list): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_list): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: _cake_model_ cache was unable to write 'default_passbolt_list' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_email_queue): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_email_queue): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: _cake_model_ cache was unable to write 'default_passbolt_email_queue' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_email_queue): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_email_queue): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: _cake_model_ cache was unable to write 'default_passbolt_email_queue' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_file_map): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: _cake_core_ cache was unable to write 'file_map' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
PHP Warning:  fwrite(): 111 is not a valid stream resource in /var/www/passbolt/lib/Cake/Console/ConsoleOutput.php on line 278
PHP Warning:  fwrite(): 111 is not a valid stream resource in /var/www/passbolt/lib/Cake/Console/ConsoleOutput.php on line 278
crond[75]: USER root pid 125 cmd run-parts /etc/periodic/1min
PHP Warning:  SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_file_map): failed to open stream: Permission denied in /var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php on line 356
PHP Warning:  SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_cake_console_eng): failed to open stream: Permission denied in /var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php on line 356
PHP Warning:  SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_cake_console_eng): failed to open stream: Permission denied in /var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php on line 356
PHP Warning:  _cake_core_ cache was unable to write 'cake_console_eng' to File cache in /var/www/passbolt/lib/Cake/Cache/Cache.php on line 328
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_cake_console_eng): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
2017-08-03 11:20:00 Warning: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_cake_console_eng): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_cake_console_eng): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
2017-08-03 11:20:00 Warning: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_cake_console_eng): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: _cake_core_ cache was unable to write 'cake_console_eng' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
2017-08-03 11:20:00 Warning: _cake_core_ cache was unable to write 'cake_console_eng' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_list): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_list): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: _cake_model_ cache was unable to write 'default_passbolt_list' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_method_cache): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_list): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_list): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: _cake_model_ cache was unable to write 'default_passbolt_list' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_email_queue): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_email_queue): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: _cake_model_ cache was unable to write 'default_passbolt_email_queue' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_email_queue): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_email_queue): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: _cake_model_ cache was unable to write 'default_passbolt_email_queue' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_file_map): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: _cake_core_ cache was unable to write 'file_map' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 328]
PHP Warning:  fwrite(): 145 is not a valid stream resource in /var/www/passbolt/lib/Cake/Console/ConsoleOutput.php on line 278
PHP Warning:  fwrite(): 145 is not a valid stream resource in /var/www/passbolt/lib/Cake/Console/ConsoleOutput.php on line 278
c

**Comment by dlen** [comment]
Hi thanks for your report! This looks like a permission problem. Could you paste the permissions assigned to   `/var/www/passbolt/app/tmp/`.
If you are using passbolt official docker image and, considering the trace you are providing, seems like a good idea to report this issue to the passbolt_docker repo issues.

**Comment by mannp** [comment]
ls -la /var/www/passbolt/app/tmp/
total 48
drwxrwxr-x    1 nginx    nginx         4096 Jul 26 15:32 .
drwxrwxr-x    1 nginx    nginx         4096 Jul 26 15:32 ..
drwxrwxr-x    1 nginx    nginx         4096 Aug  3 11:48 cache
drwxrwxr-x    2 nginx    nginx         4096 Jul 26 15:32 gpg
drwxrwxr-x    2 nginx    nginx         4096 Jul 26 15:32 image-processing
drwxrwxr-x    2 nginx    nginx         4096 Jul 26 15:32 logs
drwxrwxr-x    1 nginx    nginx         4096 Aug  3 11:48 purifier
drwxrwxr-x    2 nginx    nginx         4096 Jul 26 15:32 schema
drwxrwxr-x    2 nginx    nginx         4096 Jul 26 15:32 selenium
drwxrwxr-x    2 nginx    nginx         4096 Jul 26 15:32 sessions
drwxrwxr-x    2 nginx    nginx         4096 Jul 26 15:32 swagger
drwxrwxr-x    2 nginx    nginx         4096 Jul 26 15:32 tests

**Comment by dlen** [comment]
Looks good, please make sure that `cache/persistent/` has the following permissions:

```bash-4.3# ls -las
total 24
     4 drwxrwxr-x    2 nginx    nginx         4096 Aug  3 12:12 .
     4 drwxrwxr-x    4 nginx    nginx         4096 Jul 26 15:32 ..
     0 -rw-rw-r--    1 nginx    nginx            0 Jul 26 15:32 empty
     4 -rw-rw-r--    1 nginx    nginx           43 Aug  3 12:12 passbolt_cake_core_cake_console_eng
     8 -rw-rw-r--    1 nginx    nginx         5071 Aug  3 12:12 passbolt_cake_core_file_map
     4 -rw-rw-r--    1 nginx    nginx         2062 Aug  3 12:12 passbolt_cake_core_method_cache
```

**Comment by mannp** [comment]
/var/www/passbolt/app/tmp/logs # ls -la /var/www/passbolt/app/tmp/cache/persistent/
total 40
drwxrwxr-x    1 nginx    nginx         4096 Aug  3 11:49 .
drwxrwxr-x    1 nginx    nginx         4096 Aug  3 11:48 ..
-rw-rw-r--    1 nginx    nginx            0 Jul 26 15:32 empty
-rw-rw-r--    1 nginx    nginx           43 Aug  3 11:49 passbolt_cake_core_cake_console_eng
-rw-rw-r--    1 nginx    nginx           43 Aug  3 11:48 passbolt_cake_core_cake_en-gb
-rw-rw-r--    1 nginx    nginx           43 Aug  3 11:48 passbolt_cake_core_default_en-gb
-rw-rw-r--    1 nginx    nginx         8692 Aug  3 11:49 passbolt_cake_core_file_map
-rw-rw-r--    1 nginx    nginx         5069 Aug  3 11:49 passbolt_cake_core_method_cache

**Comment by mannp** [comment]
@dlen if the permissions are all correct, does the passbolt docker have the necessary email apps/libs installed for ssl/tls transfers to the likes of gmail?

There are a number of email issues mentioned on github and I have followed those, but cannot get any error message in a log or anything; very frustrating setup.

Executing /var/www/passbolt/app/Console/cake EmailQueue.sender -v gives me nothing.

**Comment by dlen** [comment]
@mannp the passbolt docker image hass all the necessary libs to use with gmail. However you might have to enable "Less secure applications" to connect in your gmail account and DisplayUnlockCaptcha to make possible for passbolt to use gmail servers. More info [here](https://support.google.com/accounts/answer/2461835?hl=en) and [here](https://support.google.com/accounts/answer/6010255?hl=en).

It's a tested use case of passbolt docker and it works.

**Comment by mannp** [comment]
@dlen ok less secure is not needed with 2fa according to google, but the app password is, but I am already using a passbolt specific password.

I have done the DisplayUnlockCaptcha and still nothing as yet.

Is there any way to debug this as cake EmailQueue.sender -v is **next to useless** with no output at all.

Email also doesn't appear in the healthcheck either, which seems odd for such a critical requirement.

**Comment by stripthis** [comment]
HI @mannp,

Something like this will work for gmail (I just tried it to make sure it works):
```
	public $default = array(
		'transport' => 'Smtp',
		'from' => array('your@gmail.com' => 'Passbolt'),
		'host' => 'ssl://smtp.gmail.com',
		'port' => 465,
		'timeout' => 30,
		'username' => 'your@gmail.com',
		'password' => 'applicationpassword'
	);
```

If this still does not work, maybe you have an issue on your network / with your ISP not allowing outbound SMTP connections.

> Email also doesn't appear in the healthcheck either, which seems odd for such a critical requirement.
This is actually a complicated topic. Implementations of the protocol between vendors vary also, making it complicated to display error messages or even assert a status.

**Comment by mannp** [comment]
@stripthis thanks for that :) mine was failing on the new app password I had created for passbolt, when I used my original app password it connected straight away.

I do though get this message with each email?

> Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_default_eng): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]

I just meant if Cakephp gets a return code from the email command it could be checked for a successful email send or failure?
