### ISSUE TITLE
New install error when 'retrieving server key'

### ISSUE THREAD

**Issue by andydixon** [passbolt/passbolt_api#136]
I've set up a new install, however it's erroring when requesting the server key. I enabled debug in core.php and found the following exception:

[Fri Aug 04 15:20:34.907305 2017] [:error] [pid 6700] [client 185.62.156.218:55146] PHP Fatal error:  Uncaught Error: Class 'Common' not found in /var/www/passbolt/app/Controller/AppController.php:227\nStack trace:\n#0 /var/www/passbolt/lib/Cake/Network/CakeRequest.php(532): AppController->{closure}(Object(CakeRequest))\n#1 /var/www/passbolt/app/Controller/AppController.php(198): CakeRequest->is('json')\n#2 /var/www/passbolt/app/Controller/AppController.php(106): AppController->_setDefaultLayout()\n#3 /var/www/passbolt/lib/Cake/Event/CakeEventManager.php(243): AppController->beforeFilter(Object(CakeEvent))\n#4 /var/www/passbolt/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))\n#5 /var/www/passbolt/lib/Cake/Error/ExceptionRenderer.php(158): Controller->startupProcess()\n#6 /var/www/passbolt/lib/Cake/Error/ExceptionRenderer.php(95): ExceptionRenderer->_getController(Object(Error))\n#7 /var/www/passbolt/lib/Cake/Error/ErrorHandler.php(126): ExceptionRenderer->__construct(Object(Error))\n#8 [internal function]: ErrorHandler::handleException(Object(Error))\n#9 {main}\n  thrown in /var/www/passbolt/app/Controller/AppController.php on line 227
[Fri Aug 04 15:20:34.907865 2017] [:error] [pid 6700] [client 185.62.156.218:55146] PHP Fatal error:  Uncaught Error: Class 'Common' not found in /var/www/passbolt/app/Controller/AppController.php:227\nStack trace:\n#0 /var/www/passbolt/lib/Cake/Network/CakeRequest.php(532): AppController->{closure}(Object(CakeRequest))\n#1 /var/www/passbolt/app/Controller/AppController.php(198): CakeRequest->is('json')\n#2 /var/www/passbolt/app/Controller/AppController.php(106): AppController->_setDefaultLayout()\n#3 /var/www/passbolt/lib/Cake/Event/CakeEventManager.php(243): AppController->beforeFilter(Object(CakeEvent))\n#4 /var/www/passbolt/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent))\n#5 /var/www/passbolt/lib/Cake/Error/ExceptionRenderer.php(158): Controller->startupProcess()\n#6 /var/www/passbolt/lib/Cake/Error/ExceptionRenderer.php(95): ExceptionRenderer->_getController(Object(InternalErrorException))\n#7 /var/www/passbolt/lib/Cake/Error/ErrorHandler.php(126): ExceptionRenderer->__construct(Object(InternalErrorException))\n#8 /var/www/passbolt/lib/Cake/Error/ErrorHandler.php(269): ErrorH in /var/www/passbolt/app/Controller/AppController.php on line 227

**Comment by stripthis** [comment]
Hi Andy, can yo try running the healtcheck? This looks like that some configuration file might be missing.
`./app/Console/cake passbolt healthcheck`

**Comment by andydixon** [comment]
Hello, the following is the output of my healthcheck:

$ sudo ./app/Console/cake passbolt healthcheck
---------------------------------------------------------------
     ____                  __          ____  
    / __ \____  _____ ____/ /_  ____  / / /_ 
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/ 
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /    
 /_/    \__,_/____/____/_.___/\____/_/\__/   

 Open source password manager for teams
---------------------------------------------------------------
 Healthcheck shell        
---------------------------------------------------------------

 Environment

 [PASS] PHP version 7.0.18-0ubuntu0.16.10.1
 [PASS] PCRE compiled with unicode support
 [PASS] The app/tmp directory is writable
 [PASS] The app/webroot/img/public directory is writable

 Config files

 [PASS] The core config file is present
 [PASS] The database config file is present
 [PASS] The email config file is present
 [PASS] The application config file is present

 Core config

 [FAIL] Debug mode is on.
  [HELP] Set Configure::write('debug', 0); in app/Config/core.php
 [PASS] Cache is working.
 [PASS] Unique value set for security.salt
 [PASS] Unique value set for security.cipherSeed
 [PASS] Full base url is set to https://keymaster.andydixon.com
 [PASS] App.fullBaseUrl validation OK.
 [PASS] /healthcheck/status is reachable.

 SSL Certificate

 [PASS] SSL peer certificate validates
 [PASS] Hostname is matching in SSL certificate.
 [PASS] Not using a self-signed certificate

 Database

 [PASS] Configured to use a supported database backend
 [PASS] The application is able to connect to the database
 [PASS] Not using a prefix for database tables
 [PASS] 20 tables found
 [PASS] Some default content is present
 [PASS] The database schema up to date.

 GPG Configuration

 [PASS] PHP GPG Module is installed and loaded
 [PASS] The server gpg key is not the default one
 [PASS] The environment variable GNUPGHOME is set to /var/www/passbolt/gnupg
 [PASS] The directory containing the keyring is writable by root.

 Application configuration

 [PASS] Using latest passbolt version (1.6.1)
 [PASS] Passbolt is configured to force SSL use
 [PASS] App.fullBaseUrl is set to HTTPS
 [PASS] Selenium API endpoints are disabled.
 [PASS] Search engine robots are told not to index content.
 [WARN] Registration is open to everyone.
  [HELP] Make sure this instance is not publicly available on the internet.
  [HELP] Or set App.registration.public to false in app/Config/app.php
 [PASS] Serving the compiled version of the javascript app

 Development Tools (optional)

 [PASS] Phpunit is installed
 [PASS] Phpunit version is 3.7.38

  1 error(s) found. Hang in there!


Cheers!

Andy

**Comment by stripthis** [comment]
This is very strange. Did you modify the app/Config/bootstrap.php or remove app/lib/common.php by any chance? This is where Common.php is included / defined.

**Comment by andydixon** [comment]
Nope!
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    app/Config/gpg/unsecure.key
	deleted:    app/Config/gpg/unsecure_private.key
	modified:   app/Console/Command/InstallShell.php

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	app/Config/gpg/private.key
	app/Config/gpg/public.key

no changes added to commit (use "git add" and/or "git commit -a")

The change made to InstallShell was just a print_r to identify why I was getting the test GPG key (it was a long day):

+++ b/app/Console/Command/InstallShell.php
@@ -256,7 +256,8 @@ class InstallShell extends AppShell {
                // Check that the private key match the fingerprint
                $privateKeyInfo = $gpg->getKeyInfo($privateKeydata);
                if ($privateKeyInfo['fingerprint'] != $keyid) {
-                       throw new CakeException('The private key does not match the fingerprint mentioned in the config');
+                       print_r($privateKeyInfo);
+                       throw new CakeException('The private key does not match the fingerprint mentioned in the config '.$privateKeyInfo['fingerprint']);
                }
 
                // Check that there is a public key found at the given path

Cheers,

Andy

**Comment by stripthis** [comment]
Hi, I could reproduce the issue by creating an invalid app.php file. Could you double check there is no error in this file (like a missing "]").

**Comment by andydixon** [comment]
Just checked through it, and it's syntactically correct and parses:
# php -l ./app/Config/app.php
No syntax errors detected in ./app/Config/app.php
# php ./app/Config/app.php
PHP Notice:  Use of undefined constant APP - assumed 'APP' in /var/www/passbolt/app/Config/app.php on line 56
PHP Notice:  Use of undefined constant DS - assumed 'DS' in /var/www/passbolt/app/Config/app.php on line 56
PHP Notice:  Use of undefined constant DS - assumed 'DS' in /var/www/passbolt/app/Config/app.php on line 56
PHP Notice:  Use of undefined constant APP - assumed 'APP' in /var/www/passbolt/app/Config/app.php on line 57
PHP Notice:  Use of undefined constant DS - assumed 'DS' in /var/www/passbolt/app/Config/app.php on line 57
PHP Notice:  Use of undefined constant DS - assumed 'DS' in /var/www/passbolt/app/Config/app.php on line 57

I'm happy those notices are nothing to be concerned of since I executed the script directly without the defines being in place.

**Comment by stripthis** [comment]
Maybe there is an issue with the anonymous_statistics file in tmp/config/anonyous_statistics.php?

**Comment by andydixon** [comment]
That file does not exist, and I have created the tmp/config folder (it was missing), now everything is returning a 200, but still get the "Could not retrieve server key. Please contact administrator." message. I cant find any errors in any of the logs either!

I have checked the access.log and I can see the call to /auth/verify.json, and I have tested that myself and get a valid JSON object from that.

I'm completely confuzzled!

**Comment by stripthis** [comment]
Hang in there @andydixon! :)

There is something wrong with your config but I can't nail it down. It should be fine if the file is not there. You can delete this directory. Please delete any "anonymous_statistics" file in app/Config also, if any.

Concerning the  "Could not retrieve server key. Please contact administrator." , this is a known issue that appears when either the server key does not contain an email id (in the gpg uid field), or if the url is not valid (example: https://invalid-url/ ). Can you double check with the later?

**Comment by stripthis** [comment]
see. https://github.com/passbolt/passbolt_api/issues/100

**Comment by andydixon** [comment]
Haha! I love a good headscratcher! Its been a fair few years since I worked with cakePHP so it's quite nice to be snooping around the code! I'll regenerate the gpg key and see how that goes.

I'll also hunt out the anonymous_statistics too.

Cheers!

Andy

**Comment by andydixon** [comment]
Woot! Just regenerated the gpg key as per #100 and that's fixed that. Onwards and upwards. Thanks very much for your help! :D

**Comment by stripthis** [comment]
Great, i'm pushing a fix this week to trigger some warning about this issue during install. Have a good day!
