### ISSUE TITLE
As a user I can import my passwords from a CSV file generated by 1password

### ISSUE THREAD

**Issue by mannp** [passbolt/passbolt_api#137]
I am using 1password for teams and am hoping Passbolt will mature into a worthy replacement.

Transferring my data will be a nightmare without any way to import.

Thanks for your consideration.

**Comment by stripthis** [comment]
ref. https://support.1password.com/export/

**Comment by stripthis** [comment]
Hi @mannp it's a good suggestion, i'm sure other people coming from 1password would find this useful. Thanks!

**Comment by mannp** [comment]
Thanks for updating the title and export to csv. 

I'll try to add any other issues/requests/observations in the same format you have used.

**Comment by dromeo5** [comment]
Hi @stripthis I'd like to +1 this request as well. Can it be extended to cater for Keepass XML export files as well?

**Comment by twotwenty** [comment]
I have been eyeing  up pass bolt to use in my department >100 users but if it cant import I cant migrate easily enough and managers are pushing to get password management even if its proprietary.

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-a-user-i-can-import-my-passwords-from-a-csv-file-generated-by-1password/20
