### ISSUE TITLE
Share 2FA generator

### ISSUE THREAD

**Issue by Ducatel** [passbolt/passbolt_api#139]
Hi everybody,

I have an idea to share which should be great if it's included in Passbolt.

## Example 

In fact I'm currently facing to a problem which cannot be solved by Passbolt yet.
I'm trying to share the AWS root account of my company. 
The strong password is already in my own Passbolt instance but isn't enough.
My Root account is secure by a MFA process, and I cannot share it securely.

## Idea 

So my idea is to share 2FA generator like we can already do with password. 
TOTP should be enough for a first shot but HOTP can be great also.
I thinks, It's possible to do that with the current GPG process. (For storing the "secret")
In UI, attached to an existing password entry  seems to be a good place.

## Resources

* [TOTP RFC](https://tools.ietf.org/html/rfc6238)
* [HOTP RFC](https://tools.ietf.org/html/rfc4226)

**Comment by stripthis** [comment]
@Ducatel is this a #71 duplicate?

**Comment by Ducatel** [comment]
Oh damn....
I have search existing issue with 2FA and MFA keyword and I didn't find anything.
Soo Yes, it's seems to be the same idea.
My apologize

**Comment by stripthis** [comment]
No worries! Closing this one then.
