### ISSUE TITLE
As logged in user, I should be able to get passbolt to remember my private key password for more than 5 minutes

### ISSUE THREAD

**Issue by passboltUser** [passbolt/passbolt_api#140]
Hello,
our Passbolt users don't like the need to enter passwords for all kind of actions, i.e.: "the need to enter a password every 5 minutes is annoying". Can this be changed? Either disabling it or increasing the log-in time? I understand that it increases security, but many of our users find it annoying.

**Comment by stripthis** [comment]
Yes, we've seen this request also coming up quite a bit in our support channels. @kevinmuller already started working on this. In the future we will allow user to choose how long they want the plugin to remember their password. This is how it will look like in the future.

Ref. PASSBOLT-2132
![screen shot 2017-08-09 at 17 56 40](https://user-images.githubusercontent.com/77410/29121459-34972df6-7d2c-11e7-84c1-a547fb018ded.png)

Related.  #132

**Comment by passboltUser** [comment]
Thanks.

**Comment by r3vile** [comment]
I am also in need of this feature. Can you give an estimated date of release? :X

**Comment by bryanmathers** [comment]
Moved to:
https://community.passbolt.com/t/as-logged-in-user-i-should-be-able-to-get-passbolt-to-remember-my-private-key-password-for-more-than-5-minutes/43
(plus other stories)
