### ISSUE TITLE
I got my passbolt through git master, how can I update it to the current master (1.6.0 to 1.6.1)?

### ISSUE THREAD

**Issue by passboltUser** [passbolt/passbolt_api#146]
I'm using this version: 
```
# git log
commit 179cbe1aa2a581eddb9704f0d6b28175711eef9f
[...]
```
( https://github.com/passbolt/passbolt_api/compare/179cbe1a...v1.6.1 )

How can I update to the latest compatible build (that would be either v1.6.1 or master, if master is compatible)?

**Comment by stripthis** [comment]
Hi, you can pull from master, we only put stable releases on this branch.
See: https://www.passbolt.com/help/tech/update

**Comment by passboltUser** [comment]
Thanks, it worked.
