### ISSUE TITLE
With SMTP Relay

### ISSUE THREAD

**Issue by princechennai** [passbolt/passbolt_api#147]
public $default = array(
                'transport' => 'Smtp',
                'from' => array('passbolt@vspengg.com' => 'Passbolt'),
                'host' => '192.168.1.20',
                'port' => 25,
                'timeout' => 30,
                'tls' => false,
        );
No emails.. No error messages? I'm using SMTP Relay

**Comment by stripthis** [comment]
Hello @princechennai,

It is hard to tell what is wrong this amount of data. It is probably one or the other:
- the smtp server is not configured properly or not accessible
- you are not executing the script manually / through a cron job

I hope this helps,
