### ISSUE TITLE
As a logged in user, I should not be able to access /register and create a new account, regardless of whether public registration is enabled or not

### ISSUE THREAD

**Issue by Poeticode** [passbolt/passbolt_api#148]
When app.php has public registration set to false, attempting to access /register correctly redirects to the homepage.

If the user is logged in, however, attempting to access /register does not redirect to home, and you can successfully create a new account through it.

**Comment by stripthis** [comment]
Thanks for the suggestion. This seems like a minor issue though.

**Comment by bryanmathers** [comment]
Moved to:
https://community.passbolt.com/t/as-a-logged-in-user-i-should-not-be-able-to-access-register-and-create-a-new-account-regardless-of-whether-public-registration-is-enabled-or-not/41
(plus more stories)

**Comment by stripthis** [comment]
This has been fixed in v2
