### ISSUE TITLE
As a logged in user I can display the "Shared with" information as a collumn of the password workspace table

### ISSUE THREAD

**Issue by passboltUser** [passbolt/passbolt_api#150]
After login one sees an overview table:

`Resource | Username | Password | URI | Modified`

But one doesn't see a `Shared with` and it's only visible when one clicks on one of those rows and on the right button at the top with the (i) as icon. Is it possible to add the `Shared with` column to the table, so it'd look like this?:
 `Resource | Username | Password | URI | Modified | Shared with`
(this may of course expand the rows and they would be higher when there are many shared with entries, but if one wants to see all the shared with entries, that's unavoidable and still exactly what I'd want so I can see straight away which entries are shared with whom)

I need this feature to see straight away with whom a certain entry is shared with.
We have already like over 100 entries (PS: showing the number of entries would be good) and clicking each one to see with who it's shared with is impractical.

**Comment by stripthis** [comment]
Thank you for the suggestion, our plan is to add a button on the top right of the table to allow the user to choose which collumn to display. Your request could fit within this future change.

**Comment by bryanmathers** [comment]
Moved to:
https://community.passbolt.com/t/as-a-logged-in-user-i-can-display-the-shared-with-information-as-a-column-of-the-password-workspace-table/40
(plus other stories)

**Comment by Nihvel** [comment]
Hi all, is there a reason why this issue was closed? I can't see the solution implemented and the links above bring to basically nothing.
