### ISSUE TITLE
OAuth2: Office365 Authentication

### ISSUE THREAD

**Issue by passboltUser** [passbolt/passbolt_api#151]
Any plans on this? Not sure if this is even possible since you use your own plugin, but maybe it is?

**Comment by stripthis** [comment]
Thank you for the suggestion. There is no plan for Office365 integration in the short/mid-term future.

**Comment by passboltUser** [comment]
Ok, thanks.

**Comment by passboltUser** [comment]
I'll let it open? Close if you want.

**Comment by stripthis** [comment]
You can let it open no problem. This way other users can formulate interest and pitch in with their idea.
