### ISSUE TITLE
The server was unable to respect the authentication protocol! There was a problem when trying to communicate with the server (HTTP Code:404)

### ISSUE THREAD

**Issue by BigGold1310** [passbolt/passbolt_api#152]
Hi everyone

I installed passbolt on a fresh Centos 7 OpenVZ Container (I'm not Hoster)

I got every thing up and running. But now I'm hanging up at the first logging with my new created admin user.

![17-08-_2017_21-49-51](https://user-images.githubusercontent.com/4549960/29430874-4c03a67a-8396-11e7-9850-ffc1b13bdb05.png)

Can anyone help me to solve this issue?

Is additional information needed?
If yes, how can i provide these?

Kind regards

**Comment by stripthis** [comment]
There seems to be an issue with entropy on Centos with VM. See #141
