### ISSUE TITLE
Passbolt should not escape html in email subject lines

### ISSUE THREAD

**Issue by heldmar** [passbolt/passbolt_api#153]
I saw a problem in the subject lines of the emails. When created a new item with this name:
`
"R&Y - GoDaddy Account... "
`
Instead you will see it reads on the subject line:
`
"R &amp;Y - GoDaddy Account "
 `
I hope this contributes with future releases.

**Comment by stripthis** [comment]
Thank you for the bug report @heldmar . 
Ref. PASSBOLT-2326

**Comment by martinvonwittich** [comment]
I just stumbled over this issue - I created a password that contains double quotes (`"`), and the email subject looks like this:

```
Subject: You added the password foo &quot;bar&quot;
```

I was about to file a bug when I noticed this one. Why is it wontfix?

**Comment by stripthis** [comment]
@martinvonwittich this is to prevent getting security reports that passbolt can be used to send insecure emails. In practice we could provide an option to disable this behavior if this is an acceptable risk for your use case.

**Comment by stripthis** [comment]
Fixed with 2.12
