### ISSUE TITLE
As logged user I can't share a password to a new owner AND delete me as an owner

### ISSUE THREAD

**Issue by lcpdn** [passbolt/passbolt_api#154]
As I create entries for a user, I would like to modify ownership to make him the owner and to delete me as granted user on this entry at the same step.
In facts, it generates an error:

> error Invalid secret provided for user XXXXXXX and resource XXXXXXXXXX.

If I make the user owner then save, then delete me as granted user in two steps, it works fine.

**Comment by stripthis** [comment]
Hi @lcpdn thank you for the bug report!
ref PASSBOLT-2349

**Comment by cedricalfonsi** [comment]
It has been fixed with v2
