### ISSUE TITLE
Vendor dir naming

### ISSUE THREAD

**Issue by DanielRuf** [passbolt/passbolt_api#155]
Shouldn't it be lowercase in general or is there a specific reason why it is capitalized?

**Comment by stripthis** [comment]
Historically cakephp 2.x used 'vendors' as a directory where composer default is 'vendor'. Apart from that i'm not sure why @cedricalfonsi capitalized it in https://github.com/passbolt/passbolt_api/commit/ab76c79a3fd67e6e2ac60108974f80e07f1adbe8 . Anyways this will change with the upgrade to cakephp 3 next month.

Does it cause any problems to you?

**Comment by DanielRuf** [comment]
Currently it does not cause any issues but I thought about systems where the file handling may be different and older Git versions prior 1.6.1.9 may not have `core.ignorecase` set to `true`.

Thanks for the information.
Is there some rough roadmap?

**Comment by stripthis** [comment]
There you go: https://www.passbolt.com/roadmap

**Comment by DanielRuf** [comment]
> There you go: https://www.passbolt.com/roadmap

I guess I saw it yesterday but thought this would be also available as milestones, boards and project(s) here on GitHub but I'm fine with this visual representation =)
