### ISSUE TITLE
As a user I can edit the online documentation

### ISSUE THREAD

**Issue by DanielRuf** [passbolt/passbolt_api#156]
I would like to file some PRs for https://www.passbolt.com/help/tech/install but I can not find any repository for the website.

**Comment by stripthis** [comment]
The public website source is currently not availablem even though the content is license under CC BY-SA 4.0. We will move the help sections to an open source code base in the course of fall 2017 where we will propose more open community tools. In the meantime feel free to suggest the changes here and we'll edit the relevant pages (I know it's not convenient, but that's what we can do in the meantime).

**Comment by bryanmathers** [comment]
Moved to:
https://community.passbolt.com/t/as-a-user-i-can-edit-the-online-documentation/38
(plus more stories)

**Comment by DanielRuf** [comment]
This does not ease collaboration but ok. Thanks for the update about the docs. Should I close the issue here?

**Comment by stripthis** [comment]
@DanielRuf thanks for your understanding, we're trying to move feature requests and installation issues away from github so that more people can participate to the conversation and avoid having people email directly the developers with questions.
