### ISSUE TITLE
As a user I can import the private key in GPA (gpg4win) and Enigmail (Thunderbird)

### ISSUE THREAD

**Issue by DanielRuf** [passbolt/passbolt_api#158]
I tried importing the private key / keypair in GPA (gpg4win) and Enigmail in Thunderbird but it was not added to the keyring there. Just the commandline gpg/gpg2 tools imported it without any issues.

As I worked on some GnuPG project in the past I guess this is probably related to the flags or some other parts of the key headers.

Also the encrypted text from the email is not a valid encrypted text in GPA (not sure if it is due to the linewrap length or the missing keypair, I'll try to find the cause for this).

So far anything else works flawlessly. Great work!

**Comment by stripthis** [comment]
@DanielRuf thanks for the bug report. I've seen also sometimes we have issues with decryting the email content with other tools such as mailvelope. Let us know if you find something.

**Comment by stripthis** [comment]
Closing as stalled. Feel free to reopen if you have more info.
