### ISSUE TITLE
Entries should not appear in Group Screen after creation

### ISSUE THREAD

**Issue by lcpdn** [passbolt/passbolt_api#161]
When I create entries while I am on a Group screen, the created entries automatically appear in the "Password shared with the group screen". Even if they are not shared with the group. 
Entries remain until a hard refresh (or sometimes a simple refresh, not sure of the behaviour). Even if you create more passwords, they remain on the list of shared passwords.

IMHO: Problem is that if you don't show them on a list, users can believe they were not created. But if you show them on this list, users can believe they were shared. Maybe a splashscreen ?

**Comment by stripthis** [comment]
hi @lcpdn, i'm not understanding this one, do you mind illustrating the issue with screenshots?

**Comment by lcpdn** [comment]
Sure. When I am displaying all passwords shared with a Group :
![image](https://user-images.githubusercontent.com/11770960/29862644-665eea26-8d6d-11e7-8e6b-b92cc38e03ca.png)

If I click on "create" from this screen and add an entry:
![image](https://user-images.githubusercontent.com/11770960/29862287-74dbf310-8d6c-11e7-9d92-bad763c24f14.png)

Then, the entry appear in the list of the passwords shared with the Group:
![image](https://user-images.githubusercontent.com/11770960/29862358-a410af22-8d6c-11e7-8e00-a23bfa36a7b8.png)

If I go on the details, it shows that the password is not, in facts, shared with the Group:
![image](https://user-images.githubusercontent.com/11770960/29862460-e9ebbc6c-8d6c-11e7-9d0c-ddf7e1b52aae.png)

If I had more entries, they will also appear on the list, and the previously created won't disappear:
![image](https://user-images.githubusercontent.com/11770960/29862567-2b56cc32-8d6d-11e7-9f62-ef08c07373fb.png)

If I make a Refresh or browse in Passbolt, depending on the browser, these entries still remain (but I wasn't able to reproduce this one here) displayed in the Group. 
A hard refresh cleans it:
![image](https://user-images.githubusercontent.com/11770960/29862750-b431b814-8d6d-11e7-89a4-ebd0bb4c9b60.png)

**Comment by stripthis** [comment]
@lcpdn thanks for the explanation it's clear now. Ref. PASSBOLT-2367

**Comment by cedricalfonsi** [comment]
Small update on this bug. With the next version v2.3.0, while creating a password the workspace will target the "All items" filter and display passwords by last modified dates.

**Comment by cedricalfonsi** [comment]
Fixed with v2.3.0
