### ISSUE TITLE
Multiple secret for one entry

### ISSUE THREAD

**Issue by Ducatel** [passbolt/passbolt_api#162]
Hi everybody,
There is a way to store multiple *secret string* inside one Passbolt entry ?

For example in my Passbolt entry you would like to put:

* The DB passbolt user password
* The root DB password
* The root server password
* Etc...

This is possible ?
If not, there a plan for that in the roadmap ? (I didn't saw anything about that)

Thanks ;)

**Comment by stripthis** [comment]
Hi @Ducatel I guess it would make sense to group these passwords by categories and/or create a secure note with all the information in it. I don't see the advantage of having multiple secrets inside an entry, but if other people upvote this issue we will consider it.

**Comment by Ducatel** [comment]
Hi @stripthis ,
I use both options (secure note and multiples secure string) very very often in my keepass
For example, a keepass entry for my passbolt server:

![keepass_2017-09-01_10-38-57](https://user-images.githubusercontent.com/1184332/29962097-2667023c-8f02-11e7-85a5-41d1ee9ed485.png)

String fields contains passwords, or other single line string. And Secure note, contains fiels like PGP keys or SSL certificate.

But all off that can be split in multiple entry and put all together in a group. 
However, I thinks it isn't very "ergonomics"

**Comment by bryanmathers** [comment]
Moved to:
https://community.passbolt.com/t/as-a-logged-in-user-i-can-have-multiple-secrets-for-a-single-entry/37
(plus other stories)
