### ISSUE TITLE
DB update policy violated - updating 1.6.0 to 1.6.4 includes DB changes?

### ISSUE THREAD

**Issue by et304383** [passbolt/passbolt_api#166]
https://www.passbolt.com/help/tech/update

According to this, going from 1.6.0 to 1.6.4 should only be a patch update and not include schema changes.

However, I did the update then got an error on the healthcheck page:

The database schema is not up to date.

Sure enough, a schema update is required:

```
[root@ip-10-121-64-17 passbolt]# ./app/Console/cake Migrations.migration status
Cake Migration Shell
---------------------------------------------------------------
Application

Current version:
  #1497890584 1497890584_Migration_1.6.0
Latest version:
  #1498311597 1498311597_Migration_1.6.1
---------------------------------------------------------------
Migrations Plugin

Current version:
  #003 003_increase_class_name_length
Latest version:
  #003 003_increase_class_name_length
---------------------------------------------------------------
[root@ip-10-121-64-17 passbolt]# 
```

I'm not saying you can't update the DB, but the documentation clearly states that this patch update should not have included schema changes.

**Comment by stripthis** [comment]
Yes we are aware of this, this was done on purpose since 1.6.1 migration is non-breaking and backward compatible with 1.6.0, even if the healtcheck is complaining. We'll avoid doing this in the future as this is confusing.

**Comment by et304383** [comment]
OK great.  Thanks for clarifying.
