### ISSUE TITLE
On Passbolt 1.6.4 I can't add a password with the username including a plus (+) character

### ISSUE THREAD

**Issue by et304383** [passbolt/passbolt_api#168]
We liberally use plus (+) characters in various email addresses used to signup for services.

Passbolt is rejecting this in both the username and comment fields for some reason.

Please, this is absolutely required.

**Comment by stripthis** [comment]
Hi @et304383, thank your for your contribution. We're planning to allow any utf8 char in passbolt v2 (and even utf8 extended in some fields). We will most likely squeeze your change (and \ char) to a version before that. Thank you for your patience.

**Comment by et304383** [comment]
Hey thanks for the notice, but we really can't wait.  We're trying to migrate our passwords now.

We're going to use my fork for now.  I really hope you can merge it in.  We need this today though.

**Comment by cedricalfonsi** [comment]
Fixed with v1.6.5.
