### ISSUE TITLE
As a logged in user I should be able to select a given resource using URLs

### ISSUE THREAD

**Issue by claudiutraistaru** [passbolt/passbolt_api#171]
This could be included in the emails sent on shared password , or would be easier by a user to send the direct url of the credentials from passbolt to another user.

**Comment by stripthis** [comment]
Example: /home/passwords/[uuid_of_resource] should open the password workspace with that ressource selected. Something similar for user records would be nice too.

Ref. PASSBOLT-2418

**Comment by bryanmathers** [comment]
Moved to:
https://community.passbolt.com/t/as-a-logged-in-user-i-should-be-able-to-select-a-given-resource-using-urls/34
(and lots of others there too)
