### ISSUE TITLE
404 error after installation

### ISSUE THREAD

**Issue by tpape** [passbolt/passbolt_api#172]
Hello ! 
I'm trying to install Passbolt on my server. PHP7 is installed.
After following all of the instructions, I got my URL after creating the first user, but when I try to reach it with my browser all I get is a 404 error. Same issue with this URL : `https://10.207.86.150/users/login`.
I tested my PHP server with this index.php :` <?php phpinfo(); ?>`, and it seems to work well...
Here is the report of the Healthcheck scan. My server is not connected to the internet, is it a problem ?

Thanks for the project, and I hope you will  be able to help me.

-------------------------------------------------------------

 Open source password manager for teams
---------------------------------------------------------------
 Healthcheck shell
---------------------------------------------------------------

 Environment

 [PASS] PHP version 7.0.22-0ubuntu0.16.04.1
 [PASS] PCRE compiled with unicode support
 [PASS] The app/tmp directory is writable
 [PASS] The app/webroot/img/public directory is writable

 Config files

 [PASS] The core config file is present
 [PASS] The database config file is present
 [PASS] The email config file is present
 [PASS] The application config file is present

 Core config

 [PASS] Debug mode is off.
 [PASS] Cache is working.
 [PASS] Unique value set for security.salt
 [PASS] Unique value set for security.cipherSeed
 [PASS] Full base url is set to https://10.207.86.150
 [PASS] App.fullBaseUrl validation OK.
 **[FAIL] Could not reach the /healthcheck/status with the url specified in App.fullBaseUrl
  [HELP] Check that the domain name is correct in app/Config/core.php
  [HELP] Check the network settings**

 SSL Certificate

 **[FAIL] SSL peer certificate does not validate
 [FAIL] Hostname does not match when validating certificates.
 [WARN] Using a self-signed certificate**

 Database

 [PASS] Configured to use a supported database backend
 [PASS] The application is able to connect to the database
 [PASS] Not using a prefix for database tables
 [PASS] 20 tables found
 [PASS] Some default content is present
 [PASS] The database schema up to date.

 GPG Configuration

 [PASS] PHP GPG Module is installed and loaded
 [PASS] The server gpg key is not the default one
 [PASS] The environment variable GNUPGHOME is set to /home/www-data/.gnupg
 [PASS] The directory containing the keyring is writable by root.
 [PASS] The public key file is defined in app/config.php and readable.
 [PASS] The public key file is defined in app/config.php and readable.
 [PASS] The server key fingerprint matches the one defined in app/config.php.
 [PASS] There is a valid email id defined for the server key.

 Application configuration

 **[FAIL] Could not connect to passbolt repository to check versions. It is not possible check if your version is up to date.**
  [HELP] Check the network configuration to allow this script to check for updates
 **[FAIL] Passbot is not configured to force SSL use
  [HELP] Set App.ssl.force to true in app/Config/app.php**
 [PASS] App.fullBaseUrl is set to HTTPS
 [PASS] Selenium API endpoints are disabled.
 [PASS] Search engine robots are told not to index content.
 [PASS] Registration is closed, only administrators can add users.
 [PASS] Serving the compiled version of the javascript app
 [PASS] All email notifications will be sent.

 Development Tools (optional)

 [PASS] Phpunit is installed
 [PASS] Phpunit version is 3.7.38

  5 error(s) found. Hang in there!

**Comment by kevinmuller** [comment]
Hi @tpape 

It could be many things. I'd be more enclined to think that it's a url rewriting issue. What is your operating system / http server ?

**Comment by tpape** [comment]
I feel a bit stupid, i forgot to check rewrite mod... It's a ubuntu 16.04
server with apache2, now it's good. Thanks, and sorry for the issue...

2017-09-15 13:24 GMT-03:00 Kevin Muller <notifications@github.com>:

**Comment by Dexirian** [comment]
@tpape How did you fix this issue exactly? I'm having the same exact issue and cannot figure it out

**Comment by tpape** [comment]
I enabled the rewrite mod on apache (something like a2enmod rewrite, i
can't remember the exact name of the module but a quick search helped me)

**Comment by huangy10** [comment]
Same issue with Nginx. Rewrite mod is not enable to redirect non-file request to index.php file. To fix this problem, add the following configuration to server:

```nginx
if (!-e $request_filename)
    {
            # If the requested path is not a file, then pass it as a parameter to index.php
            rewrite ^(.*)$ /index.php?s=$1 last;
    }
```
