### ISSUE TITLE
The following passbolt template is missing or not included: setup/importKeyRecoverInfo.ejs

### ISSUE THREAD

**Issue by ktosiek** [passbolt/passbolt_api#175]
I'm filling an issue as this might be interesting, I haven't linked this to any problem.

When trying to recover an account, on the key input page, I'm seeing this error in the console:
`The following passbolt template is missing or not included: setup/importKeyRecoverInfo.ejs`

I found this because I had a problem with the "Browse" button, but I can't reproduce it now.

**Comment by cedricalfonsi** [comment]
Hi @ktosiek,
Thanks for your report.
We added the task PASSBOLT-2423 in our ticketing system to take care of it.

**Comment by stripthis** [comment]
v1.6.6 fix this issue. Thank you for your contribution @ktosiek.
