### ISSUE TITLE
As a firefox user i want to use passbolt without allowing 3rd party cookies for every website

### ISSUE THREAD

**Issue by rotanid** [passbolt/passbolt_api#177]
as lined out in #143 i am unable to use passbolt in firefox as long as i don't enable third/3rd party cookies.
privacy sensible users don't want to enable this for every website, not even the variant "only visited websites"

**Comment by stripthis** [comment]
Hi @rotanid, it is not something we can change easily as the url of the background page in extension (chrome-url://uuid) is different than your passbolt instance url and therefore considered third party. In the future we will support cookie-less session-less authentication, but not in this year. In the meantime have you tried adding a specific exception for your domain?

<img width="689" alt="screen shot 2017-10-02 at 09 55 57" src="https://user-images.githubusercontent.com/77410/31068744-c0d10efc-a759-11e7-8198-61318a3b1d82.png">

**Comment by rotanid** [comment]
which domain would have to be added? the domain passbolt is running on or the chrome-url://uuid  or both?

**Comment by stripthis** [comment]
That will be the domain your passbolt instance is running on. Thank you for trying it out, let us know if it work.

**Comment by rotanid** [comment]
that works, adding the complete URL as an exception, thanks!
