### ISSUE TITLE
Could not validate the controller log

### ISSUE THREAD

**Issue by sfhaider** [passbolt/passbolt_api#178]
I set up a new instance and had some difficulties with getting the gpg keys set up (I created multiple keys, eventually delete them all except for the one I got one working correctly). I also deleted all users in the DB (directly) from previous tests then added a new user via cake register_user and followed the url for user set up. I defined my keys, chose a passphrase, set a security token, got the success message but never got redirected to log in...
Error! Something unexpected happened. The setup cannot be completed.

When I go to /auth/login page after that, I get this error:

Could not validate the controller log {"user_id":["The UUID must be in correct format"],"role_id":["UUID must be in correct format"]} {"ControllerLog":{"level":"error","user_id":null,"role_id":null,"user_agent_id":"c48aa5b5-e7ac-344b-a43d-e86cd2de7232","ip":"172.0.3.116","method":"GET","controller":"auth","action":"login","message":"login_failure","request_data":"{\"data\":[],\"query\":[],\"params\":{\"plugin\":\"\",\"controller\":\"auth\",\"action\":\"login\",\"named\":[],\"pass\":[]}}"}}

Error: An Internal Error Has Occurred.

Stack Trace

APP/Controller/AuthController.php line 45 → ControllerLog::write(string, CakeRequest, string, string)
[internal function] → AuthController->login()
CORE/Cake/Controller/Controller.php line 491 → ReflectionMethod->invokeArgs(AuthController, array)
CORE/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
CORE/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(AuthController, CakeRequest)
APP/webroot/index.php line 111 → Dispatcher->dispatch(CakeRequest, CakeResponse)

Here's my healthcheck:

Passbolt API Status

Environment

PHP version 5.6.30-0+deb8u1
PCRE compiled with unicode support
The temporary directory and its content are writable
The public image directory and its content are writable
SSL access is enabled.
Config files

The core config file is present
The database config file is present
The email config file is present
The application config file is present
Core config

Debug mode is on.
Cache is working.
Unique value set for security.salt
Unique value set for security.cipherSeed
Full base url is set to https://passbolt.pllock.com
App.fullBaseUrl validation OK.
/healthcheck/status is reachable.
Database

Configured to use a supported database backend
The application is able to connect to the database
Not using a prefix for database tables
20 tables found
Some default content is present
The database schema up to date.
GPG Configuration

PHP GPG Module is installed and loaded
The server gpg key is not the default one
The environment variable GNUPGHOME is set to /home/www-data/.gnupg
The directory /home/www-data/.gnupg containing the keyring is writable by the user the webserver is running as.
The public key file is defined in app/config.php and readable.
The private key file is defined in app/config.php and readable.
The server key fingerprint matches the one defined in app/config.php.
The server key defined in the app/Config.php is in the keyring.
There is a valid email id defined for the server key.
The public key can be used to encrypt and sign a message.
The private key can be used to decrypt a message.
Application configuration

Using latest passbolt version (1.6.5)
Passbolt is configured to force SSL use
App.fullBaseUrl is set to HTTPS
Selenium API endpoints are disabled.
Search engine robots are told not to index content.
Registration is closed, only administrators can add users.
Serving the compiled version of the javascript app
All email notifications will be sent.
Development Tools (optional)

Phpunit is installed
Phpunit version is 3.7.38

any idea?

**Comment by stripthis** [comment]
There seems to be an issue with the user that got created via the command line since at the end of the setup the message show an empty user id and empty role id. I'm not sure what could cause this, I invite you retry by following one of the tutorial on the installation manual and reopen an another issue if you still encounter the issue.

http://www.passbolt.com/help/tech/install

**Comment by sfhaider** [comment]
Ended up nuking it and doing a clean install and it worked. Still scratching my head as to what would cause that error however. Oh well...

**Comment by stripthis** [comment]
@sfhaider gremlins? 
I'll keep an eye open in case someone report this behavior again. Thanks for the update.

**Comment by huoming** [comment]
I have the same problem.

**Comment by jcbreel** [comment]
Same issue here. Anyone?
