### ISSUE TITLE
The server key defined in the app/Config.php is not in the keyring

### ISSUE THREAD

**Issue by lanaiscool** [passbolt/passbolt_api#179]
im getting this error however when i run gpg --home /home/www-data/.gnupg --import /var/www/passbolt/app/Config/gpg/private.key it says it is already imported into the keyring what do i do ?

[FAIL] The server key defined in the app/Config.php is not in the keyring
  [HELP] Import the private server key in the keyring of the user the webserver is running as.
  [HELP] you can try:
  [HELP] sudo su -s /bin/bash -c "gpg --home /home/www-data/.gnupg --import /var/www/passbolt/app/Config/gpg/private.key" www-data

**Comment by cedricalfonsi** [comment]
Hello,

Thanks for trying out passbolt.

Can you please give us more details regarding : 
- The linux OS & version
- The name of the user running the web server
- The entire healthcheck report
- The app/Config/app.php (Obfuscate the fingerprint).

**Comment by stripthis** [comment]
@lanaiscool do you still need help?

**Comment by lanaiscool** [comment]
not with this i fixed this issue it can be closed
