### ISSUE TITLE
[FAIL] SSL peer certificate does not validate

### ISSUE THREAD

**Issue by kingfisher77** [passbolt/passbolt_api#180]
Hi,

we just installed Passbolt 1.6.5 successfully on CentOS 7.3. Everything looks trustworty and seems to work properly. Eager to go in production.

Just one thing:

```
$ app/Console/cake passbolt healthcheck
[...]
 SSL Certificate

 [FAIL] SSL peer certificate does not validate
 [FAIL] Hostname does not match when validating certificates.
 [WARN] Using a self-signed certificate
  [HELP] stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://our.internal.domain:443 (Unknown error)
[...]
```
Components are:
CentOS 7.3
nginx 1.13.5
php 7.0.24

We utilize a self signed certificate for internal server which is signed by a self signed root ca certificate. We already added our Certificate Authority (visible in /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt). This is normaly not needed but maybe for Passbolt?

What can be the reason for the error message?

**Comment by stripthis** [comment]
We use generic healthcheck tests to act as a safety net for people that forget to configure SSL. If you are confident about your configuration it is probably a false positive. You can use more specialized tools than passbolt to verify your SSL config.

**Comment by kingfisher77** [comment]
We solved the issue. Passbolt brings an custom cacert.pem. By replacing /lib/Cake/Config/cacert.pem with the version from the os which includes our self signed ca the Passbolt healthcheck ends with

`No error found. Nice one sparky!`

**Comment by RamonAbudAlcala** [comment]
Just for the record. @kingfisher77's comment helped me find the correct place for the CA certificate. I was having a similar problem and with the Docker install. And solved it by adding the personal and local CA root authority that I use at home to the docker-compose file as follows:

```
passbolt:
 ...
  volumes:
     ...
      # SSL
      - /home/passbolt/certs/passbolt-cert.pem:/etc/ssl/certs/certificate.crt:ro
      - /home/passbolt/certs/passbolt-cert-key.pem:/etc/ssl/certs/certificate.key:ro
      - /home/passbolt/certs/ca.pem:/usr/share/php/passbolt/vendor/composer/ca-bundle/res/cacert.pem:ro
```

Now I have a full pass health check :)
