### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by kingfisher77** [passbolt/passbolt_api#181]
Hi again,

we are eager to go in production with Passbolt 1.6.5. But is this a good idea? It is still carrying "Alpha" badge. Does anyone use Passbolt already on a daily base with a team?

**Comment by stripthis** [comment]
Many organization are already using passbolt in production. Wether this is desirable in your case depends on your threat model and functional requirements. See the answer in the faq: http://www.passbolt.com/faq#security

**Is it secure to use passbolt in its current version?**

Currently passbolt is in “alpha”, which means it is not yet a completely finished product. While we encourage you to try it out, the answer to whether you should store critical information with it depends on your security level requirements.

For instance, if your team currently stores its passwords in plaintext, passbolt will definitely be an improvement. Similarly, if you plan to host passbolt in way that it is only accessible on your local machine or network or via a VPN, then the security level is also likely to be appropriate.

On the other hand if you have very high security requirements, for example if you are dealing with systems holding credit card information, or if you are a human-rights organisation, you may want to wait until an independent code review is done before starting using passbolt!
