### ISSUE TITLE
Copy username

### ISSUE THREAD

**Issue by kingfisher77** [passbolt/passbolt_api#182]
Automatically filling the username and the password in a website is nothing we would expect from Passbolt currently like e.g. 1password does.

But copying the password and login manually could be easier.

Copying the password in the clipboard is easy by clicking on the dots in the list but what is with the username? It is not possible to highlight the username in the list and then copy it to the clipboard. We have to checkbox the entry, clicking "more" and then again clicking "copy login to clipboard".

Is there a better way? Do we overlook something obvious? :)

**Comment by stripthis** [comment]
Hello @kingfisher77, you can also right click on a row and it will open a menu where you can see "copy username" among other things.
