### ISSUE TITLE
As an admin i should be able to add an group to a group 

### ISSUE THREAD

**Issue by kingfisher77** [passbolt/passbolt_api#183]
It would be very handy to manage groups by adding groups. We have a couple of core teams which should have access to passwords in several groups where different customer passwords are going to be managed. Adding each user in each customer group is a lot of clicking and hard to maintain properly.

**Comment by passboltUser** [comment]
Groupception

**Comment by bryanmathers** [comment]
Moved to:
https://community.passbolt.com/t/as-an-admin-i-should-be-able-to-add-a-group-to-a-group/33
(and lots of others there too)
