### ISSUE TITLE
Password "Types"... ssl certificates, ssh, ftp, pin . . or template ability

### ISSUE THREAD

**Issue by keimond** [passbolt/passbolt_api#184]
Hello, I saw that the ability to add secret notes was in the backlog but also wanted to see if something was on the horizon to add other "types".. For example let's say I want to add the pin number to a site (technically I could use a secret note here.. but it would be cool to say this type of entry is for a "pin")

Basically like what Thycotic Secret Server has with the ability to add certain types.. 

One that I like is an SSL cert and then having a field for adding the CSR, CRT, and KEY . . . then when we deploy or redeploy a server with ansible, ansible is able to pull those from the password server :)

Thinking about all this, what if the user had the ability to make a template, they can define their own "types" and put any number of fields they like in that template.

Thanks
   Keimond

**Comment by stripthis** [comment]
Yes that's pretty much the plan: we will allow admin to create any secret format, and present a form based on the metadata they select (field type and validation rules). We will provide a few base types by default such as passwords (url, login, password), credit card (owner, card number, etc.), notes (textarea), and people can create their own. This will not be available soon, but that's our long term vision.

**Comment by prSchoene** [comment]
+1

**Comment by ekwus** [comment]
Apologies for raising the duplicate, I did have a look over the titles and read any I thought were the same.

This would be a great addition to the system!!

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-an-administrator-i-can-create-new-secret-types-and-define-their-associated-fields/19
