### ISSUE TITLE
The server was unable to respect the authentication protocol. HTTP Error 500

### ISSUE THREAD

**Issue by ilyansolo** [passbolt/passbolt_api#185]
Trying to make passbolt running but having The server was unable to respect the authentication protocol. HTTP Error 500.

Environment details:
VM inside ESXi 6.5
Debian Wheezy
Apache2
MySQL
PHP 5.6
Passbolt 1.6.5

Healthcheck report (note, i switched it to HTTP to rule out any SSL cert issues, but it didn't help):
---------------------------------------------------------------
 Healthcheck shell
---------------------------------------------------------------

 Environment

 [PASS] PHP version 5.6.31-1~dotdeb+7.1
 [PASS] PCRE compiled with unicode support
 [PASS] The temporary directory and its content are writable
 [PASS] The public image directory and its content are writable

 Config files

 [PASS] The core config file is present
 [PASS] The database config file is present
 [PASS] The email config file is present
 [PASS] The application config file is present

 Core config

 [PASS] Debug mode is off.
 [PASS] Cache is working.
 [PASS] Unique value set for security.salt
 [PASS] Unique value set for security.cipherSeed
 [PASS] Full base url is set to http://MY_DOMAIN
 [PASS] App.fullBaseUrl validation OK.
 [PASS] /healthcheck/status is reachable.

 SSL Certificate

 [PASS] SSL peer certificate validates
 [PASS] Hostname is matching in SSL certificate.
 [PASS] Not using a self-signed certificate

 Database

 [PASS] Configured to use a supported database backend
 [PASS] The application is able to connect to the database
 [PASS] Not using a prefix for database tables
 [PASS] 20 tables found
 [PASS] Some default content is present
 [PASS] The database schema up to date.

 GPG Configuration

 [PASS] PHP GPG Module is installed and loaded
 [PASS] The server gpg key is not the default one
 [PASS] The environment variable GNUPGHOME is set to /home/www-data/.gnupg
 [PASS] The directory /home/www-data/.gnupg containing the keyring is writable by the user the webserver is running as.
 [PASS] The public key file is defined in app/config.php and readable.
 [PASS] The private key file is defined in app/config.php and readable.
 [PASS] The server key fingerprint matches the one defined in app/config.php.
 [PASS] The server key defined in the app/Config.php is in the keyring.
 [PASS] There is a valid email id defined for the server key.
 [PASS] The public key can be used to encrypt and sign a message.
 [PASS] The private key can be used to decrypt a message.

 Application configuration

 [PASS] Using latest passbolt version (1.6.5)
 [FAIL] Passbot is not configured to force SSL use
  [HELP] Set App.ssl.force to true in app/Config/app.php
 [FAIL] App.fullBaseUrl is not set to HTTPS
  [HELP] Check App.fullBaseUrl url scheme in app/Config/core.php
 [PASS] Selenium API endpoints are disabled.
 [PASS] Search engine robots are told not to index content.
 [PASS] Registration is closed, only administrators can add users.
 [PASS] Serving the compiled version of the javascript app
 [PASS] All email notifications will be sent.

 Development Tools (optional)

 [PASS] Phpunit is installed
 [PASS] Phpunit version is 3.7.38

  2 error(s) found. Hang in there!

**Comment by cedricalfonsi** [comment]
Everything looks good regarding your healthcheck, the SSL issues are not a blocker here.

To investigate this issue I'll need more information :
- Browser type and version
- If FF do you authorize third party cookies ?
- The browser debug trace
- The cake php error log located in app/tmp
- The entropy level of your VM : `cat /proc/sys/kernel/random/entropy_avail`

**Comment by ilyansolo** [comment]
HI,
Browser: Chrome 64-bit 61.0.3163.100
Browser debug trace - i suppose it's a har file from chrome? it's exporting incomplete JSON, bust still, see attached.
[har_trace.zip](https://github.com/passbolt/passbolt_api/files/1375439/har_trace.zip)


Error log:
2017-10-11 06:44:56 Error: [InternalErrorException] The GnuPG key for the user could not be imported
Request URL: /auth/login.json
Stack Trace:
#0 /var/www/passbolt/app/Controller/Component/Auth/GpgAuthenticate.php(96): GpgAuthenticate->_setUserKey('9225ea13a840e1e...', Array)
#1 /var/www/passbolt/lib/Cake/Controller/Component/AuthComponent.php(770): GpgAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#2 /var/www/passbolt/lib/Cake/Controller/Component/AuthComponent.php(611): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#3 /var/www/passbolt/app/Controller/AuthController.php(35): AuthComponent->login()
#4 [internal function]: AuthController->login()
#5 /var/www/passbolt/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(AuthController), Array)
#6 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AuthController), Object(CakeRequest))
#8 /var/www/passbolt/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}

Entropy level: 180

**Comment by stripthis** [comment]
Looks like PHP GNUPG is not able to import that particular user public key. Could you attach a copy of the public key for this user? Did you generate that key during the setup or did you import it?

**Comment by ilyansolo** [comment]
Key was generated a new as i tried to install passbolt into a different directory from /var/www and failed miserably for reason i don't understand.

Question - how do i get to the public key for a specific user?

**Comment by stripthis** [comment]
Two options:
- From the client side (if have downloaded the private key during the setup) you can import the key into any GnuPG keyring tools and then export the public key section. 
- From the server side: you can look in the mysql database under the gpgkeys table. You should find the key that match your user ids of course. (see table users and map it to gpgkeys.user_id).

**Comment by stripthis** [comment]
@ilyansolo also the entropy level on this machine is very low, maybe gpg doesn't like that.

**Comment by ilyansolo** [comment]
here is the key
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: OpenPGP.js v2.5.11
Comment: https://openpgpjs.org

xsBNBFneEsYBCADHRG6MWDIbwFeY94gonwBjjE2DmsZ43HxNInp4NPLfbaio
fSIELJYfIda5bptFA8d6vk2iuSr10+xUEPbWB5BsqAEDB9zHhYazPfkoQ2jv
Nx7gk0G0xD3tu5mOVucZvbajldpxV276gD9X8F0ftFa7xsyFTkS/GKiZiIIF
7u4Nd0vDar0BXej7RJdeTJimXiKA1NsRwZGzyIf/fd6IWWxhgDBz01Eo5yQJ
+6bpiQ1tP6WulvUYnk66/TXyvGX8pkt2Tqc1xX5LeqTccRTFGx2j7bwYaQic
NQVWfGtEIqtAjGlVvHoB8g3CR/mPvXX3er02fHVxfwwVWokY/if67uI/ABEB
AAHNHUpvaG4gRG9lIDxzb21lb25lQGRvbWFpbi5jb20+wsB1BBABCAApBQJZ
3hLHBgsJBwgDAgkQvjd1lOK39QAEFQgKAgMWAgECGQECGwMCHgEAAG5bB/4i
6PsAzCD9Jh4vfDSDr/XT5WHou9NiNmtbGljdIW8E0lDyZNNWLnZvakW8ZRUx
iiuhpAm0d4+Gj086miWbLt0dO8iFMgId7FDJYmC7HlQWodkxTARSut8SDqeJ
q3cr7Gxd5MMq/eLaHs/ZopMrvic6hqqFSulTpVMp/ZyO1rU7hy2XDQSoLLfu
c+6UlOOGSOq+MtoyHtsXFmshiqlYo2VYP5KWEZVXSnzTZrGjzxU2UB9KFD9q
qI0zwpYJ9CSK4MZ1FYFyTm0qbl7BgZGaJVCCA53vOQjDzXOPTM+aqPg9lgf3
1SYuz6KGZWTF8hmrLv/vh8Fh/7tnrs0wB0UR+mlXzsBNBFneEsYBCAC1E+Bp
KizY0sHUMJQNthEx4z9Jn5ejhDKj/LKzC4sd+mf/nMa+BcR5bfhHpXKGP05m
e8iwresQWgdtldt6YOwMe34d6ZIjhawX0ZwbV4OcPcOxj/hN7Zr3PWFy7RaP
m1qxCovryIQRi0qQTQlG94gMT+2cKTObHIV7s34Ql8vviI1OD9Do4nEsFbMz
bPcQtfC41AQirIKPU82geEPIkzwb3TfvMnyrds7MUp2lbll/4V0l7kgxRGkp
XRbsohLVwMhhTNDYYOYIzAm65sfCfGrX+m3PKzHJFZs0JnuacU8l1vls+Iep
kNvEV/70Wqu80a6Qd7CW48Mo8ib12+3TiPBxABEBAAHCwF8EGAEIABMFAlne
EscJEL43dZTit/UAAhsMAAB9Gwf9EDjfH26hY37Uqqxzoop1AO6/oQy4/ok3
r5l8rnxM+7CXSIu1K7A7qnvH5gN3sYHVQxK31Hm6OuMd8iYzr6XFL4+R3wKE
Z6y6WNb67nmPPOHSJbb/uBlMQi/w8wb2yTp3IIbRWI5TlcZz9tPcfhFkJdfE
HRkEHYDYkwZv9KwuFKFCdwtWymMyi438VKm9XK/VqrQ8Yp3vm2uCv1b4mGMb
oJj/Ly9mcqOJMXLjayTvJYQzNwSM13C78o1nMEXTHzmfwdtzqVIIz61nXEkg
TsQgzD5FZoYswq6Xgmqt489QTzkKXfzXmA7zct7Ur8f2XPQs61cWZIgzhv4x
qoQQriqklw==
=I1Hn
-----END PGP PUBLIC KEY BLOCK-----

the low entropy idea is...curious but i can't seem to grasp how to mitigate it :(

**Comment by ilyansolo** [comment]
Is there anything else i can provide to investigate this issue? Pretty much it's a full showstopper for me to proceed with evaluating the product as i can't even login for the first time :(
Thanks!

**Comment by cullam3n** [comment]
I recently installed it and I had that issue as well, my config was a little bit different but here are the things I did to get it to work.

CentOS7 LXC container under Proxmox 4.4
nginx
MariaDB
PHP7

1. The entropy was too low in the VM.  I had to use rng-tools on the Proxmox host and generate the gpg keys there, and then moved them into the VM.  Use `cat /proc/sys/kernel/random/entropy_avail` to make sure you have enough (mine worked with 1700+). 
2. The nginx logs were showing it was blocking the connection to localhost:9000, this was due to SELinux.  Allowing an exception (or disabling SELinux) was the fix on this one.

**Comment by ilyansolo** [comment]
Alright, thanks cullam3n, it was an entropy issue.
Horrible thing to think about.

**Comment by superhawk610** [comment]
@cullam3n @ilyansolo I'm having the same issue, and after enabling rng tools my entropy is 3091 but I am still running into this issue - I'm getting the HTTP 500 error when attempting to log in, and I see "The GnuPG key for the user could not be imported" in the error log. Any other ideas?

**Comment by ilyansolo** [comment]
From the looks of it i'd say it's a different problem which still crashes the app. Your config file maybe wrong or something...
Anyway, i am not using the passbolt, it's too complicated and immature functionality-wise so can't help any further

**Comment by stripthis** [comment]
@superhawk610 I would say either there is a problem with the key itself or the keyring is not writable/accessible for the web server user.

**Comment by DMKmod** [comment]
Hey guys! I have experienced same issue.
OracleVBox
Centos7 VM
PHP7
Nginx
MariaDB
Entropy avail 3132
and I have to agree with @ilyansolo regarding immaturity of the product, looks like it adds more problems than solves.

**Comment by stripthis** [comment]
If you experience similar issues please open a request for help on the community forum.
https://community.passbolt.com with information about your system, what you have tried to fix the issues, etc.
