### ISSUE TITLE
Support for U2F keys

### ISSUE THREAD

**Issue by ninjanerdbgm** [passbolt/passbolt_api#186]
I know two-factor auth is in the roadmap, but it says it will be utilizing our phones for it. I request that there also be support for U2F authentication as well.

**Comment by sgalam** [comment]
+1

**Comment by ekwus** [comment]
+1, strangely enough we do have engineers that don't have mobile phones!

**Comment by bryanmathers** [comment]
Moved to:
https://community.passbolt.com/t/two-factor-authentication/32
(and lots of others there too)
