### ISSUE TITLE
 error after install

### ISSUE THREAD

**Issue by shin2344234** [passbolt/passbolt_api#187]
After install i am getting a  error. I have the healthcheck output below. 

I set the url to the ip without a port. i tried with 8085 and 8081 to the same issue. Did i miss something?
[root@localhost` passbolt]#  su -s /bin/bash -c "app/Console/cake passbolt healthcheck" nginx
---------------------------------------------------------------
     ____                  __          ____
    / __ \____  _____ ____/ /_  ____  / / /_
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /
 /_/    \__,_/____/____/_.___/\____/_/\__/

 Open source password manager for teams
---------------------------------------------------------------
 Healthcheck shell
---------------------------------------------------------------

 Environment

 [PASS] PHP version 7.0.23
 [PASS] PCRE compiled with unicode support
 [PASS] The temporary directory and its content are writable
 [PASS] The public image directory and its content are writable

 Config files

 [PASS] The core config file is present
 [PASS] The database config file is present
 [PASS] The email config file is present
 [PASS] The application config file is present

 Core config

 [PASS] Debug mode is off.
 [PASS] Cache is working.
 [PASS] Unique value set for security.salt
 [PASS] Unique value set for security.cipherSeed
 [PASS] Full base url is set to http://192.168.5.221
 [PASS] App.fullBaseUrl validation OK.
 [FAIL] Could not reach the /healthcheck/status with the url specified in App.fullBaseUrl
  [HELP] Check that the domain name is correct in app/Config/core.php
  [HELP] Check the network settings

 SSL Certificate

 [FAIL] SSL peer certificate does not validate
 [FAIL] Hostname does not match when validating certificates.
 [WARN] Using a self-signed certificate

 Database

 [PASS] Configured to use a supported database backend
 [PASS] The application is able to connect to the database
 [PASS] Not using a prefix for database tables
 [PASS] 20 tables found
 [PASS] Some default content is present
 [PASS] The database schema up to date.

 GPG Configuration

 [PASS] PHP GPG Module is installed and loaded
 [PASS] The server gpg key is not the default one
 [PASS] The environment variable GNUPGHOME is set to /var/cache/nginx/.gnupg
 [PASS] The directory /var/cache/nginx/.gnupg containing the keyring is writable by the user the webserver is running as.
 [PASS] The public key file is defined in app/config.php and readable.
 [PASS] The private key file is defined in app/config.php and readable.
 [PASS] The server key fingerprint matches the one defined in app/config.php.
 [PASS] The server key defined in the app/Config.php is in the keyring.
 [PASS] There is a valid email id defined for the server key.
 [PASS] The public key can be used to encrypt and sign a message.
 [PASS] The private key can be used to decrypt a message.

 Application configuration

 [PASS] Using latest passbolt version (1.6.5)
 [FAIL] Passbot is not configured to force SSL use
  [HELP] Set App.ssl.force to true in app/Config/app.php
 [FAIL] App.fullBaseUrl is not set to HTTPS
  [HELP] Check App.fullBaseUrl url scheme in app/Config/core.php
 [PASS] Selenium API endpoints are disabled.
 [PASS] Search engine robots are told not to index content.
 [PASS] Registration is closed, only administrators can add users.
 [PASS] Serving the compiled version of the javascript app
 [PASS] All email notifications will be sent.

 Development Tools (optional)

 [PASS] Phpunit is installed
 [PASS] Phpunit version is 3.7.38

  5 error(s) found. Hang in there!

**Comment by stripthis** [comment]
Which error are you getting?

**Comment by shin2344234** [comment]
Apologies, i am getting a 500 error when visiting the default page http://192.168.5.221

**Comment by stripthis** [comment]
Can you paste the detail of that error from the log? (see. app/tmp/log/error.log )

**Comment by shin2344234** [comment]
only thing there is an empty file. 

[root@localhost logs]# ll
total 0
-rw-r--r--. 1 nginx nginx 0 Oct 12 10:21 empty

**Comment by stripthis** [comment]
That's not normal. Can you check the apache error log maybe?

**Comment by shin2344234** [comment]
using nginx as the site tutorial suggests. The pid issue was because i started nginx with the start command in the tutorial but switch it to the systemctl start. 
2017/10/12 10:35:24 [emerg] 27574#27574: open() "/var/run/nginx.pid" failed (13: Permission denied)
2017/10/12 10:38:10 [notice] 27698#27698: signal process started
2017/10/12 10:59:50 [notice] 28523#28523: signal process started

nothing there to point to anything.

**Comment by shin2344234** [comment]
php-fpm log
  thrown in /var/www/passbolt/lib/Cake/Cache/Cache.php on line 186
[12-Oct-2017 16:02:39 UTC] PHP Warning:  _cake_core_ cache was unable to write 'cake_dev_en-us' to File cache in /var/www/passbolt/lib/Cake/Cache/Cache.php on line 327
[12-Oct-2017 16:02:39 UTC] PHP Warning:  /var/www/passbolt/app/tmp/cache/persistent/ is not writable in /var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php on line 385
[12-Oct-2017 16:02:39 UTC] PHP Fatal error:  Uncaught CacheException: Cache engine "_cake_core_" is not properly configured. Ensure required extensions are installed, and credentials/permissions are correct in /var/www/passbolt/lib/Cake/Cache/Cache.php:186
Stack trace:
#0 /var/www/passbolt/lib/Cake/Cache/Cache.php(151): Cache::_buildEngine('_cake_core_')
#1 /var/www/passbolt/app/Config/core.php(400): Cache::config('_cake_core_', Array)
#2 /var/www/passbolt/lib/Cake/Core/Configure.php(72): include('/var/www/passbo...')
#3 /var/www/passbolt/lib/Cake/bootstrap.php(432): Configure::bootstrap(true)
#4 /var/www/passbolt/app/webroot/index.php(98): include('/var/www/passbo...')
#5 /var/www/passbolt/index.php(41): require('/var/www/passbo...')
#6 {main}
  thrown in /var/www/passbolt/lib/Cake/Cache/Cache.php on line 186
[12-Oct-2017 16:02:45 UTC] PHP Warning:  _cake_core_ cache was unable to write 'cake_dev_en-us' to File cache in /var/www/passbolt/lib/Cake/Cache/Cache.php on line 327
[12-Oct-2017 16:02:45 UTC] PHP Warning:  /var/www/passbolt/app/tmp/cache/persistent/ is not writable in /var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php on line 385
[12-Oct-2017 16:02:45 UTC] PHP Fatal error:  Uncaught CacheException: Cache engine "_cake_core_" is not properly configured. Ensure required extensions are installed, and credentials/permissions are correct in /var/www/passbolt/lib/Cake/Cache/Cache.php:186
Stack trace:
#0 /var/www/passbolt/lib/Cake/Cache/Cache.php(151): Cache::_buildEngine('_cake_core_')
#1 /var/www/passbolt/app/Config/core.php(400): Cache::config('_cake_core_', Array)
#2 /var/www/passbolt/lib/Cake/Core/Configure.php(72): include('/var/www/passbo...')
#3 /var/www/passbolt/lib/Cake/bootstrap.php(432): Configure::bootstrap(true)
#4 /var/www/passbolt/app/webroot/index.php(98): include('/var/www/passbo...')
#5 /var/www/passbolt/index.php(41): require('/var/www/passbo...')
#6 {main}

**Comment by shin2344234** [comment]
i havent gotten those on any recent tests.

**Comment by stripthis** [comment]
I guess app/tmp is not writable for nginx. Did you run the healthcheck as nginx user? Something like:
```
su -s /bin/bash -c "app/Console/cake passbolt healtcheck" nginx
```

**Comment by shin2344234** [comment]
yeah in my opening post i posted that result.

**Comment by infectormp** [comment]
what is php-fpm run user\group?

**Comment by shin2344234** [comment]
user is apache but group is nginx

**Comment by infectormp** [comment]
php-fpm must be run with same user\group as nginx

**Comment by stripthis** [comment]
@shin2344234 please reopen this issue if @infectormp comment didn't help you to solve this issue.
