### ISSUE TITLE
Email Prefferences

### ISSUE THREAD

**Issue by peterhogg** [passbolt/passbolt_api#188]
In it's current state, especially with use in groups, passbolt sends out a lot of emails. The only option for unsubscribing seems to be to completely remove your account.

**Comment by Poeticode** [comment]
If you're using [Passbolt v1.6.2 or higher](http://www.passbolt.com/release/notes#BoomBoom), you can change what events Passbolt sends out emails for by editing `config/default.php` under EmailNotification.

**Comment by peterhogg** [comment]
Thanks,

Is it in the roadmap to expose these options on a dashboard, and allow user-specific email preferences?

**Comment by Poeticode** [comment]
Not sure if any progress is currently being made on it, but there's an enhancement issue ( ref: #59 ) for that. I also think it'd be a really nice thing to have.

@stripthis will the v3 CakePHP migration be happening soon? I'd love to work on this feature.

**Comment by stripthis** [comment]
Hi, closing this issue as this is a duplicate from #59.
@Poeticode we're on it. It should be done by the end of the month, new feature will start rolling out after that more easily. Thank you for your patience!
