### ISSUE TITLE
As a logged in user I should be able to store secure notes

### ISSUE THREAD

**Issue by p4tpr0** [passbolt/passbolt_api#19]
I'm currently exploring passbolt as a replacement for my current secret safe. I'm using "secret notes" in Apple's keychain on OS X which allows me to store all website/app passwords but also qrcodes, ssl certificates private keys, etc.
That would be an absolutely killing feature if passbolt would allow storage of more complex items than passwords!
see attached screenshot.
![exemplenote](https://cloud.githubusercontent.com/assets/5785416/18697829/6179cce4-7fc5-11e6-999e-f206c3142773.png)

**Comment by stripthis** [comment]
Thanks for the suggestion @p4tpr0. It is in indeed in the roadmap. Our current focus is the Chrome plugin and Groups, but ultimately we'll get there!

**Comment by gregsymons** [comment]
At the very least, allowing passwords longer than 50 characters would be good.

**Comment by ipshenicyn** [comment]
Secure notes  - are very helpful features. We really need it.

**Comment by direvus** [comment]
My team has just started with passbolt and this is one of the very few rough edges -- we want to store RSA private keys in passbolt, and the only thing preventing us from doing so is that passbolt replaces newlines in the password with spaces.  If newlines were preserved (i.e., multiline strings were allowed in a password) then we'd be golden.

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-a-logged-in-user-i-should-be-able-to-store-secure-notes/17
