### ISSUE TITLE
Addition of Customisation Fields for Entries

### ISSUE THREAD

**Issue by ekwus** [passbolt/passbolt_api#190]
Hi

We have a number of IT, DevOps & System Test system in-house and in the cloud and have started to use Passbolt to secure and share the various user accounts and passwords that engineers need to manage these systems.

It would be really helpful if we could also add custom fields to each entry and be able to choose if these get displayed in a summary/list view. This would help with our asset management and allow us to move away from keeping a Wiki page with machine details, etc (which used to also keep our passwords).

Example fields;

ID: TEST31
TestRails Project: some-test-run
Private IP: 10.10.2.1
VPN IP: 192.168.2.2
Operating System: Windows 10
Location: Edinburgh
Wiki Entry: http://gitlab.local/Machines/TEST31

Cheers

Dave

**Comment by stripthis** [comment]
duplicate with https://github.com/passbolt/passbolt_api/issues/184
