### ISSUE TITLE
Feature requests: UI enhancements (columns, column size, sorting)

### ISSUE THREAD

**Issue by et304383** [passbolt/passbolt_api#192]
We have some pretty long names for some of our passwords that don't fit in the given space.  The URI column is way too big and we often don't care to see all of it as long as it's clickable.

It would be nice if the UI provided the ability to resize the columns.

Also, if we could select columns to display it would be awesome.

Finally, it would be nice if the UI remembered our sorting selection.  I sort by name, leave the page and return to find the rows are not sorted.

**Comment by stripthis** [comment]
Moved to:
https://community.passbolt.com/t/as-a-logged-in-user-i-can-select-which-resource-collumn-are-displayed-in-the-workspace-grid/27
(and other stories there)
