### ISSUE TITLE
PHP Gnupg library is not installed

### ISSUE THREAD

**Issue by MenakaNibaya** [passbolt/passbolt_api#193]
I Installed every requirements for the installation(Appache ,Php7.0 ,MySql 5.7, GIT, Gnupg...) and I try this installation in Amazon ami ec2 instance and Ubuntu 16.04.But unfortunately these two time I got this same error "PHP Gnupg library is not installed" in the installation  step.I attached every screen shots here,

This one I got while cake Installation;
![installation](https://user-images.githubusercontent.com/32890985/32159684-7e52514a-bd74-11e7-9517-800ff761bf37.png)

then i run health check and I got these error list in terminal,
![healthcheck](https://user-images.githubusercontent.com/32890985/32159764-cce9309e-bd74-11e7-8336-7b38ab5ee416.png)

Please help me to solve this problem and install passbolt correct in my PC.

**Comment by stripthis** [comment]
You need to make sure you install php gnupg for both apache and the cli. See. https://medium.com/passbolt/passbolt-on-debian-8-71-from-scratch-4438dad18908
