### ISSUE TITLE
 Passbolt hangs on login

### ISSUE THREAD

**Issue by soportenq** [passbolt/passbolt_api#195]
I installed passbolt on a ubuntu 14.04 based on this guide: https://medium.com/passbolt/passbolt-on-debian-8-71-from-scratch-4438dad18908

It seems all ok, I generate the user with: "su -s / bin / bash www-data -c" app / Console / cake passbolt register_user -u egedwillo@netqual.com.ar -f support -l nq -r admin "

It gives me the url, I add the plugin, I configure the password, but when I want to login it hangs and does not advance.

Could you help me? Thank you.

![passbolt](https://user-images.githubusercontent.com/33285577/32276918-7a2a3868-beef-11e7-80a2-11f84ca34842.JPG)

**Comment by stripthis** [comment]
Hi @soportenq we're trying to keep github only for bugs for now. Can you create an issue under "installation issues" in the new support forum? https://community.passbolt.com/c/installation-issues

Also please include: healthcheck logs, and browser console output. From what i'm seeing it is likely that you have some issues with URL rewriting and that the passbolt.js script is not loading.
