### ISSUE TITLE
Deactivate users

### ISSUE THREAD

**Issue by passboltUser** [passbolt/passbolt_api#196]
It should be possible to deactivate users. In a company environment users are not deleted but disabled first.

**Comment by stripthis** [comment]
@passboltUser please use the community for feature / change request. Github will only be used for bugs from now on.
http://community.passbolt.com/

**Comment by passboltUser** [comment]
Thanks, did that now.

**Comment by stripthis** [comment]
@passboltUser please create a new issue under https://community.passbolt.com/c/backlog using the proposed format.

**Comment by passboltUser** [comment]
Hm, when I go to /backlog, I can't see where to create a new Topic. It was there, and I was able to create my first issue, but now I don't see it anymore? In my private messages it says: "Account temporarily on hold". Maybe that's the reason?

**Comment by stripthis** [comment]
Strange, your account must have caught in some spam rule. You should be fine now.

**Comment by passboltUser** [comment]
Thanks for activating. https://community.passbolt.com/t/deactivating-users/101
