### ISSUE TITLE
Server key fingerprint doesn't match

### ISSUE THREAD

**Issue by HeartOfDavid** [passbolt/passbolt_api#198]
When running install (or healthcheck), I get an error that "The server key fingerprint doesn't match the one defined in app/config.php"

I don't have a file in app called config.php. Here are the results for the healthcheck specifically for the GPG Configuration

GPG Configuration

[PASS] PHP GPG Module is installed and loaded
[PASS] The server gpg key is not the default one
[PASS] The environment variable GNUPGHOME is set the /var/www/passbolt/app/Config/gpg
[PASS] The directory /var/www/passbolt/app/Config/gpg containing the keyring is writable by the user the webserver is running as.
[PASS] The public key file is defined in app/config.php and readable.
[PASS] The private key file is defined in app/config.php and readable.
[FAIL] The server key fingerprint doesn't match the one defined in app/config.php.
 [HELP] Double check the key fingerprint, example:
 [HELP] sudo su -s /bin/bash -c "gpg --list-keys --fingerprint --home /var/www/passbolt/Config/gpg" www-data | grep -i -B 2 'SERVER_KEY_EMAIL'
 [HELP] SERVER_KEY_EMAIL: The email you used when you generate the server key.
 [HELP] See. https://www.passbolt.com/help/tech/install#toc.gpg
[PASS] The server key defined in the app/Config.php is in the keyring.
[PASS] There is a valid email id defined for the server key.
[PASS] The public key can be used to encrypt and sign a message.
[PASS] The private key can be used to decrypt a message.

**Comment by stripthis** [comment]
Hi @HeartOfDavid please use the community forum for installation issue: https://community.passbolt.com/c/installation-issues
