### ISSUE TITLE
Issue with mysql 5.7 running with sql_mode=only_full_group_by (temporary workaround)

### ISSUE THREAD

**Issue by stripthis** [passbolt/passbolt_api#20]
Currently passbolt permissions views are not SQL99 compliant and triggering the following errors when mysql sql_mode contains only_full_group_by (a default setting since 5.7):

```
[PDOException] SQLSTATE[42000]: Syntax error or access violation: 1140 In aggregated query without GROUP BY, expression #2 of SELECT list contains nonaggregated column 'UserResourcePermission.permission_id'; this is incompat\
ible with sql_mode=only_full_group_by
```

In order to run passbolt on mysql5.7 you will still need to disable the sql_mode only_full_group_by with for example the following command:

```
SET global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
```

This is a temporary workaround, we’ll try to address this in a future release.
ref. PASSBOLT-1646

**Comment by cedricalfonsi** [comment]
Fixed with v1.4.0
