### ISSUE TITLE
An Internal Error Has Occurred.

### ISSUE THREAD

**Issue by paisakya** [passbolt/passbolt_api#200]
I have installed passbolt by using https://medium.com/passbolt/passbolt-on-centos-7-with-nginx-php7-fpm-mariadb-from-scratch-7b2a9b15f3a4

I am getting error after successfully installed as passbolt healthcheck stated, Trying to access the url but getting "An Internal Error has occured"

Here is the error what I am seeing in logs 

2017-11-21 12:52:46 Error: [InternalErrorException] The GPG Server key defined in the config is not found in the gpg keyring
Request URL: /auth/login
Stack Trace:
#0 /var/www/passbolt/app/Controller/Component/Auth/GpgAuthenticate.php(49): GpgAuthenticate->_initKeyring()
#1 /var/www/passbolt/lib/Cake/Controller/Component/AuthComponent.php(770): GpgAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#2 /var/www/passbolt/lib/Cake/Controller/Component/AuthComponent.php(611): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#3 /var/www/passbolt/app/Controller/AuthController.php(35): AuthComponent->login()
#4 [internal function]: AuthController->login()
#5 /var/www/passbolt/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(AuthController), Array)
#6 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AuthController), Object(CakeRequest))
#8 /var/www/passbolt/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 /var/www/passbolt/index.php(41): require('/var/www/passbo...')
#10 {main}

**Comment by stripthis** [comment]
Check out this thread: https://community.passbolt.com/t/what-is-the-list-of-selinux-settings-passbolt-needs/143/4

Also please use the community forum for installation issues as requested in the issue template.
