### ISSUE TITLE
Right Error after finish install

### ISSUE THREAD

**Issue by ArkaineHeinlein** [passbolt/passbolt_api#202]
Hello,

Thx for the nice job with passbolt.

I've follow this:

https://medium.com/passbolt/passbolt-on-centos-7-with-nginx-php7-fpm-mariadb-from-scratch-7b2a9b15f3a4

But at the step 4 to Wrapping up i have this error.

Thx for help ;)

## ISSUE NAME
* Passbolt Version: 1.6.4.
* Platform and Target:
-- Operating system: CENTOS7
-- PHP: VERSION
-- Web server: NAME AND VERSION
-- Database server: NAME AND VERSION
-- etc.: OTHER RELEVAT PLATFORM INFO

### What you did
su -s /bin/bash -c "/var/www/passbolt/app/Console/cake passbolt healtcheck" nginx

### What happened
Warning Error: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_file_map): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]

2017-11-24 12:49:21 Warning: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_file_map): failed to open stream: Permission denied in [/var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php, line 356]
Warning Error: _cake_core_ cache was unable to write 'file_map' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 327]

2017-11-24 12:49:21 Warning: _cake_core_ cache was unable to write 'file_map' to File cache in [/var/www/passbolt/lib/Cake/Cache/Cache.php, line 327]

### What you expected to happen
No error

**Comment by ArkaineHeinlein** [comment]
I have find the problem but now i have a another problem when i do the healtcheck.

`[PASS] Debug mode is off.
 [PASS] Cache is working.
 [PASS] Unique value set for security.salt
 [PASS] Unique value set for security.cipherSeed
 [PASS] Full base url is set to http://10.80.3.35
 [PASS] App.fullBaseUrl validation OK.
 [FAIL] Could not reach the /healthcheck/status with the url specified in App.fullBaseUrl
  [HELP] Check that the domain name is correct in app/Config/core.php
  [HELP] Check the network settings
`

**Comment by stripthis** [comment]
@ArkaineHeinlein please open an installation issue on https://community.passbolt.com github is only for bugs. Thanks,
