### ISSUE TITLE
Login Redirected to Login Page

### ISSUE THREAD

**Issue by tylershuster** [passbolt/passbolt_api#203]
Passbolt version 1.6.5
CentOS 7
PHP 5.6.2
Apache 2.4.29 (cPanel)
MySQL Ver 14.14
Chrome  63.0.3239.84

I installed Passbolt as per [the guide](https://www.passbolt.com/help/tech/install). Healthcheck is clear. Register user as per the guide, walked through setup, logged in.

I expected to be logged in but instead it returns to the login screen. Nothing in the browser console. In error.log, this is appended every time a login attempt fails (but in no other cases):

```
Error: [ForbiddenException] You need to login to access this location
Request URL: /auth/checkSession.json
Stack Trace:
#0 /home/pacificsky/passwords.pacificsky.co/lib/Cake/Controller/Component/AuthComponent.php(349): GpgAuthenticate->unauthenticated(Object(CakeRequest), Object(CakeResponse))
#1 /home/pacificsky/passwords.pacificsky.co/lib/Cake/Controller/Component/AuthComponent.php(305): AuthComponent->_unauthenticated(Object(AuthController))
#2 [internal function]: AuthComponent->startup(Object(AuthController))
#3 /home/pacificsky/passwords.pacificsky.co/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 /home/pacificsky/passwords.pacificsky.co/lib/Cake/Event/CakeEventManager.php(243): call_user_func(Array, Object(CakeEvent))
#6 /home/pacificsky/passwords.pacificsky.co/lib/Cake/Controller/Controller.php(678): CakeEventManager->dispatch(Object(CakeEvent))
#7 /home/pacificsky/passwords.pacificsky.co/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#8 /home/pacificsky/passwords.pacificsky.co/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AuthController), Object(CakeRequest))
#9 /home/pacificsky/passwords.pacificsky.co/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
```

**Comment by stripthis** [comment]
Could be the same issue than: https://github.com/passbolt/passbolt_api/issues/177 ?

**Comment by tylershuster** [comment]
I don't think it is. I added the URL to the cookie exception list and nothing changed.

**Comment by stripthis** [comment]
This is definitely a problem with the session, but it's hard to tell which one.

**Comment by stripthis** [comment]
@tylershuster I take it your are using the file session handler (default). Maybe there are some issues in the way the tmp/ rights are setup or the file directory is mounted. Also maybe worth trying to setup an alternate session handler (redis for example)? Ref. https://book.cakephp.org/2.0/en/development/sessions.html#built-in-session-handlers-configuration
