### ISSUE TITLE
Adding admin user Failed

### ISSUE THREAD

**Issue by microniko** [passbolt/passbolt_api#204]
Hi,
I'm trying PassBolt but I can't add the admin user :\

`$  app/Console/cake install --no-admin` ⇒ Ok
> Datasource : default
 File :/var/www/xxx/app/tmp/schema/default_default.sql
 Success: the database was saved on file!
[…]
 Passbolt installation success! Enjoy! ☮

But :
`$ app/Console/cake passbolt register_user -u xxx@xxxx.net -f XX -l XX -r admin`  ⇒ KO :-(
> Error: Table roles for model Role was not found in datasource default.

It could be usefull :
`$ ./app/Console/cake passbolt healthcheck` 
>  Healthcheck shell 
 Environment
 [PASS] PHP version 7.0.19-1
 [PASS] PCRE compiled with unicode support
 [PASS] The temporary directory and its content are writable
 [PASS] The public image directory and its content are writable
 Config files
 [PASS] The core config file is present
 [PASS] The database config file is present
 [PASS] The email config file is present
 [PASS] The application config file is present
 Core config
 [PASS] Debug mode is off.
 [PASS] Cache is working.
 [PASS] Unique value set for security.salt
 [PASS] Unique value set for security.cipherSeed
 [PASS] Full base url is set to https://xxxxx
 [PASS] App.fullBaseUrl validation OK.
 [PASS] /healthcheck/status is reachable.
 SSL Certificate
 [PASS] SSL peer certificate validates
 [PASS] Hostname is matching in SSL certificate.
 [PASS] Not using a self-signed certificate
 Database
 [PASS] Configured to use a supported database backend
 [PASS] The application is able to connect to the database
 [PASS] Not using a prefix for database tables
 [FAIL] No table found
  [HELP] Run the install script to install the database tables
  [HELP] sudo su -s /bin/bash -c "/var/www/xxxx/app/Console/cake install" www-data
 [FAIL] No default content found
  [HELP] Run the install script to set the default content such as roles and permission types
  [HELP] sudo su -s /bin/bash -c "/var/www/xxxx/app/Console/cake install" www-data
 [PASS] The database schema up to date.
 GPG Configuration
 [PASS] PHP GPG Module is installed and loaded
 [PASS] The server gpg key is not the default one
 [PASS] The environment variable GNUPGHOME is set to /var/www/.gnupg
 [PASS] The directory /var/www/.gnupg containing the keyring is writable by the user the webserver is running as.
 [PASS] The public key file is defined in app/config.php and readable.
 [PASS] The private key file is defined in app/config.php and readable.
 [PASS] The server key fingerprint matches the one defined in app/config.php.
 [PASS] The server key defined in the app/Config.php is in the keyring.
 [PASS] There is a valid email id defined for the server key.
 [PASS] The public key can be used to encrypt and sign a message.
 [PASS] The private key can be used to decrypt a message.
 Application configuration
 [PASS] Using latest passbolt version (1.6.5)
 [PASS] Passbolt is configured to force SSL use
 [PASS] App.fullBaseUrl is set to HTTPS
 [PASS] Selenium API endpoints are disabled.
 [PASS] Search engine robots are told not to index content.
 [PASS] Registration is closed, only administrators can add users.
 [PASS] Serving the compiled version of the javascript app
 [PASS] All email notifications will be sent.
 Development Tools (optional)
 [PASS] Phpunit is installed
 [PASS] Phpunit version is 3.7.38
  2 error(s) found. Hang in there!

Thx :)

**Comment by deurk** [comment]
Same thing. If I check the database, the tables do exist. Any ideas?

**Comment by deurk** [comment]
CakePHP cache got in the way for me, after using the solution provided here (https://github.com/passbolt/passbolt_api/issues/164) I was able to get a full clean healthcheck and the user addition command worked.

**Comment by microniko** [comment]
I confirm : it works ! :)
