### ISSUE TITLE
Can't delete user; Sole owner of 0 passwords.

### ISSUE THREAD

**Issue by aricav96** [passbolt/passbolt_api#205]
Here are my server specs:
* Passbolt Version: 1.6.5
* Platform and Target:
-- Operating system: Debian 9 Jessie
-- PHP: 7.0.19-1
-- Web server: Nginx 1.13
-- Database server: Mariadb 10.1.26
-- etc.: This server is on a VM (Virtualbox)

I created three users (one admin and two users). Then, I created a password with one of the users and proceeded to delete it. As an admin, I can't delete this user; a dialog box opens and says "This user is the sole owner of 0 password: .". Ownership can't be transferred because the password was deleted. It's worth mentioning that the deletion was attempted via the browser (Chrome), since I have no knowledge of a way of doing this via CLI.  

As of now, I'm trying to look into the database to see if there's a way to "purge" this password. But it's certainly something worth checking out. I apologize beforehand if this is a duplicate or if I used the wrong section. I am new at this and I tried to look for issues related to this (having found only one, where the issue was virtually the same, sans the deleted password).

**Comment by stripthis** [comment]
Hi @aricav96 this issue should be fixed with version 2. 
Thanks for reporting the issue.

**Comment by stripthis** [comment]
You can fix this issue by running the cleanup task as an admin in version 2:
```
./bin/cake passbolt cleanup
```
