### ISSUE TITLE
Error: Email not send, email_queue was not found

### ISSUE THREAD

**Issue by paulohg92** [passbolt/passbolt_api#210]
Hello,
I have the next problem,
I have taken the examples for given for testing the email but I get the following error:

See email queue
/var/www/passbolt/app/Console/cake EmailQueue.preview

The error:
Error: Table email_queue for model EmailQueue was not found in datasource default.
#0 /var/www/passbolt/lib/Cake/Model/Model.php(3667): Model->setSource('email_queue')
#1 /var/www/passbolt/lib/Cake/Model/Model.php(3038): Model->getDataSource()
#2 /var/www/passbolt/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#3 /var/www/passbolt/app/Plugin/EmailQueue/Console/Command/PreviewShell.php(18): Model->find('all', Array)
#4 /var/www/passbolt/lib/Cake/Console/Shell.php(461): PreviewShell->main()
#5 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand(NULL, Array)
#6 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/passbolt/app/Console/cake.php(52): ShellDispatcher::run(Array)
#8 {main}

Send email queue
/var/www/passbolt/app/Console/cake EmailQueue.sender

the error:
Error: Table email_queue for model EmailQueue was not found in datasource default.
#0 /var/www/passbolt/lib/Cake/Model/Model.php(3667): Model->setSource('email_queue')
#1 /var/www/passbolt/app/Plugin/EmailQueue/Model/EmailQueue.php(74): Model->getDataSource()
#2 /var/www/passbolt/app/Plugin/EmailQueue/Console/Command/SenderShell.php(47): EmailQueue->getBatch(50)
#3 /var/www/passbolt/lib/Cake/Console/Shell.php(461): SenderShell->main()
#4 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand(NULL, Array)
#5 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#6 /var/www/passbolt/app/Console/cake.php(52): ShellDispatcher::run(Array)
#7 {main}

please help me, I just need to send mail to finish

**Comment by stripthis** [comment]
Hi @paulohg92 please do not use github issues for installation issues. You can ask the community for help here: https://community.passbolt.com

Concerning your issue, it seems that the database table to send email is not present. I'm not sure how you installed passbolt but it look like some tables are missing.
