### ISSUE TITLE
Delete user

### ISSUE THREAD

**Issue by BaumannMisys** [passbolt/passbolt_api#215]
Version: 1.6.5
Change: UserController.php line: 662

$errorData['resources'] = $Resource->find('all', $resourcesFindOptions);

to somthing like this:
$temp = $Resource->find('all', $resourcesFindOptions);
if (!empty($temp)) {
    $errorData['resources'] = $temp;
}

other wise the exception:
throw new ValidationException(
    __('The user cannot be deleted. You need to transfer some ownerships to other users before you can proceed.'),
    $errorData
);
will throws with empty $errorData['resources'] object

**Comment by stripthis** [comment]
This is fixed in v2.0.0-rc1
