### ISSUE TITLE
Password field should not have a limited size

### ISSUE THREAD

**Issue by bappr** [passbolt/passbolt_api#216]
(not sure if I am in a good section but it might be related to an API limitation)

## Password field has a limited size
* Passbolt Version: 1.6.5
* Platform and Target:
-- Operating system: Mac OS
-- Browser: Chrome

### What you did
Related to this topic: https://community.passbolt.com/t/as-a-user-i-can-create-resources-with-encrypted-file-attachement/74
A workaround would be to encode the file with base64.
I encoded a private key in base64 and copy-paste the base64 string in the password field.

### What happened
The password field has a limited size and the base64 string is truncated. 

### What you expected to happen
The base64 string should not be truncated.

**Comment by bappr** [comment]
Anyway to fix this issue manually?
We d like to fully use passbolt but this field size makes it very limited (we cannot store our certificates)...

**Comment by bappr** [comment]
Using the last version of passbolt, I am able to save max 4096 characters.
If I edit the code and remove the maxlength, I can finally save and retrieve more than 4096 characters. So there is no limitations in the API. The limitation is directly in the plugin extension.
=>
`<input maxlength="4096" type="password" id="js_secret" placeholder="password" value="">`

**Comment by stripthis** [comment]
> So there is no limitations in the API
There is a limitation on upload size, which is a server configuration, since secrets are encrypted individually and sent altogether if your server limit is 10Mo and the file is like 1M you will hit issues when sharing with more than 10 people. We need to have proper handling for this case, that's why we didn't rollout the simple change you are requesting.

**Comment by bappr** [comment]
Ok well noted. I was not aware of this limitation. ;-)
Thanks. I will wait for the rollout.

**Comment by stripthis** [comment]
Closing as stalled. Limit is currently 4096. Longer content will be supported via file attachment in the future.
