### ISSUE TITLE
Default Function Request - Default to "Favorites" or "Items I Own"

### ISSUE THREAD

**Issue by technogenus** [passbolt/passbolt_api#217]
When opening Passbolt the default screen/list is "All Items" which takes considerable time to load and resources if you have lots of items saved.   This multiplied by a significant factor when you have a team of users sharing Passbolt.

If the default opening list could be set to "FAVORITES" or "ITEMS I OWN" (normally a much smaller subset of password entries) then this would eliminate the huge hit every time someone logs into Passbolt.   Even better would be user config setting that would let you change the 'Default List" to open.

**Comment by stripthis** [comment]
Hello @technogenus can you create a feature requests on the community forum? Github issues are only used for bugs now. https://community.passbolt.com/c/backlog

**Comment by technogenus** [comment]
Sorry - will move the request right away.
