### ISSUE TITLE
installation fails with "Error: Table roles for model Role was not found in datasource default."

### ISSUE THREAD

**Issue by dafeer** [passbolt/passbolt_api#218]
## ISSUE NAME
* Passbolt Version: 978c348e2 PASSBOLT-2599 Fix travis. Update changelog
* Platform and Target:
```
# lsb_release -d
Description:	Debian GNU/Linux 9.3 (stretch)
# dpkg -l php7.0 apache2 mariadb-server | awk '/^ii/{print($2,$3)}' | column -t
apache2         2.4.25-3+deb9u3
mariadb-server  10.1.26-0+deb9u1
php7.0          7.0.27-0+deb9u1
```

### What you did
Installation according to https://www.passbolt.com/help/tech/install up to "Create the first admin account".

### What happened
```
www-data@host:/var/www/passbolt# app/Console/cake passbolt register_user -u passbolt@example.org -f myFirstname -l myLastname -r admin
Error: Table roles for model Role was not found in datasource default.
#0 /var/www/passbolt/lib/Cake/Model/Model.php(3653): Model->setSource('roles')
#1 /var/www/passbolt/lib/Cake/Model/Model.php(3031): Model->getDataSource()
#2 /var/www/passbolt/lib/Cake/Model/Model.php(3003): Model->_readDataSource('first', Array)
#3 /var/www/passbolt/app/Console/Command/Task/RegisterUserTask.php(111): Model->find('first', Array)
#4 /var/www/passbolt/lib/Cake/Console/Shell.php(458): RegisterUserTask->execute()
#5 /var/www/passbolt/lib/Cake/Console/Shell.php(455): Shell->runCommand('execute', Array)
#6 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(212): Shell->runCommand('RegisterUser', Array)
#7 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#8 /var/www/passbolt/app/Console/cake.php(47): ShellDispatcher::run(Array)
#9 {main}
```

### What you expected to happen
Well, that should be obvious. No stacktrace, but a working user account.

The `app/Config/database.php` looks like this:
```
...
class DATABASE_CONFIG {

        public $default = array(
                'datasource' => 'Database/Mysql',
                'persistent' => false,
                'host' => 'localhost',
                'login' => 'passbolt',
                'password' => '...',
                'database' => 'passbolt',
                'prefix' => '',
                'encoding' => 'utf8',
        );
...
}
```
The database is setup correctly, checked using the copy-pasted values from the config:
```
www-data@host:~$ mysql -u passbolt --host localhost -p -e 'select count(1) from roles' passbolt 
Enter password: 
+----------+
| count(1) |
+----------+
|        4 |
+----------+
```

What's wrong here?

**Comment by cedricalfonsi** [comment]
Hello @dafeer,

Thanks for your interest in passbolt.

Have you run the healthcheck command ? It could help to figure out what's the problem.
`app/Console/cake passbolt healthcheck`

Also I don't know if you noticed, but we have now a community forum which has a dedicated installation section, the github is dedicated for bugs only. https://community.passbolt.com/

**Comment by dafeer** [comment]
My post there: https://community.passbolt.com/t/error-missingtableexception-table-users-for-model-user-right-after-installation/296 (for anyone that might run into the same problem). Note that details changed, but the cause still seems to be the database config/wrappers.

**Comment by ermisus** [comment]
Please delete all files which one name is starting with passbolt_ just delete manually under these folders:

```
app/tmp/cache/
app/tmp/cache/models/
app/tmp/cache/persistent/
```

and voila! Try to visit your passbolt url or IP address.
