### ISSUE TITLE
That version of GPGAuth is not supported

### ISSUE THREAD

**Issue by working4computers** [passbolt/passbolt_api#221]
## That version of GPGAuth is not supported
* Passbolt Version: 1.6.9
* Platform and Target:
-- Operating system: CentOS Linux release 7.4.1708
-- PHP: PHP 7.1.11
-- Web server: Apache/2.4.6
-- Database server: MariaDB 5.5.52

### What you did
This is a clean install, following the centos install tutorial, though using Apache instead of nginx.
Followed the instructions to the dot. Healthcheck is all green apart from the update message (1.6.9)

### What happened
When I'm trying to login, I am able to type my password in, but I receive the following error:
"The server was unable to respect the authentication protocol! That version of GPGAuth is not supported. (undefined)"

**Comment by stripthis** [comment]
Hi @working4computers Could you open the browser console and show the http reponse from the server to see if the gpgauth headers are set properly? You need to do this in Chrome since firefox won't give you the extension request response.

**Comment by stripthis** [comment]
@working4computers I forgot to mention: you need to open the browser extension page and click on "index.html" under inspect view, this will show the request specifically made by the extension during login.
![screen shot 2018-01-23 at 19 24 09](https://user-images.githubusercontent.com/77410/35279499-4243c958-0073-11e8-8640-196c97abc6fa.png)

**Comment by working4computers** [comment]
**Page Load:**
Request URL:http://pwds.circulate.digital/auth/login
X-GPGAuth-Authenticated:false
X-GPGAuth-Debug:There is no user associated with this key
X-GPGAuth-Error:true
X-GPGAuth-Login-URL:/auth/login
X-GPGAuth-Logout-URL:/auth/logout
X-GPGAuth-Progress:stage0
X-GPGAuth-Pubkey-URL:/auth/verify
X-GPGAuth-Verify-URL:/auth/verify
X-GPGAuth-Version:1.3.0
X-Powered-By:PHP/7.1.11

Just to add, I've got debugging on and force SSL is set to false.
If I turn debugging off, the page will simply reload and I'm unable to capture a POST request.

**Comment by stripthis** [comment]
Looks like a similar issue than: 
- https://community.passbolt.com/t/plugin-check-gpg-error-and-oops-something-went-wrong-when-trying-to-login/90/9

Could you check if the server clock is set properly?

**Comment by working4computers** [comment]
Server clock is correctly set ( Wed Jan 24 15:49:26 GMT 2018).
And I did try and set the default timezone within /app/Config/core.php to see whether that would make a difference but it didn't unfortunately!

Is a certain version supported? Or anything else I can try?
Apache is being used instead of nginx, does that make any real difference?

**Comment by stripthis** [comment]
This "There is no user associated with this key" error is triggered when the key fingerprint is invalid (wrong format) or when there is no user in the database for that fingerprint. Sometimes we have seen that the key is not imported when the client / server dates are not set properly (e.g. gpg does not like if a key was created in the future). But it seems to be something else in your case, maybe the DB cache is not set properly (that can happen if you ran some commands as root for example). You can check in the database directly if these are set correctly or if there was an issue during the setup. You can try to also clear the cache in /tmp/cache

Your target version works, i'm thinking there must be an issue with the way it's setup, but it's hard to tell which issue from your report. We'll introduce more health checks in the future to help identify more of these corner cases. Apache or Nginx should make much difference, you can try the docker container: https://github.com/passbolt/passbolt_docker

**Comment by stripthis** [comment]
See also. https://community.passbolt.com/t/v2-0-0-rc1-that-version-of-gpgauth-is-not-supported/292/2

**Comment by lanaiscool** [comment]
same error after upgrading from 1.6.9 to 2.0.0RC1

**Comment by stripthis** [comment]
@lanaiscool please open a new issue on the community forum. Maybe it's the same issue, maybe it's a different one.
