### ISSUE TITLE
API Doc using Swagger

### ISSUE THREAD

**Issue by gregsymons** [passbolt/passbolt_api#23]
I can't seem to find any API documentation other than the code itself (which given my unfamiliarity with cake, doesn't really jump out at me:). Am I missing something?

**Comment by stripthis** [comment]
Hi Greg,

We started working on documenting the API with Swagger. So if you navigate to https://yourdomain/api/swagger.json you'll see that the models are "done". We still need to go through the controllers, and then we'll be able to generate live docs like http://petstore.swagger.io/ . Bear with us, we'll get it done in some time!

Cheers,

ref. PASSBOLT-1561

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-a-developper-i-can-browse-the-api-documentation/75
