### ISSUE TITLE
First name cannot contain a middle initial and period when installing (2.0.0-rc2)

### ISSUE THREAD

**Issue by tbradsha** [passbolt/passbolt_api#230]
* Passbolt Version: 2.0.0-rc2
* Platform and Target:
-- Operating system: Ubuntu 17.10
-- PHP: 7.1
-- Web server: Apache 2.4
-- Database server: MariaDB 10

### What you did
When installing, it prompted for my first name, I would put my first name and middle initial (e.g. "John S."). I tried several times, each time with the same error.

### What happened
The installation proceeds and tells me it was successful. However, when navigating to the link in question, it states an error occured. In the debug, the error says "User could not be validated". Healthcheck passes in its entirety. The setup block in the debug JSON had empty values.

### What you expected to happen
I expect to be able to register with the just-created user regardless of the name I put in. Note that after I registered the user I was then able to log in and update the first name field.

**Comment by stripthis** [comment]
Fixed with v2
