### ISSUE TITLE
URI field overlaps the "Modified" column (2.0.0-rc2)

### ISSUE THREAD

**Issue by tbradsha** [passbolt/passbolt_api#231]
## ISSUE NAME
* Passbolt Version: 2.0.0-rc2
* Platform and Target:
-- Operating system: Ubuntu 17.10
-- PHP: 7.1
-- Web server: Apache 2.4
-- Database server: MariaDB 10

### What you did
Create a password with a moderately long URI (~60 chars).

### What happened
The URI column text overlaps (underlaps) the "modified" column text.

### What you expected to happen
The columns should allow a change in width, or at minimum the "modified" column text should cover the URI text.

**Comment by tbradsha** [comment]
Note that if there are parameter delimiters in the URI (? or &) it will wrap to a new line, which also looks a bit messy (rows aren't an even height).

**Comment by stripthis** [comment]
Fixed with v2.1
