### ISSUE TITLE
Incomplete cleanup when deleting passwords

### ISSUE THREAD

**Issue by tbradsha** [passbolt/passbolt_api#232]
##IMPORTANT: PLEASE READ

Only use github issues for bugs.

We will be more than happy to help you on the community forum for:
- feature requests: https://community.passbolt.com/c/backlog
- issues related to installations: https://community.passbolt.com/c/installation-issues
- general questions: https://community.passbolt.com/c/uncategorized

This is only a issue tracker for bugs related to the Passbolt API.
For passbolt docker, browser extension, command line interface, in short any other bugs 
please use [the other relevant repositories](https://github.com/passbolt).

If you are certain this is a new API bug please use the following format:

## ISSUE NAME
* Passbolt Version: 2.0.0-rc2
* Platform and Target:
-- Operating system: Ubuntu 17.10
-- PHP: 7.1
-- Web server: Apache 2.4
-- Database server: MariaDB 10

I have NOT yet set up an email cron so as to prevent myself from being spammed by password changes.

### What you did
I deleted a password.

### What happened
The password no longer shows in the passwords list, but the entry in the secrets table is still present.

### What you expected to happen
The entry in the secrets table should be removed when deleting a password.

**Comment by stripthis** [comment]
This was done for historical reason to allow to "soft delete" a password but will be fixed in next release. @cedricalfonsi already prepared a fix for this.

**Comment by cedricalfonsi** [comment]
It has been solved with PASSBOLT-2751 Delete secrets when a password is soft deleted. The code should be released with the stable v2.

**Comment by cedricalfonsi** [comment]
Fixed with v2.0.0
