### ISSUE TITLE
Cannot use 'object' as class name

### ISSUE THREAD

**Issue by Flo0010** [passbolt/passbolt_api#233]
Hi people,
I came across an issue when installing Passbolt on Ubuntu Bionic Beaver 18.04. I ran the setup as described in [https://help.passbolt.com/hosting/install](https://help.passbolt.com/hosting/install). On app/Console/cake install --no-admin the script returned "PHP Fatal error:  Cannot use 'object' as class name as it is reserved in /var/www/html/passbolt/lib/Cake/Core/Object.php on line 18". I can't figure out, how to fix it.
PHP Version: 7.2.2-1ubuntu2
MySQL Version: 5.7.21-1ubuntu1
Thanks for help

**Comment by stripthis** [comment]
Passbolt v1 is not compatible with php7.2, you can install passbolt v2-rc instead: https://docs.google.com/document/d/1GVJKALg2RP2mUdUr_FaASvLtTUMbs6I_4Gq9XrzODyM/edit#
