### ISSUE TITLE
controller_logs slows down mysql user lookup

### ISSUE THREAD

**Issue by chrrobi** [passbolt/passbolt_api#235]
Passbolt_version:1.6.5
OS: Centos7.3
PHP:5.4.16
Web: nginx 1.10.2
DB: MariaDB 5.5.52

While loading the users, I noticed it was taking a long time. I activated slow query log and found that it was hanging on its lookup: **select created, user_id from controller_logs where message='login_success' and user_id = ('large guid') order by created desc**

I looked at controller_logs and it has over 250k records. The query is doing a full table scan as there don't seem to be any indexes... I would suggest indexing your userid, your message, your ceated... Also, if possible, would suggest not requiring full text search on the elements, maybe use numbers/ids that are quicker to scan. Same for messages...

In order to reproduce, generate alot of controller_logs, add many users, and you will see the individual lookup per user being done and each one taking a table scan... Can see easy with enabled slow_logs

**Comment by cedricalfonsi** [comment]
Hi @chrrobi,

Thanks for you report.

I'm closing your issue as we have removed the controller_logs table in the v2 of passbolt.
If you want to migrate to the v2, here is the documentation: https://docs.google.com/document/d/1GVJKALg2RP2mUdUr_FaASvLtTUMbs6I_4Gq9XrzODyM/edit#heading=h.snkvmfmtcj2b

Cheers
