### ISSUE TITLE
The username should be a valid email address. 

### ISSUE THREAD

**Issue by jidea** [passbolt/passbolt_api#236]
PassBolt Version 2.0.0-rc2 commit c1e824c860e9ab448cad54e5874cf0718811947f
Centos 7.4.1708
php 7.2.3
nginx 1.12.2
mariadb 10.2.13

as nginx user i tried to create a user
bin/cake passbolt register_user -u my-name.lastname@first-second.ext -f my-name -l lastname
then i tried
bin/cake passbolt register_user -u myname.lastname@first-second.ext -f myname -l lastname
and finally i tried
bin/cake passbolt register_user -u lastname@first-second.ext -f myname -l lastname
then I tried with graphical interface, but the result was the same : 
"The username should be a valid email address."
passbolt don't validate hyphen in domain name.

**Comment by kevinmuller** [comment]
Hi @jidea ,

Thanks for the report.

I just checked, and the problem doesn't seem to be with the hyphen. The validation rule also checks that the domain extension is a valid one. In this case, .ext is not a valid domain extension, hence the validation rule breaks.

If you try with .com instead, it will work fine.

**Comment by jidea** [comment]
hello,
thx for the quick answer. i did not try with first-second.ext. i did'nt want to expose my domain name.
in fact, the extension is .fr 
i tried to change . fr by .com but it did'nt validate it.
i have a real true domain in .fr whith a hyphen and one without hyphen. only one validate, not the other. (eg first-second.fr and firstsecond.fr only firstsecond.fr validate)

**Comment by kevinmuller** [comment]
Without knowing your domain it's difficult to reproduce. Maybe you could email it to us at contact[at]passbolt[dot]com so that we can have a look at the issue? Or, if you don't want to expose your domain at all could you provide a different domain name with a similar format that triggers the same issue, so that we can reproduce the bug?

I don't think the problem is with the hyphen, because if you try with myname-lastname@first-second.com, it works fine.

**Comment by jidea** [comment]
Okay first thanks to remy. you had the good pov.
some past admin for unknonwn reason duplicated the dns on active directory on internal network as if it was primary for servers (and nobody manage them). my fedora has a different dns server
Problem resolved. thanks again.
