### ISSUE TITLE
As an admin I should not get a warning in the healthcheck for release candidates

### ISSUE THREAD

**Issue by rahra** [passbolt/passbolt_api#237]
According to my `app/Config/version.php` I'm running version 1.6.10 which is in sync with the current Github version https://github.com/passbolt/passbolt_api/blob/master/app/Config/version.php but when I run `./app/Console/cake passbolt healthcheck` it complains that it should be 2.0.0-rc2.

**Comment by stripthis** [comment]
Hi @rahra this is a known bug, thanks for the report. You can ignore the warning for now.

**Comment by cedricalfonsi** [comment]
Fix with v2.0.0 release
