### ISSUE TITLE
installation guide not up-to-date

### ISSUE THREAD

**Issue by erikschwalbe** [passbolt/passbolt_api#241]
Hello,
I try to install passbolt without using docker. 
https://help.passbolt.com/hosting/install
But I think all the instructions on this site are not up-to-date.

....
cd /var/www
git clone https://github.com/passbolt/passbolt_api.git
mv passbolt_api passbolt
....
cd /var/www/passbolt/app/Config
cp core.php.default core.php
cp database.php.default database.php
....
But there is no "app" folder in the repo!

Did you reorganize the repo?
Thanks and regards,
Erik

**Comment by cedricalfonsi** [comment]
@erikschwalbe the documentation is live
let us know if something goes wrong
https://help.passbolt.com/hosting/install

**Comment by xpico** [comment]
Hi @cedricalfonsi,

You know when will it be available the install documentation for Centos7?

Great job and thank you,

**Comment by dlen** [comment]
Hey @xpico 

It will be published in the following days.

Thanks for your support and patience!

**Comment by CodeBrauer** [comment]
https://github.com/passbolt/passbolt_help/issues/4

The migrate from v1 to v2 is not available (yet?)

**Comment by dlen** [comment]
Hi @CodeBrauer!
There is an upgrade section here: https://help.passbolt.com/hosting/upgrade

Some more upgrading scenarios will be included in the next few days!

**Comment by kevinmuller** [comment]
@xpico The tutorial for CentOS7 is now available : https://help.passbolt.com/hosting/install/ce/centos-7.html

**Comment by xpico** [comment]
thank you very much @kevinmuller

**Comment by CodeBrauer** [comment]
@dlen Thanks - Fyi: there is still a dead link on https://help.passbolt.com/hosting/update on `Update from v1 to v2`

**Comment by stripthis** [comment]
It's fixed thanks
