### ISSUE TITLE
Feature Request: File Attachment

### ISSUE THREAD

**Issue by jhmk** [passbolt/passbolt_api#25]
Is it possible to add files to a login e.g. SSL certs, Keys, PDFs and so on?

**Comment by stripthis** [comment]
That's a good idea @jhmk! How do you think this should work? Should passbolt encrypt these files too?

**Comment by jhmk** [comment]
Yes in the same way as password so that they can be shared and secure.
For SSH Keys you need to share with your team of DevOps that would be an important feature

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-a-user-i-can-create-resources-with-encrypted-file-attachement/74

**Comment by MCM-Mike** [comment]
**Please close it again if needed**, but I wanted to ask if this feature [as its being discussed a long ](https://community.passbolt.com/t/as-a-user-i-can-create-resources-with-encrypted-file-attachement/74)time could be implemented at least in the pro-version as more advances setups are currently required to use two solutions to store small encrypted user files?

As it seems to reach to a wide spectrum of the community it's also possible to implement it in the community edition. 

Currently its in `backlog` any way we can bring it into `development` , **let us know what you need to prioritize it ?**

**Comment by PihrtV** [comment]
Please, this is a core missing future for lot of us. Is there any technical issue blocking this to be done or it is only a low priority?
Just for us to self-estimate how long it could be... Thanks a lot for all your work on passbolt!
