### ISSUE TITLE
Share with group when group name length is only two characters

### ISSUE THREAD

**Issue by ajcamilo** [passbolt/passbolt_api#250]
## Share with group when group name length is only two characters
* Passbolt Version: 2.0.4
* Platform and Target:
-- Operating system: Linux
-- Docker image

### What you did
I created a group called `dg`. Then I created a new password and tried to share this password with the group `dg`.

### What happened
When I typed `dg` in the search box of the share modal, it continue to show the loading icon.

### What you expected to happen
It was expected to appear the `dg` group.

**Comment by stripthis** [comment]
Thanks for the report @ajcamilo we'll get it fixed in the next release

**Comment by stripthis** [comment]
Fixed in 2.0.7
