### ISSUE TITLE
Migration from MySQL 5.7 -> 8.0 and passbolt views

### ISSUE THREAD

**Issue by MYDIH** [passbolt/passbolt_api#253]
## Migration from MySQL 5.7 -> 8.0 and passbolt views
* Passbolt Version: latest docker image
* Platform and Target: Archlinux / Docker version 18.04.0-ce, build 3d479c0af6
-- Operating system: Linux 4.15.15-1-ARCH

### What you did
I just upgraded Mysql from 5.7.22 -> 8.0 (latest).

### What happened
My backend seems nice and runs smoothly, but I get errors like this in passbolt logs :
```
General error: 1356 View 'passbolt.users_resources_permissions' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them in [/var/www/passbolt/vendor/cakephp/cakephp/src/Database/Schema/Collection.php, line 131]
```
It seems like the migration messed up some views ? Any way to recreate them or am I stuck in 5.7 ? The passbolt database is already pretty big, I don't want to loose it.

Thanks

**Comment by stripthis** [comment]
Which version of passbolt are you running?
Also we've seen some issues with Mysql 8.0 so I wouldn't recommend using it at the moment.

**Comment by MYDIH** [comment]
I'm using latest docker image (2.0.7 if I read correctly). 
Okay, will stay on 5.7 then, 

Thanks for the fast reply.

**Comment by dlen** [comment]
@MYDIH you can check this thread for more information: https://github.com/passbolt/passbolt_docker/issues/103
