### ISSUE TITLE
cron EmailQueue.sender job fails if db password contains certain characters

### ISSUE THREAD

**Issue by kissge** [passbolt/passbolt_api#254]
## ISSUE NAME
* Passbolt Version: 2.0.7 (latest on Docker version as of now)
* Platform and Target:
-- Operating system: Docker on Amazon Linux 2 (2017.12) LTS Release Candidate
-- PHP: PHP 7.2.5 (cli) (built: May  5 2018 00:31:05) ( NTS )
-- Web server: nginx/1.10.3
-- Database server: 10.1.31-MariaDB MariaDB Server
-- etc.: OTHER RELEVANT PLATFORM INFO

### What you did
1. Configure Passbolt properly, with `DATASOURCES_DEFAULT_PASSWORD='y$ybDzq5C#Oq=?,(=L2vR,N6GpVJFlDf'`
2. Start account recovery

### What happened
No mail gets delivered

### What you expected to happen
Recovery mail gets delivered

---

Inspected DB and found `email_queue` filled with unsent items.
This means DB config is right.
Then I checked `/var/log/cron.log` and it contained lots of copies of the following line:

    Exception: SQLSTATE[HY000] [1045] Access denied for user '*******'@'*******' (using password: YES) in [/var/www/passbolt/vendor/cakephp/cakephp/src/Database/Driver/PDODriverTrait.php, line 48] 

This is strange. Then I changed DB password to alphabet-only word, and that worked.

**Comment by dlen** [comment]
Hi @kissge thanks for your report! This looks like an issue specific with the docker image, could you please open an issue on https://github.com/passbolt_docker ?

**Comment by kissge** [comment]
@dlen Thanks for guidance. I did that.
