### ISSUE TITLE
As a user sharing a password I should get an error message when I lost the right to share in the meantime

### ISSUE THREAD

**Issue by stripthis** [passbolt/passbolt_api#255]
We have found a small bug:      

2 accounts : A and B
A create a password
A share the password with B (B is set to owner)
B change the rights of A to read only (or read/write)
A try to share it again with another user

Results : the share hangs indefinitely (on the encrypting window), only a refresh of the page allow to recover access (close button does not work). After the refresh A cannot share the password anymore

Expected result: A message is shown to A when he clicks on the share button indicate he does not have the right to share.

**Comment by cedricalfonsi** [comment]
Fixed, the share button is disabled if the user doesn't have the right to share anymore
