### ISSUE TITLE
[2.0.7] Email not being sent with EmailQueue.sender , but send_email_test works

### ISSUE THREAD

**Issue by claudiutraistaru** [passbolt/passbolt_api#257]
## ISSUE NAME
* Passbolt Version: 2.0.7
* Platform and Target:
-- Operating system: Docker version latest
-- PHP: version 7.2.5.
-- Web server: Nginx
-- Database server: Mysql

### What you did
Setup the email variables with Envroinment variables to use gmail account
  ./bin/cake passbolt send_test_email 
Everything works ok , there are no errors.
```
Trace
[220] smtp.gmail.com ESMTP t189-v6sm6361980wmf.22 - gsmtp
> EHLO localhost
[250] smtp.gmail.com at your service, [1.1.1.1]
[250] SIZE 35882577
[250] 8BITMIME
[250] STARTTLS
[250] ENHANCEDSTATUSCODES
[250] PIPELINING
[250] CHUNKING
[250] SMTPUTF8
> STARTTLS
[220] 2.0.0 Ready to start TLS
> EHLO localhost
[250] smtp.gmail.com at your service, [1.1.1.1]
[250] SIZE 35882577
[250] 8BITMIME
[250] AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH
[250] ENHANCEDSTATUSCODES
[250] PIPELINING
[250] CHUNKING
[250] SMTPUTF8
> AUTH LOGIN
[334] VXNlcm5hbWU6
> *****
[334] UGFzc3dvcmQ6
> *****
[235] 2.7.0 Accepted
> MAIL FROM:<*****>
[250] 2.1.0 OK t189-v6sm6361980wmf.22 - gsmtp
> RCPT TO:<myemail@mydomain.com>
[250] 2.1.5 OK t189-v6sm6361980wmf.22 - gsmtp
> DATA
[354] Go ahead t189-v6sm6361980wmf.22 - gsmtp
> From: *****
To: myemail@mydomain.com
Date: Fri, 18 May 2018 07:08:27 +0000
Message-ID: <7149fa3b559e4b81bf8c719e6eefd52f@passbolt>
Subject: Passbolt test email
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Congratulations!
If you receive this email, it means that your passbolt smtp configuration is working fine.
```

### What happened
When adding or creating a new account in passbolt, the new email shows in the passbolt.email_queue table , after a while it gets the value locked set to 1 , but then nothuing happens , the sent value remains 0

I ran also from the command line with www-data the EmailQueue.sender command without luck , and no output is shown.

### What you expected to happen
Emails are not sent from passbolt , just marked as locked in the database. I cannot debug to see what is going on and have tried also manually setting the variables in app.php still no luck on ghetting emails on events from passbolt. Could you please provide some input on what to look for?
Thank you

**Comment by claudiutraistaru** [comment]
Also send_tries column is always 0 in the database.

**Comment by stripthis** [comment]
Is it a fresh install or did you upgrade from v1?

**Comment by claudiutraistaru** [comment]
I used the 2.0.7 docker version and just ran migrate on the database and imported the server keys.

**Comment by dlen** [comment]
Hi @claudiutraistaru 

Is there any information on /var/log/cron.log ? Could you check as the www-data user that the EMAIL env variables are set correctly with `printenv | grep EMAIL` ?

**Comment by claudiutraistaru** [comment]
Hi , the envrinment variables are correct :
EMAIL_TRANSPORT_DEFAULT_CLASS_NAME=Smtp
EMAIL_DEFAULT_FROM      =<mysendemail@mydomain.com>
EMAIL_TRANSPORT_DEFAULT_PASSWORD=<mypassword>
EMAIL_TRANSPORT_DEFAULT_USERNAME= <mysendemail@mydomain.com>
EMAIL_TRANSPORT_DEFAULT_TLS=false
EMAIL_TRANSPORT_DEFAULT_HOST=smtp.gmail.com
EMAIL_TRANSPORT_DEFAULT_PORT=587


the /var/cron.log seems to be empty, but if I run the comand as www-data I get no output.
`www-data@passbolt:/var/www/passbolt$ ./bin/cake EmailQueue.sender
www-data@passbolt:/var/www/passbolt$
`

**Comment by claudiutraistaru** [comment]
OK, it seems it is working now , the issue was that the first couple of emails were not sending because at first it was an issue with the email settings, and appeared with lock . After i have solved the issue with the email sending all others were still m,arked as locked.
I havd to execute the command :  ./bin/cake email_queue.sender clear_locks and now the emails are sent as they should be.

Thank you for your help , hope if someone gets into this issue this will help.
