### ISSUE TITLE
As a user I would like to group passwords by projects

### ISSUE THREAD

**Issue by SkaveRat** [passbolt/passbolt_api#258]
Having to handle lots of different projects is quite a pain, as all passwords are listed in a single view.

Currently we name passwords like "Projectname | Environment | System", which makes it possible to use the search to group things, but having a way to tag or group passwords by project would make organization a lot more useful.

Example:

```
MyProject
    Servers
       Dev
       Live
    Databases
    Email
    Backends
MyOtherProject
    etc...
```

**Comment by stripthis** [comment]
Duplicate from: https://community.passbolt.com/t/as-a-logged-in-user-i-can-organized-my-passwords-using-categories-in-the-form-of-a-folder-tree/137
