### ISSUE TITLE
As a user I'd like to have the option to see comments and descriptions on a glance

### ISSUE THREAD

**Issue by SkaveRat** [passbolt/passbolt_api#259]
Currently I have to click the tabs on the right if I want to check if someone commented on it.

It would be quite useful to see comments and descriptions on a glance, without having to open them one by one.

Maybe remember the state, e.g. once opened, keep them opened until closed again

**Comment by stripthis** [comment]
@SkaveRat  can you please create feature request on the community forum? As indicated in the template the github issues are for bugs only. Thanks,

**Comment by stripthis** [comment]
Ref. https://community.passbolt.com/t/as-a-logged-in-user-navigating-the-ui-my-sort-orders-should-be-remembered/57
