### ISSUE TITLE
Feature Request: Multiple secret types

### ISSUE THREAD

**Issue by veisis** [passbolt/passbolt_api#26]
Why secret can be only password? 
When creating new record allow to enter plain text as secret.

No big changes needed here. 
1. Change field secrets.data to mediumtext.
2. Add new field secrets.type to indicate what kind of field type to show in edit.
3. Add option to choose type in add and edit view.

And after this we can start thinking about full file encryption: issue #25

**Comment by stripthis** [comment]
Hi @veisis, actually we thought of that too, this is why we named the model 'secret' and not password, in order to allow supporting more secret types in the future. We'll come to this in due time!

**Comment by pablodgonzalez** [comment]
@stripthis I agree with @veisis, that is useful to save PEM files just to give an example. Maybe you can put it on the roadmap, just for visibility.

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-an-administrator-i-can-create-new-secret-types-and-define-their-associated-input-fields/19
