### ISSUE TITLE
gpg key - Could not verify server key. An Internal Error Has Occurred.

### ISSUE THREAD

**Issue by Croenen** [passbolt/passbolt_api#262]
## ISSUE NAME
* Passbolt Version: 2.0.7, Latest commit 1c07f21
* Platform and Target:
-- Operating system: Ubuntu 16.04.4
-- PHP: 7.0.3
-- Web server: nginx 1.12.2
-- Database server: mysql-5.7.21

### What you did
I tried to change the login page template.
To begin with, I wanted to remove some div elements with element method like
`$this->element('Public/Promo/cloud');`
in **login.ctp**

### What happened

At first everything worked correctly, but after a while the error began to appear on the page.

![pass](https://user-images.githubusercontent.com/27514830/40408663-f8b8eeb0-5e70-11e8-95cc-2ca1adef8ff1.PNG)

Even after I returned the template to its original state, the error is repeated.

**Error log**
`2018-05-23 07:10:04 Error: [InvalidArgumentException] Invalid header value type; must be a string or numeric; received boolean
Request URL: /auth/verify.json?api-version=v1
2018-05-23 07:10:06 Error: [InvalidArgumentException] Invalid header value type; must be a string or numeric; received boolean
Request URL: /auth/verify.json?api-version=v1
2018-05-23 07:10:07 Error: [InvalidArgumentException] Invalid header value type; must be a string or numeric; received boolean
Request URL: /settings.json?api-version=v2
2018-05-23 07:10:09 Error: [InvalidArgumentException] Invalid header value type; must be a string or numeric; received boolean
Request URL: /auth/verify.json?api-version=v1`

### What you expected to happen
As I said, I wanted to change the page template a little. And I do not know yet whether there is an error due to an attempt to change or something else here.

**Comment by stripthis** [comment]
Try resetting the code to the original version and open a new issue if the problem persist.
We do not provide support for customized version of passbolt.
