### ISSUE TITLE
After Passbolt upgrade HTML Entities are not correctly rendered in the frontend

### ISSUE THREAD

**Issue by shochdoerfer** [passbolt/passbolt_api#263]
## After Passbolt upgrade HTML Entities are not correctly rendered in the frontend
* Passbolt Version: 2.0.7
* Platform and Target:
-- Operating system: Debian Stretch
-- PHP 7.2
-- Web server: nginx 1.10.3
-- Database server: MySQL 5.5

### What you did
After upgrading from Passbolt 1.6.10 to 2.0.7 stored HTML Entities are not correctly rendered in the frontend any more.

### What happened
We have some resources stored with HTML Entities in our database, e.g. "A \&amp; B". In 1.6.10 that data was rendered in the frontend as "A & B". After the upgrade the frontend shows "A \&amp; B". 

### What you expected to happen
Turn "A \&amp; B" into "A & B" again ;)

**Comment by stripthis** [comment]
This comes from the fact that v1 was converting user inputs to HTML entities and now the v2 does not. There is no more sanitation or transformation of user input, creating this backward compatibility issue for already transformed strings. 

I'm not too keen on transforming the input again, I think it would be simpler for you to change the values manually. :)

**Comment by cedricalfonsi** [comment]
Thank you @shochdoerfer.
If you have a lot of entries that are screwed, we could consider scripting something in sql to revert this.
For now I'm closing this ticket.
