### ISSUE TITLE
Healthcheck within web app not working : Page not found

### ISSUE THREAD

**Issue by Raptor039** [passbolt/passbolt_api#264]
* Passbolt Version: 2.0.7 (origin master)
* Platform and Target:
-- Operating system: debian 9.4 (LXC container under Proxmox 5)
-- PHP: 7.0.27
-- Web server: nginx 1.10.3
-- Database server: mariaDB 10.1.26
-- etc.: My passbolt is an upgraded version from 1.X

### What you did
Run healthcheck using the web interface by accessing this URL : https://mypassboltinstance/healthcheck

### What happened

It returns "Page not found" and my user is log out

### What you expected to happen
Same result like it was in 1.X version of passbolt, a fully functionnal healthcheck withing the web app.

PS : Cli healthcheck works fine.

Any idea why this happen ? Except that problem, my passbolt instance is working like a charm.

**Comment by dlen** [comment]
Hi @Raptor039 !

Thanks for your bug report! Your issue might be related with this thread: https://community.passbolt.com/t/site-not-loading-post-1-6-10-to-2-0-5-upgrade/653/19 
Long story short there is a bug in that doesn't allow admin logged users to check the healthcheck, it has been already reported and a fix is already included for the next release!

**Comment by Raptor039** [comment]
Hi @dlen and thanks for your quickly answer!

I'm happy you know this bug and that it has already been fixed!

I'm closing this thread and waiting for an update!

Continue your good work on this wonderfull soft!

Greetings.
