### ISSUE TITLE
After entering the password wrong 3 times, I am not able to unlock a ressource

### ISSUE THREAD

**Issue by shochdoerfer** [passbolt/passbolt_api#265]
## After entering the password wrong 3 times, I am not able to unlock a ressource
* Passbolt Version: 2.0.7
* Platform and Target:
-- Operating system: Debian Stretch
-- PHP: 7.2
-- Web server: nginx 1.10.3
-- Database server: MySQL 5.5

### What you did

I tried to unlock a stored password, checked the "Don't ask for password for the next 5 minutes" and entered my password wrong 3 times. A message appeared that "Your passphrase is wrong ! The operation has been aborted."

### What happened
After trying again to unlock the stored password, I am not able to enter anything as the popup does not open. I assume this is a side-effect of the "Don't ask for password for the next 5 minutes" feature. I assume the flag needs to be reset once the password was entered wrong 3 times and the message "Your passphrase is wrong ! The operation has been aborted." appeared.

### What you expected to happen
The popup should show and let me unlock the stored password.

**Comment by stripthis** [comment]
Hi stephan,

Thanks for the bug report i'll have a look and publish patch asap.

**Comment by stripthis** [comment]
Fixed with v2.1
