### ISSUE TITLE
Remote Desktop Connection  An internal error has occurred

### ISSUE THREAD

**Issue by Rajborwade12** [passbolt/passbolt_api#266]
i am not able to get any system in remote through remote desktop connection 
it showing an error: An internal error has occurred how i can fix it

**Comment by infectormp** [comment]
@Rajborwade12 you a sure this is right place for this error?

**Comment by cedricalfonsi** [comment]
@Rajborwade12 If it's an installation issue or a something not relative to a passbolt bug, please use the community forum https://community.passbolt.com.

If you are encountering a bug, could you follow the template and give us more details so we could try to reproduce it.

**Comment by stripthis** [comment]
Closing as this does not meet the minimum standard for issue report.
