### ISSUE TITLE
"Remember passphrase" checkbox label should be clickable

### ISSUE THREAD

**Issue by rgpublic** [passbolt/passbolt_api#268]
The pro version has the following checkbox under login:
[x] Remember passphrase until I log out
The label of this checkbox should have a "for" attribute, because just clicking on the label currently doesnt check the checkbox. You have to exactly hit the checkbox which is cumbersome.

**Comment by stripthis** [comment]
Hi @rgpublic that's right, i'll include a fix in a next release (most likely this week)

**Comment by stripthis** [comment]
Fixed with v2.1
