### ISSUE TITLE
Demo disclaimer in self hosted

### ISSUE THREAD

**Issue by abimelex** [passbolt/passbolt_api#269]
I have a self hosted version of Passbolt using the docker container. But the Demo Warning and Disclaimer still appears on the register screen.

Is this normal behaviour or did I configured something wrong?

**Comment by stripthis** [comment]
Hi @abimelex, yes that's normal. The register screen is meant to be used in demo mode. If you are running a production instance it is better to disable public registration and then as an admin add users.
