### ISSUE TITLE
A route matching "/account/settings.json" could not be found.

### ISSUE THREAD

**Issue by danpospisil** [passbolt/passbolt_api#270]
I have upgraded Passbolt CE to recent version (2.1.0) sucessfully (running on Centos 7.4 - installed from source) - everything works as expected but in the error log I see message:
`Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/account/settings.json" could not be found.
Request URL: /account/settings.json?api-version=v2`
This appears after an user logs in. 

I have no idea what that means and how to fix that. I also have a fresh install that is doing exactly the same.

**Comment by stripthis** [comment]
This is normal, this is the web extension trying to find out if you have the account settings module installed (used for the black theme in passbolt pro edition).

**Comment by danpospisil** [comment]
@stripthis - well then why is it an error? I expect error log to show errors and not to be filled with spam so you can say if everything is ok with one glance.

**Comment by stripthis** [comment]
@danpospisil  alright fair enough, we'll look into it

**Comment by danpospisil** [comment]
Ok, thanks! :)

**Comment by stripthis** [comment]
Fixed around 5 months ago
