### ISSUE TITLE
Could not add user to a group

### ISSUE THREAD

**Issue by damien-list** [passbolt/passbolt_api#273]
## Could not add user to a group
* Passbolt Version: 2.1.1
* Platform and Target:
-- Operating system: Ubuntu 14.04
-- PHP: 7.1
-- Web server: Apache 2.4
-- Database server: MySQL 5.5

### What you did
1. Click on "users" in the top bar.
2. Click on the "+" symbol in the left bar for the group I want to add a user in.
3. Click on "edit group".
4. Search user in the add people field and then click on the user found.
5. Save the group
6. Enter the password to validate my privilege (I guess)
7. Get this error message : `Error The group could not be saved`

### What happened
The user is not added to the group.

### What you expected to happen
The user being added to the group.

In the log, I have : 

> 2018-07-10 15:55:30 Error: [App\Error\Exception\ValidationRuleException] Could not validate group data.
> Request URL: /groups/a8e0b304-cef0-4b9f-ae5f-f6a4794791fb.json?api-version=v1

I have tried what it is described in this #247 but it doesn't work.

**Comment by cedricalfonsi** [comment]
Hello @damien-list,

Would you be available for a call so we can dig into it together?
Send us an email to support@passbolt.com with your availabilities.

Best regards,
Cédric

**Comment by stripthis** [comment]
Solved over the phone.
