### ISSUE TITLE
As LU I can't see passwords shared with me clicking on the "shared with me" shortcut filter

### ISSUE THREAD

**Issue by mikusHusbando** [passbolt/passbolt_api#278]
## ISSUE NAME
* Passbolt Version: finished installing normal build like a week ago, dont know where to check
* Platform and Target:
-- Operating system: Ubuntu Server 16.05 LTS
-- PHP: PHP 7.0.30-0ubuntu0.16.04.1
-- Web server: Apache/2.4.18 (Ubuntu)
-- Database server: mysql  Ver 14.14 Distrib 5.7.23, for Linux (x86_64) using  EditLine wrapper
-- etc.: OTHER RELEVANT PLATFORM INFO

### What you did
added new password. selected someone else as owner and myself being able to update it.

### What happened
The item is only in "All Items" not in shared with me or items I own. Using the star to add it to favorites works fine.

### What you expected to happen
Should be in "shared with me", but isnt

**Comment by cedricalfonsi** [comment]
Hello @mikusHusbando,
Thank you for you report. This bug is already referenced in our ticketing system (ref: PASSBOLT-2966) and is marked with a high priority. We'll update this ticket once it's fixed.
Best regards

**Comment by cedricalfonsi** [comment]
Fixed with v2.4
