### ISSUE TITLE
Group creator/owner should be automatically added inside the group as administrator

### ISSUE THREAD

**Issue by fxdstudio** [passbolt/passbolt_api#279]
At this moment if you create a group and forgot to set you as administrator but you add another person you lose the control of the group itself even if you are full ADMIN.
Group creator/owner should be automatically added inside the group as administrator

**Comment by stripthis** [comment]
Moved to community forum: https://community.passbolt.com/t/as-a-an-admin-i-should-be-automatically-added-removed-to-the-admin-group-when-my-role-change/1009
