### ISSUE TITLE
Sys admin should be able to edit users inside groups even if that groups are not created by him

### ISSUE THREAD

**Issue by fxdstudio** [passbolt/passbolt_api#280]
Passbolt i guess is meant as company/team system and data inside should be in control of the administrator Sys admin should be able to edit users inside groups even if that groups are not created by him

**Comment by stripthis** [comment]
See. https://community.passbolt.com/t/as-a-an-admin-i-should-be-automatically-added-removed-to-the-admin-group-when-my-role-change/1009
