### ISSUE TITLE
All users should not be able to export

### ISSUE THREAD

**Issue by cordeosdev** [passbolt/passbolt_api#282]
After recently updating one of our Passbolt servers, very carefully, to 2.3.0 we were extremely happy to see there is now an 'export' function available.   However, this new functionality creates a major issue (not neccessarily a bug) for us:

**General users should not be able to export usernames and password.**

Preventing users from easily copying out a large number of usernames/passwords is one of the central, key reasons we are investing in setup, evaluate and implementation of several password control platforms.

Exporting passwords should be at the very least limited to "admin" role users.   Additionally, a per entry or per group setting of 'exportable' would be nice as well a separate user 'export' role/permissions setting.

Passbolt 2.3.0 / 2.2.1
CentOS 7 PHP 7.1

**Comment by stripthis** [comment]
Hello @cordeosdev ,

The export functionality is only available to pro users at the moment. To my knowledge your company subscription was cancelled. Please contact us at support@passbolt.com (or the community forum) to discuss this new feature that will allow more granularity in the access role base.
