### ISSUE TITLE
SMTP Error: 550

### ISSUE THREAD

**Issue by m333w** [passbolt/passbolt_api#283]
Hi all, 

I cant undestand why i dont got the email for new user : 

`root@passbolt:/var/www/passbolt# ./bin/cake EmailQueue.sender
SMTP Error: 550 5.7.1  Reject for policy reason RULE3_2. See http://postmaster.gandi.net
Email 50 was not sent`

But i make a test : 

`root@passbolt:/var/www/passbolt# ./bin/cake passbolt send_test_email

     ____                  __          ____
    / __ \____  _____ ____/ /_  ____  / / /_
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /
 /_/    \__,_/____/____/_.___/\____/_/\__/

 Open source password manager for teams
---------------------------------------------------------------
 Debug email shell
---------------------------------------------------------------

Email configuration
---------------------------------------------------------------
Host: mail.gandi.net
Port: 587
Username: noreply@domain.tld
Password: *********
TLS: true

Sending email from: Passbolt <noreply@domain.tld>
Sending email to: email@gmail.com
---------------------------------------------------------------

Trace
[220] relay.mail.gandi.net ESMTP Postfix
> EHLO localhost
[250] relay9-d.mail.gandi.net
[250] PIPELINING
[250] SIZE 35651584
[250] VRFY
[250] ETRN
[250] STARTTLS
[250] AUTH PLAIN LOGIN
[250] ENHANCEDSTATUSCODES
[250] 8BITMIME
[250] DSN
> STARTTLS
[220] 2.0.0 Ready to start TLS
> EHLO localhost
[250] relay9-d.mail.gandi.net
[250] PIPELINING
[250] SIZE 35651584
[250] VRFY
[250] ETRN
[250] AUTH PLAIN LOGIN
[250] ENHANCEDSTATUSCODES
[250] 8BITMIME
[250] DSN
> AUTH LOGIN
[334] VXNlcm5hbWU6
> *****
[334] UGFzc3dvcmQ6
> *****
[235] 2.7.0 Authentication successful
> MAIL FROM:<*****>
[250] 2.1.0 Ok
> RCPT TO:<email@gmail.com>
[250] 2.1.5 Ok
> DATA
[354] End data with <CR><LF>.<CR><LF>
> From: Passbolt <*****>
To: email@gmail.com
Date: Sat, 29 Sep 2018 12:32:39 +0000
Message-ID: <470f591d488d47e2bfcdb9cfad8e8700@passbolt>
Subject: Passbolt test email
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Congratulations!
If you receive this email, it means that your passbolt smtp configuration is working fine.

.
[250] 2.0.0 Ok: queued as 4DF7BFF80B
> QUIT

The message has been successfully sent!
root@passbolt:/var/www/passbolt#`

Its ok, someone can help me please ? 

Best regards.

**Comment by infectormp** [comment]
> 5.7.1 Reject for policy reason RULE3_2
you need look at your SMTP server, this is not a passbolt problem

**Comment by m333w** [comment]
Thx @infectormp for this reply 👍 

Can you help me to edit my configuration ? 

Her is my settings : 

`    // Email configuration.
    'EmailTransport' => [
        'default' => [
            'host' => 'mail.gandi.net',
            'port' => 587,
            'username' => 'email@domain.tld',
            'password' => 'strongpassworld',
            // Is this a secure connection? true if yes, null if no.
            'tls' => true,
            //'timeout' => 30,
            //'client' => null,
            //'url' => null,
        ],
    ],
    'Email' => [
        'default' => [
            // Defines the default name and email of the sender of the emails.
            'from' => ['email@domain.tld' => 'Passbolt'],
            //'charset' => 'utf-8',
            //'headerCharset' => 'utf-8',
        ],
    ],
`

**Comment by infectormp** [comment]
I don't think that are you have problem in your config.
According to http://postmaster.gandi.net/ your mail was rejected by RULE3_2: High score Spam detected.
So problem in your mail provider.

**Comment by m333w** [comment]
Oh realy ? Realy strange i use this provider for all my other services ( i dont gona list all of them, its wasting time for us^^)

I think its passbolt the problem, like you see "High score Spam detected" that not realy correct and when you take a look of the mail with the comand 'EmailQueue.preview' the container of the mail is more than weird with tags everywhere

**Comment by stripthis** [comment]
> So can we have an update with a beter template mail ?

The email template uses a lot of tables and inline style because this is still the recommended way to optimize compatibility with email clients. They are unfortunately industry standards, and crafted using best practices defined by the mailchimp team.

I suggest getting in touch with Gandi support to get more information why your email is getting high spam score. It is most likely coming from other factors.

**Comment by m333w** [comment]
Hi, 

Ok i gona send an email to gandi see if we can do something. 
Thx for this reply, i will update my post soon as possible.

Regards.

**Comment by ericandreani** [comment]
Hi,

I've the same problem.
Gandi says me that problem is email language, I'm french and Passbolt emails are in English.

I see in the project variable __('...') in template email files, is it possible to set translation files (like csv) ?

**Comment by stripthis** [comment]
@ericandreani I have added to this reference to the ticket. Unfortunately we cannot bump this up the roadmap as we already have commitments to existing customers (2FA, second round of ldap improvements, audit logs, etc.).

**Comment by m333w** [comment]
Can i translate my self the template mail to get worked with gandi ?

**Comment by stripthis** [comment]
@m333w yes of course. They are all located in src/Template/Email/html
