### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by zeppelinlg** [passbolt/passbolt_api#285]
## Login failed
* Passbolt Version: 2.4.0
* Platform and Target:
-- Operating system: Debian 9.5
-- PHP: 7.0.30-0+deb9u1
-- Web server: 2.4.25-3+deb
-- Database server: mariadb-server-10.1              10.1.26-0+deb9u1
-- etc.: Containers Proxmox

### What you did
Just after an update from 2.3.0
I try to login.

### What happened
 It say "An Internal Error Has Occurred. "
![screencapture-passbolt-ivalley-fr-auth-login-2018-10-12-14_57_42](https://user-images.githubusercontent.com/1419315/46870597-4f0f7d00-ce2f-11e8-868e-cf9c4b5d86c3.png)

### What you expected to happen
To log me in

When I read logs/error.log I find :
> 2018-10-12 12:54:31 Error: [PDOException] SQLSTATE[HY000]: General error: 1364 Field 'type' doesn't have a default value
> Request URL: /auth/login.json?api-version=v1

This is my healthcheck

> www-data@passbolt ~/passbolt $ ./bin/cake passbolt healthcheck
> 
>      ____                  __          ____  
>     / __ \____  _____ ____/ /_  ____  / / /_ 
>    / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/ 
>   / ____/ /_/ (__  |__  ) /_/ / /_/ / / /    
>  /_/    \__,_/____/____/_.___/\____/_/\__/   
> 
>  Open source password manager for teams
> ---------------------------------------------------------------
>  Healthcheck shell       
> ---------------------------------------------------------------
> 
>  Environment
> 
>  [PASS] PHP version 7.0.30-0+deb9u1.
>  [PASS] PCRE compiled with unicode support.
>  [PASS] The temporary directory and its content are writable.
>  [PASS] The public image directory and its content are writable.
>  [PASS] The logs directory and its content are writable.
>  [PASS] GD or Imagick extension is installed.
>  [PASS] Intl extension is installed.
>  [PASS] Mbstring extension is installed.
> 
>  Config files
> 
>  [PASS] The application config file is present
>  [PASS] The passbolt config file is present
> 
>  Core config
> 
>  [PASS] Debug mode is off.
>  [PASS] Cache is working.
>  [PASS] Unique value set for security.salt
>  [PASS] Full base url is set to https://passbolt.*****.**
>  [PASS] App.fullBaseUrl validation OK.
>  [PASS] /healthcheck/status is reachable.
> 
>  SSL Certificate
> 
>  [PASS] SSL peer certificate validates
>  [PASS] Hostname is matching in SSL certificate.
>  [PASS] Not using a self-signed certificate
> 
>  Database
> 
>  [PASS] The application is able to connect to the database
>  [PASS] 19 tables found
>  [PASS] Some default content is present
>  [PASS] The database schema up to date.
> 
>  GPG Configuration
> 
>  [PASS] PHP GPG Module is installed and loaded.
>  [PASS] The server gpg key is not the default one
>  [PASS] The environment variable GNUPGHOME is set to /var/www/.gnupg.
>  [PASS] The directory /var/www/.gnupg containing the keyring is writable by the webserver user.
>  [PASS] The public key file is defined in config/passbolt.php and readable.
>  [PASS] The private key file is defined in config/passbolt.php and readable.
>  [PASS] The server key fingerprint matches the one defined in config/passbolt.php.
>  [PASS] The server public key defined in the config/passbolt.php is in the keyring.
>  [PASS] There is a valid email id defined for the server key.
>  [PASS] The public key can be used to encrypt a message.
>  [PASS] The private key can be used to sign a message.
>  [PASS] The public and private keys can be used to encrypt and sign a message.
>  [PASS] The private key can be used to decrypt a message.
>  [PASS] The private key can be used to decrypt and verify a message.
>  [PASS] The public key can be used to verify a signature.
> 
>  Application configuration
> 
>  [PASS] Using latest passbolt version (2.4.0).
>  [PASS] Passbolt is configured to force SSL use.
>  [PASS] App.fullBaseUrl is set to HTTPS.
>  [PASS] Selenium API endpoints are disabled.
>  [PASS] Search engine robots are told not to index content.
>  [PASS] Registration is closed, only administrators can add users.
>  [PASS] Serving the compiled version of the javascript app
>  [PASS] All email notifications will be sent.
> 
>  No error found. Nice one sparky!

Thank for your work

**Comment by stripthis** [comment]
You need to run the migration scripts.
```
./bin/cake passbolt migrate
```

**Comment by zeppelinlg** [comment]
It's already done.
I run it again

> 
>      ____                  __          ____  
>     / __ \____  _____ ____/ /_  ____  / / /_ 
>    / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/ 
>   / ____/ /_/ (__  |__  ) /_/ / /_/ / / /    
>  /_/    \__,_/____/____/_.___/\____/_/\__/   
> 
>  Open source password manager for teams
> ---------------------------------------------------------------
>  Running migration scripts.
> ---------------------------------------------------------------
> using migration paths 
>  - /var/www/passbolt/config/Migrations
> using seed paths 
>  - /var/www/passbolt/config/Seeds
> using environment default
> using adapter mysql
> using database passbolt
> 
> All Done. Took 0.1285s
> using migration paths 
>  - /var/www/passbolt/config/Migrations
> using seed paths 
>  - /var/www/passbolt/config/Seeds
> Writing dump file `/var/www/passbolt/config/Migrations/schema-dump-default.lock`...
> Dump file `/var/www/passbolt/config/Migrations/schema-dump-default.lock` was successfully written

Same error :'(

**Comment by stripthis** [comment]
Can you try:
```
 ./bin/cake cache clear_all
```

**Comment by zeppelinlg** [comment]
Nice, it's works

**Comment by zeppelinlg** [comment]
Always a good idea to clear the cache after upgrade.
Thanks :)
