### ISSUE TITLE
cannot login on freshinstall

### ISSUE THREAD

**Issue by youvnor** [passbolt/passbolt_api#286]
healthcheck is ok
everything seem fine but i cannot login and nothing is logged.

i made a vieo to make it clear:
[https://share.vidyard.com/watch/LgSu8nhvySd87YMbeDLV3U?](https://share.vidyard.com/watch/LgSu8nhvySd87YMbeDLV3U?
)
how can i debug this?

**Comment by stripthis** [comment]
See. https://community.passbolt.com/t/fresh-install-login-fail/1129/2

**Comment by youvnor** [comment]
sorry it was not a passbolt issue it was a problem about server configuration: 
Pound - Varnish - Apache2 with mod_pagespeed - Php7-FPM
