### ISSUE TITLE
Secret to clipboard fails when "remember" is active

### ISSUE THREAD

**Issue by sgargel** [passbolt/passbolt_api#287]
I've recently upgraded my passbolt_api to version 2.4

I've noticied that secrets are not correctly copied into clipboard when the "remember" flag is activated.

The secret copied is always the same.

Not using "Remember it for" flag works correcly.

My browser is Firefox 62.0.3 (64 bit) and the extension version is 2.4.0

**Comment by stripthis** [comment]
hi @sgargel,

I'm not able to reproduce the issue here. There is a known issue is when you click "somewhere else" before the secret is copied to clipboard it is not able to do so. Can you try again and make sure you wait until the loading bar is complete?

**Comment by stripthis** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#Browser-specific_considerations

Some improvements are coming with firefox 63, so hopefully this will get smoother soon.

**Comment by sgargel** [comment]
hi @stripthis 

Thanks for your reply. Today is working.. may be a cache related issue or as you stated a timing issue.
I'm not able to reproduce anymore the issue so I think we can close.

**Comment by stripthis** [comment]
Fixed another issues related to this with v2.4.2.
