### ISSUE TITLE
I am unable to share the password using passbolt. The browser gets hanged if i click Share option. (Passbolt API v1.x)

### ISSUE THREAD

**Issue by gogularaja** [passbolt/passbolt_api#288]
I am unable to share the password using passbolt. The browser gets hanged if i click Share option.

I am getting the below error from my browser console

Error: 

shareChanges.js:30 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at resource.permissions.forEach.permission (shareChanges.js:30)
    at Array.forEach (<anonymous>)
    at ShareChanges.resources.forEach.resource (shareChanges.js:28)
    at Array.forEach (<anonymous>)
    at new ShareChanges (shareChanges.js:27)
    at init (share.js:46)
    at <anonymous>
resource.permissions.forEach.permission @ shareChanges.js:30
ShareChanges.resources.forEach.resource @ shareChanges.js:28
ShareChanges @ shareChanges.js:27
init @ share.js:46
async function (async)
init @ share.js:43
(anonymous) @ share.js:385
mightThrow @ jquery.js:3534
process @ jquery.js:3602
setTimeout (async)
(anonymous) @ jquery.js:3640
fire @ jquery.js:3268
fireWith @ jquery.js:3398
fire @ jquery.js:3406
fire @ jquery.js:3268
fireWith @ jquery.js:3398
ready @ jquery.js:3878
completed @ jquery.js:3888

![selection_097](https://user-images.githubusercontent.com/14348828/47064686-193b1180-d1fe-11e8-9c34-909d063ec057.png)

**Comment by cedricalfonsi** [comment]
Hello @gogularaja,

This error you see in the web console is relative to the version 2.3 of the js application served by the API. The share feature has been upgraded in the version 2.4 and is now embedded in the browser extension which replaces the behavior of the js application.

This error should not block the share to work properly, or block the application. Once you will upgrade to the v2.4 of the API you won't see it anymore.

Could you give us more information to help to debug this issue ?
- Firefox/Chrome version
- Output of the browser extension console (the one you gave is relative to the web console). You can open it following these instructions :
-- Firefox: https://developer.mozilla.org/en-US/docs/Tools/Browser_Console
-- Chrome: https://stackoverflow.com/a/10258029/4063145

**Comment by gogularaja** [comment]
Hi Cedri,

I have been using 
- passbolt api version : 1.6.5
- passbolt add-on version in chrome : 2.4.1

Attached my extension page image in developer mode. 
![selection_098](https://user-images.githubusercontent.com/14348828/47068688-91a7cf80-d20a-11e8-8b36-96f9858ac3ee.png)
The is no keyword "Inspect views: background page" for the passbolt add-on.

**Comment by stripthis** [comment]
@gogularaja passbolt v1 is deprecated since June 2018. Please upgrade to v2.

**Comment by stripthis** [comment]
See. https://help.passbolt.com/hosting/upgrade
