### ISSUE TITLE
Unable to share passwords, 404 on /share/search-users/resource/

### ISSUE THREAD

**Issue by gileri** [passbolt/passbolt_api#289]
* Passbolt Version: 2.4.0
* Passbolt extension : 2.4.1
* Platform and Target: [passbolt_docker on master](https://github.com/passbolt/passbolt_docker/commit/f217edac79be63bb0e68f005784ae75c3c22a153)

### What you did
Any user click on Share on an existing or new password (or multiple passwords), input some text in the autocomplete input

### What happened
The spinner is stuck, results are not displayed  and I get a 404 with "Page not found" HTML body on `/share/search-users/resource/<resource id>?api-version=2&filter%5Bsearch%5D=<search term>`

An error is added in passbolt's error.log :
```
2018-10-24 16:15:54 Error: [Cake\Network\Exception\NotFoundException] Page not found.
Request URL: /share/search-users/resource/<resource id>?api-version=2&filter%5Bsearch%5D=<search term>
```

Similar error when bulk sharing password :
```
2018-10-26 09:52:47 Error: [Cake\Network\Exception\NotFoundException] Page not found.
Request URL: /share/search-aros?api-version=2&filter%5Bsearch%5D=<search term>
```

### What you expected to happen
The autocomplete returns a list of entries

### Additional testing :
The resource exists in database :

```
       name: <name with only ascii>
   username: NULL
        uri: NULL
description: NULL
    deleted: 0
    created: 2018-10-24 15:37:32
   modified: 2018-10-24 15:37:32
 created_by: <my user id>
modified_by: <my user id>
```

User :
```
      id: <my user id>
 role_id: <admin role id>
username: <my email>
  active: 1
 deleted: 0
 created: 2017-12-19 15:58:24
modified: 2017-12-19 16:03:46
```

Permission for resource :
```
MariaDB [passbolt]> SELECT * FROM permissions WHERE aco='Resource' AND aco_foreign_key='<resource id>'\G
*************************** 1. row ***************************
             id: <permission id>
            aco: Resource
aco_foreign_key: <resource id>
            aro: User
aro_foreign_key: <my user id>
           type: 15
        created: 2018-10-24 15:37:32
       modified: 2018-10-24 15:37:32
```

**Comment by cedricalfonsi** [comment]
Hello @gileri,

I cannot reproduce your bug with passbolt_docker on master.
Do you also have the same issue while looking for users to add to a group ?

**Comment by gileri** [comment]
Hello @cedricalfonsi, adding users to groups works fine here.

I have added information on database entities on OP (I'm not sure where to look)

**Comment by cedricalfonsi** [comment]
Do you have only one line in your './log/error.log' ? No full trace ?
> Request URL: /share/search-users/resource/<resource id>?api-version=2&filter%5Bsearch%5D=<search term>

Even if the resource doesn't exist, this entry point shouldn't return a 404.
It could come from a cache issue, did you configure your passbolt to use an external cache ? Redis or whatever other flavor (mounted volume) ?

**Comment by cedricalfonsi** [comment]
Can you search for users when sharing multiple resources ?

**Comment by gileri** [comment]
>Do you have only one line in your './log/error.log' ? No full trace ?
You're right, I forgot a line of log, sorry about that :
```2018-10-24 16:00:01 Error: [Cake\Network\Exception\NotFoundException] Page not found.
Request URL: /share/search-users/resource/508bfbcf-2f63-4682-b2ba-962a65d81429?api-version=2&filter%5Bsearch%5D=q
```

> It could come from a cache issue, did you configure your passbolt to use an external cache ? Redis or whatever other flavor (mounted volume) ?

Our Passbolt instance sits behind a CDN (Cloudfront), but it's configured to do no caching (Response headers confirm that requests do not hit the cache). There is no application cache such as redis in our setup.

> Can you search for users when sharing multiple resources ?

I got the same error on the first autocomplete XHR request:

```
2018-10-26 09:52:47 Error: [Cake\Network\Exception\NotFoundException] Page not found.
Request URL: /share/search-aros?api-version=2&filter%5Bsearch%5D=<search term>
```

**Comment by cedricalfonsi** [comment]
The entry point `/share/search-users/resource/<resource id>` has been deprecated in 2.4 and the requests coming on this route are redirected to `/share/search-aros`. But here you cannot reach both of them. It is probably relative to the framework cache, you could try to clean it and test again `bin/cake cache clear_all`

**Comment by gileri** [comment]
Using docker, and not having cache binded/mounted, it is "flushed" at each `docker run`. I cleared the cache anyway :

```
# bin/cake cache clear_all
Cleared default cache
Cleared _cake_core_ cache
Cleared _cake_model_ cache
```

**Comment by cedricalfonsi** [comment]
Indeed, the cache is flushed at each `docker run`.
I'm wondering if the CDN is not the source of your issue here.
Can you try to access directly to the route using the server IP (if possible).
`http://0.0.0.0/share/search-aros.json`
If you get a 403 it could mean that the application is well answering to the route.

**Comment by gileri** [comment]
I did not test without the CDN earlier as I thought it would be trickier with our setup, but I should have, as when I repeat the same HTTP request with curl (with copy as cURL in browser devtools), it works fine.

```
% curl -k 'https://<direct server ip>/share/search-users/resource/<resource id>?api-version=2&filter%5Bsearch%5D=<search term>'

<normal JSON response>
```

What threw my off that track early (CDN issue) is that 404 are cached for 5 minutes at most in our setup, cache keys should be based on all headers.
I'm really sorry for the disturbance, closing.
