### ISSUE TITLE
first party isolation prevent me to log in on firefox

### ISSUE THREAD

**Issue by lunika** [passbolt/passbolt_api#291]
## impossible to login on firefox

* Passbolt Version: online demo so think it is the last one.
* Platform and Target: online demo, I don't have this information.

### What you did

After configuring my account I am not able to connect to my account. Each time I submit the form I'm redirected to the login page.

I found the setting responsible of this behaviour. in `about:config` I changed the setting `privacy.firstparty.isolate` to false (the default value) and I can login. First party isolation is also know as [Cross-Origin Identifier Unlinkability](https://www.torproject.org/projects/torbrowser/design/#identifier-linkability) and I don't really want to disable it.

**Comment by stripthis** [comment]
Hi @lunika,

Yes this feature prevents the cookie holding the session id to be accessed by the web extension, therefore preventing it to persist login. It is a similar issue than https://github.com/passbolt/passbolt_api/issues/177 albeit for different reason.

Solution would be to provide a Cookie-less session system for the extension, which is something we want to do at some point but kind of low on the priority of requested changes by existing users.

**Comment by stripthis** [comment]
Closing because stalled.
