### ISSUE TITLE
Could not add user to a group

### ISSUE THREAD

**Issue by AnswerKAS** [passbolt/passbolt_api#292]
### Could not add user to a group
* Passbolt Version: 2.5.0
* Platform and Target:
-- Operating system: Debian 9.6
-- PHP: 7.0.30
-- Web server: Apache/2.4.25 (Debian)
-- Database server: 10.1.37-MariaDB-0+deb9u1 Debian 9.6

### What you did
1. Click on "users" in the top bar.
2. Click on the "+" symbol in the left bar for the group I want to add a user in.
3. Click on "edit group".
4. Search user in the add people field and then click on the user found.
5. Save the group
6. Enter the password to validate my privilege (I guess)
7. Get this error message : Error The group could not be saved

### What happened
The user is not added to the group. I'm get error: "Error The group could not be saved"

### What you expected to happen
The user being added to the group.

**Comment by stripthis** [comment]
Hello @AnswerKAS,
Can you try to add the user and check the logs in your passbolt directory:
```
tail /var/www/passbolt/logs/error.log 
```
Can you also run the following command in your passbolt directory:
```
./bin/cake passbolt cleanup --dry-run
```

**Comment by AnswerKAS** [comment]
Thanks. Problem solved.

**Comment by AnswerKAS** [comment]
@stripthis Thanks. Problem solved.

**Comment by AnswerKAS** [comment]
@stripthis Sorry, we checked on the wrong group. The problem is not solved.
`2018-12-05 05:11:21 Error: [App\Error\Exception\ValidationException] Could not validate group data.
Request URL: /groups/5a17d64e-d37c-44a9-81ef-73000a505813.json?api-version=v1`

Result `root@uhq-passbolt:/var/www/passbolt# ./bin/cake passbolt cleanup --dry-run` 
`7 orphan records found in table GroupsUsers (hard deleted groups)`
`7 issues detected, please run the same command without --dry-run to fix them.`
`root@uhq-passbolt:/var/www/passbolt# tail -f /var/www/passbolt/logs/error.log`

**Comment by cedricalfonsi** [comment]
Hello @AnswerKAS,

We'd like to help you with your issue. For this we'll need an obfuscated version of your database.
We have released debug scripts to help obfuscate database. See: https://github.com/passbolt/passbolt_api_dev_tools.

To obfuscate your database :
1. Download the obfuscating script:
`wget https://raw.githubusercontent.com/passbolt/passbolt_api_dev_tools/master/scripts/obfuscdump.sql`
2. Check where mysql can output files
`mysql -u USERNAME -p DBNAME -e "SELECT @@global.secure_file_priv"`
3. If the value of @@global.secure_file_priv is different of NULL
In obfuscdump.sql replace the occurrences of "/tmp/obfuscated_dump/" by the value returned by the sql command
4. Execute the obfuscating script
`mysql -u USERNAME -p DBNAME < obfuscdump.sql`
5. Compress the files, and send them to us at support@passbolt.com

**Comment by cedricalfonsi** [comment]
Hello @AnswerKAS,

Unfortunately, I didn't receive your email.
Did you get an error later maybe? How big was the attached file?

**Comment by AnswerKAS** [comment]
@cedricalfonsi 

Sent file from another email. There were no errors when sending. 
File size 1MB

**Comment by cedricalfonsi** [comment]
Hello @AnswerKAS
Yes I'm investigating it today.
Can you give me the group name / or the group id you have problem with.

**Comment by albertmatyi** [comment]
I am getting the same error message on the frontend. Tailing the error log gives me:
```
2019-03-08 10:40:23 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/account/settings.json" could not be found.
Request URL: /account/settings.json?api-version=v2
2019-03-08 17:26:13 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/account/settings.json" could not be found.
Request URL: /account/settings.json?api-version=v2
2019-03-08 17:26:36 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/account/settings.json" could not be found.
Request URL: /account/settings.json?api-version=v2
2019-03-08 18:37:20 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/account/settings.json" could not be found.
Request URL: /account/settings.json?api-version=v2
2019-03-09 12:49:33 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/robots.txt" could not be found.
Request URL: /robots.txt
2019-03-09 12:49:34 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/sitemap.xml" could not be found.
Request URL: /sitemap.xml
2019-03-09 12:49:35 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/.well-known/security.txt" could not be found.
Request URL: /.well-known/security.txt
2019-03-11 13:17:20 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/cgi-bin/config.exp" could not be found.
Request URL: /cgi-bin/config.exp
2019-03-11 13:41:50 Error: [Cake\Network\Exception\BadRequestException] The authentication token is not valid or expired.
Request URL: /setup/install/7d25fe14-5b25-4567-8ebd-94fa4217a710/b879d07e-6c45-43ec-b27e-f486645dfb48
2019-03-11 13:46:23 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/account/settings.json" could not be found.
Request URL: /account/settings.json?api-version=v2
2019-03-11 13:46:31 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/account/settings.json" could not be found.
Request URL: /account/settings.json?api-version=v2
2019-03-11 13:48:57 Error: [App\Error\Exception\ValidationException] Could not validate group data.
Request URL: /groups/ff615e5a-5ea7-46aa-a5e5-91f08ee6b355.json?api-version=v1
2019-03-11 13:49:02 Error: [App\Error\Exception\ValidationException] Could not validate group data.
Request URL: /groups/ff615e5a-5ea7-46aa-a5e5-91f08ee6b355.json?api-version=v1
2019-03-11 13:49:20 Error: [App\Error\Exception\ValidationException] Could not validate group data.
Request URL: /groups/ff615e5a-5ea7-46aa-a5e5-91f08ee6b355.json?api-version=v1
2019-03-11 13:49:28 Error: [App\Error\Exception\ValidationException] Could not validate group data.
Request URL: /groups/ff615e5a-5ea7-46aa-a5e5-91f08ee6b355.json?api-version=v1
2019-03-11 13:49:47 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/account/settings.json" could not be found.
Request URL: /account/settings.json?api-version=v2
2019-03-11 13:50:03 Error: [App\Error\Exception\ValidationException] Could not validate group data.
Request URL: /groups/ff615e5a-5ea7-46aa-a5e5-91f08ee6b355.json?api-version=v1
2019-03-11 13:51:41 Error: [App\Error\Exception\ValidationException] Could not validate group data.
Request URL: /groups/ff615e5a-5ea7-46aa-a5e5-91f08ee6b355.json?api-version=v1
2019-03-11 13:52:42 Error: [App\Error\Exception\ValidationException] Could not validate group data.
Request URL: /groups/ff615e5a-5ea7-46aa-a5e5-91f08ee6b355.json?api-version=v1
2019-03-11 13:54:08 Error: [App\Error\Exception\ValidationException] Could not validate group data.
Request URL: /groups/ff615e5a-5ea7-46aa-a5e5-91f08ee6b355.json?api-version=v1
```

I tried running the cleanup, without any success

```
./bin/cake passbolt cleanup          

     ____                  __          ____  
    / __ \____  _____ ____/ /_  ____  / / /_ 
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/ 
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /    
 /_/    \__,_/____/____/_.___/\____/_/\__/   

 Open source password manager for teams
---------------------------------------------------------------
 Cleanup shell (delete mode)
---------------------------------------------------------------
No issue found, data looks squeaky clean!
```

**Comment by cedricalfonsi** [comment]
Hello @albertmatyi,

To help you I need to have a look at an obfuscated version of your database.

If it's possible for you, send me an email at support( at )passbolt( .dot )com following the process describe in the [comment above](#issuecomment-444384135).

Best regards

**Comment by albertmatyi** [comment]
Thanks @cedricalfonsi !

The last time I've just created a new group and migrated all passwords - it seemed to work then.

On the other hand a colleague of mine, Krisztina Fekete has sent you an email with the full report as described in the comment and screenshot of the issue as requested.

Shall I have the time I'll try to debug the extension if possible, because it seems to be an issue that happens in the extension. (there are no visible requests when the error occurs, but it occurs in passbolt.js in a request handler). My assumption is that it is a response of the extension that somehow fails to identify the group.

I've checked the database, and all entities seem to be connected correctly by id, and the frontend loads through requests the correct user / group ids.

Hope we'll get to the bottom of it (because this is currently forcing us to recreate groups and manually migrate all passwords  / users, which is quite a hassle).

Regards
m

**Comment by albertmatyi** [comment]
We've debugged the code, and the issue lies somewhere among the lines
```
             $resources = $this->_patchAndValidateResourcesEntities($group, $groupUserOriginal,    Hash::get($data, 'secrets', []));
            //THE RESOURCES OBJECT IS BUILT UP, WITH NO APPARENT EXCEPTIONS

            // Save the group resources secrets.
            $saveResult = $this->_saveResourcesEntities($resources);
            // THE SAVEMANY CALL FAILS 
            if ($saveResult === false) {
                $this->_handleValidationError($group, $resources);
                // EXCEPTION IS REPORTED
                return false;
            }
```

Unfortunately we could not pinpoint the issue, but the assumption is that the data relations got corrupted, through a specific sequence of passwordcreation / sharing /etc.

Afterwards we've identified a password that was having trouble being shared.

We've deleted the password (that was also shared with the group we couldn't add users to).

The "Adding a user to a group" started working again.

**Comment by stripthis** [comment]
@albertmatyi thank you for the follow up. Yes if you have more information about the failing changes that will certainly help.

**Comment by albertmatyi** [comment]
Hi @stripthis ,

I've sent all the details we have regarding this issue to support at passbolt dot com, including dump, screenshot, print_rs 

![2019-04-25-102439_865x563_scrot](https://user-images.githubusercontent.com/1370078/56721077-6c10fb00-6744-11e9-9b0c-5250dd8d53e4.png)

Hope it helps!
cheers
m

**Comment by cedricalfonsi** [comment]
Closing as stalled. Feel free to reopen if you are still experiencing the problem.
