### ISSUE TITLE
Improve performance password workspace loading time (800 records / 18 sec)

### ISSUE THREAD

**Issue by damien-list** [passbolt/passbolt_api#293]
## ISSUE NAME
* Passbolt Version: 2.5.1 (I checkout the tag v2.5.1 but the version.php file says that I'm in 2.5.0) 
* Platform and Target:
-- Operating system: Ubuntu 16.04
-- PHP: 7.1.23
-- Web server: Apache 2.4
-- Database server: MySQL 5.5
-- etc.: Passbolt is served on a virtual machine, not by docker.

### What you did
I log in our passbolt instance.

### What happened
1. It takes 18s to resources.json to finish. 

### What you expected to happen
Startup being faster.

**Comment by stripthis** [comment]
@damien-list can you give more details? What kind of machine you are running passbolt on? What kind of connection you have? How many records you have in the db? There are a lot of criteria that affects performance, we need precise indicators to be able to work on it.

**Comment by damien-list** [comment]
Hi @stripthis , sure I can give more details :)

- The Virtual Machine : CPU Intel(R) Xeon(R) CPU E5-1410 v2 @ 2.80GHz, 12Go RAM, 500 Go SSD
- Connection = fiber.
- # of records : 793

**Comment by cedricalfonsi** [comment]
Hi @damien-list 

We just published a performance fix with the release v2.7.0. 
I'm closing your ticket. Reopen it if you are still encountering this issue.

Cheers

**Comment by damien-list** [comment]
Hi @cedricalfonsi,

I've upgraded our passbolt instance to 2.7.2 and it loads at the same speed.
I've followed the [update documentation](https://help.passbolt.com/hosting/update) for the minor update part.

Thanks

**Comment by cedricalfonsi** [comment]
On some benchmarks especially the call to /resources.json we noticed a 10x improvement with large database (~4000 passwords). I can see that you are using the pro version, would you mind sending me a message on support(at)passbolt(dot)com, we could organize a call and dig into this issue.
