### ISSUE TITLE
No indexes on resources and secrets

### ISSUE THREAD

**Issue by eddie4** [passbolt/passbolt_api#294]
## ISSUE NAME
* Passbolt Version: 2.5.0
* Platform and Target:
-- Operating system: Ubuntu 16.04
-- PHP: 7.0.32-0ubuntu0.16.04.1 
-- Web server: Apache/2.4.18 (Ubuntu)
-- Database server: mysql  5.7.24,

### What you did
I had a huge performance issue when creating 15000 sharing records. While debugging i spotted that there are no index's on secrets and resources. I added a few indexes on them solved a big part of the issue. I would post the indexes but my random quick fixes are probably not the best to use.

Also had to increase max_execution in php.ini

**Comment by cedricalfonsi** [comment]
Hello @eddie4,

Your contribution will be very much appreciated. We are continuously working to improve the performance of the application and the user experience. Don't hesitate to share your findings with us we will integrate them.

**Comment by stripthis** [comment]
Solved in v2.7
