### ISSUE TITLE
SMTP Password with double quotes breaks mail sending

### ISSUE THREAD

**Issue by Kukuruts** [passbolt/passbolt_api#296]
## SMTP Password with double quotes breaks mail sending
* Passbolt Version: 2.6.1 / 2.4.6 
* Platform and Target:
-- Operating system: Debian 9
-- PHP: 7.0.33
-- Web server: nginx/1.10.3

### What you did
The mailbox we use for sending mails with Passbolt includes a double quote (") in it's password. I entered this password in the configuration wizard after installing Passbolt Pro.

### What happened
The wizard's SMTP test worked, I got the test email. However, the password was saved escaped in the configuration file passbolt.php which broke the email configuration.
To clarify: I entered 
`123"456`
the configuration contained
`'password' => '123\"456'`

### What you expected to happen
Because you use single quotes in your config files you don't need to escape double quotes. I just changed the password settings to `'password' => '123"456'` and everything worked as expected.

**Comment by cedricalfonsi** [comment]
Hello from 2022. Enjoy 2018, it was awesome :) 

Fixed with [v3.8.0](https://help.passbolt.com/releases/pro/syria) and the SMTP settings now stored encrypted in the database.
