### ISSUE TITLE
Passwords are shown twice in workspace list

### ISSUE THREAD

**Issue by stripthis** [passbolt/passbolt_api#299]
From: https://community.passbolt.com/t/bugfix-filter-by-groups-shows-passwords-twice/1450

In v2.7 and before.
How to reproduce:
- login
- do a search
- click on a filter before the search is done updating the workspace
- items are shown twice even if you click on another filter.
![screenshot 2019-02-15 at 16 16 28](https://user-images.githubusercontent.com/77410/52865543-28df4e00-313d-11e9-9094-f09aed1984ac.png)

**Comment by cedricalfonsi** [comment]
Fixed with v2.8.4
