### ISSUE TITLE
Feature Request: Support categories/tag for resources

### ISSUE THREAD

**Issue by jinhill** [passbolt/passbolt_api#30]
I suggest:  can set resource group, such as Web, SSH, FTP, and so on.

**Comment by glebaccon** [comment]
Categories/tags should be shared with groups/users.

**Comment by passboltUser** [comment]
+1

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-a-user-i-can-manage-and-organize-resources-with-tags/73
