### ISSUE TITLE
Nginx is not correctly configured for IPv6

### ISSUE THREAD

**Issue by tuxis-ie** [passbolt/passbolt_api#302]
The passbolt_pro_debian_installer.sh script configures Nginx incorrectly, as it configures it to listen on IPv4 only. Please make Nginx listen on IPv4 and IPv6.

**Comment by cedricalfonsi** [comment]
Hello @tuxis-ie,

Thank you for your report.

I moved this ticket to the install_scripts repository: https://github.com/passbolt/passbolt_install_scripts/issues/4.
