### ISSUE TITLE
Multi-team configuration

### ISSUE THREAD

**Issue by thommierother** [passbolt/passbolt_api#304]
Currently a given firefox profile with an installed passbolt addon is linked to one passbolt server installation (domain).  If you work in multiple teams which have different passbolt server instances (domains), you need  separate firefox profiles for each of them.  An enhancement would offer an option to link one firefox profile (pb addon) to different domains in different working teams/projects

**Comment by stripthis** [comment]
Hi @thommierother, there is a feature request on the community forum for this (we use github only for bugs). https://community.passbolt.com/t/as-a-user-i-can-configure-passbolt-browser-extension-to-work-with-multiple-passbolt-instances/77
