### ISSUE TITLE
OTP recovery codes

### ISSUE THREAD

**Issue by esprit-libre** [passbolt/passbolt_api#306]
## ISSUE NAME
* Passbolt Version: 2.7.2
* Platform and Target:
-- Operating system: Debian Stretch
-- PHP: 7.0
-- Web server: Apache 2.4
-- Database server: MariaDB

### What you did
On my account, I set up OTP and everything worked fine until... I broke my phone! Now I can't connect and I don't have OTP recovery codes.

### What you expected to happen
Is there a way to reinitialize my OTP settings without removing and recreating my account? I don't wan't to loose my passwords set, even if it's a small one.
Have I miss OTP recovery codes or does they exists at all?

Thanks for your help

**Comment by stripthis** [comment]
hi @esprit-libre,

There are no recovery code at the moment (instead we encourage people to setup different OTP mechanism in case they loose one). Generally the token is active on devices that are already recognize, so if you can login, you could just disable/renable it to create a new OTP secret. 

However if you lost your phone and you are logging in from a new device (or the token expired) It is possible to drop the configuration for that user by editing the database:
```
delete from account_settings where property='mfa' and user_id = (select id from users where username='your@email.com');
```

By the way this feature is part of Passbolt Pro, so you can contact us at support@passbolt.com for further help.
