### ISSUE TITLE
sending mail from wamp server in php

### ISSUE THREAD

**Issue by developer-new** [passbolt/passbolt_api#307]
Sending mail from wamp server in php
The error is:
SMTP -> FROM SERVER:220 smtp.gmail.com ESMTP t10sm19500684pfa.151 - gsmtp 
SMTP -> FROM SERVER: 250-smtp.gmail.com at your service, [103.51.28.50] 250-SIZE 35882577 250-8BITMIME 250-STARTTLS 250-ENHANCEDSTATUSCODES 250-PIPELINING 250-CHUNKING 250 SMTPUTF8 
SMTP -> ERROR: AUTH not accepted from server: 530 5.7.0 Must issue a STARTTLS command first. t10sm19500684pfa.151 - gsmtp 
SMTP -> FROM SERVER:250 2.1.5 Flushed t10sm19500684pfa.151 - gsmtp 
SMTP -> FROM SERVER:530 5.7.0 Must issue a STARTTLS command first. t10sm19500684pfa.151 - gsmtp 
SMTP -> ERROR: MAIL not accepted from server: 530 5.7.0 Must issue a STARTTLS command first. t10sm19500684pfa.151 - gsmtp 
The following From address failed: pkkumari842@gmail.com : MAIL not accepted from server,530,5.7.0 Must issue a STARTTLS command first. t10sm19500684pfa.151 - gsmtp
SMTP server error: 5.7.0 Must issue a STARTTLS command first. t10sm19500684pfa.151 - gsmtp

Mailer Error: The following From address failed: pkkumari842@gmail.com : MAIL not accepted from server,530,5.7.0 Must issue a STARTTLS command first. t10sm19500684pfa.151 - gsmtp
SMTP server error: 5.7.0 Must issue a STARTTLS command first. t10sm19500684pfa.151 - gsmtp

SMTP server error: 5.7.0 Must issue a STARTTLS command first. t10sm19500684pfa.151 - gsmtp
 I cant understand what is this problem.
The code i'm using i.e.

<?php

	require 'PHPMailer/class.phpmailer.php';

	$mail = new PHPMailer();
	  
	  //Enable SMTP debugging.
	  $mail->SMTPDebug = 2;
	  //Set PHPMailer to use SMTP.
	  $mail->isSMTP();
	  //Set SMTP host name
	  $mail->Host = "smtp.gmail.com";
	  //Set this to true if SMTP host requires authentication to send email
	  $mail->SMTPAuth = TRUE;
	  //Provide username and password
	  $mail->Username = "pkkumari842@gmail.com";
	  $mail->Password = "@@##$$12";
	  //If SMTP requires TLS encryption then set it
	  $mail->SMTPSecure = "true";
	  $mail->Port = 587;
	  //Set TCP port to connect to
	  
	  $mail->From = "pkkumari842@gmail.com";
	  $mail->FromName = "priyanka";
	  
	  $mail->addAddress("pkkumari842@gmail.com", "priyanka");
	  $mail->addReplyTo("pkkumari842@gamil.com", "priyanka");
	  
	  $mail->isHTML(true);
	 
	  $mail->Subject = "test mail";
	  $mail->Body = "<i>this is your password:</i>";
	  $mail->AltBody = "This is the plain text version of the email content";
	  if(!$mail->send())
	  {
	   echo "Mailer Error: " . $mail->ErrorInfo;
	  }
	  else
	  {
	   echo "Message has been sent successfully";
	  }

**Comment by stripthis** [comment]
Please use the community forum for installation issues: 
https://community.passbolt.com/
