### ISSUE TITLE
Can't login with Firefox after initial setup, but Chrome works

### ISSUE THREAD

**Issue by nodje** [passbolt/passbolt_api#309]
Disclaimer: `If you are certain this is a new API bug...` I am not certain of this.
But there are so many project in your git hub that I don't know better

Can't login with Firefox after initial setup, but Chrome works
* Passbolt Version: latest on DigitalOcean market

### What you did
Fresh install

### What happened
Chrome let me login, but Firefox lands me back to the login after I enter the password.

### What you expected to happen
To be logged in ! :)

Please help me transfer the issue to the right project if it is not this one (it's actually very likely that this has nothing to do with the API per se)

And help me debug the issue for you. (no proxy active, no add-blocker, Content Blocking set to Standard, cookies allowed... no error in the console)
It would actually be nice to know the requirements on the browser side (in terms of cookies and stuff like that)

**Comment by cedricalfonsi** [comment]
Hello @nodje,

Did you disable third party cookie on Firefox ?

Other people faced the same issue: https://community.passbolt.com/t/issue-with-firefox-57-and-accept-third-party-cookies-disabled/162/4

**Comment by nodje** [comment]
hi @cedricalfonsi , as i wrote, I saw other people issues, and I took care to enable cookies in FF before testing.
`Content Blocking set to Standard` actually means enabling all cookies in FF.

I'd be nice to have a list of browser requirements to get passbolt working

**Comment by cedricalfonsi** [comment]
I am not able to reproduce your issue with a fresh droplet on Digital Ocean and the following versions of Firefox :
- FF ESR 60.5.2esr: The third party cookies have to be allowed, by default it is.
- FF latest 65.0.1: Content blocking strategy set to standard (by default) as well as with a more aggressive strategy which blocks all the third party cookies.
- FF Developer edition 66.0b14: Same config as the stable edition.

What we know is that the Passbolt plugin is not working properly with the [Firefox Multi-Account Container addon](https://github.com/passbolt/passbolt_browser_extension/issues/41). And that it requires third party-cookies enabled for the version prior to the 65, it looks like that with newer version it is working even with an aggressive strategy (to be confirmed with the following versions).

To help you debug your issue could you please copy/paste here what you see in the plugin console.
1. Go to about:debugging#addons
2. Enable add-on debugging
3. Click on the debug link of the Passbolt Extension.

**Comment by nodje** [comment]
Ok, I'm using Firefox Multi-Account Container addon.
I didn't realize it could cause this kind of trouble.

I guess your post could server as guidelines for browser usage.

Thank you for your prompt reply.
