### ISSUE TITLE
Bump version string in files from 2.8.1 to v2.8.2.

### ISSUE THREAD

**Issue by b4d** [passbolt/passbolt_api#312]
Error is displayed in healthcheck, as two minor revisions followed in quick order and nobody updated all the version strings in files:

`[FAIL] This installation is not up to date. Currently using 2.8.1 and it should be v2.8.2.`

**Comment by stripthis** [comment]
Thanks for the heads up @b4d

**Comment by vrobic** [comment]
In addition, the two links in the [update documentation](https://help.passbolt.com/hosting/update#where-to-find-the-latest-release-version-number) are broken: 

> You can find information about which version is the latest in the release notes. It is generally a good idea to check these notes before running an update. You can also find it on the official GIT repository.

Thanks! :-)

**Comment by cedricalfonsi** [comment]
Version string in /config/version.php fixed with v2.8.3.
Broken links fixed as well.
Thank you
