### ISSUE TITLE
Password permalink

### ISSUE THREAD

**Issue by vrobic** [passbolt/passbolt_api#315]
Hello,

The permalink to a single password is not working:

<img width="452" alt="Screenshot" src="https://user-images.githubusercontent.com/5630306/55715408-f6432a80-59f4-11e9-898e-08b425879856.png">

It gives an undefined URL: https://passbolt.example.org/app/passwords/view/undefined.

Thanks :-)

**Comment by cedricalfonsi** [comment]
Hello @vrobic,

Thank you for the report.
I'm able to reproduce it, I added a ticket to our current sprint to handle it.

**Comment by cedricalfonsi** [comment]
Fixed with v2.8.4

**Comment by vrobic** [comment]
Fixed. Thanks!
