### ISSUE TITLE
Can not edit shared resource or remove user

### ISSUE THREAD

**Issue by patrickghg** [passbolt/passbolt_api#316]
**Can not edit shared resource or remove user**
* Passbolt Version: 2.8.3
* Platform and Target: 
- CentOS Linux release 7.6.1810 (Core)
- PHP 7.2.17 
- nginx/1.14.2
- 5.5.60-MariaDB

### What you did
1) I removed a user of a shared resource 
2) I changed the password of a resource

However if I creat a new resource and share it with the same group and remove the group again everything works fine. So only the old created resources are affected.

### What happened
1) Passbolt displayed a success message that everything is done. However, the user still has access to this resource. He is also still in the list of shared users.
2) Passbolt is stuck at Encrypting 2/6 33%

Log for 1 & 2:
[App\Error\Exception\ValidationException] Could not validate resource data.
Request URL: /share/resource/28b06ada-20ff-4190-b4be-b6cb4d17cbb2.json?api-version=v1

### What you expected to happen
1) The deleted user no longer has access to the password.
2) The password of the resource is updated

I've executed the command  ./bin/cake passbolt cleanup --dry-run but unfortunately it had no effect on the problem.

**Comment by stripthis** [comment]
Hi @patrickghg, what happen when you try to remove the user again? The interface says it is removed but then reapear in the list again?

**Comment by patrickghg** [comment]
> Hi @patrickghg, what happen when you try to remove the user again? The interface says it is removed but then reapear in the list again?

Exactly. I can't remove the user from the shared tab. We are currently using a small workaround by completely removing and recreating the resource.

**Comment by stripthis** [comment]
@patrickghg  can you contact us at support@passbolt.com, what would be useful is an obfuscated dump of your data so that we can investigate how to reproduce and fix this issue.

**Comment by patrickghg** [comment]
@stripthis I contacted you

**Comment by cedricalfonsi** [comment]
Inactive users were added to groups manually in the database. Editing the database manually is not recommended as it could break the integrity of the data. The best approach would be to :
- Implement scripts that request the API (see the api [reference](https://api-reference.passbolt.com/) and [documentation](https://help.passbolt.com/api)) 
- Use [the passbolt cli](https://github.com/passbolt/passbolt_cli) (which will support all the API in a near future)
