### ISSUE TITLE
Wrong label for unlock button after cancel

### ISSUE THREAD

**Issue by vrobic** [passbolt/passbolt_api#321]
## Wrong label for unlock button after cancel
* Passbolt Version: 2.9.0
* Platform and Target:
-- Operating system: Mac OS Mojave
-- Browser: Chrome 74

### What you did

Edit a password, then click on _click here to unlock_:

<img width="244" alt="Capture d’écran 2019-05-15 à 09 31 36" src="https://user-images.githubusercontent.com/5630306/57757368-9deb0100-76f5-11e9-8f38-cbbe6b8f6cd4.png">

Click _cancel_:

<img width="244" alt="Capture d’écran 2019-05-15 à 09 31 43" src="https://user-images.githubusercontent.com/5630306/57757369-9deb0100-76f5-11e9-9f6a-6345036ec232.png">

### What happened

The password field is no more showing _click here to unlock_ but _password_:

<img width="244" alt="Capture d’écran 2019-05-15 à 09 31 49" src="https://user-images.githubusercontent.com/5630306/57757370-9e839780-76f5-11e9-8c76-6cc87d36c88a.png">

### What you expected to happen

I expected the password field to be reset to its original state, showing _click here to unlock_.

**Comment by abhinavkumar940** [comment]
Hey @vrobic thank you for reporting this. I am able to reproduce this and have added this to our backlog. For future reference, you can also use our internal bug tracking issue id for this `PB-326`.

We'll take care of this in future sprints and will keep you posted.

**Comment by stripthis** [comment]
Fixed with v2.13
