### ISSUE TITLE
Outdated health check instructions

### ISSUE THREAD

**Issue by ElliottLandsborough** [passbolt/passbolt_api#322]
* Passbolt Version: 2.10.0
* Platform and Target: All

### What you did
Failed a health check.

### What happened
Copy pasted the command outputted by the [help] lines but it didn't work because it is outdated.

```bash
[HELP] sudo su -s /bin/bash -c "/home/elliott/projects/passbolt_api/bin/cake install" www-data
```

### What you expected to happen
Copy paste the line and install starts.

```bash
[HELP] sudo su -s /bin/bash -c "/home/elliott/projects/passbolt_api/bin/cake passbolt install" www-data
```

**Comment by stripthis** [comment]
Thanks for the report.
