### ISSUE TITLE
Confusing import/export button icons

### ISSUE THREAD

**Issue by jsm222** [passbolt/passbolt_api#324]
## Confusing import button icon (css-class)
* Passbolt Version: v2.10.0
* Platform and Target: 
-- Operating system: Ubuntu 18.04
-- PHP: v7.2.19-0ubuntu0.18.04.1
-- Web server: nginx 1.14.0-0ubuntu1.3
-- Database server: mariadb-server-10.1  1:10.1.40-0ubuntu0.18.04.1

In my opinion the css class for the import button, right of the "Create" button  on the pasowrds page, should be fa-download not fa-upload, as importing is more like downloading.. :-)
Just a little thing but I personally discovered the import feature by accident, thinking it was an export feature.

The code is here

```html
<button id="js_wsp_pwd_import_button" class="mad.component.Button mad.View button ready"><i class="fa fa-fw fa-upload"></i>
<span class="visuallyhidden">upload</span></button>
```

**Comment by stripthis** [comment]
Thanks for the feedback, we have had mixed results on the meaning of these icons. From our user tests, it's split some people understand the meaning from the user perspective, and some like you other way around (from the server perspective). We should probably aim at a new set of icon that works for everyone.

**Comment by jsm222** [comment]
Perhaps an arrow downwards pointing to the graphical part of the passbolt logo. Just a thought.

**Comment by stripthis** [comment]
Closing as stall. Feel free to open an feature request on the community forum. We'll revise the icon set in 2021.
