### ISSUE TITLE
"Groups" is a reserved word in MySQL 8.0.2+

### ISSUE THREAD

**Issue by garrettboone** [passbolt/passbolt_api#325]
## "Groups" is a reserved word in MySQL 8.0.2+
* Passbolt Version: 2.10
* Platform and Target:
-- Database server: MySQL 8.0.2+

### What you did
`su -s /bin/bash -c "./bin/cake passbolt cleanup" www-data`

### What happened
`Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups Groups ON Groups.id = (GroupsUsers.group_id) WHERE Groups.deleted = 1' at line 1 in [/var/www/passbolt/vendor/cakephp/cakephp/src/Database/Statement/MysqlStatement.php, line 39]
`

### What you expected to happen
No problem with table names.

Suggestion: if passbolt is for teams, what a great opportunity to use the word "teams"!

I'd be willing to tackle this one if it's a change desired.

**Comment by cedricalfonsi** [comment]
Hello @garrettboone,
Thank you for you report.

https://dev.mysql.com/doc/refman/8.0/en/keywords.html

**Comment by vhf** [comment]
Had the exact same issue, solved it by putting this to true in our config file mysql connection section:
https://github.com/passbolt/passbolt_api/blob/81c3747d56c6d9a300c85a14debea08b30615569/config/app.default.php#L257

**Comment by garrettboone** [comment]
> 
> 
> Had the exact same issue, solved it by putting this to true in our config file mysql connection section:
> 
> https://github.com/passbolt/passbolt_api/blob/81c3747d56c6d9a300c85a14debea08b30615569/config/app.default.php#L257

I had not considered that, thank you for pointing it out. I moved to MariaDB in the meantime.

**Comment by garrettboone** [comment]
@cedricalfonsi If you decide to make the quoteIdentifiers solution the official chosen approach for now, feel free to consider closing this. I was unaware of this option.

**Comment by JamesCullum** [comment]
I am encountering the same issue with the docker version, where I don't believe I can easily modify this. It should be enabled by default.
