### ISSUE TITLE
Annoying session timeouts

### ISSUE THREAD

**Issue by imrejonk** [passbolt/passbolt_api#327]
## Annoying session timeouts
* Passbolt Version: v2.11.0
* Platform and Target:
-- Operating system: Debian 10
-- PHP: 7.3
-- Web server: NGINX 1.14
-- Database server: MariaDB 10.3
-- etc.: Using various Firefox versions

### What you did
I'm not sure if this is an API or browser plugin bug, feel free to move this issue if it's filed in the wrong repository.

We have a self-hosted Passbolt server that's currently used by myself and a few of my colleagues. We're testing things out before we switch over the whole organisation to use Passbolt. We currently experience a blocking issue, namely a strange case of unintended session timeouts. We're using various versions of Firefox (some with extensions, some without). During login we tick 'Remember passphrase until I log out'. We're logged in successfully and proceed to work on something else.

### What happened
After some time (around 20-30 minutes, we don't have an exact number), when we return to Passbolt which is still in an open Firefox window, we notice that we've been logged out.

### What you expected to happen
We should not get logged out at all unless we either close Firefox or click the 'logout' button.

**Comment by imrejonk** [comment]
Some additional information: we're on v2.11.0 right now, but I only personally only confirmed this issue on v2.10.0. I see that there is a new session check endpoint in v2.11.0, maybe that will solve our issue.

**Comment by Mainbird** [comment]
We are on v2.11.0 and we have noticed the same issue like you @imrejonk. Passbolt it's also self hosted in our case, but we are using Chrome.

**Comment by stripthis** [comment]
Hello @Mainbird @imrejonk prior to v2.11 the session check was extending the session timeout, e.g. the plugin was checking every 5 minutes, then 10, then 20, and therefore extending the session for more than the regular duration. Now the check is performed only at the end of the session timeout period defined in the php settings, which we believe is a more accurate and secure behavior.

If the default session timeout is too short for you and your user you can extend it in the PHP configuration. See the directive session.gc-maxlifetime https://www.php.net/manual/en/session.configuration.php#ini.session.gc-maxlifetime

**Comment by imrejonk** [comment]
@stripthis thanks, increasing `session.gc-maxlifetime` seems to work for us! Maybe it can be added to the [installation guide](https://help.passbolt.com/hosting/install/ce/from-source.html), as the PHP default is too short to be practical?

**Comment by stripthis** [comment]
@imrejonk that's an option, but somehow i'm afraid if we encourage to increase this by default another part of our audience will complain that we encourage "unsecure defaults". It's always tricky to strike a balance.

**Comment by stripthis** [comment]
@imrejonk I ended up adding a link to another documentation page at the end of the installation pages, with other frequently asked questions. Thanks for the feedback.

**Comment by imrejonk** [comment]
@stripthis I feel your pain... Maybe give them some of these cables for layer 1 firewalling. That should shut them up :wink:
Thanks for adding it to the documentation!

![Ethernet cable with print "Cable made for OHM2013 sponsored by BIT - www.bit.nl - Cut here to activate firewall"](https://www.bit.nl/uploads/images/Fotos/OHM2013-9.png)

**Comment by burasuk** [comment]
For me, increasing session.gc-maxlifetime doesnt help at all.
Randomly i've been logged out. Sometimes after 30 min, sometimes after 20 seconds.
