### ISSUE TITLE
env key_length and subkey_length can be more that 2048?

### ISSUE THREAD

**Issue by John3** [passbolt/passbolt_api#329]
I'm using oficial Passbolt Docker 2.11.0 with docker-compose

I add the key length in my config file env/passbolt.env before run the first time

PASSBOLT_KEY_LENGTH=4096
PASSBOLT_SUBKEY_LENGTH=4096

### What happened
Use the 2048

### What you expected to happen
Use the value 4096 from env/passbolt.env

**Comment by dlen** [comment]
Hi @John3, 

Thanks for your report. I'm not able to reproduce what you describe:

My passbolt.env looks like this:

```# URL
APP_FULL_BASE_URL=http://passbolt.local

# Database settings
DATASOURCES_DEFAULT_HOST=db
DATASOURCES_DEFAULT_USERNAME=passbolt
DATASOURCES_DEFAULT_PASSWORD=P4ssb0lt
DATASOURCES_DEFAULT_DATABASE=passbolt
DATASOURCES_DEFAULT_PORT=3306

# Registration
PASSBOLT_REGISTRATION_PUBLIC=true

PASSBOLT_KEY_LENGTH=4096
PASSBOLT_SUBKEY_LENGTH=4096
```

After docker-compose up (clean volumes of course):

```
$ docker-compose exec passbolt bash                                                                                               
root@ec5f7f531d4d:/var/www/passbolt# su -c "gpg --list-keys" -s /bin/bash www-data
/home/www-data/.gnupg/pubring.kbx
---------------------------------
pub   rsa4096 2019-11-27 [SC]
      E556A084555EDF4A6B19061634A8D6473F0B3504
uid           [ultimate] Passbolt default user <passbolt@yourdomain.com>
sub   rsa4096 2019-11-27 [E]
```
Just heads up: the env variables you refer to are to change the size of the serverkeys  of the API not the user generated keys on your setup.

**Comment by John3** [comment]
> Thanks for your report. I'm not able to reproduce what you describe:

Hey hi... thank for you answer, but right now I'm not using passbolt to give a proper reply. Feel free to close the issue.

I was using the CE, and yes I just add the value in the env file for docker, I don't remember anything else :/
