### ISSUE TITLE
Impossible to recover a user deleted and recreated

### ISSUE THREAD

**Issue by bestlibre** [passbolt/passbolt_api#33]
I have deleted a user and then created a new user with the same email. When I try to recover the user (from chrome) I have an error message : 

> This user has been deleted. Please contact your administrator.

**Comment by kevinmuller** [comment]
Hi,

Indeed it seems that it's a bug. I could reproduce it. 
I've created a ticket in our JIRA (bug ref: PASSBOLT-1835). We'll fix it soon.
Thanks for reporting!

Kevin

**Comment by o-be-one** [comment]
+1 i've this bug even on the latest version. Thanks for report and fix :) !

For information, this user had some shared passwords. When removed him these share and passwords owned by him are not available for delete or share delete ... So i've some old password that i can't drop too ; and maybe we cant create the same user again (well, we can, but he cant "recover") cause of these previous passwords ?

Anyway, thanks for JIRA.

**Comment by stripthis** [comment]
Fixed with v1.4.0
