### ISSUE TITLE
[Cloud] New user does not receive registration mail

### ISSUE THREAD

**Issue by gmichard** [passbolt/passbolt_api#331]
## [Cloud] New user does not receive registration mail

* Passbolt Version: Cloud (2019-09-09 14:30)

### What you did

As administrator, I add a new user.

### What happened

No email is sent to the user address.  
The user can't finalize his registration.

### What you expected to happen

The user should be notify by a mail to finalize his registration.  

---

## Feature?

- Can I try to send the expected notification again?

**Comment by dlen** [comment]
Hi @gmichard,

Could you contact us through support@passbolt.com to continue helping you with your issue?
