### ISSUE TITLE
Repeated passphrase check is needed

### ISSUE THREAD

**Issue by k3a** [passbolt/passbolt_api#333]
## ISSUE NAME
* Passbolt Version: demo

### What you did
Attempted to test out the demo. Entered a passphrase but due to enormous requirements for character set, I appended a few characters which I forgot couple of seconds after the generation of the key.

### What happened
It created a key I could not delete or re-create, preventing me to even try the first demo login. Deleting and reinstalling the extension just offered to recover the key, asking for the private key.

### What you expected to happen
See a second field asking to repeat the passphrase or more easier way to start from scratch with a new key and account.

I know it's a stupid case and I know there was a text asking me to remember the passphrase and backup the key. But I find this user-unfriendly.

**Comment by Melkor333** [comment]
I second this, I also think it's weird that you only have to enter the passphrase once!

**Comment by stripthis** [comment]
Closing, as it won't be implemented. 
However now it is possible to view the passphrase when entering it in v3.
