### ISSUE TITLE
Can't use passbolt after deleting a secret

### ISSUE THREAD

**Issue by damien-list** [passbolt/passbolt_api#334]
## ISSUE NAME
* Passbolt Version: 60ad4780555dd891183147f599e1476d4114395f
* Platform and Target:
-- Operating system: Ubuntu 16.04
-- PHP: 7.3
-- Web server: Apache 2.4
-- Database server: MySQL 5.7

### What you did
A user delete a secrect since then he can't use passbolt, the loading red bar is stucked at 3/4.

### What you expected to happen
That the user can still use Passbolt :)

**Comment by stripthis** [comment]
Hello @damien-list,

Can you check if there are any errors in the browser console?
Please also checks for information in the error log file on the server (in your passbolt directory on the server in `/logs/errors.log` ). Feel free to send us this additional information at support@passbolt.com if you are not comfortable posting it here.

**Comment by damien-list** [comment]
Hi @stripthis and thanks for your quick answer,

There is no error in console log in the chrome dev toolbar and no error shown in logs/errors.log.

**Comment by stripthis** [comment]
Can you check in the browser extension console also, under chrome://extensions/ click on inspect view for the passbolt plugin for index.html. It will open a separate console.

Can you also try running on the server `./bin/cake passbolt cleanup --dry-run`, to check for any data integrity issues.

**Comment by damien-list** [comment]
Here a screen for the chrome://extensions inspection :

![image (2)](https://user-images.githubusercontent.com/1785580/69232534-8c465280-0b8b-11ea-879b-453bd3a7f555.png)

`su -s /bin/bash -c "./bin/cake passbolt cleanup --dry-run" www-data

     ____                  __          ____
    / __ \____  _____ ____/ /_  ____  / / /_
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /
 /_/    \__,_/____/____/_.___/\____/_/\__/

 Open source password manager for teams
---------------------------------------------------------------
 Cleanup shell (dry-run)
---------------------------------------------------------------
No issue found, data looks squeaky clean!`

**Comment by stripthis** [comment]
From what I can see it looks like the user is not authenticated. Can you tell the user to go to your domain.com/logout, clear the console and go the url of login again. Show us any error if any from the console.

**Comment by damien-list** [comment]
The user have uninstalled the plugin extension and reinstalled it and it works again.

Thank you for your help
