### ISSUE TITLE
Can't edit Group

### ISSUE THREAD

**Issue by hudus** [passbolt/passbolt_api#335]
## Can't edit Group
* Passbolt Version: 2.11.0
* Platform and Target:
-- Operating system: Ubuntu 16.04.6 LTS
-- PHP: v7.0.33
-- Web server: nginx/1.10.3
-- Database server: MariaDB 10.0.38

### What you did
- As an Admin i want to edit group (add new users to it)

### What happened
- The modal opens, but the Group name is empty and searching for people does not work
- There are no errors in browser console
- In `/var/www/passbolt/logs/error.log` there is an error: `Error: [Error] Call to undefined method App\Model\Entity\Group::getVisible()
Request URL: /groups/5aa4facc-6010-4d8d-b867-1341ac211d18.json?api-version=v1`

![image](https://user-images.githubusercontent.com/31574632/69727002-f2018400-1121-11ea-9252-03dc78a5aad5.png)

- Running `./bin/cake passbolt cleanup --dry-run` solves nothing: `No issue found, data looks squeaky clean!`

### What you expected to happen
I expect to be able to add another user as was able to do before.

I don't recall exact time, when it stopped working. I doubt it is related to updating to latest version, as it happened a long time ago and I think we would have stumbled on this problem sooner. But cannot rule it out for sure.

**Comment by stripthis** [comment]
Hi @hudus, 

Do you have this issue with all groups or only one group specifically?

**Comment by hudus** [comment]
Hi @stripthis. All the groups.

**Comment by stripthis** [comment]
@hudus can you get in touch with us at support@passbolt.com, most likely we're going to need an obfuscated copy of the db to get to the bottom of this.

**Comment by cedricalfonsi** [comment]
Hello @hudus,

Another user had the same problem as you on the [community forum](https://community.passbolt.com/t/group-handling-in-2-11-0-ce-does-not-work/2244/2?u=cedric).

Cleaning the CakePHP cache solved the issue, you can execute the following command from the pasbolt folder:
`./bin/cake cache clear_all`

Let us know how it goes.

**Comment by hudus** [comment]
@cedricalfonsi Hi. That unfortunately did not help.

But then I tried to reinstall the app and it's now working. I just used your [update guide](https://help.passbolt.com/hosting/update) (for minor update) and it's now working. Not sure which command fixed it. Composer updated bunch of dependencies as well. I am still on the same version as before FYI.

Anyway everything seems to be working for me again. Thank you

**Comment by hudus** [comment]
This is output from the composer install, in case it can help you:

```
$ composer install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
  - Updating cakephp/plugin-installer (1.1.0 => 1.1.1)
    Checking out af9711ee5dfbe62a76e8aa86cb348895fab23b50

  - Updating symfony/polyfill-ctype (v1.11.0 => v1.12.0)
    Checking out 550ebaac289296ce228a706d0867afc34687e3f4

  - Updating symfony/yaml (v3.4.27 => v3.4.30)
    Checking out 051d045c684148060ebfc9affb7e3f5e0899d40b

  - Updating symfony/polyfill-mbstring (v1.11.0 => v1.12.0)
    Checking out b42a2f66e8f1b15ccf25652c3424265923eb4f17

  - Updating symfony/debug (v3.4.27 => v3.4.30)
    Checking out bc977cb2681d75988ab2d53d14c4245c6c04f82f

  - Updating symfony/console (v3.4.27 => v3.4.30)
    Checking out 12940f20a816c978860fa4925b3f1bbb27e9ac46

  - Updating symfony/filesystem (v3.4.27 => v3.4.30)
    Checking out 70adda061ef83bb7def63a17953dc41f203308a7

  - Updating symfony/config (v3.4.27 => v3.4.30)
    Checking out 623fd6be3e5d4112d667003488c8c3ec12b66f62

  - Updating cakephp/chronos (1.2.5 => 1.2.8)
    Checking out 0292f06e8cc23fc82f0574889da2d8bf27b613c1

  - Updating cakephp/cakephp (3.7.7 => 3.8.1)
    Checking out faefcba4cb332d6abfe3f2693346e805ef6e3857

  - Updating robmorgan/phinx (0.10.7 => 0.10.8)
    Checking out 1960e93169707096fdfde04904a204970077f4be

  - Updating cakephp/migrations (2.1.1 => 2.2.0)
    Checking out 38fbee62e7f387dbe0dc7ef492aa7dddb8e304fc

  - Updating burzum/cakephp-file-storage (2.0.x-dev c0b3eef => 2.1)
    Checking out e0cc17e262ad314a904cf57069f619b9561b48e9

  - Updating ralouphie/getallheaders (2.0.5 => 3.0.3)
    Checking out 120b605dfeb996808c31b6477290a714d356e822

  - Updating guzzlehttp/psr7 (1.5.2 => 1.6.1)
    Checking out 239400de7a173fe9901b9ac7c06497751f00727a

  - Updating lorenzo/cakephp-email-queue (3.2.0 => 3.3.0)
    Checking out 5226745930cced1bffd9e6f09146513bd4d8b32a
```

The DB migration (as part of the update process) took only `0.0981s`, so there was probably not much happening there...
