### ISSUE TITLE
/var/www/html/YouPHPTube/objects/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer not writable

### ISSUE THREAD

**Issue by risleem** [passbolt/passbolt_api#336]
I am getting an error when uploading a video on my streamer and encoder server. This is the error I am getting.
/var/www/html/YouPHPTube/objects/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer not writable please chmod to 777. Any help would be appreciate. Thanks

**Comment by risleem** [comment]
![error](https://user-images.githubusercontent.com/52410929/71609720-cd515f80-2b58-11ea-97eb-96d2422b1585.PNG)

**Comment by kevinmuller** [comment]
Hi @risleem ,
It seems that you posted your issue on the wrong project. We are the folks at Passbolt here, the password manager. 
You might get support from YouPHPTube on their github repo: https://github.com/YouPHPTube
Best of luck.
