### ISSUE TITLE
Error uploading videos to stream server

### ISSUE THREAD

**Issue by risleem** [passbolt/passbolt_api#337]
I am getting an error when uploading a video on my streamer and encoder server. This is the error I am getting.
/var/www/html/YouPHPTube/objects/htmlpurifier/HTMLPurifier/DefinitionCache/Serializer not writable please chmod to 777. Any help would be appreciate. Thanks

**Comment by risleem** [comment]
![image](https://user-images.githubusercontent.com/52410929/71823014-51797a80-3064-11ea-8735-fb060387ad58.png)

Here is the error I am receiving.

**Comment by stripthis** [comment]
This is the not the right project repository.  You might get support from YouPHPTube on their github repo: https://github.com/YouPHPTube
Best of luck.
