### ISSUE TITLE
Why do you don't use Secure Flag and HttpOnly Flag headers for Cookies ?

### ISSUE THREAD

**Issue by NRGLine4Sec** [passbolt/passbolt_api#338]

**Comment by stripthis** [comment]
Can you be more specific as of which cookie you are seeing without these flags and where?

The value of the these flags depend on the cookies (for example the csrfToken cookie is intentionally readable over http), as well as your configuration.

Mfa and Session cookie should use Secure Flag and HttpOnly Flag by default.

**Comment by NRGLine4Sec** [comment]
I have run test with ZAProxy and I check with chrome developer tools too.
For exemple there are no Secure Flag and HttpOnly Flag headers for Cookies with with these path :
```
https://passbolt.test/roles.json?api-version=v2
https://passbolt.test/auth/login
https://passbolt.test/js/app/bundles/passbolt-appjs/passbolt.js?version=2.12.0
```
And also, why do you don't use `preload` directive in HSTS ?
