### ISSUE TITLE
Issues with installation wizard links when installing passbolt with a 'base' / in a directory

### ISSUE THREAD

**Issue by runderwo** [passbolt/passbolt_api#339]
## Impossible to complete setup without manual hacking when fullBaseUrl/base set
* Passbolt Version: commit 3eaf5fcf6457b477cd5371b33f8f1a80e53e9273 (HEAD -> master, tag: v2.12.0, origin/master, origin/HEAD)
* Platform and Target:
-- Operating system: Debian Stretch
-- PHP: 7.0.22
-- Web server: Apache 2.4.41
-- Database server: 8.0.18

### What you did
Cloned Passbolt and attempted to begin setup wizard.  Passbolt is installed in an aliased subdirectory that is reachable at https://www.myserver.net/passbolt.  I copied the default config and applied only the following options:
```
    'App' => [
        'fullBaseUrl' => 'https://www.myserver.net',
        'base' => '/passbolt'
    ],
```
### What happened
Every stepInfo['next'] link generated does not include trailing slash after 'base' component, so the URLs are invalid.  Example:
https://www.myserver.net/passboltinstall/options

This can be worked around manually, but then the final step:
https://www.myserver.net/passbolt/install/installation/do_install.json
throws a 500 error with nothing logged.  "An Internal Error Has Occurred" is in the browser.  What's worse, it has overwritten my configuration above with only:
```
    'App' => [
        'fullBaseUrl' => 'https://www.myserver.net/passbolt'
    ],
```
and as such, the config has to be manually hacked again to proceed, but I'm unable to get this step to complete.

### What you expected to happen
URLs generated by setup wizard routes should be valid, e.g.:
https://www.myserver.net/passbolt/install/options

**Comment by stripthis** [comment]
Fixed with v3.0.0.
