### ISSUE TITLE
Config/email.php should not be tracked on Git

### ISSUE THREAD

**Issue by BaumannMisys** [passbolt/passbolt_api#34]
Hello

It's possible to rename the file /app/Config/email.php to email.php.default.
The last pull overwrites our email setting the renaming could prevent this in the future.

Best regards
Daniel

**Comment by stripthis** [comment]
Yes @BaumannMisys, we completely agree. We have bug filled on our end for this issue already as it was reported by another user. ref. PASSBOLT-1511. We will do that as part of the next release.

**Comment by stripthis** [comment]
Fixed with v1.4.0
