### ISSUE TITLE
Can't log in after renewing the server's key

### ISSUE THREAD

**Issue by ialbors** [passbolt/passbolt_api#340]
## Problems with renew key
* Passbolt Version: 2.12.0
* Platform and Target:
-- Operating system: Linux
-- PHP: 7.0
-- Web server: nginx
-- Database server: mysql

### What you did
Not sure if this is the right place or maybe on the extension repo.

I had the server's gpg key expired so I couldn't log in with this error messages:

* Could not verify server key. Unable to encrypt the verify token. Error encrypting message: Could not find valid key packet for encryption in key 9bb42ffb20cde310

* Oops, something went wrong

So I changed the expiration date for the key and subkey.

After that, the healtcheck was ok. But I couldn't log in either.

I read it could be because I had to recover my account. But when I try to follow the recovery process and set my private key there's an error saying that account doesn't exist (¿¿??).

BUT... I can log in without recovery using the "quick access" browser icon. 

### What happened

See above.

### What you expected to happen

To be able to log in from the web page the same as I do it with the "quick access" without having to recover my account.

Also it would be cool to know why I cannot recover my account.

I'm sorry if this is not clear enough. Please let me know if you have any question or I can make it clearer.

Thanks!

**Comment by stripthis** [comment]
Hello,

Please open an issue on the community forum, this space is used only for bugs not for installation/configuration issues. There might already be some topics on the forum that can give you some hints:
https://community.passbolt.com/search?q=expired

**Comment by ialbors** [comment]
Ok, thanks for the advice!
