### ISSUE TITLE
 In ReverseProxy + subdirectory setup: users/recover "start recover" button wrong URL

### ISSUE THREAD

**Issue by norbertmm** [passbolt/passbolt_api#343]
## In ReverseProxy + subdirectory setup: users/recover "start recover" button wrong URL
* Passbolt Version: 2.12.0
* Platform and Target:
-- Operating system: Debian 10
-- PHP: 7.3.11-1~deb10u1
-- Web server: nginx 1.14.2-2+deb10u1
-- Database server: mariadb  Ver 15.1 Distrib 10.3.18-MariaDB
-- etc.: Passbolt is behind an Apache/2.4.6 (CentOS) as ReverseProxy

My new Passbolt installation should work behind some ReverseProxy. It should proxy from `https://my.public-domain.de/my-passbolt` to the passbolt server within private network, address space `http://some.internal.addr`.

Apache virtual host config is like this:
```apache
<VirtualHost 123.4.5.67:443>
    ServerName my.public-domain.de
    ...
    <Location /my-passbolt>
        ProxyPreserveHost On
        RequestHeader set X-Forwarded-Proto "https"
        ProxyPass        http://some.internal.addr:80
        ProxyPassReverse http://some.internal.addr:80
    </Location>
</VirtualHost>
```
My `conf/passbolt.php` has this:
```php
'App' => [
    'fullBaseUrl' => 'https://my.public-domain.de/my-passbolt',
],
```
Note that I do not use `'base' => '/my-passbolt'` as this breaks css, js, ... loading.
(BTW: I ran the install wizard from internal network with URL `http://some.internal.addr`)

### Everything works nice -- except for the user recover and registration pages:
`https://my.public-domain.de/my-passbolt/users/recover` and 
`https://my.public-domain.de/my-passbolt/users/register` have wrong Post Buttons in the HTML form. They post to `https://my.public-domain.de/users/recover`. Missing `my-passbolt` within the URL.

### This is my quick-and-dirty fix for the issue:
```diff
--- passbolt/src/Template/Users/recover.ctp     2020-01-31 01:59:44.963954282 +0100
+++ passbolt/src/Template/Users/recover.ctp.orig        2020-01-31 02:11:13.140975272 +0100
@@ -20,12 +20,11 @@
 $formContext = [
     'context' => [
         'validator' => [
             'Users' => 'recover',
         ]
-    ],
-    'url' => false
+    ]
 ];
 ?>
 <div class="grid">
     <div class="row">
         <div class="col6 push1 information">
```
```diff
--- passbolt/src/Template/Users/register.ctp    2020-01-31 02:07:55.625239311 +0100
+++ passbolt/src/Template/Users/register.ctp.orig       2020-01-31 02:07:02.284230252 +0100
@@ -22,12 +22,11 @@
     'context' => [
         'validator' => [
             'Users' => 'register',
             'Profiles' => 'register'
         ]
-    ],
-    'url' => false
+    ]
 ];
 ?>
 <div class="grid">
     <div class="row">
         <div class="col6 push1 information">
```
I have nearly no idea about Apache, NGINX, PHP, CakePHP... But this small modification works for me.

**Comment by stripthis** [comment]
Fixed with v3.0.0.
