### ISSUE TITLE
Saving a tag without changes deletes it

### ISSUE THREAD

**Issue by samuel-apps** [passbolt/passbolt_api#345]
## Saving a tag without changes deletes it
* Passbolt Version: 2.12.0
* Platform and Target:
-- CentOS Linux release 8.1.1911 (Core)
-- NGINX 1.14.2
-- mysql  Ver 15.1 Distrib 10.3.17-MariaDB, for Linux (x86_64) using readline 5.1
-- PHP 7.2.11 (cli) (built: Oct  9 2018 15:09:36) ( NTS )

### What you did
I edit a tag, don't change anything, and press save

### What happened
The tag seems to have disappeared entirely and immediately. Inspecting any passwords which previously had the tag in question, shows that they no longer have the tag in question.

### What you expected to happen
I expected pretty much the same thing would happen as when i pressed cancel. From the end user's point of view anyway. But I _would_ argue that it's a flaw in the API that it blatantly deletes a tag when you make a PUT request with a specific payload.

**Comment by supergoudvis112** [comment]
Just came here to say, haha told you we shouldn't have switched ;-)

**Comment by samuel-apps** [comment]
It seems kind of like whenever a tag is edited, the API creates a new tag... I suppose it might be an issue if it immediately tried to create the same tag again?

**Comment by cedricalfonsi** [comment]
Sorry for the delay to answer.
It seems to have been fixed.
Feel free to reopen if the bug persists.
