### ISSUE TITLE
First letter of last name is converted to uppercase on save

### ISSUE THREAD

**Issue by rctgamer3** [passbolt/passbolt_api#346]
## First letter of last name is converted to uppercase on save
* Passbolt Version: v2.12.0
* Platform and Target:
-- Operating system: Debian 10
-- PHP: 7.4
-- Web server: Apache2 2.4.41
-- Database server: MariaDB 15.1

### What you did
I edited profile details of a user (example: first name `Foobar` last name `bar Foo`)

### What happened
After saving, the first letter of the last name was converted to uppercase (`Bar Foo`)

### What you expected to happen
Not convert it to uppercase and just leave it as-is (`bar Foo`) as different countries follow different name capitalisation standards.

**Comment by rctgamer3** [comment]
https://github.com/passbolt/passbolt_api/blob/7234d18dfb4a3c33c174bc4a8759e894d84ec6ef/src/Model/Table/ProfilesTable.php#L143

**Comment by ishanvyas22** [comment]
Hey @rctgamer3, this issue has been fixed and released with [v4.2.0](https://community.passbolt.com/t/new-release-v4-2-0/8336) ([see the full changelog](https://github.com/passbolt/passbolt_api/releases/tag/v4.2.0)).

Thanks for the report.
