### ISSUE TITLE
Newly created passwords are duplicated

### ISSUE THREAD

**Issue by kevingimbel** [passbolt/passbolt_api#349]
## Newly created passwords are duplicated (up to 3x)
* Passbolt Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target:
-- Operating system: `Ubuntu 18.04`
-- PHP: `7.2.24`
-- Web server: `nginx/1.14.0 (Ubuntu)`
-- Database server: `mariadb  Ver 15.1 Distrib 10.1.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`
-- Custom PHP settings:
--- `session.gc_maxlifetime = 86400`

### What you did
- Saved a new Password using the Web UI
- Shared the password with a Group

### What happened
After a reload the password is there 3 times. If I delete two, the third still exists so it is not the same object - it seems as if the password really is saved three times with the same name and values.

### What you expected to happen
I expect the password to be saved once and not three times.

---

If there is any more information I can provide please let me know.

**Comment by stripthis** [comment]
This can happen when several webextension workers are inserted on the page. While we are going to fix this with the next release, in the meantime, if you experience this, you will need to restart your browser so that the problem goes away.

**Comment by stripthis** [comment]
Should be fixed with v2.13. Feel free to reopen if you are still encountering the behavior.
