### ISSUE TITLE
PHP Gnupg library is not installed

### ISSUE THREAD

**Issue by abeumer** [passbolt/passbolt_api#35]
I wanted to try out Passbolt so I'm trying to install it locally on a testing machine but I keep running into:
PHP Gnupg library is not installed
Installation failed.

PHP Version 7.0.13
gnupg support	enabled
GPGme Version 	1.6.0
Extension Version 	1.4.0
 
Is PHP7 not supported?

**Comment by stripthis** [comment]
Hello,

It should work with PHP7 (we tested it on major distributions). Have you checked the troubleshooting section in the installation manual?
https://www.passbolt.com/help/tech/install#toc_troubleshoot 

If this doesn't help can you provide more information about your stack (linux distribution, nginx or apache, etc.) so that we can try to recreate the problem?

Thanks,

**Comment by abeumer** [comment]
The command "app/Console/cake install --no-admin" produces the error so I can't even open the healthcheck. (Error: An Internal Error Has Occurred.)
(I also tried: su -s /bin/bash -c "app/Console/cake install --no-admin" www-data)

Ubuntu 16.10
Linux machine.testing.local 4.8.0-32-generic #34-Ubuntu SMP Tue Dec 13 14:30:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Apache/2.4.18 (Ubuntu)
Virtualhost doc root: /var/www/passbolt/app/webroot
Internal address: https://passbolt
drwxrwxr-x 12 root www-data 4096 Jan 18 11:18 app/tmp/

root@machine:/var/www/passbolt# app/Console/cake install --no-admin
.....
 Open source password manager for teams
 (c) 2015-present passbolt.com
---------------------------------------------------------------
PHP Gnupg library is not installed
Installation failed.

**Comment by infectormp** [comment]
@abeumer did you have installed pecl-gnupg?

**Comment by abeumer** [comment]
root@machine:/var/www/passbolt/app# pecl install gnupg
pecl/gnupg is already installed and is the same as the released version 1.4.0

**Comment by stripthis** [comment]
Is gnupg showing in your phpinfo?
$ php --info | grep 'gnupg support'

Can you show what the permission is like for the gnupg keyring?

**Comment by abeumer** [comment]
php had gnupg enabled but php-cli did not. Now I run into th permission issue but now I can continue testing. I will update the ticket when the installation has completed with the result

**Comment by abeumer** [comment]
Passbolt installation success! Enjoy! ☮
