### ISSUE TITLE
New version reported without a new tag on repo or release notes

### ISSUE THREAD

**Issue by mwkcoding** [passbolt/passbolt_api#351]
## ISSUE NAME
* Passbolt Version: 1.12.0
* Platform and Target:
-- Operating system: CentOS Linux release 7.4.1708 (Core)
-- PHP: 7.1.15
-- Web server: Apache 2.4.6
-- Database server: MariaDB 10.3.31

### What you did
Loaded self-hosted Passbolt website and checked version in the bottom right corner

### What happened
Shows 1.13.0 version which does not show up anywhere else on Passbolt's website or repo.

### What you expected to happen
I expected to not see a version that presumably doesn't exist.

**Comment by stripthis** [comment]
Hi @mwkcoding ,

We are actually in the middle of the release process. Resources will be updated soon. Unfortunately we don't control the agenda here, as google can publish whenever they are done with their review of the extension.

Best,
