### ISSUE TITLE
Dokumentation for Update 

### ISSUE THREAD

**Issue by MdmrBerlin** [passbolt/passbolt_api#355]
composer installation with php runs permanently in timeout -> curl is the way to go 

 git pull origin master  -> wat is to pull from where to where ? Exist there an Update Repository?  Url /Path? Direct into the installation directory or did an script update the files in the installation directory ?

After all  ./bin/cake passbolt healthcheck ->  [FAIL] This installation is not up to date. Currently using 2.2.0 and it should be v2.13.0.

Exist there an running and usable update script?

**Comment by cedricalfonsi** [comment]
Hello @MdmrBerlin,

Would you mind providing us with additional information, it will help us to understand if there is a bug in the process or if it is something else.

Can you point us to the documentation you are following, and give us some details about the step and command that are failing, such as the output of the command?

Best regards.

**Comment by stripthis** [comment]
@MdmrBerlin for installation or update issues, please open a thread on the community forum with more information as indicated by @cedricalfonsi , if following the update procedure on the help site doesn't work for you: https://help.passbolt.com/hosting/update
As indicated in the project template issues this repository is reserved for bugs.
