### ISSUE TITLE
As a user I shouldn't be able to export folders if export plugin is disabled

### ISSUE THREAD

**Issue by mms-gianni** [passbolt/passbolt_api#356]
## ISSUE NAME
* Passbolt Version: 2.13.1 
* Platform and Target:
-- Operating system: Docker image passbolt:latest-pro

### What you did
Diabled Exports with ENV var PASSBOLT_PLUGINS_EXPORT_ENABLED=false

- Created a test folder.
- Created a password in this new folder
- Opened the context Menu (Hovering the folder, +sign on the right side)
- Select "Export"

### What happened
The export modal appears an it is possible to export all the passwords contained in this folder

### What you expected to happen
The Export option in the flyout should not appear. It should also not be possible to export passwords when this flag is set.

**Comment by stripthis** [comment]
Hi @mms-gianni, it's indeed a bug. We'll get it fixed in the next release.
Thanks for the report.

**Comment by stripthis** [comment]
Fix with webextension v3.
