### ISSUE TITLE
On-Premise

### ISSUE THREAD

**Issue by Senectus** [passbolt/passbolt_api#358]
Incorrect useage of word "on-premise" 

Your site is littered with the incorrect usage of the word "Premise" (ie on-premise, meaning located on my own site...)

Please note the dictionary meanings of the words "Premise" and "Premises" below, then I would suggest a site wide search and replace to the correct word :-)

Premise:

noun /ˈprɛmɪs/ LOGIC a previous statement or proposition from which another is inferred or follows as a conclusion. "if the premise is true, then the conclusion must be true" 
verb /prɪˈmʌɪz/ base an argument, theory, or undertaking on. "the reforms were premised on our findings"

Premises:

noun a house or building, together with its land and outbuildings, occupied by a business or considered in an official context. "the company has moved to new premises"

**Comment by stripthis** [comment]
Reviewed the website and product, it fixed, let me know if I forgot one.
