### ISSUE TITLE
The GPG Server key defined in the config is not found in the gpg keyring

### ISSUE THREAD

**Issue by abeumer** [passbolt/passbolt_api#36]
**The GPG Server key defined in the config is not found in the gpg keyring**

**Error:** An Internal Error Has Occurred.
**Stack Trace**

    APP/Controller/Component/Auth/GpgAuthenticate.php line 49 → GpgAuthenticate->_initKeyring()
    CORE/Cake/Controller/Component/AuthComponent.php line 770 → GpgAuthenticate->authenticate(CakeRequest, CakeResponse)
    CORE/Cake/Controller/Component/AuthComponent.php line 611 → AuthComponent->identify(CakeRequest, CakeResponse)
    APP/Controller/AuthController.php line 35 → AuthComponent->login()
    [internal function] → AuthController->login()
    CORE/Cake/Controller/Controller.php line 491 → ReflectionMethod->invokeArgs(AuthController, array)
    CORE/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
    CORE/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(AuthController, CakeRequest)
    APP/webroot/index.php line 110 → Dispatcher->dispatch(CakeRequest, CakeResponse)

gpg --homedir /home/www-data/.gnupg --gen-key
gpg --homedir /home/www-data/.gnupg --armor --export-secret-keys user@testing.local > /var/www/passbolt/app/Config/gpg/serverkey.private.asc
gpg --homedir /home/www-data/.gnupg --armor --export user@testing.local > /var/www/passbolt/app/Config/gpg/serverkey.asc

/var/www/passbolt/app/Config/app.php
```
$config = [
  // GPG Configuration
  'GPG' => [
	// Tell GPG where to find the keyring
	// Needs to be available by the user the webserver is running as
	'env' => [
	  // you can set this to false if you want to use *nix $GNUPGHOME environment variable
	  'setenv' => true,
	  // otherwise you can set the location here
	  // typically on Centos it would be in '/usr/share/httpd/.gnupg'
	  'home' => '/home/www-data/.gnupg',
	],
	// Main server key
	'serverKey' => [
	  // Server private key location and fingerprint
	  'fingerprint' => '683BDFDC69BDC5A4B0AAC64EEBA1095058A19',
	  'public' => APP . 'Config' . DS . 'gpg' . DS . 'serverkey.asc',
	  'private' => APP . 'Config' . DS . 'gpg' . DS . 'serverkey.private.asc',

	  // PHP Gnupg module currently does not support passphrase, please leave blank
	  'passphrase' => ''
	]
  ]
];
```

**Comment by cedricalfonsi** [comment]
Hello @abeumer,

It's maybe related to the permission on /home/www-data/.gnupg.
Which user did you use to generate the gpg key ? Does www-data is allowed to access /home/www-data/.gnupg ?

Thanks,

**Comment by abeumer** [comment]
root@machine:/home/www-data# 
drwxr-xr-x  4 www-data employees 4096 Jan 18 15:25 .gnupg/

**Comment by cedricalfonsi** [comment]
Can you list the keys in your keyring and check that the fingerprint you add in you app.php config is there ?
Once logged as www-data : `gpg --list-keys`

**Comment by abeumer** [comment]
www-data has no login.

I created /home/www-data/.gnupg manually.
But as I understand it: all I need to do is specify a homedir in which the keyring should be created and make it accessible to www-data and specify the dir in the config and it should work?

**Comment by johnny5th** [comment]
I also have a similar setup and am having the same problem

**Comment by johnny5th** [comment]
I just ran `setsebool -P httpd_read_user_content 1` and apache is now able to read my keyring.

**Comment by johnny5th** [comment]
Dang, randomly stopped working again. Sorry for the spam.

**Comment by johnny5th** [comment]
One last thing. I got it working with `sudo chcon -R -t httpd_sys_rw_content_t /usr/share/httpd/.gnupg/`

**Comment by stripthis** [comment]
@johnny5th which OS are you using? Centos, RHEL? (so that I can add it to the troubleshooting guides on the website)

**Comment by abeumer** [comment]
For me that just results in this:
```
root@machine:~# chcon -R -t httpd_sys_rw_content_t /home/www-data/.gnupg
chcon: can't apply partial context to unlabeled file '1F723DDD66BC3ACE78F3C1CC96CF17DC970992AF.key'
chcon: can't apply partial context to unlabeled file 'B7DD0D99514FADBE604384B118F4F7D3EC4C3D84.key'
chcon: can't apply partial context to unlabeled file 'private-keys-v1.d'
chcon: can't apply partial context to unlabeled file 'trustdb.gpg'
chcon: can't apply partial context to unlabeled file 'pubring.kbx'
chcon: can't apply partial context to unlabeled file 'pubring.kbx~'
chcon: can't apply partial context to unlabeled file '6DC5A4B0A69BD83BDFC0C8AC64EE95058BA10A19.rev'
chcon: can't apply partial context to unlabeled file 'openpgp-revocs.d'
chcon: can't apply partial context to unlabeled file '/home/www-data/.gnupg'
```

**Comment by johnny5th** [comment]
@stripthis CentOS 7. If SELinux is enabled, you have to let it know that HTTPD can read/write the files.

@abeumer check your message log and see if SELinux is complaining about the keyring access in the first place.

**Comment by stripthis** [comment]
@abeumer any update on this? should we close the ticket?
