### ISSUE TITLE
app_groups_index_error error in login

### ISSUE THREAD

**Issue by YehudaEi** [passbolt/passbolt_api#360]
## Error in loading home page
* Passbolt Version: 53491ac0b9081e41a03ed6770bd6443264270ddd (latest)
* Platform and Target:
-- Operating system: Ubuntu 20.04 LTS
-- PHP: 7.4
-- Web server: Apache 2
-- Database server: MySql 8.0.20

### What you did
I have installed the site now.

### What happened
and as soon as I enter the main page I get the error "An Internal Error Has Occurred.".

When I looked in the developer window I saw the following error:
![image](https://user-images.githubusercontent.com/32451776/87968816-ac873200-cac9-11ea-8eb7-276299965a50.png)

### What you expected to happen
That everything will work properly?

**Comment by stripthis** [comment]
Hello,

For mysql8 you need to enable quoteIdentifier. This is not the default as we recommend using mariadb.

If you are using docker you need to set the environment variables `DATASOURCES_QUOTE_IDENTIFIER` to true. 
If you are using the installation scripts, you need to add in the `datasource` section, under default, in config/passbolt.php:
```
 'quoteIdentifiers' => true,  
```
For example
```
    'Datasources' => [
        'default' => [
            'host' => 'localhost',
            'port' => '3306',
            'username' => 'passbolt',
            'password' => 'password',
            'database' => 'passbolt',
            'quoteIdentifiers' => true
        ],
    ],
```

**Comment by YehudaEi** [comment]
Thank you!
It works for me now.

Plus, I'd love it if you could explain a little more about the problem in terms of code. (Only if you have time)

And again thank you very much!

**Comment by stripthis** [comment]
The issues lies in the fact that since mysql8 "groups" is a reserved keyword. QuoteIdentifier basically wrap the keywords in quotes, which impact performance (that's also why it's not the default :).

**Comment by YehudaEi** [comment]
Ok, I learned something new.
Thank you!
