### ISSUE TITLE
List in Chrome doesn't show passwords

### ISSUE THREAD

**Issue by tdeuling** [passbolt/passbolt_api#361]
## List in Chrome doesn't show passwords

* Passbolt Version: 2.13.5
* Platform and Target:
-- Operating system: Debian 4.19.67-2+deb10u2
-- PHP: 7.3.14-1~deb10u1
-- Web server: Apache/2.4.38 (Debian)
-- Database server: 10.3.22-MariaDB-0+deb10u1 Debian 10
-- Browser: Version 84.0.4147.105 (Official Build) (64-bit)
-- OS: Linux Mint 20 Cinnamon (version: 4.6.6, Kernel: 5.4.0-42-generic)

### What you did
Updated my self hosted instance to 2.13.5

### What happened
After update the password list doesn't show passwords anymore in Chrome (version above). Firefox works well.
There are some JavaScript issues in developer console and the progress bar stops in the middle of the screen:
![Selection_485](https://user-images.githubusercontent.com/1298841/89100868-145b4800-d3fb-11ea-9065-cdc540bf5c34.png)

While trying to search something by using the filter it apears an additional JavaScript error
![Selection_486](https://user-images.githubusercontent.com/1298841/89100891-4371b980-d3fb-11ea-8394-f13f7d78c06e.png)

### What you expected to happen
Display passwords in list, like other browsers does.

**Comment by stripthis** [comment]
@tdeuling i'm not able to reproduce the issue. Can you check if you get the same issue in the cloud version? Just signup for a free trial so that we can check it's not this particular OS + Chrome version the issue.

Can you try to check for orphans as well in the DB:
```
sudo su -s /bin/bash -c "./bin/cake passbolt cleanup --dry-run" www-data
```

Finally can you try deleting the extension and reinstalling it, do a recover and see if the problem is still present?

**Comment by tdeuling** [comment]
Hi, thanks for your reply. Yesterday I'd cleaned up all browser cache, cookies and more, and it doesn't work. Today after restarting my System and Chrome browser it seems to work. :/
Maybe this was a strange caching behaviour of chrome!? Sorry for wasting your time.

**Comment by stripthis** [comment]
@tdeuling you're not wasting our time at all. Thanks for flagging the issue to us. Let us know if you encounter it again. Cheers,
