### ISSUE TITLE
Folderstructure gone when closing a second webbrowser window

### ISSUE THREAD

**Issue by davoezzz** [passbolt/passbolt_api#364]
##IMPORTANT: **THIS ISSUE IS ALREADY REPORTED AND KNOWN BY PASSBOLT. THEY ARE WORKING ON A FIX.**

Only use github issues for bugs.

We will be more than happy to help you on the community forum for:
- feature requests: https://community.passbolt.com/c/backlog
- issues related to installations: https://community.passbolt.com/c/installation-issues
- general questions: https://community.passbolt.com/c/uncategorized

This is only a issue tracker for bugs related to the Passbolt API.
For passbolt docker, browser extension, command line interface, in short any other bugs 
please use [the other relevant repositories](https://github.com/passbolt).

If you are certain this is a new API bug please use the following format:

## ISSUE NAME
* Passbolt Version: 2.14.0
* Platform and Target: Windows 10, Edge, Firefox or Chrome browser
-- Operating system: Ubuntu
-- PHP: Newest
-- Web server: Don't know.. Used installation script for Passbolt for ubuntu
-- Database server:  Don't know.. Used installation script for Passbolt for ubuntu

### What you did
1. You have previously open another window of the browser; 
2. You are closing this new window; 
3. You come back to passbolt. 

### What happened
Folderstructure is gone. After a refresh of the page the folder structure is back.

### What you expected to happen
Folderstructure should still be there. Not only after a refresh of the page.

**Comment by cedricalfonsi** [comment]
Thank you for the report @davoezzz, I'm moving this issue on the browser extension repository 
https://github.com/passbolt/passbolt_browser_extension/issues/105
