### ISSUE TITLE
Can't add user to the group that i'm a group manager.

### ISSUE THREAD

**Issue by sz3jdii** [passbolt/passbolt_api#366]
## Can't add user to the group that i'm a group manager.
* Passbolt Version:  HEAD 1c92561a0e94e34cfb02e2c5bc5f99aabff49457 (the newest version)
* Platform and Target:
-- Operating system: Debian 10
-- PHP: 7.3
-- Web server: nginx 1.14.2
-- Database server: MariaDB 10.3.23
-- Web browser: Google Chrome

### What you did
As a group manager and administator I wanted to add a different user to group. I expect plus button near group name or ability to click 'i' icon in the right top corner and then edit group members.

I've tried to update, migrate and clear all cache. It's kinda WEB Gui error. The problem exists on multiple account and also multiple different computers.

### What happened
Pressing i button after selecting group does nothing. Nothing displays and also there's no '+' button near group name.

### What you expected to happen
Group manager with admin should have ability to add users to group whose group manager is described group manager.

**Comment by yoshito-maeoka** [comment]
It occurs to me too, even though my environment is a little bit different like that:
-- Operating system: CentOS Linux 7 
-- PHP: 7.2.34
-- Web server: Apache 2
-- Database server: MariaDB 5.5.65
-- Web browser: Google Chrome
and version of browser extension is 2.13.7.
and My Account is admin.

the error message shows in the butter bar: 'the group could not be saved. Not Found'
And I've checked that following message was displayed in console.log
`Validation error while saving group`
`{
  header: {
   code: 400,
   message: "Not Found".
   status: "error".
   status_code: 400
  },
  body: {
    Group: {
      secrets: {
        42: {
          resource_id: {
            resource_is_not_soft_deleted: "The resource does not exist."  
          }
        }
      } 
    }
  }
}`

and this was happened in webroot/js/app/bundles/passbolt-appjs/passbolt.js
(I did not find the original source code in this project)

any advice or hints would be great.

**Comment by cedricalfonsi** [comment]
Hello @yoshito-maeoka,

It looks like a permission exists in database despite its associated resource has been deleted.
Could you run the following command in your server shell and try again the operation:
`sudo su -s /bin/bash -c "./bin/cake passbolt cleanup" www-data`

**Comment by yoshito-maeoka** [comment]
@cedricalfonsi 
thank you! your hint works for us!!

**Comment by yoshito-maeoka** [comment]
@cedricalfonsi 
thank you for your hint. it works fine for us!

btw. it shows still an error like below in console (but any functions look working fine).
`data: {
  body: "",
  code: 404,
  message: "Not Found",
  name: "PassboltApiFetchError" 
}`

can we just ignore it?

**Comment by stripthis** [comment]
Closing as this seems to be related to DB corruption issue (manual intervention). Feel free to reopen if you have a procedure to recreate the issue manually from the UI.

@yoshito-maeoka this could be another legitimate call, for example call to missing endpoint for your version such `account/settings.json` so it should be fine.
