### ISSUE TITLE
Debian Package Install Missing php-curl Dependency For Yubico MFA

### ISSUE THREAD

**Issue by Alex-Richman** [passbolt/passbolt_api#368]
Passbolt Version: Pro 2.14.0-0
Platform and Target:
-- Operating system: Debian 10
-- Web server: nginx
-- Database server: mysql

- Install Passbolt Pro using the Debian 10 package from https://help.passbolt.com/hosting/install/pro/debian/debian.html
- Configure Yubico MFA provider in administration (Client ID + Secret Key)
- Attempt to configure Yubico MFA in user profile, receive an Internal Server Error from the `https://vault.infrastructure.caristo.com/mfa/setup/yubikey` endpoint

Nothing interesting I can see in the logs, but based on this forum post `https://community.passbolt.com/t/yubikey-configuration-issue/2190` I manually installed the `php-curl` package which fixed the problem (MFA setup and authentication for a user now works fine).

Looks like `php-curl` should be added as a dependency of the passbolt-pro-server package.

**Comment by stripthis** [comment]
Thanks for the report @Alex-Richman .
@dlen can you have a look? Thanks,
