### ISSUE TITLE
Notification Emails Have Wrong Tense In Subject/Body

### ISSUE THREAD

**Issue by Alex-Richman** [passbolt/passbolt_api#369]
Passbolt Version: Pro 2.14.0-0
Platform and Target:
-- Operating system: Debian 10
-- Web server: nginx
-- Database server: mysql

Some notification emails sent by Passbolt in reference to an action by another user use 'have' (second person plural) when it should use 'has' (third person singular) or nothing at all.

For example:
`David have just activated their account on passbolt`

Should read:
`David has just activated their account on passbolt`
Or:
`David just activated their account on passbolt`

**Comment by stripthis** [comment]
Thanks for the report @Alex-Richman

**Comment by stripthis** [comment]
Fixed with v3.0.0
