### ISSUE TITLE
predefined salt in passbolt_api/app/Config/core.php.default

### ISSUE THREAD

**Issue by svennd** [passbolt/passbolt_api#37]
Not sure if this is an issue, but the value Security.salt and Security.cipherSeed is already set by default in passbolt_api/app/Config/core.php.default

**Comment by stripthis** [comment]
Hi @svennd. Yes it's normal and harmless. These are the default config value of a cakephp app. We also currently don't use this values for any crypto operations, but if you go to the healthcheck page it will give you a warning that you need to change it (in case we start using these items in the future). It is also said you need to change these values in the installation documentation.
