### ISSUE TITLE
Immediatly delete resources metadata instead of keeping them in DB

### ISSUE THREAD

**Issue by drzraf** [passbolt/passbolt_api#370]
## ISSUE NAME
* Passbolt Version: 2.13.5-1
* Platform and Target:
-- Operating system: Debian
-- PHP: 7.3
-- Web server: nginx
-- Database server: mariadb

### What you did
- Delete a password.
- grep a mysqldump for the corresponding website.

### What happened
If found occurrence because deleting a password does not actually delete it but only set `deleted: 1` in the DB.

### What you expected to happen
No occurrence

### Comments
It may be good MySQL practice and allow neat restore-like UI features, but given the nature of this software it's a pretty bad practice in that the software keep data the user explicitly removed without even given him a chance to really delete them.
(We're not talking about a WordPress post revision but about something sensible enough that the user chose to use Passbolt)

Example: I used a `cli` to import data and found:
- That the `description` field wasn't encrypted
- That one of my `description` contained sensitive data.
Not only is this data ending up in plaintext in the MySQL database & backups, ... but it's also impossible to remove other than doing `delete from resources where deleted = 1;`.

**Comment by stripthis** [comment]
Yes that make sense. Without the "recycle bin" option to delete the meta data permanently, there should be deleted by default, or at least there should be an option to force that behavior. On a side note encrypted description in coming in next release (and the ability to encrypt other metadata too), so we'd expect metadata to become less sensitive over time.

**Comment by drzraf** [comment]
`encrypted description` is critical for me. Is there an open ticket I could subscribe to track progress on this too?

**Comment by stripthis** [comment]
@drzraf you can track feature request on the forum See. https://community.passbolt.com/t/as-an-admin-i-should-be-able-to-select-which-fields-are-encrypted/114

**Comment by stripthis** [comment]
Fixed with v3.0.0.
