### ISSUE TITLE
Can't create a new group using the data model from document 

### ISSUE THREAD

**Issue by kyxyes** [passbolt/passbolt_api#373]
## ISSUE NAME
* Passbolt Version: passbolt:2.13.1-debian
* Platform and Target:
-- Operating system: Linux
-- PHP: 7.3.19
-- Web server: nginx/1.14.2
-- Database server: mariadb:10.3

### What you did

Create a new group using V2 API according to https://help.passbolt.com/api/groups/create

### What happened

Use the data model from the [document](https://help.passbolt.com/api/groups/create) to create a new group from API

` {
  "name": "newgroup",
  "groups_users": [{
    "user_id": "<uuid_of_the_user_to_add>",
    "is_admin": true
  }, {
    "user_id": "<user2_uuid>",
    "is_admin": false
  }]
} 
`

will get this error 

`{
    "header": {
        "id": "9f1fefd2-6216-4632-8ddd-4ae5c829ffc3",
        "status": "error",
        "servertime": 1608238703,
        "title": "app_groups_addPost_error",
        "action": "5bd4ecae-da08-577d-ac32-ce7b13bd7b0f",
        "message": "Not Found",
        "url": "/groups.json?api-version=v2",
        "code": 400
    },
    "body": {
        "name": {
            "_empty": "The name cannot be empty."
        }
    }
}
`

The code [here](https://github.com/passbolt/passbolt_api/blob/master/src/Controller/Groups/GroupsAddController.php#L71) is looking for `Group.name` instead of `name` and `GroupUsers` instead of `groups_users` which is different with the data structure provided in document.
In this case the post body has be changed to this then it would return success.

`{
   "Group":{
      "name":"testGroup"
   },
   "GroupUsers":[
   	{
      "GroupUser":{
         "user_id":"<uuid_of_the_user_to_add>",
         "is_admin":true
      }
   }]
}
`

### What you expected to happen

Fix this either in document or in the code

**Comment by stripthis** [comment]
Indeed there is a bug as the format specified in the doc (v2 format) is not supported and only the one you describe (v1 format) will work. This is something we fixed already for the upcoming release.

**Comment by stripthis** [comment]
Fixed with v3.0.0.
