### ISSUE TITLE
possible IPv6 support

### ISSUE THREAD

**Issue by wnhre2ur8cxx8** [passbolt/passbolt_api#375]
Your website does not have an AAA Record, so my IPv6 server is unable to connect to your server to check if their are updates available. Also the integrated healthcheck doesnt work at all because of this. Please add IPv6 support to your servers!

**Comment by garrettboone** [comment]
@wnhre2ur8cxx8 Which website? Passbolt sites use Cloudflare and have AAAA records.

**Comment by wnhre2ur8cxx8** [comment]
Omg you are right. I misstyped.

Anyway the healthcheck fails, I will check again.

**Comment by wnhre2ur8cxx8** [comment]
[FAIL] Could not connect to passbolt repository to check versions. It is not possible check if your version is up to date.

Do you know what the domain/IP of the repository is? Is it the github repo?

**Comment by garrettboone** [comment]
@wnhre2ur8cxx8 Have a look through posts on the forum - github is for bugs. For example, here is a user with that message using the docker version of passbolt that is on an internal network so no way to check for versions: https://community.passbolt.com/t/cake-exception-argument-1-passed-to-app-view-helper-avatarhelper-getavatarurl-must-be-an-instance-of-app-model-entity-avatar-null-given/3405

**Comment by wnhre2ur8cxx8** [comment]
I wanted to at first actually, but since I believed it was a general lack of IPv6 support I decided to post here. Sorry again.

I will close it and reopen again if it turns out to be connected
