### ISSUE TITLE
Passbolt behind a reverse-proxy: missing route prefix on the recovery button

### ISSUE THREAD

**Issue by DistantThunder** [passbolt/passbolt_api#376]
##IMPORTANT: PLEASE READ

This is only a issue tracker for bugs related to the Passbolt API.
For passbolt docker, browser extension, command line interface, in short any other bugs 
please use [the other relevant repositories](https://github.com/passbolt).

If you are certain this is a new API bug please use the following format:

## Missing route prefix on the recovery button
* Passbolt Version: 2.13.5
* Platform and Target: 
-- Operating system: Linux Passbolt Docker image
-- PHP: Docker container
-- Web server: Docker container
-- Database server: 10.5.5-MariaDB
-- etc.: Kubernetes 1.18.4

### What you did

Passbolt supports a base URL scheme via the `APP_FULL_BASE_URL` environment variable.
This allows Passbolt to be aware of the Base URI it's exposed through and internally rewrite frontend URIs as needed.
The said var was set to "https://domain/vault" in this case.

Uninstalled the extension, wanted to recover.

### What happened
 All the other pages worked without issue but I could never start the recovery unless I migrated Passbolt to the root path ("/") of the webserver proxy.

However, on the user recovery page, coming from the log in page:

![image](https://user-images.githubusercontent.com/3923810/105187670-560bb680-5b33-11eb-833a-dd8ec5173f4d.png)

, the URI of the "start recovery" button isn't being prefixed:
![image](https://user-images.githubusercontent.com/3923810/105187978-b13da900-5b33-11eb-80e1-5ead2c9eb370.png)

Resulting in a mis-redirection:
![image](https://user-images.githubusercontent.com/3923810/105188121-d92d0c80-5b33-11eb-8838-d8bde8e771e1.png)

### What you expected to happen
I would expect all pages/button to be prefixed with the right BaseURL.

**Comment by garrettboone** [comment]
@DistantThunder Thanks for mentioning this. We are aware of the nature of this scenario and you are right. We are not generally encouraging a url prefix at the moment. It might be possible to create a workaround in the reverse-proxy by allowing passbolt to have a prefix-less (even non-public) domain that points to a second listener in the reverse proxy, which can pass it to the https://domain/vault.

**Comment by DistantThunder** [comment]
Hi, thank for your work on this. We've been reviewing this tool and find that it kind of fits our needs save for this problem. 

Is this on a roadmap to be solved at some point? 

It was my impression  the application routing  was centralized and the general architecture clean enough for this kind of things to be handled without pain.

**Comment by garrettboone** [comment]
Yes it is an issue we are aware of. I don't understand your setup enough to recommend anything, but I do understand the complication. Without the ability to create a subdomain, this is not straightforward for you, agreed. I will let the devs address any details regarding the priority of this.

**Comment by stripthis** [comment]
@DistantThunder there is a major update (v3) coming up next week. We've tested it to work with the app running in a directory (like www.domain.tld/workspace ). We'll try our best to fix such issues in the new version if you find more of them.

**Comment by damien-list** [comment]
@stripthis Great to hear that a major version is coming next week \o/

**Comment by DistantThunder** [comment]
@stripthis Great to hear this! Amazing work you're doing, even better that it's FLOSS.

**Comment by stripthis** [comment]
Fixed with v3.0.0.
