### ISSUE TITLE
Healthcheck sslFullBaseUrl returning an incorrect error

### ISSUE THREAD

**Issue by AntiGuide** [passbolt/passbolt_api#378]
## Healthcheck sslFullBaseUrl returning an incorrect error
* Passbolt Version: 3.0.0+
* Platform and Target:
-- Operating system: FreeBSD 11.4
-- PHP: 7.3.27
-- Web server: Apache 2.4.46
-- Database server: MariaDB 10.3.27

### What you did
Manual installation with the help of https://help.passbolt.com/hosting/install/ce/from-source.html and a healthcheck.
Config was 'fullBaseUrl' => 'https://192.168.1.23'

### What happened
The healthcheck showed errors for the sslFullBaseUrl check.

### What you expected to happen
No errors as the URL is configured with HTTPS.

### Suggested change

src/Utility/Healthchecks.php:82

Old:
`$https = !strpos(Configure::read('App.fullBaseUrl'), 'https');`
`$checks['application']['sslFullBaseUrl'] = ($https === false);`

New:
`$https = strpos(Configure::read('App.fullBaseUrl'), 'https');`
`$checks['application']['sslFullBaseUrl'] = ($https !== false);`

[Reference for strpos](https://www.php.net/manual/en/function.strpos.php)

**Comment by cedricalfonsi** [comment]
Hello @AntiGuide,

Thank you for you report and the suggested code change, I confirm the issue.
A fix will be ship with the next release.

**Comment by stripthis** [comment]
Fixed with 3.0.2
