### ISSUE TITLE
Add official support for PHP >= 7.1

### ISSUE THREAD

**Issue by sandrokeil** [passbolt/passbolt_api#38]
I'm looking forward to this project, but there are some problems. 

1. Minimum PHP version 5.3 is [to old](http://php.net/supported-versions.php), no security updates
2. The [mcrypt extension](http://php.net/manual/de/migration71.deprecated.php) is deprecated on PHP 7.1

Any plans to update to PHP >= 7.1 ?

**Comment by infectormp** [comment]
+1 to up Minimum PHP version to 5.6

**Comment by kevinmuller** [comment]
We are currently compatible with PHP7.0, and possibly with PHP7.1 (not tested).
Mcrypt is a dependency that is required by CakePHP2.x, the framework behind passbolt. We have plans to upgrade CakePHP to v3.x in the coming months (see [corresponding issue](https://github.com/passbolt/passbolt_api/issues/39)), which will fix this.

@infectormp Regarding minimum PHP version, for consistency we support the same as what is supported by CakePHP 2.x. So 5.3 at the moment. After migration to CakePHP 3.x it will become 5.6.

**Comment by stripthis** [comment]
PASSBOLT-1797 - Fix PHP7 glitches, fix travis build for PHP7

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-an-admin-i-can-run-passbolt-using-php-7-1/69
