### ISSUE TITLE
Health check reporting "App.fullBaseUrl is not set to HTTPS."

### ISSUE THREAD

**Issue by JosephGarrone** [passbolt/passbolt_api#380]
## Health check reporting "App.fullBaseUrl is not set to HTTPS."
* Passbolt Version: 3.0.1
* Platform and Target:
-- Operating system: Ubuntu 20.04.2 LTS (Up to date as of 25/02/2021)
-- PHP: PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56)
-- Web server: nginx version: nginx/1.18.0 (Ubuntu)
-- Database server: mysql  Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### What you did
Upgraded from 2.13.5 to 3.0.1 as per the [migration guide](https://help.passbolt.com/hosting/upgrade/pro/migrate-to-ubuntu.html), following an 18.04.5 LTS to 20.04.2 LTS upgrade.

### What happened
System came up all good following recommended migration path. Checked the healthcheck page and the only warning was:
![image](https://user-images.githubusercontent.com/4310797/109089187-8d860800-775c-11eb-9466-6439de294d62.png)
/etc/passbolt/passbolt.php contains:
![image](https://user-images.githubusercontent.com/4310797/109089390-e2c21980-775c-11eb-9afc-0193b4399458.png)

For reference the server is running a LetsEncrypt SSL certificate, and the nginx config is unmodified from whatever `dpkg-reconfigure passbolt-server-pro` set it to.  Navigation to the site yields the HTTPS page and no cert errors in chrome.

### What you expected to happen
That the App.fullBaseUrl warning should not appear.

**Comment by cedricalfonsi** [comment]
Hello @JosephGarrone, thank you for the report. 
I'm closing it as the issue has already been reported here: #378
