### ISSUE TITLE
Chrome extension not decrypting password in all circumstances

### ISSUE THREAD

**Issue by JosephGarrone** [passbolt/passbolt_api#381]
## Chrome extension not decrypting password in all circumstances
* Passbolt Version: 3.0.1 w/ Extension 3.0.5
* Platform and Target:
-- Operating system: Ubuntu 20.04.2 LTS (Up to date as of 25/02/2021)
-- PHP: PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56)
-- Web server: nginx version: nginx/1.18.0 (Ubuntu)
-- Database server: mysql  Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

### What you did
1. Sign out of passbolt in the browser and extension
2. Navigate away from the passbolt self-hosted instance webpage (Which should be at the login prompt)
3. Sign into the extension (with "Remember Me" not checked - have occasionally replicated issue with it checked, but not reliably)
4. Navigate to a password via the extension (For any site except the site you are on, i.e. it sometimes appears to work fine if the extension has pre-loaded the password via the current tab domain search it does)
5. Try and decrypt the password
6. Re-enter password when prompted
This issue has been reported by at least 2 other colleagues.

### What happened
Password is left encrypted and the spinning wheel continues forever
![image](https://user-images.githubusercontent.com/4310797/109253127-ceece500-783a-11eb-92d5-f2fb58176464.png)

### What you expected to happen
Password to decrypt and be copied to your clipboard.

### Workaround
If you repeat the "What you did" steps above, but navigate to your self-hosted instance after signing into the extension, the password will decrypt. For example:
1. Perform No. 1- No. 6 as outlined above
2. Navigate to the self-hosted instance and refresh (i.e. it will prompt for login, refresh and the extension must pass auth through?)
3. Go back to tab where you previously tried to decrypt password
4. Re-enter your password when prompted
5. The password will be decrypted in your clipboard

**Comment by cedricalfonsi** [comment]
Hello @JosephGarrone,
Thank you for the report, I confirm you the issue.
A fix will be shipped with the next release.

**Comment by s4ke** [comment]
We are experiencing the same errors and think this is related: https://github.com/passbolt/passbolt_docker/issues/153

**Comment by vedatbotuk** [comment]
Same issue. The Password don't encrypt. Also in firefox extension.

![Bildschirmfoto von 2021-03-01 23-57-16](https://user-images.githubusercontent.com/72791621/109570166-ea314c00-7ae9-11eb-8a6f-ca0a22886db9.png)

**Comment by stripthis** [comment]
Hello, we are aware of the issue and will be publishing a fix today. No need to confirm the report further. Thanks,

**Comment by cedricalfonsi** [comment]
Fixed with browser extension v3.0.6
