### ISSUE TITLE
No mails are sent using EmailDigest

### ISSUE THREAD

**Issue by RobinR1** [passbolt/passbolt_api#383]
* Passbolt Version: 3.0.1
* Platform and Target:
-- Operating system: CentOS7
-- PHP: 7.3.27 
-- Web server: Apache 2.4.6
-- Database server: MariaDB 5.5.68

### What you did
Configure cron to use Passbolt/EmailDigest.sender :+1: 
```
* * * * * apache /var/www/vhosts/passbolt/bin/cake Passbolt/EmailDigest.sender >> /var/log/passbolt/emaildigest_sender.log 2>&1
```

### What happened
No emails are sent, but EmailDigest logs this:
```
Exception: Argument 3 passed to Passbolt\EmailDigest\Utility\Factory\EmailPreviewFactory::configureEmailView() must be of the type string or null, bool given, called in /var/www/vhosts/passbolt/plugins/Passbolt/EmailDigest/src/Utility/Factory/EmailPreviewFactory.php on line 70 in [/var/www/vhosts/passbolt/plugins/Passbolt/EmailDigest/src/Utility/Factory/EmailPreviewFactory.php, line 105]
```

### What you expected to happen
Emails actually being sent.

### Workaround/Fix(?):
edit `plugins/Passbolt/EmailDigest/src/Utility/Factory/EmailPreviewFactory.php`
line 47: change 
```
    public function renderEmailPreviewFromDigest(EmailDigestInterface $emailDigest, $layout = false)
```
into
```
    public function renderEmailPreviewFromDigest(EmailDigestInterface $emailDigest, $layout = null)
```
line 63: change
```
    public function renderEmailPreviewFromEmailEntity(Entity $emailData, $layout = false)
```
into
```
    public function renderEmailPreviewFromEmailEntity(Entity $emailData, $layout = null)
```

**Comment by stripthis** [comment]
Hi @RobinR1 thank you for the detailed bug report. We'll investigate a publish a fix shortly.

**Comment by RobinR1** [comment]
Hi
I'm running v3.7.2 and I have not experienced any problems with the emaildigest anymore.  This can be marked as fixed, I think.
