### ISSUE TITLE
App.fullBaseUrl HTTPS check fails.

### ISSUE THREAD

**Issue by jsm222** [passbolt/passbolt_api#385]
App.fullBaseUrl HTTPS check fails.

* Platform and Target: ubuntu 20.04 php 7.4 v3.0.1
-- Operating system: ubuntu 20.04
-- PHP: 7.4
-- Web server: nginx 1.18
-- Database server: mariadb-server 10.3

### What you did
set App.fullBaseUrl to start with https
ran sudo -u www-data ./bin/cake passbolt healthcheck --verbose --application 
### What happened
I was told to set fullBaseUrl to https.

### What you expected to happen
The test should pass.

**Comment by cedricalfonsi** [comment]
Hello @jsm222, 
Thank you for the report.
The bug has already been reported #378

**Comment by jsm222** [comment]
Please see https://github.com/passbolt/passbolt_api/commit/b605775df53f161fdaaaf251bd19537abde9eec2#commitcomment-47840599
