### ISSUE TITLE
Cloudflare Antiddos conflict with mobile app

### ISSUE THREAD

**Issue by Artem3213212** [passbolt/passbolt_api#390]
## Cloudflare Antiddos conflict with mobile app
* Passbolt Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target:
-- Operating system: Android

### What you did
I config my server using cloudflare.

### What happened
In mobile app I see
![image](https://user-images.githubusercontent.com/37815717/111662524-0b4fa780-8821-11eb-87c2-f929a783350d.png)

**Comment by garrettboone** [comment]
This is not a Passbolt-endorsed or Passbolt-created app, but rather just an app someone made. Passbolt has open-source products - if this is not an open source app then you can't review what it is doing. That would be a general concern from a security standpoint.

**Comment by Artem3213212** [comment]
ok
