### ISSUE TITLE
Mysql query causes web app to be unreachable

### ISSUE THREAD

**Issue by nelson-sean** [passbolt/passbolt_api#395]
## Mysql query causes web app to be unreachable
* Passbolt Version: 2.13.5-pro-debian
* Platform and Target:
-- Operating system: Hosted using docker-compose on Ubuntu 20.04
-- PHP: 7.3.21
-- Web server: nginx? (unsure, whatever comes with the passbolt docker image)
-- Database server: mariadb 10.3
-- etc. Hosted on AWS ec2 on an instance dedicated for this service. 4GB RAM and 2 vCPUs

### What you did
User rapidly clicks on copy secret action multiple times from the browser extension or web app. I am not 100% certain this action is what causes the freeze. But it seems to fairly reliably cause it to happen.
![image](https://user-images.githubusercontent.com/6550505/116120762-83618680-a685-11eb-9a99-d5560c25f442.png)

### What happened
Backend then service becomes unresponsive for all users, hanging on "loading, please wait" for around 1 minute.
![image](https://user-images.githubusercontent.com/6550505/116120902-ab50ea00-a685-11eb-8431-e70b1e232b5d.png)

I have managed to catch the lockup in action and the culprit seems to be this query:

`SELECT 
  (
    Count(*)
  ) AS \`count\` 
FROM 
  (
    SELECT 
      \`actionlogs\`.\`id\` AS \`actionlogs__id\`, 
      \`actionlogs\`.\`user_id\` AS \`actionlogs__user_id\`, 
      \`actionlogs\`.\`action_id\` AS \`actionlogs__action_id\`, 
      \`actionlogs\`.\`context\` AS \`actionlogs__context\`, 
      \`actionlogs\`.\`status\` AS \`actionlogs__status\`, 
      \`actionlogs\`.\`created\` AS \`actionlogs__created\`, 
      \`actions\`.\`name\` AS \`actions__name\` 
    FROM 
      \`action_logs\` \`actionlogs\` 
      INNER JOIN \`users\` \`users\` ON \`users\`.\`id\` = (\`actionlogs\`.\`user_id\`) 
      INNER JOIN \`profiles\` \`profiles\` ON \`users\`.\`id\` = (\`profiles\`.\`user_id\`) 
      LEFT JOIN \`entities_history\` \`entitieshistory\` ON \`actionlogs\`.\`id\` = (
        \`entitieshistory\`.\`action_log_id\`
      ) 
      LEFT JOIN \`permissions_history\` \`permissionshistory\` ON \`permissionshistory\`.\`id\` = (
        \`entitieshistory\`.\`foreign_key\`
      ) 
      LEFT JOIN \`users\` \`permissionshistoryusers\` ON \`permissionshistoryusers\`.\`id\` = (
        \`permissionshistory\`.\`aro_foreign_key\`
      ) 
      LEFT JOIN \`resources\` \`permissionshistoryresources\` ON \`permissionshistoryresources\`.\`id\` = (
        \`permissionshistory\`.\`aco_foreign_key\`
      ) 
      LEFT JOIN \`groups\` \`permissionshistorygroups\` ON \`permissionshistorygroups\`.\`id\` = (
        \`permissionshistory\`.\`aro_foreign_key\`
      ) 
      LEFT JOIN \`folders\` \`permissionshistoryfolders\` ON \`permissionshistoryfolders\`.\`id\` = (
        \`permissionshistory\`.\`aco_foreign_key\`
      ) 
      LEFT JOIN \`resources\` \`resources\` ON \`resources\`.\`id\` = (
        \`entitieshistory\`.\`foreign_key\`
      ) 
      LEFT JOIN \`secret_accesses\` \`secretaccesses\` ON \`secretaccesses\`.\`id\` = (
        \`entitieshistory\`.\`foreign_key\`
      ) 
      LEFT JOIN \`resources\` \`secretaccessresources\` ON \`secretaccessresources\`.\`id\` = (\`secretaccesses\`.\`resource_id\`) 
      LEFT JOIN \`secrets_history\` \`secretshistory\` ON \`secretshistory\`.\`id\` = (
        \`entitieshistory\`.\`foreign_key\`
      ) 
      LEFT JOIN \`users\` \`secretshistoryusers\` ON \`secretshistoryusers\`.\`id\` = (\`secretshistory\`.\`user_id\`) 
      LEFT JOIN \`resources\` \`secretshistoryresources\` ON \`secretshistoryresources\`.\`id\` = (\`secretshistory\`.\`resource_id\`) 
      LEFT JOIN \`folders_history\` \`foldershistory\` ON \`foldershistory\`.\`id\` = (
        \`entitieshistory\`.\`foreign_key\`
      ) 
      LEFT JOIN \`actions\` \`actions\` ON \`actions\`.\`id\` = (\`actionlogs\`.\`action_id\`) 
    WHERE 
      (
        \`actionlogs\`.\`status\` = 1 
        AND (
          \`permissionshistoryresources\`.\`id\` = '<uuid>' 
          OR \`resources\`.\`id\` = '<uuid>' 
          OR \`secretaccesses\`.\`resource_id\` = '<uuid>' 
          OR \`secretshistoryresources\`.\`id\` = '<uuid>'
        )
      ) 
    GROUP BY 
      \`actionlogs\`.\`id\`, 
      \`entitieshistory\`.\`created\`
  ) \`count_source\`;
`

When I run this query manually against our passbolt database the runtime matches up with the length of the backend service being unavailable. For reference here are the record counts for all tables from the database:

![image](https://user-images.githubusercontent.com/6550505/116121373-25816e80-a686-11eb-9a2a-1e9ab55a05f7.png)

### What you expected to happen
Secret is copied for user with no service interruptions for others.

**Comment by cedricalfonsi** [comment]
Hello @nelson-sean,

Could you try to update at least to v2.14.0, the performance issues of the action logs queries have been fixed with this release. See [https://help.passbolt.com/releases/pro/v2140-sunshine](https://help.passbolt.com/releases/pro/v2140-sunshine)

**Comment by nelson-sean** [comment]
> Hello @nelson-sean,
> 
> Could you try to update at least to v2.14.0, the performance issues of the action logs queries have been fixed with this release. See https://help.passbolt.com/releases/pro/v2140-sunshine

Updating to v2.14.0 seems to have taken care of our issue thank you!
