### ISSUE TITLE
Username validation might be too restrictive

### ISSUE THREAD

**Issue by chenz67r** [passbolt/passbolt_api#40]
An account like cn=admin,dc=example,dc=com is not accepted

**Comment by stripthis** [comment]
ref. PASSBOLT-1637 / #17

**Comment by stripthis** [comment]
Ref. PASSBOLT-1934 As a user I should be allowed to add the a ldap path as username

**Comment by euterklaas** [comment]
Will this issue be resolved in the near future?

**Comment by stripthis** [comment]
Hi @euterklaas I will bump it up in the backlog.

**Comment by kevinmuller** [comment]
This issue has been solved in 1.6.1: http://www.passbolt.com/release/notes#Fresh
