### ISSUE TITLE
gnupg issue following install (500 server error)

### ISSUE THREAD

**Issue by dm2912** [passbolt/passbolt_api#400]
## ISSUE NAME
* Passbolt Version: Latest Git
* Platform and Target:
-- Operating system: Ubuntu Server 20.04
-- PHP: 8.0.5
-- Web server: Apache
-- Database server: MariaDB
-- etc.: OTHER RELEVANT PLATFORM INFO

### What you did
Ran through entire installation process. Everything installed without errors. 

### What happened

However, on visiting the domain I am getting http error 500

![image](https://user-images.githubusercontent.com/25871666/120037821-25182280-bffa-11eb-9798-0354faf9c02f.png)

Apache error log is showing:

```
[Fri May 28 20:09:24.849966 2021] [mpm_prefork:notice] [pid 25589] AH00169: caught SIGTERM, shutting down
[Fri May 28 20:09:24.974736 2021] [mpm_prefork:notice] [pid 29763] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f configured -- resuming normal operations
[Fri May 28 20:09:24.974781 2021] [core:notice] [pid 29763] AH00094: Command line: '/usr/sbin/apache2'
[Fri May 28 20:09:38.736439 2021] [proxy_fcgi:error] [pid 29768] [client 141.101.104.159:65304] AH01071: Got error 'PHP message: PHP Fatal error:  You must enable the gnupg extension to use Passbolt. in /var/www/passbolt/config/requirements.php on line 31'
[Fri May 28 20:09:41.853819 2021] [proxy_fcgi:error] [pid 29769] [client 141.101.104.159:14128] AH01071: Got error 'PHP message: PHP Fatal error:  You must enable the gnupg extension to use Passbolt. in /var/www/passbolt/config/requirements.php on line 31'

```
however 

`php --info | grep 'gnupg support'`

is returning

`gnupg support => enabled`

I have checked that

`extension=gnupg.so`

is present in both /etc/php/8.0/apache2/php.ini and /etc/php/8.0/cli/php.ini

Just as a test i commented out the gnupg line in requirements.php just to see if everything else was working and passbolt loaded with the install process but of course jammed when it came to...

![image](https://user-images.githubusercontent.com/25871666/120037662-e6826800-bff9-11eb-86db-1efdaad7ff84.png)

**Comment by dm2912** [comment]
Also checked extension directory

`php -r "print phpinfo();" | grep "extension_dir"`

which results in

```
extension_dir => /usr/lib/php/20200930 => /usr/lib/php/20200930
sqlite3.extension_dir => no value => no value
```

Its present there

![image](https://user-images.githubusercontent.com/25871666/120051443-936bdd80-c018-11eb-86a6-db287fbeadfa.png)

**Comment by stripthis** [comment]
Hello,

This is an installation issue, please open a thread on the community forum:
https://community.passbolt.com/c/installation-issues/5

As indicated on the issue template we use only github for bugs.
Best,
