### ISSUE TITLE
Can't view a group whereas status code is 200

### ISSUE THREAD

**Issue by tsergue** [passbolt/passbolt_api#407]
## Can't view a group whereas status code is 200
* Passbolt Version: 3.0.1
* Platform and Target:
-- Operating system: Ubuntu 20.04
-- PHP: 7.3.29
-- Web server: Apache/2.4.41
-- Database server: MySQL 5.7

### What you did
I make a GET request to `/groups/<groupId>.json`.
```js
axios.get(`${this.host}/groups/${groupDataId}.json?api-version=v2`)
      .then(res => {
          var groupsUsers = res.data.body.groups_users;
          // groupsUsers is undefined

          // ...
      }
```

### What happened
I have a status code 200 but i haven't  the `groups_users` key in the response body.

### What you expected to happen
Get data for a single group.
It was working without any problem before.
Actual response:
```js
data:
   { header:
      { id: '09efcdd2-3651-4656-a68d-57bc4c7a82d0',
        status: 'success',
        servertime: 1627481063,
        action: 'f0c5d1cd-b3e3-5494-8fb7-73a427790ce2',
        message: 'The operation was successful.',
        url:
         '/groups/<our_groupId>.json?api-version=v2',
        code: 200 },
     body:
      { id: '<our_groupId>',
        name: 'Data',
        deleted: false,
        created: '2018-05-02T15:39:37+00:00',
        modified: '2018-07-11T09:08:17+00:00',
        created_by: '3de7bf20-5e5b-499e-bd8a-e3be47ef45db',
        modified_by: '3de7bf20-5e5b-499e-bd8a-e3be47ef45db' } } }
```

We can't understand why we can't get the group anymore.

Thank you in advance for your help !

**Comment by garrettboone** [comment]
Just a note - starting v3.0.0 support for <PHP7.3 was dropped. https://help.passbolt.com/releases/ce/v300-our-house

**Comment by damien-list** [comment]
I've not double checked, the version of PHP used before @tsergue submitted the issue (We work together). It's not 7.2.24 but 7.3.29.

**Comment by zentavr** [comment]
I have the same issue with PHP 7.4.21 as well.

**Comment by stripthis** [comment]
Hi,

Unlike in previous API version, in API version 3 the associations are not returned on the view or index endpoint.
It's possible to get the group user data by using the contain parameters, for example:
```
https://yourpassbolt.com/groups/<uuid.json>?
  contain[groups_users]=1
```

There are multiple supported parameters depending on what you need to retrieve, e.g.:
```
modifier', 'modifier.profile', 'my_group_user',
                'users', 'groups_users', 'groups_users.user',
                'groups_users.user.profile', 'groups_users.user.gpgkey',
```       

See also. https://help.passbolt.com/api/groups

**Comment by zentavr** [comment]
Hello @stripthis,

The documentation here: https://help.passbolt.com/api/groups/read does not mention that there are any parameters expected.
There is nothing here as well: https://api-reference.passbolt.com/#/Group/getGroup

I wonder if it is possible to update the docs and provide the examples?

**Comment by stripthis** [comment]
Yes updating the doc in on our radar. We have new members joining the team so we'll be able tackle this next quarter.

**Comment by tsergue** [comment]
@zentavr  Thanks a lot, problem solved
