### ISSUE TITLE
Unable to setup first Admin account

### ISSUE THREAD

**Issue by nevasway** [passbolt/passbolt_api#41]
Why can't I setup the first Admin account? Here's what happens... 

First, I successfully initialize the Passbolt mysql database and register my first admin user:
```
su -s /bin/bash -c "/var/www/passbolt/app/Console/cake install --no-admin" www-data
/var/www/passbolt/app/Console/cake passbolt register_user -u henry@xxxx.com -f Henry -l xxxxx -r admin
```
Then I copy the link displayed (I don't have email configured yet) and paste it into my browser (Chrome):
https://server-name:6443/setup/install/d46de1f2-ed84-3d5c-aedb-5bda3ecbc43a/35f779d0-072e-419a-a98e-c0182c34a54a

My browser flashes up a page for a few milli-seconds that says something like `Welcome to passbolt! Let's take 5 min to setup your system` But then displays a page with the following error:
```
Damn...
An error occured
 Error! Something unexpected happened. The setup cannot be completed.
What to do now ?
Please contact us or your system administrator, and provide the debug information below.
 See debug info
```
Here's the debug info:
```
{
  "error": "settings could not be validated",
  "setup": {
    "stepId": "",
    "stepsHistory": "",
    "user": {
      "username": "henry@xxxx.com",
      "firstname": "Henry",
      "lastname": "xxxxx",
      "id": "d46de1f2-ed84-3d5c-aedb-5bda3ecbc43a"
    },
    "key": {},
    "settings": {
      "token": "",
      "domain": "",
      "securityToken": {},
      "armoredServerKey": ""
    }
  },
  "additional": {
    "settings": {
      "token": "35f779d0-072e-419a-a98e-c0182c34a54a",
      "domain": "https://server-name:6443"
    },
    "user": {
      "username": "henry@xxxx.com",
      "firstname": "Henry",
      "lastname": "xxxxx",
      "id": "d46de1f2-ed84-3d5c-aedb-5bda3ecbc43a"
    }
  }
}
```

No errors reported in `/var/log/apache2/error.log`
No errors reported in `/var/www/passbolt/app/tmp/logs/error.log`
Are there any other log files that might help me troubleshoot this problem?

I'm running a Passbolt server on my own computer inside the Passbolt Debian Docker container. I don't think my trouble is with docker, which is why I'm looking for help here in the passbolt_api repository. I'm also using port 6443 for ssl, which *shouldn't* be a problem, but I'm open to anything at this point.

**Comment by cedricalfonsi** [comment]
Hello nevasway,

Thanks for your interest in passbolt.

Did you check the passbolt healhcheck yet ? if not, ensure first that your passbolt is fine tuned.

1. Enable the debug mode. In the file app/Config/core.php, set the debug variable to 1.
2. Go to the healthcheck page : https://server-name:6443/healthcheck

Best regards.

**Comment by nevasway** [comment]
Yes, healcheck was a useful tool for finding some permission errors. Here's the output:

```
Passbolt API Status

Core configuration

Your version of PHP is 5.2.8 or higher.
Your tmp directory is writable.
The FileEngine is being used for core caching. To change the config edit core.php
Your database configuration file is present.
Passbolt is able to connect to the database.
Debug mode is on.
Application configuration

Your webroot/img/public directory is writable.
SSL access is enabled.
Passbolt is configured to force SSL use.
PHP GPG Module is on.
The server GPG key is not the default one.
Your install is not up to date. It should be: v1.4.0. But you are using: 1.3.2
Your schema up to date.
Selenium API endpoints are disabled.
Registration is closed, only administrators can add users.
There is at least one admin account.
Serving the compiled version of the javascript app.
Development tools

Phpunit v3.7.38 is installed.
DebugKit is not installed. It is useful if you are extending passbolt. Learn more.
```

I see that v1.4.0 just came out. I'll pull it.

**Comment by nevasway** [comment]
I updated to v1.4.0 and migrated the schema.  But I still can't setup my first admin user. Here's what the /healtcheck page says now:
```
Passbolt API Status

Core configuration

Your version of PHP is 5.2.8 or higher.
Your tmp directory is writable.
The FileEngine is being used for core caching. To change the config edit core.php
Your database configuration file is present.
Passbolt is able to connect to the database.
Debug mode is on.
Application configuration

Your webroot/img/public directory is writable.
SSL access is enabled.
Passbolt is configured to force SSL use.
PHP GPG Module is on.
The server GPG key is not the default one.
You application is up to date. You are using: v1.4.0
Your schema up to date.
Selenium API endpoints are disabled.
Registration is closed, only administrators can add users.
There is at least one admin account.
Serving the compiled version of the javascript app.
Development tools

Phpunit v3.7.38 is installed.
DebugKit is not installed. It is useful if you are extending passbolt. Learn more.
```

Now for some new errors. Now I'm getting an error reported in /var/www/passbolt/app/tmp/logs/error.log:
```
2017-02-16 16:56:49 Error: [ForbiddenException] Forbidden
Request URL: /healthcheck
Stack Trace:
#0 /var/www/passbolt/app/Controller/HealthCheckController.php(57): HealthCheckController->__accessChecks()
#1 [internal function]: HealthCheckController->index()
#2 /var/www/passbolt/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(HealthCheckController), Array)
#3 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#4 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(HealthCheckController), Object(CakeRequest))
#5 /var/www/passbolt/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#6 {main}
```

Also, there is an error displayed *behind* the text of the /healthcheck page:
```
Warning: SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/persistent/passbolt_cake_core_file_map): failed to open stream: Permission denied in /var/www/passbolt/lib/Cake/Cache/Engine/FileEngine.php on line 356
Call Stack
#	Time	Memory	Function	Location
1	0.0001	239200	{main}( )	../index.php:0
2	0.0002	240784	include( '/var/www/passbolt/lib/Cake/bootstrap.php' )	../index.php:95
3	0.0009	595528	Configure::bootstrap( )	../bootstrap.php:432
4	0.0024	703288	App::init( )	../Configure.php:79
5	0.0024	703496	Cache::read( )	../App.php:776
6	0.0026	768216	FileEngine->read( )	../Cache.php:363
7	0.0026	768480	FileEngine->_setKey( )	../FileEngine.php:158
8	0.0028	790256	trigger_error ( )	../FileEngine.php:356
```
Any ideas?

**Comment by cedricalfonsi** [comment]
Hello nevasway,

Regarding the error your get after the migration, it looks like the right on the /var/www/passbolt/app/tmp have changed. You have to ensure that all subfolders and files are writable for your apache/nginx user.

About the plugin setup issue, can you reinstall the plugin and check again. It should empty the plugin local storage, and might solve your issue.

Best regards,
Cédric

**Comment by nevasway** [comment]
Cedric - Thank you for your time! 

The following command fixed the permission issue that popped up after upgrading to v1.4.0:
```
chown -R www-data:www-data /var/www/passbolt/app/tmp/
```

I removed the Passbolt Chrome extension (I didn't restart Chrome). Then I reinitialized the mysql database so I could re-create my admin user:
``` 
su -s /bin/bash -c "/var/www/passbolt/app/Console/cake install --no-admin" www-data
```
The `cake install` completed successfully but the following warning was printed, which I'm pretty sure is new (since I upgraded to v1.4.0):
```
Warning Error: file_put_contents(/var/www/passbolt/app/Config/anonymous_statistics.php): failed to open stream: Permission denied in [/var/www/passbolt/app/Model/AnonymousStatistic.php, line 80]
```
No errors were printed to `/var/www/passbolt/app/tmp/logs/error.log` so I continued with creating my admin user:
```
/var/www/passbolt/app/Console/cake passbolt register_user -u henry@xxxx.com -f Henry -l xxxxx -r admin
```
Then I copied the link into chrome.
Installed the Passbolt extension.
Tried the link again but I got the same error:
```
{
  "error": "settings could not be validated",
  "setup": {
    "stepId": "",
    "stepsHistory": "",
    "user": {
      "username": "henry@xxxx.com",
      "firstname": "Henry",
      "lastname": "xxxxx",
      "id": "7b666c8f-d9ed-36f3-a035-b4de023c9299"
    },
    "key": {},
    "settings": {
      "token": "",
      "domain": "",
      "securityToken": {},
      "armoredServerKey": ""
    }
  },
  "additional": {
    "settings": {
      "token": "beae78bf-ca9e-452f-ae22-58a48cf61456",
      "domain": "https://server-name:6443"
    },
    "user": {
      "username": "henry@xxxx.com",
      "firstname": "Henry",
      "lastname": "xxxxx",
      "id": "7b666c8f-d9ed-36f3-a035-b4de023c9299"
    }
  }
}
```

I don't know if these links can be used more than once and I was concerned that I used that link twice so I created a second admin user named Bob but still got the same error when I used the link provided.

What do you think?

**Comment by cedricalfonsi** [comment]
I'm sorry that you still encountered this issue.
Can you check if you can reproduce it on firefox ?

**Comment by nevasway** [comment]
Same error with firefox:
```
{
  "error": "settings could not be validated",
  "setup": {
    "stepId": "",
    "stepsHistory": "",
    "user": {
      "username": "mike@xxxx.com",
      "firstname": "Mike",
      "lastname": "xxxxx",
      "id": "636424bf-df26-3929-a29f-758bc4c11982"
    },
    "key": {},
    "settings": {
      "token": "",
      "domain": "",
      "securityToken": {},
      "armoredServerKey": ""
    }
  },
  "additional": {
    "settings": {
      "token": "318f2781-b574-402f-a8d4-49d6b21049a1",
      "domain": "https://server-name:6443"
    },
    "user": {
      "username": "mike@xxxx.com",
      "firstname": "Mike",
      "lastname": "xxxxx",
      "id": "636424bf-df26-3929-a29f-758bc4c11982"
    }
  }
}
```

Note that I'm not configuring the Passbolt plugin after I install it, I just go directly to the link provided by `cake passbolt register_user`.

I'm using a self-signed certificate with Apache which shouldn't matter but it's one more data point. Also, I'm a noob with Apache which is one reason why I'm using your docker container: https://github.com/passbolt/passbolt_docker_debian.git
There maybe something obvious that I'm missing about how Apache should be configured.

**Comment by victort** [comment]
I too am having this error.

firefox, debian here, basically word for word the same issue as above

is this issue solved, what was the fix?

**Comment by stripthis** [comment]
@victort  can you open a new issue on the community forum with more information about your system (which version of passbolt, php, etc.), any error log from the application or the browser, so that we can reproduce the issue and try to figure what issue is?

https://community.passbolt.com/c/installation-issues
