### ISSUE TITLE
Warning Error: file_get_contents(/usr/share/nginx/passbolt/config/jwt/jwt.pem): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by marcgenou** [passbolt/passbolt_api#415]
Hi guys

I was upgrading from 3.2.1 to this new 3.3.0-1 and a warning showed up after a healthcheck.

## ISSUE NAME
* Passbolt Version: 3.3.0-1 a1f8ab1ab2080e5a7782a263f32be1ba353de8fb
* Platform and Target:
-- Operating system: alma 8.4
-- PHP: 7.4.25
-- Web server: nginx
-- Database server: mariadb
-- etc.: OTHER RELEVANT PLATFORM INFO

### What you did
su -s /bin/bash -c "./bin/cake passbolt healthcheck" nginx

### What happened

     ____                  __          ____  
    / __ \____  _____ ____/ /_  ____  / / /_ 
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/ 
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /    
 /_/    \__,_/____/____/_.___/\____/_/\__/   

 Open source password manager for teams
-------------------------------------------------------------------------------
 Healthcheck shell........Warning Error: file_get_contents(/usr/share/nginx/passbolt/config/jwt/jwt.pem): failed to open stream: No such file or directory
In [/usr/share/nginx/passbolt/plugins/Passbolt/JwtAuthentication/src/Service/AccessToken/JwtKeyPairService.php, line 110]

2021-10-28 09:20:29 Warning: Warning (2): file_get_contents(/usr/share/nginx/passbolt/config/jwt/jwt.pem): failed to open stream: No such file or directory in [/usr/share/nginx/passbolt/plugins/Passbolt/JwtAuthentication/src/Service/AccessToken/JwtKeyPairService.php, line 110]

### What you expected to happen
flawless message

**Comment by stripthis** [comment]
Fix scheduled for 3.3.2 or later.

**Comment by cedricalfonsi** [comment]
Fixed with v3.4.0
