### ISSUE TITLE
Emails not being added to email field

### ISSUE THREAD

**Issue by meghanatweever** [passbolt/passbolt_api#416]
##IMPORTANT: PLEASE READ

Only use github issues for bugs.

We will be more than happy to help you on the community forum for:
- feature requests: https://community.passbolt.com/c/backlog
- issues related to installations: https://community.passbolt.com/c/installation-issues
- general questions: https://community.passbolt.com/c/uncategorized

This is only a issue tracker for bugs related to the Passbolt API.
For passbolt docker, browser extension, command line interface, in short any other bugs 
please use [the other relevant repositories](https://github.com/passbolt).

If you are certain this is a new API bug please use the following format:

## ISSUE NAME
* Passbolt Version: EXACT RELEASE VERSION OR COMMIT HASH, HERE.
* Platform and Target:
-- Operating system: NAME AND VERSION
-- PHP: VERSION
-- Web server: NAME AND VERSION
-- Database server: NAME AND VERSION
-- etc.: OTHER RELEVANT PLATFORM INFO

**We are using the hosted version so this does not apply**

### What you did
When I tap the credentials I need to add from the suggested list in Passbolt, the password is added to the password field, but them email is blank. Then when I copy and paste the email out of passbolt and into the password field, the credentials don't work. After a hard refresh, if I copy and paste the email, then I'm able to login, but for some reason, if I just tap the credentials from the list when I'm not able to login

![Screen Shot 2021-10-28 at 3 51 29 PM](https://user-images.githubusercontent.com/16941313/139326048-c233e2fd-a938-4b6a-8879-54a24dcd3a44.png)

### What happened
When I tap the credentials I need to add from the suggested list in Passbolt, the password is added to the password field, but them email is blank. Then when I copy and paste the email out of passbolt and into the password field, the credentials don't work. After a hard refresh, if I copy and paste the email, then I'm able to login, but for some reason, if I just tap the credentials from the list when I'm not able to login
### What you expected to happen

EXPLAIN WHAT IS TO BE EXPECTED, HERE.
Tapping the suggested credentials from the list in passbolt should add the email and password to the corresponding fields in the login page. They should then work when you tap login.

**Comment by stripthis** [comment]
Hello,

Thanks for the report.
We need more information in order to reproduce the issue, such as the url of the site where we can test the behavior and/or the html code of that form.

Best,

**Comment by meghanatweever** [comment]
That's ok, It's working now. Thanks.
_______

Meghan Holding
Customer Success Manager
Weever
Toll free: 1 (800) 299-0623
Office: (905) 218-6584
weeverapps.com
