### ISSUE TITLE
Comma in names are not supported

### ISSUE THREAD

**Issue by weebl2000** [passbolt/passbolt_api#418]
### What you did
I added a user with last name: A, B

This is common in the Netherlands where people have a word in between like "van Dijk" it is common to list them as Dijk, van so they are sorted alphabetically

### What happened
It breaks registration. When you try to create a passphrase it tells you:

Error generating keypair: Invalid user id format

### What you expected to happen
Please allow me to use comma in the username creation OR prevent me from entering it in the frontend.

**Comment by stripthis** [comment]
Thanks for the report @weebl2000

**Comment by cedricalfonsi** [comment]
Fixed with v3.5.0
