### ISSUE TITLE
MissingrouteException in passbolt 3.5 on debian 11

### ISSUE THREAD

**Issue by fayak** [passbolt/passbolt_api#419]
## MissingrouteException
* Passbolt Version: passbolt-ce-server/buster,now 3.5.0-1 all [installed]
* Platform and Target:
-- Operating system: debian 11 / `Linux 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux`
-- PHP: ```
PHP 7.4.25 (cli) (built: Oct 23 2021 21:53:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.25, Copyright (c), by Zend Technologies```
-- Web server: `nginx/stable,stable,now 1.18.0-6.1 all [installed]`
-- Database server: `mariadb-server/stable,stable,now 1:10.5.12-0+deb11u1 all [installed]`
-- etc.: Migrated from passbolt 2018 (version 2.5) (commit: f9e13b696611271bffb11a5efa80038a56368114)

### What you did
Upgraded the OS and mariadb.
Installed nginx and passbolt-ce-server according to the documentation in
https://help.passbolt.com/hosting/install/ce/debian/debian.html
and
https://help.passbolt.com/hosting/upgrade/ce/migrate-to-debian.html

Made the modification in `/etc/passbolt/passbolt.php` from `/var/www/passbolt/config/passbolt.php`
Put the GPG keys in the appropriate place (as the doc explained)
Ran the migrations as described in the doc

### What happened
Migration are ok
healthcheck is ok
Login page shows up. I can login, it works but then a white page (with the grey header on top).
Checking the logs I have:

```
2022-01-19 17:07:18 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/auth/checksession.json" could not be found. in /usr/share/php/passbolt/vendor/cakephp/cakephp/src/Routing/RouteCollection.php on line 199
Request URL: /auth/checksession.json
Client IP: 10.2.13.2
```

### What you expected to happen
Passbolt working and updated to the latest version

**Comment by stripthis** [comment]
`/auth/checksession` is a deprecated endpoint. What is the version of the browser extension that you using?

**Comment by fayak** [comment]
Hello @stripthis ,

I'm trying to access passbolt via its main  `fullBaseUrl` on firefox, not even via the extension (which doesn't work either).

Not sure exactly about the previous version, it was from commit f9e13b6 which I believe is 2.5 ?

**Comment by nourcy** [comment]
Can you try to go to /logout and try to login again?
Also based on the old version I would recommend to execute 
`sudo -H -u www-data bash -c "/usr/share/php/passbolt/bin/cake passbolt cleanup"`

**Comment by fayak** [comment]
Hello @nourcy ,

I ran the cleanup also, it reported the deletion of 4 groups that had some issues but nothing more :
```
 Open source password manager for teams
-------------------------------------------------------------------------------
 Cleanup shell (fix mode)
-------------------------------------------------------------------------------
4 issues fixed in table GroupsUsers (hard deleted groups)
4 issues fixed!
```

Logout +re-login didn't change anything :/ 

```
2022-01-19 17:30:23 Error: [Cake\Routing\Exception\MissingRouteException] A route matching "/auth/checksession.json" could not be found. in /usr/share/php/passbolt/vendor/cakephp/cakephp/src/Routing/RouteCollection.php on line 199
Request URL: /auth/checksession.json
Client IP: 10.2.13.2```

**Comment by stripthis** [comment]
I would also fully restart the browser, as it seems the extension is still believing it is talking to a v2.5. I'm surprised you didn't run into issues earlier.

**Comment by fayak** [comment]
restarting/pkill-ing the browser fixed the issue ! Thank you very much !

Do you want me to make a PR to add this in the FAQ or somewhere in the documentation ?

**Comment by stripthis** [comment]
@fayak No I think it's fine. We'll make a FAQ if we see more people in your situation. ☮️
