### ISSUE TITLE
The webserver is triggering a download of the php file instead of running it

### ISSUE THREAD

**Issue by c0fe** [passbolt/passbolt_api#42]
Here is the setup:

CentOS 7
PHP 7.0
Nginx

I have Passbolt installed in /var/www/html/passbolt and the permissions are set and Nginx is pointing there as the default. But when I try to navigate it instead downloads a file called "download" (no extension) and the contents of it are:

https://hastebin.com/uvofanenib.php

What am I missing or doing wrong?

**Comment by sebastianberm** [comment]
Your PHP setup seems wrong. This file instantiates the framework, and should be ran instead of downloaded.
Can you doublecheck you Nginx config to see if you're actually sending the requests to PHP-fpm or any other form of execution system :-)?

**Comment by c0fe** [comment]
I tried Apache but same result, just get this page:

https://hastebin.com/bokunilija.php

**Comment by c0fe** [comment]
I can try the install on Debian though I am not sure what I am doing wrong.

**Comment by stripthis** [comment]
Do you manage to get a simple php page working? This seems to be a web server configuration issue, not a passbolt issue.

**Comment by c0fe** [comment]
Working on this still.

**Comment by c0fe** [comment]
So I ran the two chown commands listed in the installation documentation, but I am still getting a permission issue.

**# Setup**
**Distro:** Debian 8
**Server:** Apache (v2)
**PHP:** 5

Error Message:

`:/var/www/html# su -s /bin/bash -c "app/Console/cake install --no-admin" www-data
bash: app/Console/cake: Permission denied
`

I am also not sure what command to find the gpg keyring to add to the directory in app.php

**Comment by c0fe** [comment]
Any ideas as to why I am getting a permission isssue even after running the two permission commands?
