### ISSUE TITLE
Issue With API - sharing folder, pro edition

### ISSUE THREAD

**Issue by kotso** [passbolt/passbolt_api#421]
### What you did

I'm integrating PassBolt with my other systems (written in PHP) and need to share folder via API call. (folder is created via api call also, so not a general issue with api communication)

here is sample code:

```
        $uuid = '1cfb4393-cc9f-46a4-a61a-a4c929e3fe53';
        $share = ' {"permissions":[
			{	
				"type": 1,
				"aco": "Folder",
				"aro": "Group",
				"aro_foreign_key": "bc8af13f-7cd6-490c-8843-25c47e469283",
				"aco_foreign_key": "1cfb4393-cc9f-46a4-a61a-a4c929e3fe53"
			},
			{
				"type":15,
				"aco": "Folder",
				"aro":"Group",
				"aro_foreign_key": "ddf8bc168-246b-4be4-a0db-519844052897",
				"aco_foreign_key": "1cfb4393-cc9f-46a4-a61a-a4c929e3fe53"
			}
			]}';

        $ch = curl_init($this->serverUrl . '/share/folder/'.$uuid.'.json?api-version=v2');
        curl_setopt($ch, CURLOPT_HEADER, 0);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PUT");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_COOKIE, $this->getCookie(true));
        curl_setopt($ch, CURLOPT_POSTFIELDS, $share);
        $extraHeaders = array(
            "X-CSRF-Token: {$this->csrfToken}",
        );
        curl_setopt($ch, CURLOPT_HTTPHEADER, $extraHeaders);
        $response = curl_exec($ch);
        curl_close($ch);
``` 

code itself is taken from https://github.com/passbolt/passbolt_api_php_example with minor modifications.

### What happened

here is response:

```
 {"header":{"id":"9908c43a-d9b7-4b92-83c6-4e2f103022ca","status":"success","servertime":1644943257,"action":"d161a38f-c522-5984-85ff-17c78b2a3bb5","message":"The operation was successful.","url":"\/share\/folder\/6d49202c-8b6d-454b-a887-318067fd896e.json?api-version=v2","code":200},"body":{"id":"6d49202c-8b6d-454b-a887-318067fd896e","name":"40","created":"2022-02-15T14:23:01+00:00","modified":"2022-02-15T14:23:01+00:00","created_by":"0cefa0eb-afad-46e7-895e-07b08493e1ff","modified_by":"0cefa0eb-afad-46e7-895e-07b08493e1ff","folder_parent_id":"c09c1af3-5ba7-410d-8575-6ed012f52990","personal":true}}
```

response states: `"message":"The operation was successful."` but nothing happens, folder does not get shared with 2 groups.

### What you expected to happen

Folder to be shared with groups.

**Comment by stripthis** [comment]
Hello @kotso,

Sharing a folder only changes the permission on the folder. It doesn't trigger a share of the items contained in that folder. Passbolt is an end to end encryption system, so your script needs to get the content inside that folder (recursively or not depending on what you want to), decrypt it the items, share it with the group, etc. 

See: https://help.passbolt.com/api/resources/share

Check in the browser extension code if you want to replicate the same behavior than the extension:
https://github.com/passbolt/passbolt_browser_extension/blob/master/src/all/background_page/controller/share/shareFoldersController.js

Ps. Github issues is reserved for bugs, you can contact us on support@passbolt.com or on the community forum for questions around the API.
