### ISSUE TITLE
Imposible to use App with self signed certificate 

### ISSUE THREAD

**Issue by Stefan-CPlanet** [passbolt/passbolt_api#425]
## ISSUE NAME
* Passbolt Version: Updated to latest
* Platform and Target:
-- Operating system: Ubuntu 20.04
-- PHP: 7.4.3
-- Web server: Nginx
-- Database server: mysql
-- etc.: Self hosted in LAN

### What you did
I have Passbolt self-hosted in LAN in HQ,not accessible from the internet.
Users access HQ via VPN to use pass bolt
I wanted to set up the ios app, but it gives an untrusted certificate error, and there doesn't seem to be a way to install the certificate in iOS.
What can be done to overcome this? Can I allow an untrusted cert or install it?

### What happened
Certificate error

### What you expected to happen
Working APP

**Comment by AnatomicJC** [comment]
Hi @Stefan-CPlanet ,

Github issues are for bugs, for assistance on passbolt community, you can create a new thread on https://community.passbolt.com/

To answer to your question, we created a FAQ about how to import self-signed certificates on iOS / Android: https://help.passbolt.com/faq/hosting/how-to-import-ssl-certificate-on-mobile

Best regards,
