### ISSUE TITLE
The URL is set to localhost instead of a domain name in setup link

### ISSUE THREAD

**Issue by grimvoodoo** [passbolt/passbolt_api#43]
Hi,
I have set up and install passbolt on a centos 7 VM, the install seems to have worked ok and I can create users, I created the first admin user and the response is this:

"The user has been registered with success, to complete the registration process follow the link : http://localhost/setup/install/58ac2c36-a7d4-4a75-9a20-0d22c0a810be/69c64f45-4501-4c82-aaa6-075fe6fe42ba"

Firstly I would expect this to be a https link and secondly to display either the hostname I have supplied or an IP. I have run grep -R looking for localhost in the config files and it is not set as any defaults that are not commented out. Under the app.php settings I have left "force-ssl" as true. I have also supplied hostnames where I believe I should so I would expect this to 

Does anyone have any ideas how I can change this?

I have pointed my root directory to /usr/share/nginx/html and I cannot see any files (other than index.html and 50x.html)created there, or any .htaccess. I am not sure where this setup directory is as I have searched with "find / -name setup" and turned up nothing.

**Comment by stripthis** [comment]
Hello,

Did you set the full base url in app/Config/core.php?
Configure::write('App.fullBaseUrl', 'http://example.com');

See. https://www.passbolt.com/help/tech/install#toc_configure

Cheers,

**Comment by grimvoodoo** [comment]
I have the following set:

//Configure::write('App.fullBaseUrl', 'https://bol-passbolt.<mydomain>.com');

bol-passbolt is the hostname.
I have put my actual domain name where i have put <mydomain>.

Could i put an IP here instead of a hostname?

**Comment by stripthis** [comment]
You need to remove the comment '//' for it to be taken into consideration. There is also a double dot. "..com". It should also work with an IP address even though we generally don't test it thouroughly with this kind of host setup.

**Comment by grimvoodoo** [comment]
Brilliant, removing the // sorted it (and removing the double dot.)
