### ISSUE TITLE
Install Translate 

### ISSUE THREAD

**Issue by eltonsjbv1** [passbolt/passbolt_api#438]
Hi,

Its possible install the translate pt_BR in passbolt ce?
I had downloaded file default.po and copy for /usr/share/php/passbolt/resourcers/pt_BR/default.po but not work for me.
I need clear cache in cake.php? 
How do this? 

Thanks

**Comment by cedricalfonsi** [comment]
Hello @eltonsjbv1, sorry for the delay.
The language is supported in beta since the [v3.11.0](https://help.passbolt.com/releases/ce/regular).
