### ISSUE TITLE
Healtcheck sometimes fails, on a retry it passes

### ISSUE THREAD

**Issue by TheReptile** [passbolt/passbolt_api#439]
* Passbolt Version: 3.6.0.
   * Platform and Target:
    -- Operating system: Ubuntu 20.04.04
    -- PHP: 7.4
    -- Web server: Nginx 1.18.0
    -- Database server: MariaDB 10.3.34

### What you did

I created a cron job to extract the health check. For monitoring purposes.
Basically this command: `./bin/cake passbolt healthcheck > /data/flusso/passbolt/output/passbolt_healthcheck.txt`

### What happened

Every now and then, there are errors in the output of the health-check. The errors only occur temporarily and when I retry, the errors are gone.
These are the 2 errors shown:
```
 [FAIL] The private key cannot be used to decrypt and verify a message
 [FAIL] The public key cannot be used to verify a signature.
```
Our Passbolt installation is working fine, so I assume the health-check is sometimes wrong.

### What you expected to happen

I would expect to the health-check to give consistent results.

**Comment by stripthis** [comment]
HI @TheReptile this checks rely on functionalities provided by php-gnupg. This could mean you have some issues with Gnupg on your system. It could come from either some clock issue (can you check the server time?) or entropy issue (on virtualized environment you can use haveged or rngtools).

**Comment by stripthis** [comment]
Can you check the entropy pool size when it fails? Using /proc/sys/kernel/random/entropy_avail I think.

I'm not sure which issue this could be, but would be very grateful if you can help us narrow it down. Can you check if there are some additional information on the Gnupg side (https://www.gnupg.org/documentation/manuals/gpgme/Debugging.html)?  Do you have any particular setup filesystem wise? Something that would prevent Gnupgp to read/write on the file system like concurent access or latency issues (network disk?).

Thank for your help

**Comment by stripthis** [comment]
Can you try to set 
```
GPGME_DEBUG=9:/home/user/mygpgme.log
```

And see if any information shows when the operation is failing?
