### ISSUE TITLE
Alow to add URL with special characters allowed in a uri

### ISSUE THREAD

**Issue by ftx** [passbolt/passbolt_api#45]
Hello,
I can't add special characters in a URL.

We need sometimes for exotic login links :)

https://github.com/passbolt/passbolt_api/pull/44

**Comment by stripthis** [comment]
Duplicate with: https://community.passbolt.com/t/as-a-logged-in-user-i-can-use-any-utf8-character-for-resource-name-descriptions-comments-etc/58/2
