### ISSUE TITLE
Locale en-UK common.json apostrophe character error

### ISSUE THREAD

**Issue by cordeosdev** [passbolt/passbolt_api#451]
In the en-UK local common.json file, several strings contain converted ascii/bin code for a smart apostrophe, probably imported from working on WORD or another program...

Should change to "it will" 

  "Once the comment is deleted, **itâ€™ll** be removed permanently and will not be recoverable.": "Once the comment is deleted, **itâ€™ll** be removed permanently and will not be recoverable.",
  "Once the password is deleted, **itâ€™ll** be removed permanently and will not be recoverable.": "Once the password is deleted, **itâ€™ll** be removed permanently and will not be recoverable.",
  "Once the tag is deleted, **itâ€™ll** be removed permanently and will not be recoverable.": "Once the tag is deleted, **itâ€™ll** be removed permanently and will not be recoverable.",

**Comment by cedricalfonsi** [comment]
Thank you for your report @cordeosdev.
Ticket reference: PB-21625

**Comment by ishanvyas22** [comment]
Hey @cordeosdev, this issue has been fixed & released with [v4.4.0](https://github.com/passbolt/passbolt_browser_extension/releases/tag/v4.4.0). Feel free to try it out and let us know if issue persist.
