### ISSUE TITLE
account creation fails with umlaut (diacritic) in security token

### ISSUE THREAD

**Issue by Reise-Reise** [passbolt/passbolt_api#455]
tested with Docker image passbolt/passbolt:3.7.3-1-ce and passbolt/passbolt:3.8.1-1-ce

steps to reproduce:
1. create a new user
1. set passphrase
1. save key file
1. for the security token:
   - pick any color
   - input 3 charcaters withe at least one Umlaut (äöüÄÖÜß)

results in the error message:

_Could not validate entity Account._
```
{
    "security_token": {
        "required": "The security_token is required."
    }
}
```

**Comment by cedricalfonsi** [comment]
The issue was fixed with 4.5.0.
The UI will mark the field as error and indicates what characters are authorized.
Thank you for your report.
