### ISSUE TITLE
HostGator login site - password field has mixed behaviors

### ISSUE THREAD

**Issue by garrettboone** [passbolt/passbolt_api#457]
## HostGator login site - password field has mixed behaviors
* Passbolt Version: 3.8.3/3.82
* Platform and Target:
-- Operating system: Ubuntu 20
-- PHP: 8.1
-- Web server: NGINX
-- Database server:  MariaDB 10.6

### What you did
1. Navigate to https://portal.hostgator.com/login
2. Email Address field shows in-form passbolt icon, and clicking the icon-then-resource populates the field correctly
3. Click Next, which opens up the password field
4. The password field is showing the in-form passbolt icon, but when clicking the icon-then-resource populates the field with a password that does not work (not sure what is pasted because it's hidden)
5. If I open the extension and click Use on this page - it also does not work.
6. However, if I copy the password and paste manually, it works.

### What happened
At some point the following error was registered in the extension:
![image](https://user-images.githubusercontent.com/47018474/209276641-85271457-94e1-4938-b44c-f23c07752a10.png)

There was also an extension message on one attempt to reproduce that said to paste and that the password could not be used on the page. I could not get the message to show again.

### What you expected to happen
I guess if the icon shows, that it would work.

Also, I am noticing the icon does not show in the fields unless I hover over the fields - is that correct behavior?

**Comment by cedricalfonsi** [comment]
Hello @garrettboone,

Thank you for this Christmas bug report 🎄 
Internal ticket reference: PB-21900

**Comment by garrettboone** [comment]
🎁Merry Christmas!

**Comment by Benj1er** [comment]
Hello @garrettboone,

This error mentioned can happen in some cases.
When the browser goes to another url, the application listens to an event to check if the port is still connected.
Unfortunately in some cases the port will be disconnected by the browser long after this event which leads to this error.
For the moment, to fix this a refresh of the page is necessary.

This is a known problem on our side and with the transition from MV2 to MV3, the browser events will be better managed and this type of error will be fixed.

**Comment by Benj1er** [comment]
Fixed with v4.1.2, don't hesitate to reopen it if the issue persists.
