### ISSUE TITLE
The requested URL /users/login was not found on this server.

### ISSUE THREAD

**Issue by tomghub** [passbolt/passbolt_api#46]
I did a new installation on debian jessie, i used /var/www/passbolt/app/webroot as document root

rewrite module is enabled and running in apache2

this runs without errors and creates mysql tables:
app/Console/cake install --no-admin

when i create admin like this:
app/Console/cake passbolt register_user -u me@domain.com -f myFirtsname -l myLastname -r admin

i get mail, but in the url it mentions "localhost",
when i correct localhost to the actual ip, it also cannot find the URL

If i go to server like https://ip-address it gives:
Not Found
The requested URL /users/login was not found on this server.

User www-data has read rights to passbolt folders and write rights to:
 /var/www/passbolt/app/tmp/

Please help, below are installed php modules:

 php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
gnupg
hash
iconv
intl
json
libxml
mbstring
memcached
mhash
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by stripthis** [comment]
You seem to have several problems. 

The localhost in the email seems to be linked to the fullbase url not being set. See https://github.com/passbolt/passbolt_api/issues/43

Please double check you have followed all the steps in the installation manual:
https://www.passbolt.com/help/tech/install

Cheers,

**Comment by tomghub** [comment]
The documentation is what i followed and because its lacking information in some areas i used this also:
http://www.admin-magazin.de/Das-Heft/2016/09/Passbolt-zum-Passwort-Management-in-Teams

i have also enabled debug but dont know where the log file is.

then i was able to run test.php and saw for example:
<span>PHPUnit_Framework_Error_Warning</span><div class='msg'>file_put_contents(/var/www/passbolt/app/Config/anonymous_statistics.php): failed to open stream: Permission denied</div>

The permission is:
-rw-r--r-- 1 root www-data   539 Feb 21 19:09 anonymous_statistics.php

Is there something wrong with permissions?

**Comment by kevinmuller** [comment]
Hi. 
I see that the file anonymous_statistics.php belongs to root user and www-data group. Only root has permissions to write in it though. So if you executed the installation script with the www-data user, it couldn't write in the file. 
From there 2 options:
- Change the file owner to www-data
- Execute the install script as root (but don't forget to check/set the file permissions properly after install)
Let me know if this helps.

**Comment by tomghub** [comment]
i did chmod 777 to everything, still not work and inside the file it does not look this needs to be writeable.

Made installation on a different box, just to see if something gone wrong, i get the exact same error about no users/login. What is calling this (path doesnt exist on filesystem) and how can i troubleshoot?

**Comment by tomghub** [comment]
when i changed owner to www-data i was able to run the tests. Not sure if this is related, controller tests failed with not enough memory

https://passbolt.intern.lan/test.php?case=AllControllers

Allowed memory size of 134217728 bytes exhausted (tried to allocate 48 bytes)

Error: An Internal Error Has Occurred.

Stack Trace

CORE/Cake/Error/ErrorHandler.php line 212 → ErrorHandler::handleFatalError(integer, string, string, integer)
[internal function] → ErrorHandler::handleError(integer, string, string, integer, array)
CORE/Cake/Core/App.php line 970 → call_user_func(string, integer, string, string, integer, array)
CORE/Cake/Core/App.php line 943 → App::_checkFatalError()
[internal function] → App::shutdown()

**Comment by tomghub** [comment]
https://passbolt.intern.lan/test.php?case=Controller%2FAuthController

FAILED
Failed asserting that exception of type "HttpException" is thrown.
Test case: AuthControllerTest::testNotAllowed()
Rerun only this test: AuthControllerTest::testNotAllowed()
Stack trace:
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/Constraint.php : 91
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/Assert.php : 2137
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 1048
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 838
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestResult.php : 648
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 783
/var/www/passbolt/lib/Cake/TestSuite/CakeTestCase.php : 82
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php : 779
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php : 749
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/TextUI/TestRunner.php : 350
/var/www/passbolt/lib/Cake/TestSuite/CakeTestRunner.php : 62
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteCommand.php : 98
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 259
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 96
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 113
/var/www/passbolt/app/webroot/test.php : 105

**Comment by tomghub** [comment]
https://passbolt.intern.lan/test.php?case=Controller%2FCakeErrorController

FAILED
Selenium.active should be unabled in config to run these tests
Failed asserting that false is true.
Test case: CakeErrorControllerTest::testSeleniumConfig()
Rerun only this test: CakeErrorControllerTest::testSeleniumConfig()
Stack trace:
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/Constraint.php : 91
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/Assert.php : 2137
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/Assert.php : 888
/var/www/passbolt/app/Test/Case/Controller/CakeErrorControllerTest.php : 119
CakeErrorControllerTest::testSeleniumConfig
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 988
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 838
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestResult.php : 648
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 783
/var/www/passbolt/lib/Cake/TestSuite/CakeTestCase.php : 82
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php : 779
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php : 749
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/TextUI/TestRunner.php : 350
/var/www/passbolt/lib/Cake/TestSuite/CakeTestRunner.php : 62
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteCommand.php : 98
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 259
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 96
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 113
/var/www/passbolt/app/webroot/test.php : 105
FAILED
Failed asserting that exception message 'Forbidden' contains '404 test not found'.
Test case: CakeErrorControllerTest::test404Json()
Rerun only this test: CakeErrorControllerTest::test404Json()
Stack trace:
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/Constraint.php : 91
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/Assert.php : 2137
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 1024
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 838
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestResult.php : 648
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 783
/var/www/passbolt/lib/Cake/TestSuite/CakeTestCase.php : 82
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php : 779
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php : 749
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/TextUI/TestRunner.php : 350
/var/www/passbolt/lib/Cake/TestSuite/CakeTestRunner.php : 62
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteCommand.php : 98
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 259
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 96
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 113
/var/www/passbolt/app/webroot/test.php : 105
FAILED
Failed asserting that exception message 'Forbidden' contains 'Not Found'.
Test case: CakeErrorControllerTest::test404Json2()
Rerun only this test: CakeErrorControllerTest::test404Json2()
Stack trace:
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/Constraint.php : 91
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/Assert.php : 2137
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 1024
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 838
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestResult.php : 648
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 783
/var/www/passbolt/lib/Cake/TestSuite/CakeTestCase.php : 82
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php : 779
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php : 749
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/TextUI/TestRunner.php : 350
/var/www/passbolt/lib/Cake/TestSuite/CakeTestRunner.php : 62
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteCommand.php : 98
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 259
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 96
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 113
/var/www/passbolt/app/webroot/test.php : 105
FAILED
Failed asserting that exception message 'Forbidden' contains '404 test not found'.
Test case: CakeErrorControllerTest::test404Page()
Rerun only this test: CakeErrorControllerTest::test404Page()
Stack trace:
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/Constraint.php : 91
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/Assert.php : 2137
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 1024
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 838
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestResult.php : 648
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 783
/var/www/passbolt/lib/Cake/TestSuite/CakeTestCase.php : 82
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php : 779
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php : 749
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/TextUI/TestRunner.php : 350
/var/www/passbolt/lib/Cake/TestSuite/CakeTestRunner.php : 62
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteCommand.php : 98
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 259
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 96
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 113
/var/www/passbolt/app/webroot/test.php : 105
FAILED
Failed asserting that exception message 'Forbidden' contains 'Not Found'.
Test case: CakeErrorControllerTest::test404Page2()
Rerun only this test: CakeErrorControllerTest::test404Page2()
Stack trace:
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/Constraint.php : 91
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/Assert.php : 2137
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 1024
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 838
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestResult.php : 648
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php : 783
/var/www/passbolt/lib/Cake/TestSuite/CakeTestCase.php : 82
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php : 779
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/Framework/TestSuite.php : 749
/var/www/passbolt/Vendor/phpunit/phpunit/PHPUnit/TextUI/TestRunner.php : 350
/var/www/passbolt/lib/Cake/TestSuite/CakeTestRunner.php : 62
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteCommand.php : 98
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 259
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 96
/var/www/passbolt/lib/Cake/TestSuite/CakeTestSuiteDispatcher.php : 113
/var/www/passbolt/app/webroot/test.php : 105

**Comment by cedricalfonsi** [comment]
Hello @tomghub,

Did you check the passbolt healhcheck yet ? if not, it could help you to ensure first that your passbolt is fine tuned.

1. Enable the debug mode. In the file app/Config/core.php, set the debug variable to 1 (don't forget to revert it to 0).
2. Go to the healthcheck page : https://DOMAIN_NAME/healthcheck

Tell us what you got,
Cheers

Cédric

**Comment by tomghub** [comment]
it also cannot find healthcheck, the log in app/tmp is empty.

is something required in apache config other then a2enmod rewrite ssl ? I just put DocumentRoot /var/www/passbolt/app/webroot into the default ssl Virtualhost file (default-ssl-conf).

**Comment by stripthis** [comment]
Actually your Document Root should be /var/www/passbolt
Can you also make sure you virtual host contains the following:
```

<Directory /var/www/>
     Options FollowSymLinks
     AllowOverride All
     Require all granted
</Directory>

```
see. https://book.cakephp.org/2.0/en/installation/url-rewriting.html#apache-and-mod-rewrite-and-htaccess

**Comment by tomghub** [comment]
i can access the healthcheck page now , only problems:
Registration is closed, only administrators can add users.
There is no admin user. Create one.

however it says now access denied on the main page. Why its trying to go to /var/www/html/users and Port 80?

Browser:
Forbidden
You don't have permission to access /users/login on this server.
Apache/2.4.10 (Debian) Server at passbolt.intern.lan Port 80

Log:
[Mon Feb 27 12:10:03.856408 2017] [ssl:info] [pid 7704] [client 192.168.5.172:57426] AH01964: Connection to child 1 established (server passbolt.intern.lan:443)
[Mon Feb 27 12:10:03.857289 2017] [ssl:debug] [pid 7704] ssl_engine_kernel.c(1908): [client 192.168.5.172:57426] AH02043: SSL virtual host for servername passbolt.intern.lan found
[Mon Feb 27 12:10:03.874396 2017] [ssl:info] [pid 7705] [client 192.168.5.172:57427] AH01964: Connection to child 2 established (server passbolt.intern.lan:443)
[Mon Feb 27 12:10:03.875229 2017] [ssl:debug] [pid 7705] ssl_engine_kernel.c(1908): [client 192.168.5.172:57427] AH02043: SSL virtual host for servername passbolt.intern.lan found
[Mon Feb 27 12:10:03.878215 2017] [ssl:debug] [pid 7704] ssl_engine_kernel.c(1841): [client 192.168.5.172:57426] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
[Mon Feb 27 12:10:03.878278 2017] [ssl:info] [pid 7704] (70014)End of file found: [client 192.168.5.172:57426] AH01991: SSL input filter read failed.
[Mon Feb 27 12:10:03.878314 2017] [ssl:debug] [pid 7704] ssl_engine_io.c(1003): [client 192.168.5.172:57426] AH02001: Connection closed to child 1 with standard shutdown (server passbolt.intern.lan:443)
[Mon Feb 27 12:10:03.888384 2017] [ssl:debug] [pid 7705] ssl_engine_kernel.c(1841): [client 192.168.5.172:57427] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
[Mon Feb 27 12:10:03.888626 2017] [ssl:debug] [pid 7705] ssl_engine_kernel.c(243): [client 192.168.5.172:57427] AH02034: Initial (No.1) HTTPS request received for child 2 (server passbolt.intern.lan:443)
[Mon Feb 27 12:10:03.888965 2017] [authz_core:debug] [pid 7705] mod_authz_core.c(809): [client 192.168.5.172:57427] AH01626: authorization result of Require all granted: granted
[Mon Feb 27 12:10:03.888985 2017] [authz_core:debug] [pid 7705] mod_authz_core.c(809): [client 192.168.5.172:57427] AH01626: authorization result of <RequireAny>: granted
[Mon Feb 27 12:10:03.889349 2017] [authz_core:debug] [pid 7705] mod_authz_core.c(809): [client 192.168.5.172:57427] AH01626: authorization result of Require all granted: granted
[Mon Feb 27 12:10:03.889365 2017] [authz_core:debug] [pid 7705] mod_authz_core.c(809): [client 192.168.5.172:57427] AH01626: authorization result of <RequireAny>: granted
[Mon Feb 27 12:10:03.889492 2017] [authz_core:debug] [pid 7705] mod_authz_core.c(809): [client 192.168.5.172:57427] AH01626: authorization result of Require all granted: granted
[Mon Feb 27 12:10:03.889503 2017] [authz_core:debug] [pid 7705] mod_authz_core.c(809): [client 192.168.5.172:57427] AH01626: authorization result of <RequireAny>: granted
[Mon Feb 27 12:10:03.889724 2017] [authz_core:debug] [pid 7705] mod_authz_core.c(809): [client 192.168.5.172:57427] AH01626: authorization result of Require all granted: granted
[Mon Feb 27 12:10:03.889736 2017] [authz_core:debug] [pid 7705] mod_authz_core.c(809): [client 192.168.5.172:57427] AH01626: authorization result of <RequireAny>: granted
[Mon Feb 27 12:10:04.203189 2017] [authz_core:debug] [pid 7703] mod_authz_core.c(809): [client 192.168.5.172:57428] AH01626: authorization result of Require all denied: denied
[Mon Feb 27 12:10:04.203312 2017] [authz_core:debug] [pid 7703] mod_authz_core.c(809): [client 192.168.5.172:57428] AH01626: authorization result of <RequireAny>: denied
[Mon Feb 27 12:10:04.203318 2017] [authz_core:error] [pid 7703] [client 192.168.5.172:57428] AH01630: client denied by server configuration: /var/www/html/users
[Mon Feb 27 12:10:09.204356 2017] [ssl:info] [pid 7705] (70007)The timeout specified has expired: [client 192.168.5.172:57427] AH01991: SSL input filter read failed.
[Mon Feb 27 12:10:09.204464 2017] [ssl:debug] [pid 7705] ssl_engine_io.c(1003): [client 192.168.5.172:57427] AH02001: Connection closed to child 2 with standard shutdown (server passbolt.intern.lan:443)

apache2.conf:
<Directory />
        Options FollowSymLinks
        AllowOverride None
        Require all denied
</Directory>

default-ssl.conf:
<IfModule mod_ssl.c>
        <VirtualHost _default_:443>
                DocumentRoot /var/www/passbolt/
                <Directory /var/www/>
                Options FollowSymLinks
                AllowOverride All
                Require all granted
                </Directory>

 <FilesMatch "\.(cgi|shtml|phtml|php)$">
                                SSLOptions +StdEnvVars
                </FilesMatch>
                <Directory /usr/lib/cgi-bin>
                                SSLOptions +StdEnvVars
                </Directory>
BrowserMatch "MSIE [2-6]" \
                                nokeepalive ssl-unclean-shutdown \
                                downgrade-1.0 force-response-1.0
                # MSIE 7 and newer should be able to use keepalive
                BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

        </VirtualHost>
</IfModule>

**Comment by kevinmuller** [comment]
Hi,
If you are redirected to http instead of https, it probably comes from the setting App.fullBaseUrl in app/Config/core.php (around line 126). Can you check that your App.fullBaseUrl starts with "https" in the core.php config file ?

Regarding the admin user creation, when you install passbolt the install script should ask you to create one. Did you run the command below ?
`app/Console/cake install`

In any case, you can always create admin users from the command line later by using:
`app/Console/cake passbolt register_user -u me@domain.com -f myFirtsname -l myLastname -r admin`

You can at any time refer to the online documentation which contains everything that is needed: https://www.passbolt.com/help/tech/install

Cheers,
Kevin

**Comment by tomghub** [comment]
you were right about core.php, that was my mistake.
I read documentation multiple times, but it doesnt cover all areas needed.

Now i get this on main page:
Table users for model User was not found in datasource default.

Error: An Internal Error Has Occurred.

Stack Trace

CORE/Cake/Model/Model.php line 3667 → Model->setSource(string)
CORE/Cake/Model/Model.php line 3038 → Model->getDataSource()
CORE/Cake/Model/Model.php line 3010 → Model->_readDataSource(string, array)
APP/Model/User.php line 401 → Model->find(string, array)
APP/Model/User.php line 359 → User::setActive(string)
APP/Model/ControllerLog.php line 176 → User::get()
APP/Controller/AuthController.php line 45 → ControllerLog::write(string, CakeRequest, string, string)
[internal function] → AuthController->login()
CORE/Cake/Controller/Controller.php line 491 → ReflectionMethod->invokeArgs(AuthController, array)
CORE/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction(CakeRequest)
CORE/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke(AuthController, CakeRequest)
APP/webroot/index.php line 111 → Dispatcher->dispatch(CakeRequest, CakeResponse)

SplFileInfo::openFile(/var/www/passbolt/app/tmp/cache/models/passbolt_cake_model_default_passbolt_users): failed to open stream: Permission denied [<b>CORE/Cake/Cache/Engine/FileEngine.php

**Comment by stripthis** [comment]
Hi @tomghub, 

You are right the documentation does not cover everything, mostly because there are variation in terms of file permissions, etc. 

The last error look like www-data cannot write in the tmp cache/models directory. Maybe run a
`
chown -R www-data:www-data app/tmp/
`

**Comment by tomghub** [comment]
i did the chown and the Fileengine.php permission error went away, but was still complaining about:
Table users for model User was not found in datasource default.
then i did again as root (because i did not see any table users in passbolt db): app/Console/cake install --no-admin
now i can access the webpage, i guess its working now as intended

**Comment by stripthis** [comment]
We just published a step by step guide you can refer to if you still have issues:
https://medium.com/passbolt/passbolt-on-debian-8-71-from-scratch-4438dad18908#.34t6903cu
