### ISSUE TITLE
Release 3.10.0 self-registration doc link broken

### ISSUE THREAD

**Issue by doegox** [passbolt/passbolt_api#470]
Hello

The link to doc from the release 3.10.0 self-registration admin page is broken:
https://mydomain/app/administration/self-registration =>
https://help.passbolt.com/configure/self-registration

I wanted to check if a list of domains could be provided and what would be the syntax to do so, as the page mentions "Email domain safe list". Documenting how to provide a list (comma separated?) on the admin page itself would be welcome too.

**Comment by cedricalfonsi** [comment]
Hello @doegox,

Thank you for your report.
We'll assess and fix this issue with the next release.

**Comment by cedricalfonsi** [comment]
You can manage the whitelisted domains via the "self registration" administration page (https://passbolt-domain/app/administration/self-registration).

When the admin activates user self registration, the Email domain safe list appears with a field to fill in a domain name. This field is pre-populated with the company's domain if this one is not a public domain, such as gmail by instance. From there, administrators can whitelist as many domains as they want, each line corresponding to a whitelisted domain.

**Comment by doegox** [comment]
oops I didn't notice the "Add" button to add new lines, than you for the explanation!
Still remains that the page https://help.passbolt.com/configure/self-registration does not exist ;)

**Comment by cedricalfonsi** [comment]
A new documentation page was published by @claytontstevenson.

Thanks again for your report @doegox
