### ISSUE TITLE
Account creation fails when using "M#2" as anti-phishing token. New cloud deployment.

### ISSUE THREAD

**Issue by malteish** [passbolt/passbolt_api#471]
### What you did
- created a business test deployment in the passbolt cloud
- created new user in frontend
- new user received email, started onboarding process
- new user chose "M#2" as anti-phising token
- onboarding failed with some error like "could not create whatever"

### What happened
Could not finish onboarding when using # in anti-phising token. Could finish when using other characters.

### What you expected to happen
I expect one of:
1. Prohibit use of special characters in this token, and tell users about it when checking their input
2. Allow use of special characters in this token without failing later in the process

**Comment by Benj1er** [comment]
Hello @malteish,

At the moment the security token only accepts alphanumeric characters, numbers and "-" and "_".
A ticket has been created to resolve this.
Thank you for reporting this issue.

Best regards

**Comment by cedricalfonsi** [comment]
Issue similar was fixed with v4.5.0 https://github.com/passbolt/passbolt_api/issues/455 
Thank you for your report.
