### ISSUE TITLE
Healthcheck cannot pass JWT Authentication check

### ISSUE THREAD

**Issue by yderi** [passbolt/passbolt_api#473]
Hello all

health check command
`sudo -H -u www-data bash -c "/var/www/passbolt/bin/cake passbolt healthcheck"`
cannot pass JWT Authentication check
```
 JWT Authentication

 [PASS] The JWT Authentication plugin is enabled
 [FAIL] The /var/www/passbolt/config/jwt/ directory should not be writable.
 [HELP] You can try:
 [HELP] sudo chown -Rf root:www-data /var/www/passbolt/config/jwt/
 [HELP] sudo chmod 750 /var/www/passbolt/config/jwt/
 [HELP] sudo chmod 640 /var/www/passbolt/config/jwt/jwt.key
 [HELP] sudo chmod 640 /var/www/passbolt/config/jwt/jwt.pem
 [PASS] A valid JWT key pair was found

```
Already tried to perform recommendation HELP, unfortunately still the same error.

Here is ll command output
` ll /var/www/passbolt/config/jwt/`
```
total 16
drwxr-x--- 2 root            www-data 4096 Jun 23  2022 ./
dr-xr-x--- 7 hp              www-data 4096 Mar  7 15:48 ../
-rw-r----- 1 root            www-data 3272 Jun 21  2022 jwt.key
-rw-r----- 1 root            www-data  800 Jun 21  2022 jwt.pem
```
Any help appreciated

**Comment by nourcy** [comment]
I see a hp user here maybe a 
`chown -Rf root:www-data /var/www/passbolt/config/`
will help.

I also suggest to avoid making issue here and use the community forum instead: https://community.passbolt.com/c/installation-issues/5

Cheers

**Comment by yderi** [comment]
> chown -Rf root:www-data /var/www/passbolt/config/

Did not help, will continue with problem on community site.

Thank you all

**Comment by yderi** [comment]
Here is what helped to fix the problem in my case:

`sudo chown -R www-data:www-data /var/www/passbolt/config/jwt/`

Now it passes the JWT Authentication permissions check.
