### ISSUE TITLE
UI Bug: Hide Info Button if no passwords are present

### ISSUE THREAD

**Issue by LordSimal** [passbolt/passbolt_api#474]
## Hide Info Button if no passwords are present
* Passbolt Version: v3.11.1 (b80a660651)
* Platform and Target:
-- Operating system: Debian 11 Bullseye
-- PHP: 8.1.16 via FPM
-- Web server: NGINX 1.18.0
-- Database server: MariaDB 10.11.2

### What you did
Freshly installed Passbolt and just played around with the UI till I noticed a (for me) weird info button at the top right which doesn't do anything at first hand.

### What happened
When having no passwords present in Passbolt one can interact with the info button at the top right of the Password overview page since it toggles vissibly between "on" and "off" but nothing else is happening.

![2023-03-14_21-14-38 (1)](https://user-images.githubusercontent.com/9105243/225125869-98663f6a-5620-4ead-9f6f-b1186757b2e9.gif)

### What you expected to happen
The info button should be disabled or removed at all if no passwords are present since it is only useable when at least 1 password entry is present.

**Comment by Benj1er** [comment]
Hello @LordSimal,

Thank you for reporting this problem. A ticket has been created under the reference PB-24587.

Best regards
