### ISSUE TITLE
3.11.1 should bump version in config/version.php

### ISSUE THREAD

**Issue by blu006** [passbolt/passbolt_api#475]
## Version not updated to `3.11.1`, still shows `3.11.0`
* Passbolt Version: `3.11.1`
* Platform and Target:
-- Operating system: Docker image running on a Debian host
-- PHP: included with the docker 7.4.33
-- Web server: included with docker php-fpm 
-- Database server: mariadb 10.3

### What you did / What happened 
Downloaded the `latest-ce` image using `docker pull passbolt/passbolt:latest-ce`

checked the docker using the included healthcheck to find this:

    [FAIL] This installation is not up to date. Currently using 3.11.0 and it should be v3.11.1.

### What you expected to happen
The mentioned file [config/version.php](../blob/master/config/version.php) should be updated to have the correct version string.

**Comment by stripthis** [comment]
Apologies for the missing version bump. This should be fixed with v3.12 ;)
