### ISSUE TITLE
Help With Local SetUp

### ISSUE THREAD

**Issue by Hussainzz** [passbolt/passbolt_api#477]
#local setup

i understand that the issues are only bug report. 

![Screenshot 2023-03-18 at 8 21 53 AM](https://user-images.githubusercontent.com/13753141/226080536-39cf36f5-bfc5-48aa-8c3d-a7348b4eb3f3.png)

i generated a new key pair, no passPhrase no expiration. And tried importing, what am I doing wrong here can someone help me with my local setup
```
gpg --full-generate-key
(1) RSA and RSA

``

**Comment by garrettboone** [comment]
`what am I doing wrong here`

1) posting in github when it's not a bug
2) not posting in the forum when you need install help community.passbolt.com
3)  not using the help site resources like how to rotate your server keys https://help.passbolt.com/faq/hosting/how-to-rotate-server-gpg-keys or how to create user key from scratch when installing from source https://help.passbolt.com/hosting/install/ce/from-source.html

More help is in the forum, and when you post there please follow the directions as requested, thanks.
