### ISSUE TITLE
UI Bug: Password selection persists after moving passwords

### ISSUE THREAD

**Issue by Monachino1** [passbolt/passbolt_api#479]
## UI Bug: Password selection persists after moving passwords.

* Passbolt Version: 3.12.0
* Platform and Target:
-- Operating system: Ubuntu 22.04.2 LTS
-- PHP: 8.1.2-1ubuntu2.11
-- Web server:  nginx/1.18.0 (Ubuntu)
-- Database server: 8.0.32-0ubuntu0.22.04.2 (Ubuntu)

### What you did
Create 3 folders named "Folder1", "Folder2", "Folder3"
Create 3 passwords in "Folder1", named "Account1", "Account2", "Account3" 
Using the checkboxes select "Account1" and "Account2"  drag and drop these to "Folder2"
Do not refresh the view or change folder. 
While still in "Folder1" select "Account3" and move it to "Folder3".

### What happened
The previously selected passwords "Account1" and "Account2" are also moved into Folder3 when only "Account3" is selected.
All 3 accounts now exist in the "Folder3" folder.

![Passbolt-Moving](https://user-images.githubusercontent.com/107940343/230398579-a8cb820d-301a-4c24-a12f-580504569cb9.gif)

If instead of selecting "Account3" and moving it to "Folder3" I selected "Delete" then "Account1" and "Account2" would be deleted also.

![Passbolt-Deleting](https://user-images.githubusercontent.com/107940343/230398570-f2d9647c-14da-427e-894c-5d5200ee4248.gif)

### What you expected to happen
After following the above process, "Account1" and "Account2" should exist in "Folder2" and "Account3" should exist in "Folder3"
When selected items are moved to a folder, and the view remains the same, clear the selected items.

**Comment by Benj1er** [comment]
Hello @Monachino1,

Thanks for the bug report, a ticket has been created under the reference PB-24260.
This issue will be resolved after the next release.

Best regards

**Comment by Benj1er** [comment]
Fixed with v4.0.0, don't hesitate to reopen it if the issue persists.
