### ISSUE TITLE
Admin's dashboard user's MFA shows wrong status

### ISSUE THREAD

**Issue by shahesam84** [passbolt/passbolt_api#483]
##IMPORTANT: PLEASE READ

Only use github issues for bugs.

We will be more than happy to help you on the community forum for:
- feature requests: https://community.passbolt.com/c/backlog
- issues related to installations: https://community.passbolt.com/c/installation-issues
- general questions: https://community.passbolt.com/c/uncategorized

This is only a issue tracker for bugs related to the Passbolt API.
For passbolt docker, browser extension, command line interface, in short any other bugs 
please use [the other relevant repositories](https://github.com/passbolt).

If you are certain this is a new API bug please use the following format:

## ISSUE NAME
* Passbolt Version: CE 4.0.0.
* Platform and Target:
-- Operating system: Ubuntu
-- PHP: 7.4.3
-- Web server: Nginx 1.18.0
-- Database server: mysql 8.0.33-0ubuntu0.20.04.2
-- etc.: OTHER RELEVANT PLATFORM INFO

### What you did
Upgraded from V3.12.0 to 4.0.0.

### What happened
The user's MFA status shows disabled for all users although it is enabled and activated.
![Screenshot 2023-05-18 144007](https://github.com/passbolt/passbolt_api/assets/28066480/8727d2ac-c971-47ba-9a2c-45688553cd64)

### What you expected to happen
To show the correct MFA activation status.

**Comment by ishanvyas22** [comment]
Hey @shahesam84, we have already identified this issue (internal ticket for reference: PB-24639) and published a fix with Browser Extension version 4.0.1. Currently the extension is in review on the chrome web store, we will notify [here](https://community.passbolt.com/t/incorrect-mfa-status-on-user-accounts-expected-fix-in-extension-4-0-1/6793/5) as soon as it is available.

**Comment by ishanvyas22** [comment]
Closing this as fix is released with v4.0.1.
