### ISSUE TITLE
Passbolt crashes and users cannot log back in (after upgrading to v4)

### ISSUE THREAD

**Issue by shkarface** [passbolt/passbolt_api#485]
## API crashes after some time (after upgrading to Creep)
* Passbolt Version: 4.0.2-2-ce
* Platform and Target:
-- Operating system: Ubuntu 20.04 (Docker version 24.0.2, build cb74dfc)
-- PHP: Same as in the passbolt docker image
-- Web server: Same as in the passbolt docker image
-- Database server: mariadb v10.11

### What you did
Upgraded passbolt from v3.12.0 to 4.0.2

### What happened
Every now and then, all the users will be logged out, the API crashes.
And when users try to log back in, it says that the key does not match.

![image](https://github.com/passbolt/passbolt_api/assets/1114849/9668a89d-3012-4ea6-b732-5d9bf0c9b27c)

### What you expected to happen
Expect passbolt to work.

**Comment by shkarface** [comment]
After restarting the server a few times, all users that had issues logging in before (Error key not found) are now able to login

**Comment by stripthis** [comment]
@shkarface can you open an issue on the community forum, as this seems to be an issue specific with your install and not a bug.

**Comment by stripthis** [comment]
https://community.passbolt.com/

**Comment by shkarface** [comment]
Just to clarify, we are on a docker installation
