### ISSUE TITLE
Recovery email not send for some users.

### ISSUE THREAD

**Issue by mercy-thuyle** [passbolt/passbolt_api#486]
## ISSUE NAME
* Passbolt Version: 4.0.0
* Platform and Target:
-- Operating system: Ubuntu 20.04
-- PHP: 8.1
-- Web server: nginx/1.18.0
-- Database server: Postgresql/14.5

### What you did
I did 2 things.
1. I want to login account in an another browser (from FireFox to Edge/Chrome). I try to recovey my account by mail.
2. My friend help by recovery their account like me, and they receive email and recovery successfully.
3. I didn't received any mail even in spam so I run command line in server `sudo -H -u www-data bash -c "/var/www/passbolt/bin/cake passbolt send_test_email --recipient=thuyldx@unicloudfrom.com.vn"`
4. The config of mail recovery like this 
![image](https://github.com/passbolt/passbolt_api/assets/62128227/4b439a29-0a21-4f88-bd14-7425da4cd6ea)

### What happened
For the first action: It said that waiting for mail recovery but there are any mail sent, even in spam.
For the third action: The output in below
`sudo -H -u www-data bash -c "/var/www/passbolt/bin/cake passbolt send_test_email --recipient=thuyldx@unicloudfrom.com.vn"`

```
     ____                  __          ____  
    / __ \____  _____ ____/ /_  ____  / / /_ 
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/ 
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /    
 /_/    \__,_/____/____/_.___/\____/_/\__/   


 Open source password manager for teams
-------------------------------------------------------------------------------
 Debug email shell
-------------------------------------------------------------------------------
Email configuration
-------------------------------------------------------------------------------
Host: email-smtp.us-east-1.amazonaws.com
Port: 587
Username: AKIA4ACCESSKEYHERE
Password: *********
TLS: true
Sending email from: Passbolt <passbolt-no-reply@unicloudfrom.com.vn>
Sending email to: thuyldx@unicloudfrom.com.vn
-------------------------------------------------------------------------------
Trace
[220] email-smtp.amazonaws.com ESMTP SimpleEmailService-d-188QI6AE0 zjDzhfGNgJgcKrT3PzCE
 EHLO localhost
[250] email-smtp.amazonaws.com
[250] 8BITMIME
[250] STARTTLS
[250] AUTH PLAIN LOGIN
[250] Ok
 STARTTLS
[220] Ready to start TLS
 EHLO localhost
[250] email-smtp.amazonaws.com
[250] 8BITMIME
[250] STARTTLS
[250] AUTH PLAIN LOGIN
[250] Ok
 AUTH PLAIN AEFLSUE0UDRTSURCR1pHWjNGNzdZAEJKSUtoMU9PVm9iRUJUZWxvVjdPS20zVkwyb01tVzhDaytpMzluNzVNVmtJ
[235] Authentication successful.
 MAIL FROM:<passbolt-no-reply@unicloudfrom.com.vn>
[250] Ok
 RCPT TO:<thuyldx@unicloudfrom.com.vn>
[250] Ok
 DATA
[354] End data with <CR><LF>.<CR><LF>
 From: Passbolt <passbolt-no-reply@unicloudfrom.com.vn>
To: thuyldx@unicloudfrom.com.vn
Date: Tue, 11 Jul 2023 05:17:46 +0000
Message-ID: <96b89c70783f424c98dfe47a82f4a5ce@ip-10-5-2-108>
Subject: Passbolt test email
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Congratulations!
If you receive this email, it means that your passbolt smtp configuration is working fine.




.
[250] Ok 0100018943625917-c4d704e9-cf2a-4712-bcdf-917e879dd477-000000
 QUIT
The message has been successfully sent!
```

### What you expected to happen
Mail should send to my address mail.

**Comment by stripthis** [comment]
Sorry for the late reply, for installation issue please open an issue on the community forum. Github is reserved for bugs.

https://help.passbolt.com/faq/hosting/why-email-not-sent
https://community.passbolt.com/
