### ISSUE TITLE
When will Chinese be supported?

### ISSUE THREAD

**Issue by tengdagg** [passbolt/passbolt_api#489]

**Comment by nourcy** [comment]
Hi,

Please feel free to help: https://passbolt.crowdin.com/passbolt/zh-CN

Best,
Max

**Comment by tengdagg** [comment]
> 你好
> 
> 请随时提供帮助：https://passbolt.crowdin.com/passbolt/zh-CN
> 
> 最佳，最大

I followed this attempt to add Chinese language packs, adding my translated common.json in /usr/share/php/passbolt/webroot/locales//usr/share/php/passbolt/webroot/locales/zh-CN, and adding my translation of common.json in /usr/ share/php/passbolt/resources/locales/zh_CN, and then I restarted my service, and when I access the administration page, it displays Chinese normally, but when I access users and password, it gets stuck. Then I opened the browser check and saw
![image](https://github.com/passbolt/passbolt_api/assets/66817449/9a83a76b-92b9-45b6-a587-224c82e8e86a)
Then I tried to modify the language pack of my plugin, but after I did that, it said that my plugin is corrupted and it doesn't work properly.
