### ISSUE TITLE
Installation no Connection to MySQL

### ISSUE THREAD

**Issue by c0fe** [passbolt/passbolt_api#49]
**Distro:** Debian 8
**SQL DB:** MariaDB 10.2
**PHP:** 5
**HTTP Server:** Apache (v2)

**The error I get:**

https://hastebin.com/idevoxocaj.scala

**database.php file** (this is on a dummy server so not worried about credentials)

https://hastebin.com/focamefuhu.php

**PHP Packages I installed:**

- php5-common
- libapache2-mod-php5
- php5-cli
- php5-common
- php5-gd
- php5-mcrypt
- php5-dev
- php-pear
- php5-fpm
- php5-mysql
- php5-gnupg

The files have cloned into the /var/www/html directory

So what am I doing wrong?

**Comment by cedricalfonsi** [comment]
Hello Cofe,

Looks like cakephp doesn't find your database configuration, or your mysql is not setup with this settings. Did you copy your app/Config/database.default.php into app/Config/database.php ?

Please double check you have followed all the steps in the installation manual:
https://www.passbolt.com/help/tech/install

Best regards

**Comment by c0fe** [comment]
Yes I used the cp command to make the copy and then just make the changes using nano text editor. I have double checked to make sure mariadb is running and no errors and the database specified is there. I can even give root shell access (again isolated dummy server)

**Comment by cedricalfonsi** [comment]
I was a bit dissipated this morning, I looked closer to the file you posted on hastebin, and you have lot's of errors.

At the first line : `Installation failed.`. Do you know what failed ?
And the following lines show us that mysql cannot be loaded by php.
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/mysql.so' - libmysqlclient.so.18: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/mysqli.so' - libmysqlclient.so.18: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/pdo_mysql.so' - libmysqlclient.so.18: cannot open shared object file: No such file or directory in Unknown on line 0`

How did you install the package php5-mysql? Is your OS running on an exotic setup ?

**Comment by c0fe** [comment]
Nothing out the ordinary. I installed it using this command:

apt-get install php5-mysql that was it.

The install is a fresh install bare bones.

**Comment by c0fe** [comment]
Is there any commands that I can run to provide more details?

I can try a CentOS install.

**Comment by stripthis** [comment]
hi @c0fe apparently using php5-mysql driver with mariadb does throw warnings. It seems that it's recommended to use php5-mysqlnd now. I'm currently checking installing passbolt on a fresh install with debian 8.71 apache/php/mariadb, will post a step by step guide for your convenience a little bit later.

**Comment by c0fe** [comment]
Ok I will do another fresh debian 8 install.

Any recommendation for CentOS apache installs as to what to use?

**Comment by c0fe** [comment]
Ok so I have a fresh install of Debian 8 and installed everything using these commands:

`apt-get install software-properties-common -y && apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db && add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://mirrors.accretive-networks.net/mariadb/repo/10.2/debian jessie main' && cd /tmp && mkdir -p /opt/passbolt/ && apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y && apt-get install apache2 -y && apt-get install mariadb-server -y && mysql_secure_installation && mysql -u root -p && apt-get install php5-common php5-mysqlnd libapache2-mod-php5 php5-cli php-pear php5-gnupg php5-gd php5-mcrypt php5-dev -y && service apache2 restart && apt-get install rng-tools -y && nano /etc/default/rng-tools && service rng-tools start && gpg --gen-key && apt-get install git -y && rm -rf /var/www/html/index.html && gpg --armor --export-secret-keys general@naspos.com > /opt/passbolt/serverkey.private.asc && gpg --armor --export general@naspos.com > /opt/passbolt/serverkey.asc && cp -a /root/.gnupg/ /opt/passbolt/ && chown -R www-data.www-data /opt/passbolt/.gnupg && chown -R www-data.www-data /opt/passbolt/* && cd /var/www/html && git clone https://github.com/passbolt/passbolt.git . && chmod +w -R /var/www/html/app/tmp && chmod +w /var/www/html/app/webroot/img/public && chown -R www-data.www-data /var/www/html/ && cp app/Config/core.php.default app/Config/core.php && cp app/Config/database.php.default app/Config/database.php && cp app/Config/app.php.default app/Config/app.php && gpg --list-keys --fingerprint && a2enmod ssl && a2ensite default-ssl && service apache2 reload && service apache2 restart`

**But now I get this error:**
http://i.imgur.com/RJCNldG.png

**This is my directory:**
http://i.imgur.com/ZlpWA8V.png

What am I doing wrong?

**Comment by stripthis** [comment]
There might be multiple issues (since I cannot see the content of the config files) but off the bat it my best guess is that you don't have mod_rewrite enabled on apache.
https://book.cakephp.org/2.0/en/installation/url-rewriting.html#apache-and-mod-rewrite-and-htaccess

**Comment by c0fe** [comment]
I did run this command: a2enmod rewrite unless there is something else left to setup?

**Comment by stripthis** [comment]
Can you make sure the following is in your virtual host config file?
`<Directory /var/www/>
     Options FollowSymLinks
     AllowOverride All
     Require all granted
</Directory>
`

**Comment by c0fe** [comment]
But passbolt is installed in /var/www/html

there is no passbolt directory at all.

**Comment by stripthis** [comment]
Sure, make it /var/www/html/passbolt whatever is your setup.

**Comment by c0fe** [comment]
I have made sure, I can provide a copy of the config files for verification. I will do that a bit later today when in front of the machine.

**Comment by stripthis** [comment]
If you are still experiencing issues please have a look at this step by step guide: 
https://medium.com/passbolt/passbolt-on-debian-8-71-from-scratch-4438dad18908#.34t6903cu
