### ISSUE TITLE
Error "A route matching "/..." could not be found"

### ISSUE THREAD

**Issue by RandomUser0815** [passbolt/passbolt_api#495]
## Error "A route matching "/..." could not be found"
* Passbolt Version: 4.2.0.1 (CE)
* Platform and Target:   x86_64
-- Operating system: Ubnutu VERSION="22.04.3 LTS (Jammy Jellyfish)"
-- PHP: 8.1
-- Web server: nginx 1.18.0
-- Database server: mysql, 8.0.34-0ubuntu0.22.04.1

### What you did
Did upgrade from Passbolt 4.1.2-1 to 4.2.0.1 CE

### What happened

/var/log/passbolt/error.log   is full of these entries.

Otherwise passbolt seems to be working fine. (Some regular users missed the "share" button, seems to be resolved, after logging off and logging on again)

2023-08-31 05:43:44 error: [Cake\Routing\Exception\MissingRouteException] A route matching "/img/illustrations/pin_passbolt.gif" could not be found. in /usr/share/php/passbolt/vendor/cakephp/cakephp/src
/Routing/RouteCollection.php on line 197
Request URL: /img/illustrations/pin_passbolt.gif
Referer URL: https://.../mfa/verify/totp?redirect=/

2023-08-31 05:44:04 error: [Cake\Routing\Exception\MissingRouteException] A route matching "/img/third_party/appstore.svg" could not be found. in /usr/share/php/passbolt/vendor/cakephp/cakephp/src/Routi
ng/RouteCollection.php on line 197
Request URL: /img/third_party/appstore.svg
Referer URL: https://.../

2023-08-31 08:26:44 error: [Cake\Routing\Exception\MissingRouteException] A route matching "/img/third_party/playstore.svg" could not be found. in /usr/share/php/passbolt/vendor/cakephp/cakephp/src/Rout
ing/RouteCollection.php on line 197
Request URL: /img/third_party/playstore.svg
Referer URL: https://.../app/passwords/view/81675da4-ca0a-4559-bafa-8ee0976c67dc

2023-08-31 08:26:44 error: [Cake\Routing\Exception\MissingRouteException] A route matching "/img/illustrations/passphrase_intro.svg" could not be found. in /usr/share/php/passbolt/vendor/cakephp/cakephp/src/Routing/RouteCollection.php on line 197
Request URL: /img/illustrations/passphrase_intro.svg
Referer URL: https://.../app/passwords/view/81675da4-ca0a-4559-bafa-8ee0976c67dc

### What you expected to happen
no errors in error.log

**Comment by RandomUser0815** [comment]
Healthcheck shows no relevant errors. I ran a "passbolt cleanup" after upgrade, which fixed one error.

**Comment by ishanvyas22** [comment]
Hey @RandomUser0815, which URL you are trying to access specifically? Can you share some screenshot or something too?

Also, can you try clearing the cache using below command?
```bash
sudo -H -u www-data bash -c "/usr/share/php/passbolt/bin/cake cache clear_all"
```

**Comment by RandomUser0815** [comment]
Thank you for your answer.

Actually I did not see any errors. I was only suprised to see that many errors in passbolts error.log.  As far as I understand the error.log the referer tells us, when the errors occured. Replace the "..." with the domain passbolt is running on our server.

I ran the "cache clear_all" command now without any errors.   I will see, whether these errors disappear from now.

**Comment by ishanvyas22** [comment]
I investigated further and it seems like these gif & svg files are missing. We have created a ticket (for internal reference PB-26141) to fix this.

In meanwhile, if you think these errors are too noisy, I would suggest you configure your nginx server to [serve these static assets](https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/) and disable the logging (see [Configuring Logging](https://docs.nginx.com/nginx/admin-guide/monitoring/logging/)) for these assets.

**Comment by cedricalfonsi** [comment]
Hey there,

Some of the images that are not found are served directly by the browser extension.
There might have been a hiccup while the extension was updated to its latest version.

I'm closing this ticket in the meantime, feel free to reopen if the problem persists.
