### ISSUE TITLE
migrate: Undefined constant "no" in /etc/passbolt/passbolt.php:56

### ISSUE THREAD

**Issue by lprosch** [passbolt/passbolt_api#496]
![config](https://github.com/passbolt/passbolt_api/assets/128388674/b05a737e-ac6d-4a97-81ae-801185624580)
![Uploading migrate_fail.png…]()

**Comment by stripthis** [comment]
This is not a bug, "no" is not a valid option, it should be null if you don't want to use TLS.

**Comment by lprosch** [comment]
Interestingly enough, quoting 'no' works.
