### ISSUE TITLE
utf8_encode() still in use in enygma/yubikey dependency breaking in php8.2

### ISSUE THREAD

**Issue by BrettMerrick** [passbolt/passbolt_api#499]
This pull request against enygma/yubikey is required for php8.2 installs to validate a yubikey when configured for MFA:
[https://github.com/enygma/yubikey/pull/33](https://github.com/enygma/yubikey/pull/33)

At present the latest docker passbolt/passbolt:4.3.0-1-ce release uses php8.2 and the result is that accounts with MFA enabled cannot log in but are instead presented with:
```
[Deprecated (8192) ](javascript:void(0);): Creation of dynamic property Yubikey\Validate::$clientId is deprecated [in /usr/share/php/passbolt/vendor/enygma/yubikey/src/Yubikey/Validate.php, line 145]
[Deprecated (8192) ](javascript:void(0);): Function utf8_encode() is deprecated [in /usr/share/php/passbolt/vendor/enygma/yubikey/src/Yubikey/Validate.php, line 251]
[Deprecated (8192) ](javascript:void(0);): Function utf8_encode() is deprecated [in /usr/share/php/passbolt/vendor/enygma/yubikey/src/Yubikey/Validate.php, line 251]
```

**Comment by ishanvyas22** [comment]
Hey @BrettMerrick, these are deprecation warnings and shouldn't cause any problems if you have debug mode disabled. 

Can you run health-check command(see [Troubleshoot Docker](https://help.passbolt.com/faq/hosting/troubleshoot-docker)) to make sure you've debug mode off? Generally it's turned off by default, but if you've changed it to `true` you should make it `false` and MFA should work as expected.

**Comment by ishanvyas22** [comment]
Closing the issue for now. Feel free to reach out to [community forum](https://community.passbolt.com/) in case you are still facing any problems.
