### ISSUE TITLE
Default GnuPG server key cannot be used in production

### ISSUE THREAD

**Issue by strideynet** [passbolt/passbolt_api#50]
Hi there,  
I followed the installation instructions word for word with the exception of changing the serverKey fingerprint and the private/public key links to the ASC files produced by the export in the first few steps but I get this error:
```
root@passbolt:/var/www/passbolt# app/Console/cake install --no-admin
     ____                  __          ____
    / __ \____  _____ ____/ /_  ____  / / /_
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /
 /_/    \__,_/____/____/_.___/\____/_/\__/

 Open source password manager for teams
 (c) 2015-present passbolt.com

---------------------------------------------------------------
Default GnuPG server key cannot be used in production. Please change the values of 'GPG.server' in 'APP/Config/app.php' with your server key information. If you don't have yet a server key, please generate one, take a look at the install documentation.
```
It's mildly infuriating as I have followed the steps religiously!

**Comment by stripthis** [comment]
@strideynet I'm working on a more complete guide, it will be ready in an hour or so. Hang in there.

**Comment by strideynet** [comment]
Haha, looks as if I just got unlucky with my timings. Many thanks 😄

**Comment by cedricalfonsi** [comment]
@strideynet A key which is not the default one is required to use passbolt in production, it has to be compulsory for security reason. 

However shifting you passbolt in debug mode will allow you to use the default GPG key. You can change the debug mode in you app/Config/core.php file.

**Comment by strideynet** [comment]
I'm pretty sure I changed the key, as I noted in my original issue. I went as far as to delete the keys being provided by default!

**Comment by stripthis** [comment]
Did you provide the new key fingerprint and locationg in app/Config/app.php?

**Comment by strideynet** [comment]
Ah. I just double-checked. It looks like I forgot to change the key fingerprint! Silly me! You can close this issue!

**Comment by stripthis** [comment]
No problemo!
