### ISSUE TITLE
API ednpoint resources.json not returning all resources

### ISSUE THREAD

**Issue by cerberek** [passbolt/passbolt_api#500]
##IMPORTANT: PLEASE READ

Only use github issues for bugs.

We will be more than happy to help you on the community forum for:
- feature requests: https://community.passbolt.com/c/backlog
- issues related to installations: https://community.passbolt.com/c/installation-issues
- general questions: https://community.passbolt.com/c/uncategorized

This is only a issue tracker for bugs related to the Passbolt API.
For passbolt docker, browser extension, command line interface, in short any other bugs 
please use [the other relevant repositories](https://github.com/passbolt).

If you are certain this is a new API bug please use the following format:

## endpoint resources.json?api-version=v2 not returning all resources
* Passbolt Version: passbolt-ce-server `4.3.0-1` but issues was on `3.11.1-1` as well
* Platform and Target:
-- Operating system: Debian Bullseye
-- PHP: 7.4.33
-- Web server: nginx/1.18.0
-- Database server: 10.5.18-MariaDB-0+deb11u1

### What you did
Loading resources.json but it looks that it's not returning resource_type_id:  a28a04cd-6f53-518a-967c-9963bf9cec51. That's one with encrypted description.

Tried it with web browser or with python code. After upgrade to 4.3.0-1 i can see missing resources in browser json file but still cannot download it through my python tool ( all other api calls works correct)

### What you expected to happen
get all resources when I call resources.json api endpoint

**Comment by stripthis** [comment]
Hello, unfortunately we cannot reproduce this issue. This seems to be an issue with your python tools. You can open an issue on the community forum if you need help with 3rd party tools: https://community.passbolt.com
