### ISSUE TITLE
saving TOTP  - The message should be of type string.

### ISSUE THREAD

**Issue by stfast** [passbolt/passbolt_api#501]
Hi,

when I edit an item and add TOTP,  there are no problems with adding, but saving an Item later throws error:

There was an unexpected error...  
The message should be of type string.

Same error when you create a new TOTP directly.

* Passbolt Version: just upgraded from 3.12.2 to 4.4.2.
* Platform and Target:
-- Operating system: Fedora 36
-- PHP: 8.1
-- Web server: apache httpd 2.4.57
-- Database server: MariaDB 10.5
-- etc.: installed from the source

![Screenshot 2023-12-05 at 01 10 33](https://github.com/passbolt/passbolt_api/assets/1120689/eefb91d1-f91e-4fcc-8f5e-74a9d2f2b20a)

![Screenshot 2023-12-05 at 01 10 47](https://github.com/passbolt/passbolt_api/assets/1120689/a82d21a6-9ca6-4811-a6e6-83fe1e2951d2)

Error from Chrome Inspect Console:

{
    "stack": "Error: The message should be of type string.\n    at Fe (chrome-extension://didegimhafipceonhjepacocaffmoppf/index.min.js:2:41707)\n    at gt.encrypt (chrome-extension://didegimhafipceonhjepacocaffmoppf/index.min.js:2:65099)\n    at Cu.encryptSecrets (chrome-extension://didegimhafipceonhjepacocaffmoppf/index.min.js:2:428692)\n    at async Cu.updateResourceAndSecret (chrome-extension://didegimhafipceonhjepacocaffmoppf/index.min.js:2:428061)\n    at async Cu.main (chrome-extension://didegimhafipceonhjepacocaffmoppf/index.min.js:2:427369)\n    at async S.<anonymous> (chrome-extension://didegimhafipceonhjepacocaffmoppf/index.min.js:2:434762)",
    "message": "The message should be of type string."
}

**Comment by ishanvyas22** [comment]
Thanks for the report. We have created an internal ticket(PB-29104) to take a look at this.

**Comment by ishanvyas22** [comment]
Hey @stfast, can you check if your database migrations are ran successfully? Did you face any error during the update?

One thing you can do is run the database migrations again via below command:
```sh
sudo -H -u nginx bash -c "/usr/share/php/passbolt/bin/cake migrations migrate"
```

Once migrations are done, run below command to clear cache:
```sh
sudo -H -u nginx bash -c "/usr/share/php/passbolt/bin/cake cache clear_all"
```

**Comment by stfast** [comment]
> ```shell
> sudo -H -u nginx bash -c "/usr/share/php/passbolt/bin/cake migrations migrate"
> ```

I followed update documentation where migration is somehow different in (step 4., "cake passbolt migrate --backup")

https://help.passbolt.com/hosting/update/source.html

> ```shell
># sudo -H -u apache bash -c "./bin/cake passbolt migrate --backup"
> ```


Now I run:

> ```shell
> # sudo -H -u apache bash -c "./bin/cake migrations migrate"
>using migration paths 
 >- /WWW/Administration/passbolt.dspot.us/passbolt/config/Migrations
>using seed paths 
 >- /WWW/Administration/passbolt.dspot.us/passbolt/config/Seeds
>using environment default
>using adapter mysql
>using database passbolt
>ordering by creation time
>
>All Done. Took 0.0457s
>
>Dumps the current schema of the database to be used while baking a diff
>
>using migration paths 
 >- /WWW/Administration/passbolt.dspot.us/passbolt/config/Migrations
>using seed paths 
 >- /WWW/Administration/passbolt.dspot.us/passbolt/config/Seeds
>Writing dump file `/WWW/Administration/passbolt.domain.us/passbolt/config/Migrations/schema-dump-default.lock`...
>Dump file `/WWW/Administration/passbolt.domain.us/passbolt/config/Migrations/schema-dump-default.lock` was >successfully written
> ```



> ```shell
> # sudo -H -u apache bash -c "./bin/cake cache clear_all"
>Clearing default
>Cleared default cache
>Clearing _cake_core_
>Cleared _cake_core_ cache
>Clearing _cake_model_
>Cleared _cake_model_ cache
>Clearing _cake_routes_
>The "_cake_routes_" cache configuration does not exist.
> ```


Saving TOTP now works. You shoud update step 4.  documentation.

**Comment by stfast** [comment]
Can you also implement uploading other attachments under items. 

For example we have an item with TOTP and a also a screenshot without QR code, with 2FA recovery codes for SMS enrollment.

**Comment by cedricalfonsi** [comment]
Hey @stfast,

Great that it works for you.

In the documentation, you'll find a dedicated section that assists users in identifying the user account operating the web server. :)

```
Find out the name of your webserver user

Some commands need to be run as the same user running the web server. Generally on Debian systems it will be www-data but on other distributions like Centos it could be for example nginx or http. For the rest of this tutorial we will assume that the user named www-data.
```

For the feature request checkout the community forum, here a discussion that might interest you: https://community.passbolt.com/t/as-a-user-i-can-create-resources-with-encrypted-file-attachement/74

**Comment by phw** [comment]
@cedricalfonsi I experience the same issue, without being able to resolve it. After update the migrations ran, seemingly successfully:

```
passbolt-passbolt-1  | 2023-12-15T11:53:36.982074514Z -------------------------------------------------------------------------------
passbolt-passbolt-1  | 2023-12-15T11:53:36.982653797Z  Running migration scripts.
passbolt-passbolt-1  | 2023-12-15T11:53:36.983029019Z -------------------------------------------------------------------------------
passbolt-passbolt-1  | 2023-12-15T11:53:37.012449217Z using migration paths
passbolt-passbolt-1  | 2023-12-15T11:53:37.013664435Z  - /etc/passbolt/Migrations
passbolt-passbolt-1  | 2023-12-15T11:53:37.014194430Z using seed paths
passbolt-passbolt-1  | 2023-12-15T11:53:37.028614452Z using environment default
passbolt-passbolt-1  | 2023-12-15T11:53:37.029288321Z using adapter mysql
passbolt-passbolt-1  | 2023-12-15T11:53:37.029699243Z using database passbolt
passbolt-passbolt-1  | 2023-12-15T11:53:37.030142830Z ordering by creation time
passbolt-passbolt-1  | 2023-12-15T11:53:37.048697067Z
passbolt-passbolt-1  | 2023-12-15T11:53:37.049746733Z  == 20230512220600 V410ImproveFoldersRelationsIndexesShareFoldersPerformance: migrating
passbolt-passbolt-1  | 2023-12-15T11:53:37.103582048Z  == 20230512220600 V410ImproveFoldersRelationsIndexesShareFoldersPerformance: migrated 0.0525s
passbolt-passbolt-1  | 2023-12-15T11:53:37.103650155Z
passbolt-passbolt-1  | 2023-12-15T11:53:37.103665354Z  == 20230601101058 V410RemoveTypeFromTotpResourceTypes: migrating
passbolt-passbolt-1  | 2023-12-15T11:53:37.114447790Z  == 20230601101058 V410RemoveTypeFromTotpResourceTypes: migrated 0.0108s
passbolt-passbolt-1  | 2023-12-15T11:53:37.114485350Z
passbolt-passbolt-1  | 2023-12-15T11:53:37.114494492Z  == 20230607174200 V410DeleteRootRole: migrating
passbolt-passbolt-1  | 2023-12-15T11:53:37.119277689Z  == 20230607174200 V410DeleteRootRole: migrated 0.0047s
passbolt-passbolt-1  | 2023-12-15T11:53:37.119303939Z
passbolt-passbolt-1  | 2023-12-15T11:53:37.119335027Z  == 20230607174300 V410AddRbacsTables: migrating
passbolt-passbolt-1  | 2023-12-15T11:53:37.147085350Z  == 20230607174300 V410AddRbacsTables: migrated 0.0277s
passbolt-passbolt-1  | 2023-12-15T11:53:37.147114116Z
passbolt-passbolt-1  | 2023-12-15T11:53:37.147132774Z  == 20230607174301 V410InsertUiActions: migrating
passbolt-passbolt-1  | 2023-12-15T11:53:37.197180839Z  == 20230607174301 V410InsertUiActions: migrated 0.0498s
passbolt-passbolt-1  | 2023-12-15T11:53:37.198349664Z
passbolt-passbolt-1  | 2023-12-15T11:53:37.199081775Z  == 20230607174302 V410InsertDefaultRbacsUiActions: migrating
passbolt-passbolt-1  | 2023-12-15T11:53:37.262263432Z  == 20230607174302 V410InsertDefaultRbacsUiActions: migrated 0.0624s
passbolt-passbolt-1  | 2023-12-15T11:53:37.262998251Z
passbolt-passbolt-1  | 2023-12-15T11:53:37.263529097Z  == 20230718083939 V420AddUserIdIndexToProfiles: migrating
passbolt-passbolt-1  | 2023-12-15T11:53:37.278466590Z  == 20230718083939 V420AddUserIdIndexToProfiles: migrated 0.0142s
passbolt-passbolt-1  | 2023-12-15T11:53:37.278526291Z
passbolt-passbolt-1  | 2023-12-15T11:53:37.278534318Z  == 20230911100418 V430AddUserDisabledField: migrating
passbolt-passbolt-1  | 2023-12-15T11:53:37.301401848Z  == 20230911100418 V430AddUserDisabledField: migrated 0.0228s
passbolt-passbolt-1  | 2023-12-15T11:53:37.301455746Z
passbolt-passbolt-1  | 2023-12-15T11:53:37.301463246Z  == 20231005121310 V440MobileTransferInsertUiActions: migrating
passbolt-passbolt-1  | 2023-12-15T11:53:37.309419039Z  == 20231005121310 V440MobileTransferInsertUiActions: migrated 0.0079s
passbolt-passbolt-1  | 2023-12-15T11:53:37.309469706Z
passbolt-passbolt-1  | 2023-12-15T11:53:37.309477752Z  == 20231005123634 V440MobileTransferDefaultRbacsUiActions: migrating
passbolt-passbolt-1  | 2023-12-15T11:53:37.322410549Z  == 20231005123634 V440MobileTransferDefaultRbacsUiActions: migrated 0.0128s
passbolt-passbolt-1  | 2023-12-15T11:53:37.322463975Z
passbolt-passbolt-1  | 2023-12-15T11:53:37.322471255Z  == 20231108114414 V441AlterUidOnGpgkeys: migrating
passbolt-passbolt-1  | 2023-12-15T11:53:37.334073279Z  == 20231108114414 V441AlterUidOnGpgkeys: migrated 0.0114s
passbolt-passbolt-1  | 2023-12-15T11:53:37.334126113Z
passbolt-passbolt-1  | 2023-12-15T11:53:37.334134491Z  == 20231115235026 V441DropUserAgents: migrating
passbolt-passbolt-1  | 2023-12-15T11:53:37.354065145Z  == 20231115235026 V441DropUserAgents: migrated 0.0167s
passbolt-passbolt-1  | 2023-12-15T11:53:37.354133921Z
passbolt-passbolt-1  | 2023-12-15T11:53:37.354144365Z All Done. Took 0.3202s
passbolt-passbolt-1  | 2023-12-15T11:53:37.374287517Z Clearing cake caches
passbolt-passbolt-1  | 2023-12-15T11:53:37.774762581Z Clearing _cake_model_
passbolt-passbolt-1  | 2023-12-15T11:53:37.775858563Z Cleared _cake_model_ cache
passbolt-passbolt-1  | 2023-12-15T11:53:38.149366138Z Clearing _cake_core_
passbolt-passbolt-1  | 2023-12-15T11:53:38.150934181Z Cleared _cake_core_ cache
passbolt-passbolt-1  | 2023-12-15T11:53:38.163575324Z Enjoy! ☮
```

I executed `su -s /bin/bash -c "./bin/cake passbolt migrate" www-data` and `su -s /bin/bash -c "./bin/cake cache clear_all" www-data` again, both run without issue (and the migration does not do any new migration, as expected).

Yet still I get the "The message should be of type string." message when trying to create a TOTP.

**Comment by Dual-Boot** [comment]
Hello,

 Sorry to dig up this issue, but it is still present with : 
* Ubuntu 20.04
* env : classic LAMP
* debian package provided by Passbolt Pro
* upgrade from 4.1.2-1 to 4.6.2-1
I tried which was already posted with no success.

 Regards,

**Comment by Dual-Boot** [comment]
Hello,

 soory for the noise : a simple log out and log in fix the problem.

 Bye bye
