### ISSUE TITLE
RBAC control to deny user password copy is not working.

### ISSUE THREAD

**Issue by abhi-bay** [passbolt/passbolt_api#505]
## ISSUE NAME: RBAC control to deny user password copy is not working.
* Passbolt Version: V 4.4.2

### What you did
In RBAC, under Passwords, I set "can copy" value to Deny for user.

### What happened
Through the browser extension as well as through the UI, I am able to click on the password to copy it to clipboard.

### What you expected to happen
Setting "Can copy" to Deny for a user should mean that the user cannot copy the password to clipboard. Note that deny for "Can Preview"  works just fine. But deny for "Can copy" does not work as expected.

**Comment by ishanvyas22** [comment]
Hey @abhi-bay, thanks for reporting the issue. We have created an internal ticket(PB-29213) to investigate.

**Comment by scadra** [comment]
Hey @abhi-bay,

We have tried to reproduce the issue without success, can you provide more information : 
- Which API version are you using 
- Which browser version
- Which Browser extension version

Thanks in advance

**Comment by abhi-bay** [comment]
@scadra I tried to re-create this in production, and was unable to. I am closing this issue. Thank you for checking.

Abhi

**Comment by abhi-bay** [comment]
closing

**Comment by scadra** [comment]
@abhi-bay thanks for your answer, with pleasure

**Comment by usmanjaved02** [comment]
@scadra I am facing same issue now on production

I have deployed passbolt with docker compose
