### ISSUE TITLE
No Emails

### ISSUE THREAD

**Issue by nevasway** [passbolt/passbolt_api#51]
No emails are being sent out by my Passbolt server. I'm wondering if the problem is that Passbolt doesn't support SSL/TLS?

I verified that there are several emails in the queue using the command: 
```
/var/www/passbolt/app/Console/cake EmailQueue.preview
```

My email service is hosted by google and I have 2 step authentication enabled. I created an app password within my gmail account specifically for Passbolt. I've configured `app/Config/email.php` with the the following settings:
```
        public $default = array(
                'transport' => 'Smtp',
                'from' => array('passbolt@mydomain.com' => 'Passbolt'),
                'host' => 'smtp.gmail.com',
                'port' => 587,
                'timeout' => 300,
                'username' => 'myname@mydomain.com',
                'password' => 'xxxxxxxxx',
        );
```

I haven't set up a cron job yet for sending emails but when I run the command:
```
/var/www/passbolt/app/Console/cake EmailQueue.sender
```

I get an error:
```
    SMTP Error: 530 5.7.0 Must issue a STARTTLS command first. 23sm1297540qtp.20 - gsmtp
Email 58b5a42e-2c18-4691-aeae-3067f2bb754b was not sent
```

Does Passbolt not support SSL/TLS? Or am I doing something wrong?

**Comment by stripthis** [comment]
Accordinging to [cakephp doc](https://book.cakephp.org/2.0/en/core-utility-libraries/email.html?highlight=cakeemail#configuration), you can configure TLS SMTP extension for service providers such as Gmail. Example:
```

class EmailConfig {
    public $gmail = array(
        'host' => 'smtp.gmail.com',
        'port' => 465,
        'username' => 'my@gmail.com',
        'password' => 'secret',
        'transport' => 'Smtp',
        'tls' => true
    );
}

```

You will need to have TLS/SSL on your server and access for less secure apps enabled in your Google account for this to [work](https://support.google.com/accounts/answer/6010255).

Please read for more info: https://book.cakephp.org/2.0/en/core-utility-libraries/email.html?highlight=cakeemail#configuration

**Comment by nevasway** [comment]
Thank you for your help, I got it to work!

I have two step verification enabled on my google account.   Therefore I had to create an [App Password](https://support.google.com/accounts/answer/185833).

Also, I had to use port 587:

      public $default = array(
                'transport' => 'Smtp',
                'from' => array('passbolt@mydomain.com' => 'Passbolt'),
                'host' => 'smtp.gmail.com',
                'port' => 587,
                'timeout' => 300,
                'username' => 'myname@mydomain.com',
                'password' => 'abcdefghijklmnopqrstuvwxyz',
                'tls' => true
        );
