### ISSUE TITLE
Unsuspend didnt work

### ISSUE THREAD

**Issue by roomme13** [passbolt/passbolt_api#512]
## Unsuspend didnt work after upgrade to 4.6.0
* Passbolt Version: 4.6.0 CE
* Platform and Target:
-- Operating system: Ubuntu/Docker
-- Database server: mariadb

### What you did
Unsuspend user in user space.

### What happened
Unsuspend user didnt change any status and user still cannot login

### What you expected to happen
Before upgrade to 4.6.0 Suspend / Unsuspend work without any issue.

**Comment by ishanvyas22** [comment]
Hey @roomme13, thanks for reporting the bug. We are able to reproduce the problem, we have created an internal ticket PB-32354 to solve this problem.

**Comment by ishanvyas22** [comment]
Hey @roomme13, we have released the fix with [v4.6.1](https://github.com/passbolt/passbolt_api/releases/tag/v4.6.1). Feel free to try it out and thank you for your patience.
