### ISSUE TITLE
Import Button uses Export symbol

### ISSUE THREAD

**Issue by Nitschi** [passbolt/passbolt_api#515]
## Import Button uses Export symbol
* Passbolt Version: WebUI 4.6.2 on Firefox 124.0.1

### What you did
Open the WebUI

### What happened
![image](https://github.com/passbolt/passbolt_api/assets/5908114/2a2df121-eca6-4250-a987-90ce18e90da7)

### What you expected to happen
The import Button should be an arrow pointing *into* the container, not *out of*

**Comment by stripthis** [comment]
Hello,

This is not a bug but a known "issue": e.g. an arrow down could also be understood by users as "download", e.g. export, so there is no perfect solution. Every time we switch the arrow in the other direction someone complain about the direction of the arrow :).

Please open an thread on the community forum if you want to discuss this issue further. https://community.passbolt.com/

Best,
