### ISSUE TITLE
Error: Unable to parse the secret. (shared password)

### ISSUE THREAD

**Issue by svennd** [passbolt/passbolt_api#518]
## ISSUE NAME
* Passbolt Version: 4.9.1, vendor install 
* Platform and Target:
-- Operating system: debian 11.10
-- PHP: PHP version 7.4.33
-- Web server: nginx/1.18.0
-- Database server: MariaDB 10.5.23
-- etc.: 
using https://github.com/daniel-lynch/py-passbolt/

### What you did
- Create a password in python for user A
- Share the password with user B

### What happened
- user A can access/read the password
- user B can see the password, but **cannot** read it : _Error: Unable to parse the secret._

### What you expected to happen
I understand that this python library isn't part of passbolt, but I can't seem to find the reason of this error. I checked the logs and passbolt is okay with all the resources.

**Comment by ishanvyas22** [comment]
Hey @svennd, I see you've also created the issue in library repo (https://github.com/daniel-lynch/py-passbolt/issues/8) so closing this one for now. Feel free to create an issue if related to passbolt API.
