### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by rudminas** [passbolt/passbolt_api#52]
At the end of installation I'm just revceiving: 
```
"response": {
      "header": {
        "id": "9bf47528-77ef-3d3f-aefc-2c398e536538",
        "status": "error",
        "title": "app_users_validateaccount_error",
        "servertime": 1488395737,
        "message": "Invalid request method, should be PUT",
        "controller": "Users",
        "action": "validateAccount"
      },
      "body": []
    }
```

**Comment by stripthis** [comment]
Hello @rudminas,

Can you tell us more information about your webserver configuration so that we can try to reproduce the issue? For example which OS, webserver, versions, etc.

Cheers,

**Comment by rudminas** [comment]
Hi @stripthis,
thanks for quick response!

It's Centos 6 with Directadmin.
Apache 2.4.10
DirectAdmin 1.51.3
MySQL 5.5.38
Php 5.5.38

Let me know if you need any more details

**Comment by stripthis** [comment]
Which browser are you using?

**Comment by stripthis** [comment]
Can you try to register on the online demo and/or with another browser to see if you get this issue in other context too?

**Comment by rudminas** [comment]
MacOS Sierra Chrome 56.0.2924.87

**Comment by rudminas** [comment]
I tried your demo and it was totally fine. But good point. I'll try another browser too

**Comment by stripthis** [comment]
Alright I will try to get the organize the same build and see if I can reproduce the issue. Thanks for reporting the issue.

**Comment by rudminas** [comment]
Same with firefox. So might be issue with the server itself

**Comment by stripthis** [comment]
Or a network device transforming a PUT request to a POST?

**Comment by rudminas** [comment]
Hey guys, any news?

**Comment by stripthis** [comment]
Hi @rudminas, we still didn't manage to reproduce the issue on our end. Can you send us the network information for that particular request from the browser console (to see if the request is going out as PUT or POST from the browser extension itself).

You should see something like this in your browser console (on firefox shift + cmd + j, enable only the 'net' message).
<img width="747" alt="screen shot 2017-03-04 at 14 30 59" src="https://cloud.githubusercontent.com/assets/77410/23579152/505df0c2-00e7-11e7-901a-5d5c45141dbd.png">

**Comment by mkurzeja** [comment]
I've come across the exact same issue. Tested on MacOS and Ubuntu (both on Chrome). I've checked the browser console and it seems that our apache config is rewriting the method from PUT to POST.

**Comment by mkurzeja** [comment]
In my case I'm using Direct Admin and the issue was inside `/etc/httpd/conf/extra/httpd-directories.conf`

The important part is the Limit tag that should include the PUT method:
```
	<Limit GET POST OPTIONS PROPFIND PUT>
		Order allow,deny
		Allow from all
	</Limit>
	<LimitExcept GET POST OPTIONS PROPFIND PUT>
		Order deny,allow
		Deny from all
	</LimitExcept>
```

Can I somehow update the docs?

**Comment by rudminas** [comment]
Looks like it's working fine now. Thanks guys!
