### ISSUE TITLE
Support for Safari

### ISSUE THREAD

**Issue by sebastianpisula** [passbolt/passbolt_api#524]
<img width="529" alt="image" src="https://github.com/user-attachments/assets/c4ac480d-97c8-424c-9bd7-5af368ea87f7">

**Comment by ishanvyas22** [comment]
Hey @sebastianpisula, there's already a feature request open in the [community forum](https://community.passbolt.com/t/pb-28063-safari-plugins-support/387/2). Feel free to engage and provide your feedback there.
