### ISSUE TITLE
Where are the latest docker images for passbolt ?

### ISSUE THREAD

**Issue by craph** [passbolt/passbolt_api#526]
Hello everyone,

I wonder where are the latest release for the Docker image of Passbolt ?

[On the repository for passbolt_docker](https://github.com/passbolt/passbolt_docker) the latest release mentioned in GitHub is 4.0.0 that was released : **Jun 15, 2023**

Are they build in GitLab because I see gitlab-ci file in the repository ? 🤔 

I'm using passbolt docker images for many years now and on the dockerhub side I can see that the latest was pushed 3 month ago.

But [On the repository for passbolt_docker](https://github.com/passbolt/passbolt_docker) the latest release 4.0.0 was in Jun 15, 2023... not the same date at the latest version in dockerhub

On my server, the latest docker image I have contains the server version 4.9.1...
I'm using it like this : 
```yaml
passbolt:
    image: passbolt/passbolt:latest
```
is it still the correct way to use it ? because in the official documentation now I can see `image: passbolt/passbolt:latest-ce`
What is the difference between `latest` and `latest-ce` tag ?

Where are the missing release on this repository ?

Because yesterday was published the version 4.10.0 of the passbolt api and there is no new release of the docker image version. Is it normal ?

Thank you very much for your help.
Best regards,

**Comment by ishanvyas22** [comment]
Hey @craph, as mentioned here (https://github.com/passbolt/passbolt_docker/issues/230#issuecomment-2490496162), the docker image for v4.10.0 api will be available soon.
