### ISSUE TITLE
Failure to get passwords for mobile app

### ISSUE THREAD

**Issue by heiko-wundram** [passbolt/passbolt_api#528]
## Failure to authenticate mobile app
* Passbolt Version: v4.10.1 CE
* Platform and Target:
-- Operating system: Debian 12
-- PHP: 8.2
-- Web server: Apache2 with mod_fcgid
-- Database server: MariaDB
-- etc.: Reverse Proxy with SSL termination

### What you did
Log in on the passbolt website to attach a mobile application (Android) to my Passbolt account, using the QR-codes that are displayed on the Passbolt mobile account attachment screen, with the current Passbolt app taken from the Play Store

### What happened
The general authentication works successfully, i.e. I can log in to the authentication and get to the screen which should display the passwords, but the actual synchronization(?) workflow for the passwords seems to go wrong between app and server with authentication failures:

... - - [17/Dec/2024:09:52:19 +0100] "POST /auth/jwt/refresh.json HTTP/1.1" 200 4226 "-" "okhttp/4.12.0"
... - - [17/Dec/2024:09:52:19 +0100] "GET /resource-types.json HTTP/1.1" 401 2810 "-" "okhttp/4.12.0"
... - - [17/Dec/2024:09:52:20 +0100] "GET /users.json HTTP/1.1" 401 2801 "-" "okhttp/4.12.0"
... - - [17/Dec/2024:09:52:20 +0100] "GET /groups.json?contain%5Buser%5D=1 HTTP/1.1" 401 2823 "-" "okhttp/4.12.0"
... - - [17/Dec/2024:09:52:20 +0100] "GET /resources.json?contain%5Bpermission%5D=1&contain%5Bfavorite%5D=1&contain%5Btag%5D=1&contain%5Bpermissions.group%5D=1 HTTP/1.1" 401 2923 "-" "okhttp/4.12.0"

This repeats indefinitely while the App displays the Android "waiting" spinner.

### What you expected to happen
The application connects fully to the backend application.

**Comment by marcin-michalek-miquido** [comment]
Looks like there is a loop `sign-in -> get {users, groups, ...} -> 401 -> refresh session -> 200 -> restart get {users, groups, ...} -> 401` so even right after sign-in or successful session refresh there is immediate `Unauthorized` error. We had a similar issue reported [here](https://community.passbolt.com/t/cannot-get-passwords-on-the-android-app/4552/7) where Apache was filtering out the authentication header. Could you please check if this solves the issue?

**Comment by heiko-wundram** [comment]
Thanks, that was really the issue that the Authorization-Header wasn't being passed in the FastCGI environment in which Passbolt is executed (by mod_fcgid); I actually never had this case before, it seems. The corresponding documentation is at https://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html#fcgidpassheader which suffices to pass the HTTP_AUTHORIZATION to Passbolt. Thanks!
