### ISSUE TITLE
As a user I want to select multiple records and perform a bulk action these entries 

### ISSUE THREAD

**Issue by lcpdn** [passbolt/passbolt_api#62]
Hello,
It would be interesting to be able to select multiple entries and to perform the same action at once on those multiple selected entries (like sharing to another member).  I suppose the tickbox next to the entry is intended to do so, but it doesn't work on my install and doesn't appear on the roadmap :)

**Comment by stripthis** [comment]
Hi @lcpdn yes that was one of the feature we intended initially but since it increases the complexity quite a bit we decided to leave it out for now. 

For example: what should we show in the dialog when multiple records selected and shared is pressed especially if two passwords have different permissions.

Apart from the delete and export (not implemented), other actions don't really make sense to happen in build. What do you think?

**Comment by lcpdn** [comment]
Hi @stripthis !
Well, I faced this issue while setuping our Passbolt Instance. And after importing 50+ passwords, sharing them one by one was a bit discouraging. And same issue will happen when a new employee arrives :/ 
Maybe you could add a share option directly during the creation ? Or create a kind of "Template entry" with shared options and (later) category, labels and group. This template entry could be used by default while clicking on "Create".

If multiple selected entries have different permissions, I think the best is to raise an error ;)

I guess that the "Groups" features will solve those issues :)

**Comment by stripthis** [comment]
From the use case you describe I think group will indeed be a solution. Controlling the password access of people leaving and joining would typically be solved like this.

Thanks for the interesting comments, I'm not replying in details to your other suggestions (cause it's a bit out of scope of this ticket now) but this is good food for thoughts. I especially like the templated entry could be solved with some "clone" fonctionality. I've seen other people requesting similar things before.

**Comment by stripthis** [comment]
Moved to https://community.passbolt.com/t/as-a-user-i-want-to-select-multiple-records-and-perform-a-bulk-action-these-entries/72

**Comment by candlerb** [comment]
> For example: what should we show in the dialog if two passwords have different permissions and are selected and the shared button is pressed?

A similar user experience exists in Google Drive, when you select two or more files and then click the Sharing link.

The way they handle it is to show a list of users who access to one or more of the files, and show access of "Varies" next to each user which has different levels of access.

I think this is a clean solution:

* if you leave it as "Varies" then nothing changes
* if you select a different value from the drop-down menu, then the permissions for that user on all the selected items are updated

**Comment by stripthis** [comment]
@candlerb thanks for the example. will show it on the forum thread.
