### ISSUE TITLE
Could not retrieve server key. Please contact administrator.

### ISSUE THREAD

**Issue by Jugulaire** [passbolt/passbolt_api#63]
Hi, 

i've followed all the step described right here : https://www.passbolt.com/help/tech/install for install passbolt on my server.

**BUT** : After creating account i got an error saying : Could not retrieve server key. Please contact administrator. 

**NOTE**: i'm on self signed certificate on nginx, with pretty URL configured :

```
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	listen 443 ssl default_server;
	listen [::]:443 ssl default_server;

	ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/key.pem;
	root /var/www/html/passbolt/app/webroot/;
	index index.php;
	server_name passbolt.local;

	location / {
        try_files $uri $uri/ /index.php?$args;
	}
	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass unix:/var/run/php5-fpm.sock;
	}
}

```
**NOTE 2**: I've turned on the debug mode and healthcheck don't show any error (screenshot below)

https://ibb.co/m5YogQ

I've already check the troubleshooting but nothing works. 

Can you help me ?

**Comment by stripthis** [comment]
Hello @Jugulaire,

We have seen this error when the public key or the domain name does not validate, for example when there is no email address defined for the server key or when the domain name URL is not valid (rfc1035). 

Could you double check these two points? We will be providing better diagnosis tools for these two cases with v1.5.0.

Best regards,

**Comment by Jugulaire** [comment]
Hi @stripthis,

Many thanks for your help, i just have to use the same domain for email adress of GPG key that i use in my configuration. 
For my testing purpose i have set ``passbolt.local`` so, if i would like to generate a gpg key for my server i need to type ``something@passbolt.local`` for email. 

Hope it help !
