### ISSUE TITLE
The GnuPG key for the server could not be imported

### ISSUE THREAD

**Issue by voffkas** [passbolt/passbolt_api#65]
... this error occurs during the installation phase.

$config shows correct path to keystorage. Keys isset. 
OS: Debian
PHP Version	5.6.30-0+deb8u1 
GPGme Version	1.5.1
Extension Version	1.4.0

All steps of installation manual done.
Tested in LXC container and VirtualBox image

**Comment by ktosiek** [comment]
It get's better - for me the `app/Console/cake install --no-admin` only worked when run with strace O_o

**Comment by voffkas** [comment]
Solved.

When I tried to export generated gpg-key to serverkey.asc and serverkey.private.asc, installation of Passbolt couldn't start and show this message: "No private key found at the given path /var/www/passbolt/app/Config/gpg/severkey.private.asc
Installation failed." 

But when i export this keys to different filename - installation started normally.
