### ISSUE TITLE
Feature Request : A logged user can manage licence keys

### ISSUE THREAD

**Issue by rguillome** [passbolt/passbolt_api#66]
As an advanced feature of the "File storing", allow storing encrypted licence keys with a counter system.

1- You can specify the number of licence usage (i.e "sharing") with a max number 
2- The available slots decrease by one each time you share the licence key to a new user  (sharing to a group would decreased the available slot by the number of its members). Of course, if you remove the sharing, the available counter is increase by one (or the size of the team/group)
3- An alert inform you that you reach the max available slots and if all the members of the group can't receive a sharing of the licence key either the system alerts and only provides some of the team's by a specific order, or it doesn't share to anyone with a alert

Maybe the feature needs more reflexion but this is the basis

Regards,

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/a-logged-user-can-manage-numbered-licence-keys/70
