### ISSUE TITLE
Unable to use google servers for sending email 

### ISSUE THREAD

**Issue by Jugulaire** [passbolt/passbolt_api#68]
Hi,

I have a problem when i try to configure a gmail account on passbolt.
I've followed this topic on cakephp documentation [link](https://book.cakephp.org/2.0/en/core-utility-libraries/email.html)
But i'm unable to send any email when i create a new user. 

Anybody know how to correct this issue ? 

here is the config i use 
```
public $default = array(
          'transport' => 'Smtp',
          'from' => array('blabla@gmail.com' => 'Passbolt'),
          'host' => 'smtp.gmail.com',
          'port' => 465,
          'timeout' => 30,
          'username' => 'blabla@gmail.com',
          'password' => 'my-password',
          'tls' => true
      );
```

Can i use the CLI to test my configuration ? 

EDIT : please tell me if you need more information

**Comment by stripthis** [comment]
Hello,

Do have two step verification enabled on your google account? If so you will need to create an App Password. https://support.google.com/accounts/answer/185833
Also you need to use the port 587.

There is currently no CLI healthcheck to test your emails.
Cheers,

**Comment by Jugulaire** [comment]
Okay, so if we refer to this issue [Issue#51](https://github.com/passbolt/passbolt_api/issues/51) 
You can test email with these 2 commands : 

```bash
# See email queue 
/var/www/passbolt/app/Console/cake EmailQueue.preview
# Send email queue
/var/www/passbolt/app/Console/cake EmailQueue.sender
```
If you want to have email sending (in my case) you need to create a cron job : 

```bash
su -s /bin/bash www-data
crontab -e 
# Add this line :

* * * * * /var/www/passbolt/app/Console/cake EmailQueue.sender
```
Now it's fully working for me !

**Comment by paulohg92** [comment]
Hello,
I have the same problem,
I have taken the examples given for testing but I get the following error:
# See email queue 
/var/www/passbolt/app/Console/cake EmailQueue.preview
# The error:
Error: Table email_queue for model EmailQueue was not found in datasource default.
#0 /var/www/passbolt/lib/Cake/Model/Model.php(3667): Model->setSource('email_queue')
#1 /var/www/passbolt/lib/Cake/Model/Model.php(3038): Model->getDataSource()
#2 /var/www/passbolt/lib/Cake/Model/Model.php(3010): Model->_readDataSource('all', Array)
#3 /var/www/passbolt/app/Plugin/EmailQueue/Console/Command/PreviewShell.php(18): Model->find('all', Array)
#4 /var/www/passbolt/lib/Cake/Console/Shell.php(461): PreviewShell->main()
#5 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand(NULL, Array)
#6 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#7 /var/www/passbolt/app/Console/cake.php(52): ShellDispatcher::run(Array)
#8 {main}


# Send email queue
/var/www/passbolt/app/Console/cake EmailQueue.sender

# the error:
Error: Table email_queue for model EmailQueue was not found in datasource default.
#0 /var/www/passbolt/lib/Cake/Model/Model.php(3667): Model->setSource('email_queue')
#1 /var/www/passbolt/app/Plugin/EmailQueue/Model/EmailQueue.php(74): Model->getDataSource()
#2 /var/www/passbolt/app/Plugin/EmailQueue/Console/Command/SenderShell.php(47): EmailQueue->getBatch(50)
#3 /var/www/passbolt/lib/Cake/Console/Shell.php(461): SenderShell->main()
#4 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(219): Shell->runCommand(NULL, Array)
#5 /var/www/passbolt/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#6 /var/www/passbolt/app/Console/cake.php(52): ShellDispatcher::run(Array)
#7 {main}

please help me,  I just need to send mail to finish
