### ISSUE TITLE
As a admin installing passbolt the CLI should help me figure out which keyring is being used, if it is writable and which fingerprints are present.

### ISSUE THREAD

**Issue by rkkoszewski** [passbolt/passbolt_api#69]
Hi, I've been following the guide from here: https://medium.com/passbolt/passbolt-on-debian-8-71-from-scratch-4438dad18908

But the installation fails with: The private key does not match the fingerprint mentioned in the config
Installation failed.

I generated the gnugpg key, exported the secret keys and copied the fingerprint to the app.php config where it should be.  But I still get the same error. What could be failing here? Could the gnugpg command be in some different version than the expected one? Where is the error? Or is it a bug?

**Comment by JuergenBoe** [comment]
same here

**Comment by ktosiek** [comment]
You want to use `gpg --homedir $GNUPGHOME -K --fingerprint` to see the fingerprint (look for a line with `Key fingerprint = `), and copy that fingerprint without spaces as the `'fingerprint'` value next to paths to keys.

I think Passbolt could suggest the right fingerprint to use here (that's a new feature, but it should be easy as you the actual fingerprint is already loaded).

Also, this is the value you'll be asked to verify when finishing registration, so you might want to send it to your users.

**Comment by stripthis** [comment]
You can check if the fingerprint exist in a given keyring for a given user as follow.

sudo su -s /bin/bash -c "gpg --list-keys --fingerprint --home /home/www-data/.gnupg" www-data | grep -i -B 2 'Passbolt Server'
pub   4096R/573EE67E 2015-10-26 [expires: 2019-10-26]
      Key fingerprint = 2FC8 9458 33C5 1946 E937  F9FE D47B 0811 573E E67E
uid   Passbolt Server Test Key <no-reply@passbolt.com>

**Comment by kevinmuller** [comment]
The issue has been created in our backlog. Issue reference: PASSBOLT-2079

**Comment by spanner28** [comment]
Hello,

Has this issue been resolved as yet?

I am having this exact same issue when trying to run the installer

he server key fingerprint does not match the fingerprint mentioned in app/config.php
Please run ./app/Console/cake passbolt healthcheck for more information and help.
Installation failed.

The Passbolt fingerprint is identical to the fingerprint outputted when creating the gpg key initially

**Comment by kereza** [comment]
Hello,

Is that issue resolved ? I followed the guide for CentOS 7 and NGinx and the same issue is present there.

**Comment by damiann89** [comment]
I got the same problem, it seems that app.php doesn't like fingerprint with the spaces in it.

**Comment by dallin** [comment]
Make sure you are changing the lines in `app.php` to use `server_public_key.key` and `server_private_key.key` instead of the default values of `unsecure.key` and `unsecure_private.key`. I believe it's lines 56 and 57.

**Comment by barbiomalefico** [comment]
I got the same problem today. I found that it was not true that the gpg key was stored under /home/www-data/.gnupg
Instead they wer installed under /root/.gnupg
I copied everything from /root/.gnupg to /home/www-data/.gnupg 
after that I was able to install passbolt.
Now The problem for me is that the admin user creation fails (Error: Table roles for model Role was not found in datasource default.) but this is another story...

**Comment by stripthis** [comment]
Additional healtcheck have been added. Please open new issues here https://community.passbolt.com/c/backlog if you want to add some more.
