### ISSUE TITLE
The GPG Server key defined in the config is not found in the gpg keyring

### ISSUE THREAD

**Issue by couvreud51d** [passbolt/passbolt_api#74]
Hello

I installed passbolt on debian server 8.8

php --version :
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21)

this is my error log : 
/var/www/passbolt# vi app/tmp/logs/error.log

2017-05-23 15:40:48 Error: [CakeException] The GPG Server key defined in the config is not found in the gpg keyring
Request URL: /auth/login
Stack Trace:
#0 /var/www/passbolt/app/Controller/Component/Auth/GpgAuthenticate.php(49): GpgAuthenticate->_initKeyring()
#1 /var/www/passbolt/lib/Cake/Controller/Component/AuthComponent.php(770): GpgAuthenticate->authenticate(Object(CakeRequest), Object(CakeResponse))
#2 /var/www/passbolt/lib/Cake/Controller/Component/AuthComponent.php(611): AuthComponent->identify(Object(CakeRequest), Object(CakeResponse))
#3 /var/www/passbolt/app/Controller/AuthController.php(35): AuthComponent->login()
#4 [internal function]: AuthController->login()
#5 /var/www/passbolt/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(AuthController), Array)
#6 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#7 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(AuthController), Object(CakeRequest))
#8 /var/www/passbolt/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))

Have an idea please ?

I do it : 

chown -R www-data:www-data app/tmp
chown -R www-data:www-data app/webroot/img/public
chown www-data:www-data app/Config
chmod -R 777 app/tmp
chmod -R 777 app/webroot/img/public

/var/www/passbolt# vi app/Config/core.php
Configure::write('debug', 2);

I don't understand what's the problem.
please help me

thank you

David

**Comment by couvreud51d** [comment]
my passbolt version is  1.4.0

**Comment by stripthis** [comment]
Hello @couvreud51d 

This most likely means that they web server user cannot access the gpg keyring or that fingerprint for the key is not the right one. Please double check the following tutorial and see if you missed a step:
https://medium.com/passbolt/passbolt-on-debian-8-71-from-scratch-4438dad18908

Cheers,

**Comment by stripthis** [comment]
You can check if the fingerprint exist in a given keyring for a given user as follow.

```
sudo su -s /bin/bash -c "gpg --list-keys --fingerprint --home /home/www-data/.gnupg" www-data | grep -i -B 2 'Passbolt Server'
pub   4096R/573EE67E 2015-10-26 [expires: 2019-10-26]
      Key fingerprint = 2FC8 9458 33C5 1946 E937  F9FE D47B 0811 573E E67E
uid   Passbolt Server Test Key <no-reply@passbolt.com>
```

**Comment by couvreud51d** [comment]
thank you

David
