### ISSUE TITLE
Problems after 2 months of implementation

### ISSUE THREAD

**Issue by leomazzo** [passbolt/passbolt_api#77]
Hi Passbolt Team,

We have implemented Passbolt two months ago in two distinct enviroments (two companys). But we are using the latest version and PHP 7 running in Centos 7.

Now we cannot share more passwords and we can see this in cake error log:

2017-05-24 22:14:19 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/html/passbolt/app/Controller/ShareController.php, line 65]
Trace:
ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
ShareController::__updatePermissions() - APP/Controller/ShareController.php, line 65
ShareController::simulate() - APP/Controller/ShareController.php, line 274
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 110

In WEB UI we can see bellow:
<img width="596" alt="captura de tela 2017-05-24 as 22 11 10" src="https://cloud.githubusercontent.com/assets/13120781/26431865/f37ec990-40cd-11e7-8526-7c3532029409.png">

And the two environments starts this issue in the same day. I have tried to use plugin in Chrome, Firefox and no success.

Thanks for help

**Comment by stripthis** [comment]
Hello @leomazzo,

Did you update to v1.5.1, or are you still using 1.4.0?
Cheers,

**Comment by leomazzo** [comment]
Hi stripthis,

Thank you for reply. We are using 1.4.0.

How can i update to 1.5 ?

Regards.,
Leonardo.

**Comment by stripthis** [comment]
See. https://www.passbolt.com/help/tech/update

You need to:
0. Make a backup of your database
1. Pull the v1.5.1 of the API using git
2. Run the update script

**Comment by leomazzo** [comment]
Thank you. After the upgrade, the problem was solved. Regards!
