### ISSUE TITLE
As an admin I want to see which passwords are shared with a specific group

### ISSUE THREAD

**Issue by shochdoerfer** [passbolt/passbolt_api#83]
Currently it is not possible to easily see which passwords are shared with a group. Especially when deleting a group I would love to see which shared passwords it affects.

**Comment by stripthis** [comment]
Ref.  PASSBOLT-2129. 
I've added this to our backlog @shochdoerfer. The only issue I see with this story is that admin do not have read access to the passwords that are shared with group.

**Comment by shochdoerfer** [comment]
Good catch, makes sense.

**Comment by stripthis** [comment]
This feature is available with v1.6.5: a user can filter passwords by groups in the password workspace. Please create new issue here if needed: https://community.passbolt.com/
