### ISSUE TITLE
Username should be Minimum 1 or 2 Characters

### ISSUE THREAD

**Issue by wishmedia** [passbolt/passbolt_api#85]
WHM / CPanel accepts 2 character usernames, but Passbolt requires a minimum of 3.

**Comment by stripthis** [comment]
Yes this makes sense. We will schedule this change request.
ref. PASSBOLT-2122

**Comment by wishmedia** [comment]
To add to this, Username should allow any character. Wordpress allows spaces in their username while Passbolt doesn't.

**Comment by stripthis** [comment]
@wishmedia yes, there is another story for this one also: #40

**Comment by kevinmuller** [comment]
This issue has been solved in 1.6.1: http://www.passbolt.com/release/notes#Fresh
