### ISSUE TITLE
Support new line character in description field

### ISSUE THREAD

**Issue by glebaccon** [passbolt/passbolt_api#86]
We can not write multiple paragraph.

**Comment by stripthis** [comment]
ref. PASSBOLT-2125

**Comment by glebaccon** [comment]
To display correctly the description maybe you could add 'white-space: pre-wrap' in description_content of CSS file.

**Comment by kevinmuller** [comment]
This issue has been solved in 1.6.1: http://www.passbolt.com/release/notes#Fresh
