### ISSUE TITLE
As a group administrator I want to see which password(s) have been granted to a group

### ISSUE THREAD

**Issue by bluenetinc** [passbolt/passbolt_api#89]
Enhancement request:

A group Manager should be able to somehow click through groups and see which passwords have been assigned to a particular group.  Only way I can see now is to select each individual password, edit, and go to the share tab.

**Comment by stripthis** [comment]
I can see two options:
- As a group manager in the user workspace when clicking on a group I can see the passwords that are shared with this group in the right sidebar.
- As a user In the password workspace, on the left side panel, I am able to see the list of groups I am a member of and can use them to filter to passwords that belong to such groups.

The later is more work, but would be nice to how if people are interested in it.
Ref. PASSBOLT-2130

**Comment by bluenetinc** [comment]
I think the later is a must-have if you were to use passbolt for any kind of multi-tenant password management.  you could group it per tenant/client.  As the list of passwords gets large, this would make it much easier to manage/find passwords for a particular task

**Comment by stripthis** [comment]
As a user In the password workspace, on the left side panel, I am able to see the list of groups I am a member of and can use them to filter to passwords has been completed with latest release.
