### ISSUE TITLE
Integration with desktop app ?

### ISSUE THREAD

**Issue by rgarrigue** [passbolt/passbolt_api#9]
Hi guys

I'm looking forward for a first release of Passbolt, as a modern replacement to keepass someday hopefully.

For that purpose I'm wondering about the integration between passbolt and desktop app : will it be possible to clic somewhere to open the connexion ? 

That could be quite easy, like a custom field with ssh://, ftp://, rdp:// links and a doc about how to setup those protocol on Linux / Windows to be forwarded to ssh cli, ftp cli, Putty, Filezilla, Firefox FireFTP / FireSSH module, remina or mstsc

Best regards

**Comment by kevinmuller** [comment]
Hi @rgarrigue 

As of now, it is possible to do what you describe by using the URI field of a password. For instance, while saving a new password, if you enter ssh://127.0.0.1 in the URI field and then click on it after it is saved, then the browser will ask you if you wish to open it with your local terminal app. (see screenshot).
This is handled directly by the browser and the operating system.

![screen shot 2016-06-03 at 12 27 43](https://cloud.githubusercontent.com/assets/80405/15771702/2f701ac8-298a-11e6-87c0-2a336c566fc5.png)

However, what is not supported currently is generate dynamic uri that would include username and password (for instance, ssh://username:password@host) based on the value of their respective fields. I am not sure if this is what you meant?

It's definitely an interesting idea though. We should explore what are the options in a near future.

Kevin

**Comment by rgarrigue** [comment]
The URI field is indeed a good start for what I had in mind. Since I explained a half-technical thing with my idea of how this could work maybe I'm not clear enought.

My basic need is the following : for an entry, being able to clic and be connected automagically. We're doing that in keepass nowadays, for example we make an SSH entry with Title = hostname, login & password, and URL field is 

    cmd://putty -load "Default Settings" {TITLE} -l {USERNAME} -pw {PASSWORD}

Which pass down the command "putty ...", so it opens putty connected with SSH. Same thing with FTP entry, title login & password, and the URL field

    cmd://"C:\Program Files (x86)\FileZilla FTP Client\filezilla.exe" sftp://{USERNAME}:{PASSWORD}@{TITLE}

Clic and you're connected. Same for database connection, with an additionnal field, database ID, etc etc. 

For my current company, and the previous one too, the n°1 feature of this kind of tool is storing password, the n°2 is the time you save starting Putty / Filezilla / sqldeveloper / whatever, copy-paste login, copy-paste password, copy-paste hostname...

It may be achieved as I hinted with ssh://, ftp://, custom:// URI and OS integration or any way you might think of if you go for this feature request :smile: 

Thanks

PS : while I'm on the topic, a nice time saving feature in keepass is double-clic to copy data, I dunno if there's a button in passbolt for that, can't connect to the demo right now, but that would be usefull too !

**Comment by kevinmuller** [comment]
Thanks for the detailed explanations, and the suggestions. This  will be included in our roadmap. It's definitely a nice feature to have.

Regarding copying information in the clipboard, we have a button to copy the password in the clipboard, and a drop down menu to copy the username.

Cheers.

**Comment by stripthis** [comment]
Moved to: https://community.passbolt.com/t/as-a-user-i-can-define-url-schemes-that-open-the-relevant-desktop-app/67
