### ISSUE TITLE
As a user, I would like to get info about the password lifecycle

### ISSUE THREAD

**Issue by lcpdn** [passbolt/passbolt_api#91]
A nice feature to implement would be to set in the password template a lifecycle management indicator.
For example, set a lifetime for public websites password of 2 months. And highlight in red in the webpage the outdated credentials.

A second dependant feature would be to get a periodic mail notification of every passwords ending their lifetime.

Cheers !

**Comment by stripthis** [comment]
Moved to https://community.passbolt.com/t/as-a-logged-in-user-i-should-know-if-a-password-is-about-to-expire-and-should-be-changed/61
