### ISSUE TITLE
Locations of keys in different Directory

### ISSUE THREAD

**Issue by dipiana** [passbolt/passbolt_api#93]
Hi. I am trying to install the Passbolt but my keys are on a different location because of security reasons.

Location of the key: /var/www/virtual/username/passbolt/app/Config/gpg/serverkey.asc

Location of app.php: /var/www/virtual/username/html/passbolt/app/Config

When I set the path to the keys in app.php it now looks for the keys in: /var/www/virtual/username/html/passbolt/app/Config/gpg//var/www/virtual/username/passbolt/app/Config/gpg/serverkey.private.asc

What can I do, that the script finds the keys in the correct location.
Coping the keys to /html/ (which is accessible from outside) seems a bit insecure?

Thanks lot!

**Comment by cedricalfonsi** [comment]
Hello @dipiana,

Do you have an installation trace ? It would help to see what exception is thrown.

I'm wondering if you prefixed your path with the constant APP :
`'private' => APP . 'Config' . DS . 'gpg' . DS ...`

Best regards,
Cedric

**Comment by dipiana** [comment]
I use the standard app.php from the git; it looks like this:

```
'GPG' => [
		// Tell GPG where to find the keyring
		// Needs to be available by the user the webserver is running as
		'env' => [
			// you can set this to false if you want to use *nix $GNUPGHOME environment variable
			'setenv' => true,
			// otherwise you can set the location here
			// typically on Centos it would be in '/usr/share/httpd/.gnupg'
			'home' => '/home/back/.gnupg',
		],
		// Main server key
		'serverKey' => [
			// Server private key location and fingerprint
			'fingerprint' => '4C........2',
			'public' => APP . 'Config' . DS . 'gpg' . DS . '/var/www/virtual/username/passbolt/app/Config/gpg/serverkey.asc',
			'private' => APP . 'Config' . DS . 'gpg' . DS . '/var/www/virtual/username/passbolt/app/Config/gpg/serverkey.private.asc',

			// PHP Gnupg module currently does not support passphrase, please leave blank
			'passphrase' => ''
		]
	]
```

**Comment by cedricalfonsi** [comment]
```
'public' => APP . 'Config' . DS . 'gpg' . DS . '/var/www/virtual/username/passbolt/app/Config/gpg/serverkey.asc',
'private' => APP . 'Config' . DS . 'gpg' . DS . '/var/www/virtual/username/passbolt/app/Config/gpg/serverkey.private.asc',
```

The public and private paths lead to the application config directory. You have to remove `APP . 'Config' . DS . 'gpg' . DS ` from the paths.

**Comment by dipiana** [comment]
Ah, works like charm! Thanks a lot!
