### ISSUE TITLE
Allow JSON in the description

### ISSUE THREAD

**Issue by mikemix** [passbolt/passbolt_api#94]
Is there any possibility to make the description field accept JSON? At this moment it is not possible, however we would like to share among our team members some detailed credentials.

![zaznaczenie_005](https://user-images.githubusercontent.com/2399452/27378503-6271a1aa-5678-11e7-8d2b-887a3cfe6d6f.png)

**Comment by stripthis** [comment]
Hello @mikemix. Thank you for your suggestion it's a good one, it's added in the backlog.
Ref. PASSBOLT-2156

**Comment by kevinmuller** [comment]
This issue has been solved in 1.6.1: http://www.passbolt.com/release/notes#Fresh
