### ISSUE TITLE
Error in Group Update - API/Plugin version 1.6.0

### ISSUE THREAD

**Issue by technogenus** [passbolt/passbolt_api#95]
When adding users to an existing group (created when system was at API 1.5 version) we get an interface error of: 
error The group could not be saved

Logs show, could not validate GroupUser:

Error: [ValidationException] Could not validate GroupUser
Request URL: /groups/592bda77-d9e0-461f-b2bb-7219c0a8580e.json
Stack Trace:
#0 [internal function]: GroupsController->edit('592bda77-d9e0-4...')
#1 /var/www/passbolt/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(GroupsController), Array)
#2 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/passbolt/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(GroupsController), Object(CakeRequest))
#4 /var/www/passbolt/app/webroot/index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

**Comment by kevinmuller** [comment]
Hi @technogenus 

Thanks for your report.

Can you confirm that when you upgraded to 1.6.0 you followed the update procedure defined in our help section regarding minor updates: http://www.passbolt.com/help/tech/update#toc_minor ?

I am mainly interested to know if you ran the update script:
```./app/Console/cake Migrations.migration run all```

Thanks!

**Comment by technogenus** [comment]
We followed it exactly and ran both the cake migration for status and two upgrade scripts were reported, then "run all" and both mig scripts appeared to run correctly.

**Comment by stripthis** [comment]
@technogenus can you also confirm that you are using the plugin v1.6.0? (just to rule that out)

**Comment by technogenus** [comment]
yes.  we are testing PASSBOLT with a regional team of about 20 and we were forced to upgrade the backend quickly today because 90% of the users suddenly had the 1.6.0 plugin... and were mostly locked out of Passbolt with a message "your plugin is not compatible with your API version" message.
We are using a mix of CHROME and FIREFOX.  Error occurs in both browsers - but group seems to be updated with the added users, in spite of the error message.

**Comment by cedricalfonsi** [comment]
@technogenus

We tried many possible scenarios, but we are still unable to reproduce the bug.
Could you tell me if this bug only impacts a specific category ? or all of them ?

Could you send us a raw dump of the data exchanged between the plugin and the server ? It would help us investigate the issue. To do that, you can follow the instructions below:

0. Browser: chrome
1. Open the plugin debug console:
1.1. Go to chrome://extensions/
1.2. Locate the passbolt extension
1.3. In the section _Inspect views_, click on _index.html_ 
2. Go the network tab
3. Try to reproduce the issue
4. Copy the exchanged data:
4.1. Search for the part that looks like : http://PASSBOLT_DOMAIN/groups/640d1f30-0197-3276-a87e-a1ef389ee5fb.json, it should be the latest one
4.2. Select it
4.3. On the headers tab, you should see a Request payload section. Unfold the data, and take a screenshot.
4.5. On the response tab you copy everything

If you don't want to send sensitive data here, you can obfuscate the data and/or send them to contact@passbolt.com

**Comment by technogenus** [comment]
Thank you for taking the time to look at this.  I want to apologize, as this error was related to our customization of notifications.  We have implemented custom notification toggle and did not properly update the GroupAdd and GroupDelete notifications added to 1.6.0.

**Comment by technogenus** [comment]
We were able to fix this in our customized Controller-Component-EmailNotificatorComponent.php file and was not a problem with the base 1.6.0 Passbolt. Again, apologies.
