### ISSUE TITLE
Password description does not allow enter (new line) character

### ISSUE THREAD

**Issue by technogenus** [passbolt/passbolt_api#96]
The password description field does not allow new line character which is difficult for users to visually confirm.  This often encountered when using copy/paste for the description. 

Could new line character be 'escaped' to allow it, or internally encapsulated in a replace-to-space (or replace to markup "<br />") function?

**Comment by technogenus** [comment]
Sorry - this is a duplicate report of #86

**Comment by stripthis** [comment]
@technogenus thanks for the proactive grooming :)
