### ISSUE TITLE
Bad URL generate on login "Oops, something went wrong"

### ISSUE THREAD

**Issue by HeLLsSs** [passbolt/passbolt_api#97]
Hi, (sorry for my english)

When i used passbolt i going on interface and i got this error message : "Oops, something went wrong"

If i refresh fast i can show on right : 
"Server identity check in progress... Checking key: .... (with url)" if i click on this url i have this route : /auth/auth/verify, but she doesn't exist :/

When i use this route : /auth/verify  all is fine i got my gpg key

Some one have same problem ? Thanks

**Comment by stripthis** [comment]
Hello @HeLLsSs,

What is the url you use for passbolt? Are you using something like https://mypassbolt.com or https://mydomain.com/passbolt ? Which version of passbolt are you using?

@cedricalfonsi This issue might be related to PASSBOLT-2111.

**Comment by HeLLsSs** [comment]
Hello @stripthis 

I using https://mypassbolt.com fix didn't work :/ i'm run on NGINX

**Comment by stripthis** [comment]
It seems to me that you have some issues with URL rewriting that are specific to your config. Can you check the following: https://book.cakephp.org/2.0/en/installation/url-rewriting.html#pretty-urls-on-nginx ? Feel free to reopen if that doesnt solve your issue.

**Comment by HeLLsSs** [comment]
Hi :) 

Same problem, my config nginx :

`server {
    listen 80;
    server_name xxxx;

    include /etc/nginx/snippets/letsencrypt.conf;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
        listen       443 ssl http2;
        server_name  passbolt.etic-data.fr;

        include snippets/ssl-passbolt.etic-data.fr.conf;
        include snippets/ssl-params.conf;

        root         /var/www/passbolt/app/webroot/;
        index index.php;

        include snippets/allowdeny.conf;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root  /html;
        }

        location / {
            try_files $uri $uri/ /index.php?$args;
        }
        # pass the PHP scripts to FastCGI server listening on unix socket
        #
        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass   unix:/run/php/php7.0-fpm.sock;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

}


`

**Comment by DitItOnNix** [comment]
Hi,

I have the same issue as per the subject matter even though I follow these guides
https://book.cakephp.org/2.0/en/installation/url-rewriting.html#pretty-urls-on-nginx 
https://medium.com/passbolt/passbolt-on-centos-7-with-nginx-php7-fpm-mariadb-from-scratch-7b2a9b15f3a4

I noticed this /auth/auth/verify and it gives plugin gpg error. If I run `curl http://10.1.200.93/auth/verify.json` I get the following.
`{"header":{"id":"49cadf37-0eaf-3689-a8f7-430b02908cac","status":"success","title":"app_auth_verify_success","servertime":1509704089,"message":null,"controller":"Auth","action":"verify"},"body":{"fingerprint":"12165C90BB8584E58E4DAF18B2C4B036B252BB7B","keydata":"-----BEGIN...`

[Here](https://pastebin.com/65vyBCFs) is my nginx config. and [here](https://pastebin.com/mv6vYZHs) is my passbolt healthcheck.

Server is CentOS v7/ Nginx 1.12 / php-7.1

Appreciate little support here.

Regards
Hirantha

**Comment by stripthis** [comment]
Hi @DitItOnNix we moved the installation issues to the community forum. Can you open new issues there: https://community.passbolt.com/c/installation-issues ?

**Comment by DitItOnNix** [comment]
Noted Remy, new issue opened as advised.

https://community.passbolt.com/t/plugin-check-gpg-error-and-oops-something-went-wrong-when-trying-to-login/90
